### ISSUE TITLE
Route53 ALIAS -> ELB HostedZoneID mapping

### ISSUE THREAD

**Issue by bgentry** [fog/fog#1098]
When you create an ALIAS record to an ELB via the Route53 console, all you have to do is paste the DNS name of the ELB and it will figure out the corresponding HostedZoneID for you.

However, when you create such a record via the API, you need to specify both the DNS name and the HostedZoneID yourself. This is all fine if you own the ELB in your account, but there is no way to do this lookup for an ELB belonging to another AWS account, even though AWS has no trouble doing so from the web console.

After discussing this w/ AWS support, it turns out there's a simple trick to do this mapping ourselves. Each AWS region has a single HostedZoneID for ELBs in that region. This mapping is the same for all AWS accounts. Here is the list given to me by AWS support:

``` ruby
  def self.zone_mapping
    @zone_mapping ||= {
      "us-east-1" => "Z3DZXE0Q79N41H",
      "us-west-1" => "Z1M58G0W56PQJA",
      "us-west-2" => "Z33MTJ483KN6FU",
      "eu-west-1" => "Z3NF1Z3NOM5OY2",
      "ap-northeast-1" => "Z2YN17T5R711GT",
      "ap-southeast-1" => "Z1WI8VXHPB1R38",
      "sa-east-1" => "Z2ES78Y61JGQKS",
    }
  end
```

I propose we handle this lookup in Fog if the user specifies an AliasTarget and only an ELB DNS name (with no HostedZoneID). Since we can figure out the HostedZoneID automatically for all records matching `*.region-name.elb.amazonaws.com`, I think we should do so, rather than requiring app developers to do this mapping themselves.

FYI, this is not documented in AWS stuff anywhere, though they told me they'd do so at some point.

**Comment by mehiatt** [comment]
For those looking today: https://docs.aws.amazon.com/general/latest/gr/elb.html
