### ISSUE TITLE
Provide easy access to AWS request ids

### ISSUE THREAD

**Issue by dpiddy** [fog/fog#1118]
When debugging issues with Amazon they often want the request ids they provide in responses. It would be nice if fog made these easy to get. There are at least a few complications here:

* the various services provide the request id in different ways: differing headers, within XML responses, etc.
* hard to get access to the original response on an HTTP status error, such as when `Error.slurp` is used
* even with access the original response on an HTTP status error, the body is not parsed making it difficult to grab a request id within an XML response

For reference, here's what I'm using to reliably extract the request id on positive responses from things like `aws_compute.describe_instances` for at least the AWS Compute, ELB and IAM services:

```ruby
def extract_request_id(response)
  if header_and_value = response.headers.detect {|k, v| k =~ /\Ax-amzn?-request-?id\z/i }
    header_and_value.last
  elsif id = response.body["requestId"]
    id
  elsif response.body["ResponseMetadata"] && id = response.body["ResponseMetadata"]["RequestId"]
    id
  end
end
```

This would be a lot easier if all AWS services provided the request id in the response headers, ideally using the same header key.

**Comment by plribeiro3000** [comment]
Closing due inactivity.

Please create a new issue at [fog-aws](https://github.com/fog/fog-aws) if this needs to be fixed somehow.
