### ISSUE TITLE
reading s3 upload progress

### ISSUE THREAD

**Issue by nzaillian** [fog/fog#1187]
I'm using fog via carrierwave to allow users of my app to push videos to s3.  The arrangement right now is a proxying one where they first push the file to my server, then I do some processing and push the output to s3 via fog.  The actual upload happens via creating a Fog::Storage::AWS::File instance.  It works great, but as the uploads can take several minutes I would like to be able to let the client poll me for upload progress so I can inform the user approximately when he'll be able to view his video.  I can't figure out via documentation or looking at the source for the Fog::Storage::AWS::File model how to do this (query upload progress).  Would appreciate guidance.  To be clear, I've figured out how to report progress of the uploads to my server, but I need to know how to poll for (or otherwise be given) the progress of the upload (via fog) from my server to s3.

**Comment by plribeiro3000** [comment]
closed in favor of fog/fog-aws#7
