### ISSUE TITLE
[openstack] :openstack_auth_url should not require trailing /tokens

### ISSUE THREAD

**Issue by mvidner** [fog/fog#1210]
[Rubiojr's gist](https://gist.github.com/2627365) is the first Google hit for "ruby fog openstack". Notice how the parameters for `Fog::Compute.new` there are mostly direct equivalents of the `OS_*` environment variables of the [Unified CLI](http://wiki.openstack.org/UnifiedCLI/Authentication), except for `OS_AUTH_URL_FOG`. That is because the common `OS_AUTH_URL` is the "identity API endpoint" which, as quoted by the /tokens API output itself, is of the form `scheme://host:5000/2.0`. OS_AUTH_URL_FOG currently needs to be `${OS_AUTH_URL}/tokens`.

I think `:openstack_auth_url` should be compatible with the unified CLI and not require the trailing /tokens. 

A related issue is that the code distinguishing v1 authentication from v2 requires a trailing / after the 2.0.

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-openstack#36.
