### ISSUE TITLE
How do I create a sub-directory (or "folder") with Fog?

### ISSUE THREAD

**Issue by mpelzsherman** [fog/fog#1370]
I want to create sub-directories or "folders" under my bucket like you can with the AWS console. Is this possible with fog?

(thanks!)

**Comment by abaldwin88** [comment]
You can create a pseudo-directory in fog like this...

```
bucket.files.create(
  key: 'user_1_files/',
  body: nil
)
```

http://stackoverflow.com/questions/31732809/ruby-fog-gem-how-to-create-sub-directories/39476895#39476895
