### ISSUE TITLE
Random Error: "the specified s3 bucket name() is not a valid dns name"

### ISSUE THREAD

**Issue by rnhurt** [fog/fog#1380]
My environment: Fog 1.8.0 / JRuby 1.7.1(1.9.3p327) / Rails 3.2.9 / OS X 10.8.2

The problem: I'm getting this error sporadically when I try to save a file to S3.  Sometimes it works and sometimes it doesn't and I haven't been able to pin it down, however it seems to center around storage/get_bucket.rb file.  Most of the time after the request() call (line 47) the return value is not complete and is missing lots of entries.  When this happens Fog cannot create a proper "directory" object and creates one with a nil bucket name, and this causes a cascading failure.  :(

Like I said, I can't really reproduce it perfectly.  Sometimes it works and sometime it doesn't.  It kinda makes me think of a race condition or some other threading problem.

**Comment by Nitrodist** [comment]
Hi, I'd like to revisit this issue.

`fog: the specified s3 bucket name...` error happening does not have the explanation on [the page linked anymore](https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html). It may have been true in 2013 but in 2021 it is not indicated on the page linked.

Can @geemus comment or the current maintainer?

**Comment by fcheung** [comment]
Bucket name rules seem to have moved to https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html but I think the substance is the same.

**Comment by geemus** [comment]
@Nitrodist thanks for the heads up.

@fcheung thanks for the link.

I pushed an update the URLs here: https://github.com/fog/fog-aws/commit/db72d824b8b2c76d81e7a2fe5e8c0c895ffa18a0
