### ISSUE TITLE
AWS auto scaling: availability zones are not a required parameter

### ISSUE THREAD

**Issue by phemmer** [fog/fog#1503]
Currently AWS::AutoScaling::Group has `availability_zones` as a required parameter. Per the [AWS API documentation](http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_CreateAutoScalingGroup.html), availability zones are not a required parameter when creating an auto scaling group. If you provide VPCZoneIdentifier (subnet IDs), the zone(s) is optional.

**Comment by plribeiro3000** [comment]
Closed in favor of fog/fog-aws#15
