### ISSUE TITLE
AWS AutoScaling group min_size & max_size getting set to 0

### ISSUE THREAD

**Issue by phemmer** [fog/fog#1521]
When creating an auto scaling group, the `min_size` and `max_size` parameters are getting overridden to 0. I've tried looking through the code, but the way the mappings/aliases/etc is very strange to me, so I'm not sure where the error is occurring.

The way I'm trying to create the group is:

    as = Fog::AWS::AutoScaling.new(...)
    group = as.groups.create(..., :min_size => 1, :max_size => 2, ...)

I've put in code in the `Fog::AWS::AutoScaling::Group#save` method and at that point, both `max_size` and `min_size` are `0`.

(This is with the 1.9.0 gem)

**Comment by plribeiro3000** [comment]
Closed in favor of fog/fog-aws#12
