### ISSUE TITLE
[openstack|identity] get_user_by_name request does not work as expected

### ISSUE THREAD

**Issue by rubiojr** [fog/fog#1622]
It looks like Identity.get_user_by_name returns the full list of users currently and tests fail against a real installation.

I believe @drbrain noted this first (see b430ec6a20eb1216130df5024e32d18c4a60c3d6), so the question is, should we tweak the request to return the user requested or should we remove it?

@dprince?

I'd like to open a pull request if there's consensus around this feature.

**Comment by plribeiro3000** [comment]
Closed in favor of fog/fog-openstach#37.
