### ISSUE TITLE
Excon::Errors::SocketError Broken pipe (Errno::EPIPE)

### ISSUE THREAD

**Issue by shosanna** [fog/fog#1659]
When I try to upload an image with carrierwave/fog, I'm getting

```
Excon::Errors::SocketError in PhotosController#create
Broken pipe (Errno::EPIPE)
```

uploading just to the filesystem works, the problem is just when using S3. Here's my config

``` ruby
CarrierWave.configure do |config|
  config.fog_credentials = {
    :provider               => "AWS",
    :aws_access_key_id      => ENV["AWS_KEY"],
    :aws_secret_access_key  => ENV["AWS_SECRET"],
    :host                   => "s3.amazonaws.com",
    :endpoint               => "https://s3.amazonaws.com",
    :region                 => 'eu-west-1'
  }
  config.fog_directory  = 'foo'
  config.fog_public     = true
  config.fog_attributes = {'Cache-Control'=>'max-age=315576000'}
end
```

There's nothing special going on in the controller

``` ruby
class PhotosController < ApplicationController

  def create
    photo = Photo.create!(params[:photo])
    redirect_to photo.activity
  end

end
```

**Comment by pwenig** [comment]
Just came across @marcamillion comment and that was exactly my problem! Thanks!

**Comment by codeodor** [comment]
I ran into this after having openssl on the server updated. As soon as I restarted our app, the error went away.

**Comment by mike1011-xor** [comment]
I have to make my bucket accessible and then it worked.As there was no sensitive data being added just images, I made my bucket public and it started working.

**Comment by bchellingworth** [comment]
For me the issue was AWS permissions, I had given my IAM user permission to read and write only to the root of the bucket but not sub directories. I fixed it by changing my permissions to:

"Resource": [
                "arn:aws:s3:::bucketName/*",
                "arn:aws:s3:::bucketName"
            ]

**Comment by geemus** [comment]
@bchellingworth - got it, thanks for sharing what you found.
