### ISSUE TITLE
add missing attributes to aws describe_reserved_instances parser

### ISSUE THREAD

**Issue by geemus** [fog/fog#1746]
In particular it looks like tagSet, instanceTenancy, currencyCode, recurringCharges:amount and recurringCharges:frequency. See: http://docs.aws.amazon.com/AWSEC2/latest/APIReference/ApiReference-ItemType-DescribeReservedInstancesResponseSetItemType.html

Also, since tagSet has <item> tags it is throwing off the parser when tags are present to make it appear as though there are one or more (empty) instances in the return value.

**Comment by plribeiro3000** [comment]
closed in favor of fog/fog-aws#13
