### ISSUE TITLE
[aws|dns] Excon::Errors::SocketError: SSL_write:: bad write retry (OpenSSL::SSL::SSLError)

### ISSUE THREAD

**Issue by promisedlandt** [fog/fog#1783]
Hi,
I get `Excon::Errors::SocketError: SSL_write:: bad write retry (OpenSSL::SSL::SSLError)` when trying to access my AWS dns zones.
Any idea what might cause this?

Problem is, I can't reproduce it well. I get the error during chef runs, where I call fog from within a cookbook.
However, if I execute the same code in irb, everything works perfectly fine.

The offending code snippet is [here](https://github.com/promisedlandt/cookbook-amazon_dns/blob/master/providers/zone.rb#L9), the connection is defined [here](https://github.com/promisedlandt/cookbook-amazon_dns/blob/master/libraries/amazon_dns.rb#L11).

Full stack trace [here](https://gist.github.com/promisedlandt/5479340).

I'm guessing there's some timing problems involved, like the connection being opened and timing out, but usually when you try to execute anything on a stale connection, you get EOFError, so I'm stumped.

Further information:
ruby 1.9.3p286
fog 1.10.1
excon 0.20.1

Happens on Ubuntu 12.04, 13.04, Debian 6.0.5, 6.0.6

**Comment by brenguy** [comment]
@geemus thanks that worked for me too!
