### ISSUE TITLE
Excon::Errors::BadRequest when uploading big file to AWS

### ISSUE THREAD

**Issue by perlun** [fog/fog#1883]
Hi,

Trying to upload a big file (> 1 MiB) to AWS, which seems rather hard. I did look at #1731 and got some inspiration from there, however the suggested fix (to explicitly specify region was not enough for me).

Small files work great, no worries. It's only with bigger (= chunked) files that we run into problems.

Without specifying multipart_chunk_size, I get a boring "Connection reset by peer" in excon/connection.rb. When specifying a multipart_chunk_size which is low enough (in this case, 128 KiB seems to be the "magic number" - 256 KiB throws exceptions, 128 KiB works better), the upload progresses fine _until_ it should be "ready" and mark the multipart as complete. Then it fails like this:

```
Excon::Errors::BadRequest: Expected(200) <=> Actual(400 Bad Request)
              response_call at /Users/plundberg/.rvm/gems/jruby-1.7.2/gems/excon-0.24.0/lib/excon/middlewares/expects.rb:6
                   response at /Users/plundberg/.rvm/gems/jruby-1.7.2/gems/excon-0.24.0/lib/excon/connection.rb:353
                    request at /Users/plundberg/.rvm/gems/jruby-1.7.2/gems/excon-0.24.0/lib/excon/connection.rb:247
                    request at /Users/plundberg/.rvm/gems/jruby-1.7.2/gems/fog-1.11.1/lib/fog/core/connection.rb:21
                    request at /Users/plundberg/.rvm/gems/jruby-1.7.2/gems/fog-1.11.1/lib/fog/aws/storage.rb:506
  complete_multipart_upload at /Users/plundberg/.rvm/gems/jruby-1.7.2/gems/fog-1.11.1/lib/fog/aws/requests/storage/complete_multipart_upload.rb:33
             multipart_save at /Users/plundberg/.rvm/gems/jruby-1.7.2/gems/fog-1.11.1/lib/fog/aws/models/storage/file.rb:278
                       save at /Users/plundberg/.rvm/gems/jruby-1.7.2/gems/fog-1.11.1/lib/fog/aws/models/storage/file.rb:208
                     create at /Users/plundberg/.rvm/gems/jruby-1.7.2/gems/fog-1.11.1/lib/fog/core/collection.rb:52
                     (root) at spam.rb:19
```

I added some debugging code in expects.rb and got this (removed potentially sensitive info):

``` xml
<Error>
<Code>EntityTooSmall</Code>
<Message>Your proposed upload is smaller than the minimum allowed size</Message>
<ETag>...</ETag>
<MinSizeAllowed>5242880</MinSizeAllowed>
<ProposedSize>131072</ProposedSize>
<RequestId>...</RequestId><HostId>...</HostId>
<PartNumber>1</PartNumber>
</Error>
```

So... does this mean that I cannot chunk the data in smaller chunk than 5 megs? :) Awkward, since that was my only way to get the file up at all...

Any ideas? I'm 100% sure that the region is correct (eu-west-1), I verified that with 3Hub.

**Comment by perlun** [comment]
> Whats the status quo on this one?

I think the problem still persists, but as I changed to `aws-sdk-ruby`, it hasn't really bothered me. :smile:

**Comment by geemus** [comment]
fair enough
