### ISSUE TITLE
Unable to list all domains on XenServer via LibVirt

### ISSUE THREAD

**Issue by avic85** [fog/fog#2002]
[bin]# ./fog
[WARNING] Unsupported StormOnDemand service: network
[WARNING] Unsupported StormOnDemand service: storage
[WARNING] Unsupported StormOnDemand service: dns
[WARNING] Unsupported StormOnDemand service: billing
[WARNING] Unsupported StormOnDemand service: monitoring
[WARNING] Unsupported StormOnDemand service: support
[WARNING] Unsupported StormOnDemand service: account
[WARNING] Unsupported StormOnDemand service: vpn
  Welcome to fog interactive!
  :default provides Libvirt and Openvz

> > conn=Fog::Compute.new({:provider => "Libvirt", :libvirt_uri => "xenapi://192.168.110.14:443/?no_verify=1"})
> > # <Fog::Compute::Libvirt::Real:23081120 @uri=#<Fog::Compute::LibvirtUtil::URI:0x00000002c05b00 @parsed_uri=#<URI::Generic:0x00000002c057b8 URL:xenapi://192.168.110.14:443/?no_verify=1>, @uri="xenapi://192.168.110.14:443/?no_verify=1"> @ip_command=nil @client=#Libvirt::Connect:0x00000001a59cf8>
> > 
> > conn.servers.all
> > Libvirt::RetrieveError: Call to virDomainAutostart failed: An error occurred, but the cause is unknown
> >         from /opt/rh/ruby193/root/usr/local/share/gems/gems/fog-1.14.0/lib/fog/libvirt/requests/compute/list_domains.rb:62:in `autostart?'
> >         from /opt/rh/ruby193/root/usr/local/share/gems/gems/fog-1.14.0/lib/fog/libvirt/requests/compute/list_domains.rb:62:in`domain_to_attributes'
> >         from /opt/rh/ruby193/root/usr/local/share/gems/gems/fog-1.14.0/lib/fog/libvirt/requests/compute/list_domains.rb:16:in `block in list_domains'
> >         from /opt/rh/ruby193/root/usr/local/share/gems/gems/fog-1.14.0/lib/fog/libvirt/requests/compute/list_domains.rb:16:in`map'
> >         from /opt/rh/ruby193/root/usr/local/share/gems/gems/fog-1.14.0/lib/fog/libvirt/requests/compute/list_domains.rb:16:in `list_domains'
> >         from /opt/rh/ruby193/root/usr/local/share/gems/gems/fog-1.14.0/lib/fog/libvirt/models/compute/servers.rb:13:in`all'
> >         from (irb):2:in `<top (required)>'
> >         from /opt/rh/ruby193/root/usr/local/share/gems/gems/fog-1.14.0/bin/fog:76:in`block in <top (required)>'
> >         from /opt/rh/ruby193/root/usr/local/share/gems/gems/fog-1.14.0/bin/fog:76:in `catch'
> >         from /opt/rh/ruby193/root/usr/local/share/gems/gems/fog-1.14.0/bin/fog:76:in`<top (required)>'
> >         from ./fog:23:in `load'
> >         from ./fog:23:in`<main>'

**Comment by MrMEEE** [comment]
I'm still seeing this on RHEL7, with version 1.24.0???

**Comment by MrMEEE** [comment]
I get the:
Libvirt::RetrieveError: Call to virDomainAutostart failed: An error occurred, but the cause is unknown
