### ISSUE TITLE
auto_scaling_group.instances does not return only instances for that group

### ISSUE THREAD

**Issue by akatz** [fog/fog#2019]
here's a gist that shows the problem:
https://gist.github.com/akatz/798561a1f893b8a6750f

but essentially calling instances on an autoscaling group returns all auto scaling instances. I def don't expect that.

Relevant line here:
https://github.com/fog/fog/blob/master/lib/fog/aws/models/auto_scaling/group.rb#L77-L79

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-aws#11
