### ISSUE TITLE
[rackspace|storage] Retrieve both SSL and non-SSL public URLs for a file

### ISSUE THREAD

**Issue by samsonjs** [fog/fog#2055]
This request actually bleeds out of Rackspace land into the generic storage API. It would be great to have a way to get both the SSL and non-SSL public URLs for a file without creating 2 separate Storage instances with `rackspace_cdn_ssl: true` on one but not on the other.

I have a real world use case where we store and use both URLs after creating a file and it would be great if it were easier to access both of them. If this is something that would be considered I can start working on a pull request.

Thoughts?

**Comment by Veejay** [comment]
Hello, given the information given on http://www.rackspace.com/blog/rackspace-cloud-files-cdn-launches-ssl-delivery/ it seems like to get the `https://` URI for a give file, I would have to call `public_url` and then massage the returned URI (i.e. change the protocol and the `rXX` to `ssl`). 

Is it the only way to this day or is there a method similar to `get_https_url` that actually returns the `https://` version of the URI to a file located on a CDN?

**Comment by geemus** [comment]
@mdarby could you help out here? thanks!

**Comment by mdarby** [comment]
Will look today

**Comment by ciberch** [comment]
Did this get resolved ?

**Comment by mdarby** [comment]
Looking through the CDN API docs (https://developer.rackspace.com/docs/cdn/v1/developer-guide/) I'm not seeing a way to list CDN files. Could someone please provide a bit more detail (code example would be great) of how you're accessing the url of a CDN asset?
