### ISSUE TITLE
vSphere vm_clone a template to another datacenter/resource pool

### ISSUE THREAD

**Issue by snobear** [fog/fog#2233]
Is it possible to clone a template to a VM in another datacenter?  I have a vm template that exists in datacenter "Foo" and I'd like to deploy a VM from that template to datacenter "Bar".  I'm able to clone to datacenter "Foo", presumably because its the same datacenter where the template resides.

From reading the docs, it seems like `resource_pool` is the option to use for specifying the destination?  Here's what I'm trying:

```
connection = Fog::Compute.new(credentials)

options = {"wait"=>true,
 "numCPUs"=>1,
 "memoryGB"=>1,
 "datacenter"=>"Foo",
 "datastore"=>"VM NFS Mount",
 "network_label"=>"172.10.16.x",
 "resource_pool"=>["Bar", "Bar Cluster"],
 "template_path"=>"centos_6_4",
 "power_on"=>true,
 "customization_spec"=>
  {"domain"=>"example.com",
   "hostname"=>"test01",
   "ipsettings"=>
    {"gateway"=>["172.10.16.1"],
     "ip"=>"172.10.31.2",
     "subnetMask"=>"255.255.240.0"}},
 "name"=>"Test01"}
```

This results in:

```
/usr/lib/ruby/gems/1.8/gems/fog-1.15.0/lib/fog/vsphere/requests/compute/get_resource_pool.rb:16:in `get_raw_resource_pool': undefined method `resourcePool' for nil:NilClass (NoMethodError)
        from /usr/lib/ruby/gems/1.8/gems/fog-1.15.0/lib/fog/vsphere/requests/compute/vm_clone.rb:97:in `vm_clone'
        from ./deploy.rb:148
```

Leaving off the `resource_pool` option, it clones successfully to the same datacenter, so as I said no problem there.  

I'm sure that Bar and Bar Cluster exist, to I'm not sure what I'm doing wrong.  Let me know if I can grab some debug info. 

Great work on fog and thanks for the help.

**Comment by synthead** [comment]
+1

This would be a great feature to have!
