### ISSUE TITLE
AWS CloudFormation ListStacks options

### ISSUE THREAD

**Issue by asaenz** [fog/fog#2287]
Hello,

I've been using the API for CloudFormation, and I noticed that in list_stacks,  to give the StackStatusFilter option, instead of specifying an array of members for the option such as 
```{"StackStatusFilter"=>["CREATE_IN_PROGRESS", "CREATE_COMPLETE"...]}```
I have to do something like 
```
{"StackStatusFilter.member.1"=>"CREATE_FAILED", "StackStatusFilter.member.2"=>"CREATE_IN_PROGRESS"}
```

Is this intentional?  I know AWS APIs require StackStatusFilter.member.N, but in other API calls with Fog, instead of specifying .member for each option, I can just pass in an array (create_stack has examples of this in their options, with Parameters/Capabilities)

**Comment by plribeiro3000** [comment]
Closed in favor of fog/fog#24
