### ISSUE TITLE
cannot seem to get fog to connect to s3 at all...

### ISSUE THREAD

**Issue by rwboyer** [fog/fog#2357]
I ran into this problem trying to use another gem that uses fog and wanted to attempt to debug if it was that other gem or me or fog but here's what I get...

```
Excon::Errors::SocketError: hostname "typkit.rwboyer.com.s3.amazonaws.com" does not match the server certificate (OpenSSL::SSL::SSLError)
```

Using the latests greatest gems on rubygems for Fog and for excon as of today (and the previous versions as well)...

I get the same exact errors using even this really simple code:

```
fog = Fog::Storage.new(
    :provider => "AWS",
    :aws_access_key_id => ENV['AMAZON_ACCESS_KEY_ID'], 
    :aws_secret_access_key => ENV['AMAZON_SECRET_ACCESS_KEY']
)

directory = fog.directories.get("typkit.rwboyer.com")
```

the environment is fine considering it's used for all my production s3 stuff just doesn't seem to work here. What am I doing wrong or is it some sort of bug???

Thanks

RB

**Comment by shwoodard** [comment]
I'm having this issue, but I don't have dots in my bucket name.  It is like, `foo-bar`.

**Comment by geemus** [comment]
@shwoodard could you open a new issue with the relevant details to your case? Thanks!

**Comment by shwoodard** [comment]
The issue was that I am using carrierwave and it does not support the
latest fog; I did not lock it down in my Gemfile.

**Comment by geemus** [comment]
Ah, perhaps we need to nudge carrierwave to update that then.

**Comment by shwoodard** [comment]
Agreed.
