### ISSUE TITLE
[vsphere] clone a VM onto a specific network?

### ISSUE THREAD

**Issue by blysik** [fog/fog#2372]
Trying to figure out if it's possible to use vm_clone to clone a VM onto a specific network in vpshere. Reading the code, I see a network_label option, but it doesn't seem to work as I think.

Anyone do this successfully?

**Comment by rkatti** [comment]
Can I create a VM with multiple nics by passing in array instead of string ?

**Comment by nirvdrum** [comment]
When you clone a VM, the clone will have the same number of NICs as the template.  Please see earlier comments in this thread about how to adjust the NIC configuration after you've cloned.

**Comment by synthead** [comment]
Seems pretty crufty to not be able to add a certain NIC when cloning it, only to remove the NIC and add a different one after the clone.  Are there any plans to allow users to clone a VM with the NIC properly added?
