### ISSUE TITLE
There is no ability to manipulate sub-delegation NS records via Fog (tested with Route 53)

### ISSUE THREAD

**Issue by CpuID** [fog/fog#2419]
Due to the behaviour in lib/fog/aws/models/dns/records.rb on Line 37:

 36           # leave out the default, read only records
 37           data = data['ResourceRecordSets'].reject {|record| ['NS', 'SOA'].include?(record['Type'])}

We do not return any NS or SOA records in record lookups. We also can't do a record.find() and a destroy on the resulting object because of this.

This possibly makes sense for the NS and SOA record/s for the zone itself, but sometimes you have NS records in a zone for a subdomain, to perform delegation.

Please provide such a capability, thanks.

**Comment by rhenning** [comment]
@geemus @CpuID Hi gents.  We've noticed that this behavior of pruning NS & SOA records from the list of records in reponses is reflected in some other providers as well (Dyn in our case).  Thoughts on removing the reject of NS & SOA across the board?  Our use case is similar to the one @CpuID mentioned: Look up a record by name and use the value of its NS records to determine if it is delegated to another nameserver.  If not, potentially create a new NS record to delegate it.  I'm happy to work a pull request if you think the proposal is appropriate. Thanks.

**Comment by CpuID** [comment]
Seems plausible here, deferring to @geemus for a definitive answer :)

Nathan Sullivan

**Comment by geemus** [comment]
@rhenning sounds good, just let me know if I can assist. Thanks!
