### ISSUE TITLE
Digital Ocean API is not told to scrub (securely delete) VM on destroy

### ISSUE THREAD

**Issue by sneak** [fog/fog#2525]
Major security issue: the Digital Ocean API has a parameter on the destroy call to securely scrub the root blockdev on VM destroy, preventing future customers from reading the data left on disk by your VM.

This is surely a digitalocean security issue, but they're passing it on to users by making it a parameter - rather shitty of them.  This is documented in their API at https://cloud.digitalocean.com/api_access - see "scrub_data".

Fog does not pass this parameter, leaving Fog-destroyed VMs vulnerable to later customers stealing the data contained on them.

**Comment by sneak** [comment]
@cpach The “perm” in permalink means permanent.

**Comment by smiley** [comment]
@sneak This was the link at the time, not their fault. Looks like the blog was moved from `/company/blog/` to `/blog/`. Fixed link:
https://www.digitalocean.com/blog/transparency-regarding-data-security/

**Comment by geemus** [comment]
Thanks for updates.
