### ISSUE TITLE
[digitalocean|compute] Set reasonable defaults for bootstrap

### ISSUE THREAD

**Issue by icco** [fog/fog#2528]
I don't know about other compute providers, but EC2 and GCE both have `servers.bootstrap` set up so you can run it without any paramaters. It'd be nice if we set DigitalOcean up to do the same.

**Comment by petems** [comment]
I ran into this today, is there an example of what it's supposed to look like?

I dont get how you can bootstrap a given server...

**Comment by geemus** [comment]
@petems not sure I understand your question. The rough idea had been that bootstrap would provision the server and then do what was needed to get ssh setup with a particular username/password. It was seen as roughly a bare minimum needed to do interesting things and simplifying that step seemed like a nice touch. Does that make sense/help?

**Comment by petems** [comment]
Yeah, basically I didn't understand how bootstrap worked, I now get that it's how you create a server *and* bootstrap it at the same time, whereas I thought it was used to bootstrap a server that already existed:

```ruby
server = connection.servers.bootstrap({
  :name => 'test',
  :image_id => 1505447,
  :size_id => 33,
  :region_id => 4,
  :flavor_id => 66,
  :public_key_path => File.expand_path('~/.ssh/id_rsa.pub'),
  :private_key_path => File.expand_path('~/.ssh/id_rsa'),
})
server.wait_for { ready? }
```

I might do a PR to add some docs to the DO stuff to help out the next person who gets as stumped as I do. And possibly to fix this issue also by adding sensible defaults :smile:

**Comment by geemus** [comment]
@petems yep, sounds good, thanks!

**Comment by wolf31o2** [comment]
Sensible defaults is difficult on DO, because fog uses the image ID, which changes over time and DO even removes the older ones. Rather, we need to use the "slug names" that DO provides. See https://github.com/test-kitchen/kitchen-digitalocean/issues/7 for more information.

**Comment by geemus** [comment]
see also #3437

**Comment by tokengeek** [comment]
I'm removing the 2.0 milestone since this might be worth looking at _after_ 2.0 but it isn't something I'd want to block a release.

**Comment by geemus** [comment]
Sounds good.

On Wed, Feb 25, 2015 at 3:56 PM, Paul Thornthwaite <notifications@github.com
