### ISSUE TITLE
[OpenStack] Instance addresses are assumed to always be named 'public' or 'private'

### ISSUE THREAD

**Issue by devcamcar** [fog/fog#2559]
I have a cloud where the default names of 'public' and 'private' are not used for the collection of addresses returned upon a new server's creation.  Newer OpenStack deployments offer metadata along with the addresses to give a hint as to whether they are public or private, but given that with Neutron you can have arbitrary numbers of networks and IP addresses, simply assuming 'public' and 'private' here is insufficient.

Most OpenStack deployments have an extension enabled that gives you metadata called OS-EXT-IPS which gives you a hint as to whether the IP address is public or private.  There is a 'type' field which can contain the following values: "fixed", "floating", where fixed is assumed private and floating is assumed public.

For more detail:
https://github.com/openstack/nova/blob/master/doc/api_samples/OS-EXT-IPS/servers-detail-resp.json

**Comment by wolf31o2** [comment]
We have a pretty bad hack in our fog-based fog_provider plugin for [caskdata/coopr-provisioner](https://github.com/caskdata/coopr-provisioner) where we look for 'public' then 'private' then fall back to the first network. Obviously, this isn't the best and we're going to take an approach more like opscode/knife-openstack#85 and allow specifying the network name. Currently, we require the network UUID(s) and the first network listed is the "access" network.

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-openstack#39
