### ISSUE TITLE
Replace/phase out current data validator with JSON schema

### ISSUE THREAD

**Issue by tokengeek** [fog/fog#2626]
This was just raised on #1266 

The current code for testing if the data from an API response is limited and a bit buggy (https://github.com/fog/fog/blob/master/lib/fog/schema/data_validator.rb)

I already had a major clean up on it whilst keeping backward compatibility but there's still a few corner cases I find and it's missing functionality.

At Brightbox we've been testing our JSON output using https://github.com/hoxworth/json-schema with much better results.

Despite the name it is not JSON specific and it can verify one hash structure against the schema in another. It just uses JSON schema's terms/names/keys/structure not _only JSON_.

Unlike a real XML validator it's fairly lightweight so could be included and used by either JSON or XML apis to ensure the `data` hash after parsing matches a schema.

So I propose that we add a new version of the helper that can be used to replace our undocumented schemas over a transitional period.

This will add new helpers to https://github.com/fog/fog/blob/master/tests/helpers/formats_helper.rb and require updates to the schemas.

I expect including schema files (rather than schemas as Ruby hashes) would be acceptable but making external calls to gain a schema would not be.

**Comment by geemus** [comment]
Might be interesting for net new work, but I suspect migrating all the old stuff may be more trouble than it is worth. I leave that to the consideration of individual contributors though, who I would certainly welcome to explore as time and interest allow.
