### ISSUE TITLE
Support AWS Support API

### ISSUE THREAD

**Issue by sodabrew** [fog/fog#2656]
Amazon provides an API for managing support tickets. It'd be awesome for Fog to provide these APIs. http://docs.aws.amazon.com/awssupport/latest/APIReference/Welcome.html

I volunteer to write the support for the AWS Support API. I'm submitting the ticket as a placeholder in case anybody else is working on this as well - or in case the Fog maintainers object before I put too much time into it.

**Comment by plribeiro3000** [comment]
Closed in favor of fog/fog-aws#22
