### ISSUE TITLE
Mocking fog S3 file copy not including options hash

### ISSUE THREAD

**Issue by Matt888** [fog/fog#2686]
I'm noticing that when I try to fake a file copy to set a content-type in the options hash, the file doesn't get updated with the content-type option I'm trying to set:

```
Fog.mock!
file = fog_dir.files.create(:key => "image.png", :public => true)

options = {
  'Content-Type' => "image/png",
  'x-amz-metadata-directive' => 'REPLACE'
}
file.copy file.directory.key, file.key, options

# Failing
fog_dir.files.head(file_name).content_type.should eql "image/png"
```

Also see my stackoverflow question http://stackoverflow.com/questions/21835327/faking-fog-s3-file-copy

**Comment by Hellopenope** [comment]
@geemus This still appears to be a bug for me (using the **fog-aws 1.4.1** gem).  Any chance you could point me to the commit that fixed this?

**Comment by geemus** [comment]
@Hellopenope good question. It would presumably be in this region: https://github.com/fog/fog-aws/blob/09a405cc1474636f436406fc31c7b8baebaead8f/lib/fog/aws/requests/storage/copy_object.rb#L43. But upon further review it's not jumping out at me. So perhaps either I was incorrect before, or we had a regression. I think my previous suggestion of borrowing logic from put_object likely still stands though. Would you be willing to help us with that? Thanks!
