### ISSUE TITLE
VM rename isn't persistant (vCloud Director)

### ISSUE THREAD

**Issue by g3kk0** [fog/fog#2761]
Re-opened as the suggested fix (calling 'save' method) doesn't work.

Renaming a VM doesn't appear to work/persist in vCloud Director:

irb(main):085:0* vm
=> id="vm-fkgdcca5-725a-4e87-bff3-46ef41480b53",
vapp_id="vapp-56ab1743-d41e-42c3-8bad-8d1a958dc119",
vapp_name="testbox",
name="centos65x64",
type="application/vnd.vmware.vcloud.vm+xml",
href="https://myvdc.example.com/api/vApp/vm-fkgdcca5-725a-4e87-bff3-46ef41480b53",
status="off",
operating_system="Red Hat Enterprise Linux 6 (64-bit)",
ip_address="",
cpu=2,
memory=2048,
hard_disks=[{"Hard disk 1"=>10240}]
>

Editing it just as you would for cpu or memory changes it but it doesn't remain changed after a reload.

irb(main):105:0* vm.name = "node1"
=> "node1"

irb(main):085:0* vm
=> id="vm-fkgdcca5-725a-4e87-bff3-46ef41480b53",
vapp_id="vapp-56ab1743-d41e-42c3-8bad-8d1a958dc119",
vapp_name="testbox",
name="node1",
type="application/vnd.vmware.vcloud.vm+xml",
href="https://myvdc.example.com/api/vApp/vm-fkgdcca5-725a-4e87-bff3-46ef41480b53",
status="off",
operating_system="Red Hat Enterprise Linux 6 (64-bit)",
ip_address="",
cpu=2,
memory=2048,
hard_disks=[{"Hard disk 1"=>10240}]
>

irb(main):085:0* vm.reload
=> id="vm-fkgdcca5-725a-4e87-bff3-46ef41480b53",
vapp_id="vapp-56ab1743-d41e-42c3-8bad-8d1a958dc119",
vapp_name="testbox",
name="centos65x64",
type="application/vnd.vmware.vcloud.vm+xml",
href="https://myvdc.example.com/api/vApp/vm-fkgdcca5-725a-4e87-bff3-46ef41480b53",
status="off",
operating_system="Red Hat Enterprise Linux 6 (64-bit)",
ip_address="",
cpu=2,
memory=2048,
hard_disks=[{"Hard disk 1"=>10240}]
>

Calling the suggested vm.save method doesn't work as the method doesn't seem to exist like it does for the network object.

irb(main):033:0> vm.save
NoMethodError: undefined method save' for #<Fog::Compute::VcloudDirector::Vm:0x000000019e48b8>
from (irb):33
from /home/mnewman/.rbenv/versions/1.9.3-p448/bin/irb:12:in'

**Comment by alliantist** [comment]
Hi there, any chance you could expand on how to implement this workaround?
```
v = Fog::Compute::VcloudDirector.new(vcloud_director_username: "#{user}@#{org}",
                                      vcloud_director_password: pass,
                                      vcloud_director_host: host,
                                      vcloud_director_show_progress: true)

vm_id=v.organizations.get_by_name(org).vdcs.first.vapps.first.vms.first.id

v.put_vm(vm_id, 'new-vm-name')
ArgumentError: wrong number of arguments (2 for 3)

v.service.put_vm(vm_id, 'new-vm-name')
NoMethodError: undefined method `put_vm' for Fog::Compute::VcloudDirector:Class
```

**Comment by trilitheus** [comment]
Hi there, any chance you could expand on how to implement this workaround?
```
v = Fog::Compute::VcloudDirector.new(vcloud_director_username: "#{user}@#{org}",
                                      vcloud_director_password: pass,
                                      vcloud_director_host: host,
                                      vcloud_director_show_progress: true)

vm_id=v.organizations.get_by_name(org).vdcs.first.vapps.first.vms.first.id

v.put_vm(vm_id, 'new-vm-name')
ArgumentError: wrong number of arguments (2 for 3)

v.service.put_vm(vm_id, 'new-vm-name')
NoMethodError: undefined method `put_vm' for Fog::Compute::VcloudDirector:Class
```

**Comment by trilitheus** [comment]
For anyone else....
```
v.put_vm(vm_id, 'new-vm-name', {})
```
This does the trick

**Comment by geemus** [comment]
@trilitheus thanks!
