### ISSUE TITLE
Fog::Compute::AWS::Flavor#cores vs vCPU vs ECU

### ISSUE THREAD

**Issue by tisba** [fog/fog#2785]
I'm working on a project, where I start instances and based on the number of available cores, I do start more or less processes (say 1 process per CPU core).

When I ask `Fog::Compute::AWS::Flavors.new.get("c3.large").cores` I get 7 (as defined in https://github.com/fog/fog/blob/master/lib/fog/aws/models/compute/flavors.rb). But 7 is the amount of ECU (EC2 Compute Unit), not the number of cores in the system.

I was wondering if this is intentional (and if I need to create my own lookup), or a mistake.

**Comment by plribeiro3000** [comment]
Closing due inactivity.

Please create a issue at [fog-aws](https://github.com/fog/fog-aws) if this issue still needs a fix.
