### ISSUE TITLE
Vsphere create blank VM - create_vm.rb issues

### ISSUE THREAD

**Issue by stefancocora** [fog/fog#2798]
I'm prototyping the creation of a blank VM, using fog and vmware and I'm hitting quite a few issues with the fog library.

**Specs:**
ruby-1.9.3-p392
fog (1.16.0)
rbvmomi (1.6.0)
VMware vsphere 4.1

**Background on the infrastructure:**
- I have a quite outdated vmware 4.1 infrastructure to deal with
- I've found that the latest fog brings as a dependency rbvmomi -v=1.8.1 which doesn't work with vsphere 4.1
- I haven't tried latest fog with rbvmomi -v=1.6.0, this might work fine ( unknown as of now )

Script that I'm using is in this gist: https://gist.github.com/stefancocora/9803779

I'm putting together a **Hash** of attributes and then calling $connection.create_vm(attributes)

@geemus has been very helpful in giving advice on using fog or what to do when fog doesn't do what I need. You can see the discussion in the comments on the already mentioned gist.

**Issues list**
The issues I've seen with fog are as follows - starting with the last and working back into history:
- Revision 7 - **fog can't find the datastore path**
```bash
/home/stefan/.rvm/gems/ruby-1.9.3-p392@fog/gems/fog-1.16.0/lib/fog/vsphere/requests/compute/create_vm.rb:27:in `rescue in create_vm': failed to create vm: Could not descend into datastores. Please check your path. datastores/GRW_VMCP_MGMT_DATA_003 (ArgumentError)
from /home/stefan/.rvm/gems/ruby-1.9.3-p392@fog/gems/fog-1.16.0/lib/fog/vsphere/requests/compute/create_vm.rb:9:in `create_vm'
from ./vsphere-grw_mgm-create_vm-prototype.rb:63:in `<main>'
```
- Revision 6 - in my Hash I was passing interfaces as a Array of Hashes but fog expects it as an $connection.interfaces.new(...) object in create_vm.rb
```ruby
:interfaces =>
[{"mac" => "00:50:56:aa:aa:aa",
"network" => "GRW-CP-MGMT-INFRA-923",
"name" => "Network adapter 1",
"status" => "ok",
"summary" => "VM Network",
}]
```
Error:
```bash
/home/stefan/.rvm/gems/ruby-1.9.3-p392@fog/gems/fog-1.16.0/lib/fog/vsphere/requests/compute/create_vm.rb:26:in `rescue in create_vm': failed to create vm: undefined method `type' for #<Fog::Compute::Vsphere::Network:0x00000003203700> /home/stefan/.rvm/gems/ruby-1.9.3-p392@fog/gems/fog-1.16.0/lib/fog/vsphere/requests/compute/create_vm.rb:70:in `create_interface' (NoMethodError)
/home/stefan/.rvm/gems/ruby-1.9.3-p392@fog/gems/fog-1.16.0/lib/fog/vsphere/requests/compute/create_vm.rb:42:in `block in device_change'
/home/stefan/.rvm/gems/ruby-1.9.3-p392@fog/gems/fog-1.16.0/lib/fog/vsphere/requests/compute/create_vm.rb:42:in `map'
/home/stefan/.rvm/gems/ruby-1.9.3-p392@fog/gems/fog-1.16.0/lib/fog/vsphere/requests/compute/create_vm.rb:42:in `device_change'
/home/stefan/.rvm/gems/ruby-1.9.3-p392@fog/gems/fog-1.16.0/lib/fog/vsphere/requests/compute/create_vm.rb:14:in `create_vm'
./vsphere-grw_mgm-create_vm-prototype.rb:63:in `<main>'
from /home/stefan/.rvm/gems/ruby-1.9.3-p392@fog/gems/fog-1.16.0/lib/fog/vsphere/requests/compute/create_vm.rb:8:in `create_vm'
from ./vsphere-grw_mgm-create_vm-prototype.rb:63:in `<main>'
```
- Revision 5 - I was passing the **volumes** as an Array of Hashes but fog, inside create_vm.rb expects is to be an $connection.volumes.new instance in create_vm.rb
```ruby
:volumes =>
[{
"id" => "5303693f-eae09bc7-2dc5-0017a4772800",
"datastore" => $grwmgm_datastore,
"mode" => "persistent",
"size" => 8388608,
"thin" => true,
"name" => "fogtest01",
"size_gb" => 8
}],
```
Error:
```bash
/home/stefan/.rvm/gems/ruby-1.9.3-p392@fog/gems/fog-1.16.0/lib/fog/vsphere/requests/compute/create_vm.rb:27:in `rescue in create_vm': failed to create vm: undefined method `datastore' for #<Hash:0x000000034fc920> (NoMethodError)
from /home/stefan/.rvm/gems/ruby-1.9.3-p392@fog/gems/fog-1.16.0/lib/fog/vsphere/requests/compute/create_vm.rb:9:in `create_vm'
from ./vsphere-grw_mgm-create_vm-prototype.rb:65:in `<main>'
```

**Comment by nirvdrum** [comment]
@stefancocora Thanks for the follow-up.  I don't think anyone thinks supporting vmWare 4.x is a waste of time.  But no one working on the vmWare stuff works for vmWare . . . we're all volunteers.  Volunteers naturally work with what they have. vmWare is a harder case because the ESX products with API support all require expensive licensing.

If you'd like to see better vmWare 4 support, I'd be happy to review pull requests and I can verify that changes you suggest still work in 5.x.

**Comment by stefancocora** [comment]
That is fine @nirvdrum , I completely agree and understand the lack of support on vmWare 4.x !
I've closed this ticket because it is > 1year old and by now things have changed:
- the vmWare cluster has been upgraded to 5.x
- I don't need to do any of the hacks that I needed for version 4

I've also figured I'd remove one ticket out of your queue of open tickets :)

**Comment by nirvdrum** [comment]
Thanks.  And no worries.  I just wanted to let you know that we don't have a policy actively forcing 5.x+.  But, if you're on 5.x, I guess you're now in the camp that can't test against 4.x either ;-)
