### ISSUE TITLE
diffilculty to get the specified AMI via fog from amazon

### ISSUE THREAD

**Issue by vishnurkrishnan** [fog/fog#2850]
I have been trying to get the specified OS's AMI from amazon via fog,otherwise that list all the images(images.all), which i can't populate in a single step, that taking too time. i have used the describe_image method from  Fog::Compute::AWS::Real, but how to pass the OS name(ubuntu, windows...) to get the corresponding images from amazon via fog

**Comment by plribeiro3000** [comment]
Closing due inactivity.

**Comment by geemus** [comment]
Thanks!
