### ISSUE TITLE
[aws] key_pairs is case sensitive in get() but not at AWS

### ISSUE THREAD

**Issue by dJason** [fog/fog#2906]
I ran into an issue when requesting a key_pair from AWS Compute then trying to create that key which I thought did not exist.  It appears that the key_pairs.get("Keyname") is case sensitive, while AWS is not actually case sensitive.
```
fog.key_pairs.get("Keyname") # => <Fog::Compute::AWS::KeyPair ... >
fog.key_pairs.get("keyname") # => nil
```
but
```
fog.import_key_pair("keyname", keydata) # => Duplicate => The keypair 'Keyname' already exists.
```
I saw there was already an issue open that might be related, but I don't know if it would fix this issue: https://github.com/geemus/excon/pull/376

**Comment by plribeiro3000** [comment]
Closing due inactivity.

Please create a new issue at [fog-aws](https://github.com/fog/fog-aws) if this needs to be fixed somehow.
