### ISSUE TITLE
Ec2: If DescribeInstances fails (e.g. because of permissions) on server create, fog hangs

### ISSUE THREAD

**Issue by eherot** [fog/fog#2910]
server.create just hangs until a timeout occurs.  In debug mode you can see excon retrying and receiving 403's repeatedly.

**Comment by plribeiro3000** [comment]
@geemus This is related to aws, right?

Just to make sure before move this to the [`fog-aws`](https://github.com/fog/fog-aws) repo.

**Comment by eherot** [comment]
My original request regarded aws. Not sure if the problem is unique to aws, though.

**Comment by geemus** [comment]
It is an interesting question. I guess the problem is that wait_for can loop indefinitely, but 400 series errors are unlikely to resolve themselves. Perhaps it should be a change in the wait_for logic in fog-core actually?

**Comment by plribeiro3000** [comment]
Hmmm. If it is related to the `wait_for` then we should move it to `fog-core` indeed. Can i move it? :smile:

**Comment by geemus** [comment]
go for it, thanks!

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-core#129.

Thanks!
