### ISSUE TITLE
Ftp storage ?

### ISSUE THREAD

**Issue by suruja** [fog/fog#2914]
Hello!

I am working on a Rails project which uses [asset_sync](https://github.com/rumblelabs/asset_sync) gem using fog to upload my app precompiled assets to Amazon S3. Now I need to upload my assets to a custom FTP server. I didn't find an existing fog storage to do that. Is there actually a way?

I found this related [thread](https://groups.google.com/forum/#!msg/ruby-fog/PvMDEeooCKY/arbkkaD9dH8J). The author of the post highlights the fact that FTP storage is not technically a cloud storage, which seems true to me. Is it the reason why there is no such storage?

**Comment by plribeiro3000** [comment]
@geemus Maybe we should move this to `fog-core` ?

**Comment by geemus** [comment]
@plribeiro3000 perhaps. If we were adding this, maybe it would go in something like fog-ftp though?

**Comment by plribeiro3000** [comment]
Hmmm. Can't this be like [SSH](https://github.com/fog/fog-core/blob/master/lib/fog/core/ssh.rb) ?

Or you think we should have a provider for ftp?

**Comment by geemus** [comment]
It might be fine to be like SSH, depends on how many dependencies there are and whether they are in standard library. I wouldn't want to force extra gems on everybody for this is all.

**Comment by plribeiro3000** [comment]
@geemus Good point. I was thinking it would be something really simple. Another dependency would not be welcome indeed. =s

**Comment by ginolon** [comment]
Any news on this?

**Comment by geemus** [comment]
None that I'm aware of I fear.

**Comment by plribeiro3000** [comment]
Closed in favor of #3644
