### ISSUE TITLE
AWS security group tests have become unstable

### ISSUE THREAD

**Issue by tokengeek** [fog/fog#2932]
I've been so busy travelling to the fog summit I missed that `tests/aws/requests/compute/security_group_tests.rb` has been failing randomly on different Travis settings for a while.

https://travis-ci.org/fog/fog/jobs/25614603#L1105 is one of many failures.

It seems unstable enough that every build is failing and what I have noticed (but didn't look at further) is lots of people going "Hey it's not my changes!" about something so this hasn't been looked at.

Needs fixing or I'll disable the test.

**Comment by plribeiro3000** [comment]
Closed in favor of fog/fog-aws#16
