### ISSUE TITLE
listing files in a directory with a delimiter and iterating through it seems to not work

### ISSUE THREAD

**Issue by jiteshshetty** [fog/fog#2937]
I am seeing something which is a little strange. I have a bucket on S3, I want to get all the files in that bucket but want to filter out a sub-folder I have there. So I am doing this:

`directory = S3.directories.get(fog_bucket, prefix: "gold", delimiter: "ignoreme")`

now when I do:

`directory.files.count  `

I get the right number(10), everything under ignoreme is not part of the count, but when I do this.

```ruby
directory.files.each do |file|
  p file.key
end
```

It prints out the files under ignoreme, and the loop is run 14 times, am I missing anything here?

**Comment by plribeiro3000** [comment]
Closing due inactivity. Since this specific piece of code resides in `fog-core` please open a new issue there if you still have this issue or want to provide more feedback.

Thank you!

**Comment by geemus** [comment]
Thanks!
