### ISSUE TITLE
vSphere 5.5U1 - SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by stonith** [fog/fog#2938]
I'm trying to test fog with vSphere 5.5U1 and have started with this gist example: https://gist.github.com/jedi4ever/1216529

ruby 1.9.3p448 (2013-06-27) [x86_64-linux]
fog (1.22.0)
nokogiri (1.6.2.1)
rbvmomi (1.6.0) <- Had to downgrade in order to get past RuntimeError: unknown VMODL type AnyType error

However when trying to do a server list I get the error:

```
>> f.servers
SystemStackError: stack level too deep
        from /home/vagrant/.gem/ruby/1.9.1/gems/fog-core-1.22.0/lib/fog/core/attributes.rb:14
```

**Comment by bigon** [comment]
Hello,

It seems that the patches proposed in the bug have been merged in 1.24.

**Comment by timuralp** [comment]
Correct. I think we can close this issue.

**Comment by geemus** [comment]
Thanks!
