### ISSUE TITLE
[vsphere] modify vm_clone request to perform a windows sysprep on the image

### ISSUE THREAD

**Issue by rob12** [fog/fog#2954]
I need to modify the Vsphere vm_clone request so that when a windows VM is cloned, it is sysprep'd, and joined to an AD domain.  

In summary, this will involve replacing the current RbVmomi::VIM::CustomizationLinuxPrep object that is passed to the Vsphere API with an RbVmomi::VIM::CustomizationSysprep (parameter based), or RbVmomi::VIM::CustomizationSysprepText (to use an unattend.xml rendered from ERB).

Would the maintainers prefer that this work be done in the current vm_clone request (making decisions on the OS type), or would it be better to create something like a vm_win_clone request?

Any other requirements?

**Comment by sofam** [comment]
@rob12 also looking for info on how to pass the customization spec to foreman!

**Comment by fherbert** [comment]
I've modified to vm_clone.rb and cloudinit_to_customspec.rb to support the full vmware customization spec. I've submitted a pull request https://github.com/fog/fog/pull/3523

**Comment by geemus** [comment]
Awesome, thanks!

**Comment by plribeiro3000** [comment]
It seems that this issue was resolved with a PR to support full vmware customization spec at #3253

Closing.

Comment back if this is not the case.

Thanks!
