### ISSUE TITLE
[centurylink] Initial take at the centurylink cloud API

### ISSUE THREAD

**Issue by dJason** [fog/fog#2958]
I've been working on some initial implementation to the CenturyLink Cloud API.  They are still developing and implementing their v2 API, I implemented a few of the available requests but none of the models.  I did implement a bit of the v1 API, at least as much as I needed for my project.
I'm not too familiar with the testing requirements of a new provider, I could use some discussion and guidance on what should be added at this point.

**Comment by plribeiro3000** [comment]
Closing due inactivity. If you guys still pretend to add support to `Centurylink` let us know so we can setup a repo for `fog-centurylink`.

Thanks for your interest in adding support for `centurylink` in fog!

**Comment by geemus** [comment]
Thanks!

**Comment by allomov** [comment]
Hey, everyone! Is there are any news on implementing `for-centurylink` project?

**Comment by plribeiro3000** [comment]
Not that i know of. Let me add it to the list of requests at #3644 .
