### ISSUE TITLE
[google|compute] Remove hard-coded /projects/google/

### ISSUE THREAD

**Issue by erjohnso** [fog/fog#2981]
@icco - We're going to be getting rid of /projects/google which fog primarily uses for looking up images.  It only houses deprecated images now, so I'll send along a PR to pull that out of the image search.

**Comment by plribeiro3000** [comment]
@erjohnso Did you get a chance to open a PR for this?

**Comment by erjohnso** [comment]
No, I didn't but @icco did [https://github.com/fog/fog/commit/5f7886e08d0ecd7d84264fb9c8e1cc05ef085427]. We just forgot to close this issue (doing that now).

**Comment by plribeiro3000** [comment]
Thx @erjohnso !

**Comment by geemus** [comment]
Thanks!
