### ISSUE TITLE
RiakCS ACL 

### ISSUE THREAD

**Issue by panteo** [fog/fog#2985]
### Disclaimer

This is my first public contribute to the community and I'm not native english, so, please, help me if I'm doing something wrong. Thanks. ;-)

### Problem

I have a problem with `put_bucket_acl` and I can't figure if it's a bug or it's related to my config.

After PUT, grantee ID and DisplayName are set to nil but Permission is correctly updated. Removing the new lines and with spaces from body solved the problem.

[Here](https://github.com/panteo/fog/commit/663f922a65814f37ef9e495aa9aae6bba10f9bf9) it is my patch.

### About my config (One RiakCS server)

OS: Ubuntu 14.04 LTS x86_64
Kernel: 3.13.0-27-generic
RiakCS: 1.4.5-1
Riak: 1.4.9-1
Nginx: 1.4.6-1ubuntu3
Protocol: HTTPS with valid wildcard certificate

**Comment by plribeiro3000** [comment]
I will move this issue to fClosing in favor of fog/fog-riakcs#1.

Please comment and follow development from there. Thanks!
