### ISSUE TITLE
availability zone is ignored when creating volume

### ISSUE THREAD

**Issue by dennis-sig** [fog/fog#3011]
It seems that Fog ignores the value of the availability_zone parameter when creating OpenStack volumes. In https://github.com/fog/fog/blob/master/lib/fog/openstack/models/compute/volume.rb line 28 I would expect this argument to be passed to the create_volume call, but it's not. 

If this is by design, for example because there are problems with the OpenStack API when using this feature, it should be documented; but I would currently consider this a bug.

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-openstack#40
