### ISSUE TITLE
virtualization-type is missing from Fog::Compute::AWS::Image model response.

### ISSUE THREAD

**Issue by CpuID** [fog/fog#3019]
There looks to be a mapping in lib/fog/aws/requests/compute/describe_images.rb for:

'virtualization-type' => 'virtualizationType'

But it doesn't look to be part of the model result?

http://docs.aws.amazon.com/AWSEC2/latest/APIReference/ApiReference-query-DescribeImages.html

      <virtualizationType>paravirtual</virtualizationType>

Running fog 1.22.1 / fog-core 1.22.0

Example:

```
   <Fog::Compute::AWS::Image
    id="ami-fd2954cd",
    architecture="x86_64",
    block_device_mapping=[{"deviceName"=>"sdb", "virtualName"=>"ephemeral0"}, {"deviceName"=>"sdc", "virtualName"=>"ephemeral1"}],
    description=nil,
    location="s3_bucket_name/image.manifest.xml",
    owner_id="xxxxxxx",
    owner_alias=nil,
    state="available",
    type="machine",
    is_public=false,
    kernel_id="aki-xxxxxxxx",
    platform=nil,
    product_codes=[],
    ramdisk_id=nil,
    root_device_type="instance-store",
    root_device_name="/dev/sda1",
    tags={"Name"=>"ami_name"},
    name="AMI Name"
  >]
```

**Comment by plribeiro3000** [comment]
Closing due inactivity.

Please open a new issue at [fog-aws](https://github.com/fog/fog-aws) if this still need a fix.

Thanks!
