### ISSUE TITLE
[google|compute] Incorrect arguments for some operations.get calls causes exceptions

### ISSUE THREAD

**Issue by ashmrtnz** [fog/fog#3029]
The recent update to google/models/compute/target_pool.save and google/models/compute/forwarding_rule.save pass operations.get incorrect arguments which in turn throws an error when wait_for is called on a nil object. My colleague or I will be submitting a pull request soon to fix this

**Comment by plribeiro3000** [comment]
I'm closing this issue in favor of fog/fog-google#39.

If you have something to share, please do so there. Thanks!
