### ISSUE TITLE
Domain support in Identity v3

### ISSUE THREAD

**Issue by stenstad** [fog/fog#3084]
With the Identity v2.0 API marked as deprecated in Icehouse (alltho reverted after release), cloud providers are starting to require using the v3 API to authenticate.

This is needed to support domains, to achieve full multi-tenancy in public clouds.

The v2.0 API seems to be scheduled for removal in the Kilo release next year.

Please look into supporting v3 and domains.

Documentation for the v3 API:
* http://api.openstack.org/api-ref-identity-v3.html

Aviator support for v3 API:
* https://github.com/aviator/aviator/blob/master/lib/aviator/openstack/identity/requests/v3/public/create_token.rb

**Comment by dhague** [comment]
Within my team at SAP we are working on an implementation of identity v3 for Fog. Additionally, we have monkey-patched some existing Fog::*::OpenStack classes to support v3 authentication (these could be patched back into the main Fog code, of course). Would it be useful for us to contribute these enhancements back to Fog?

**Comment by plribeiro3000** [comment]
@dhague Pull requests are always welcome!

**Comment by geemus** [comment]
Agreed, just let us know if you have questions or there is anything we can help with. Thanks!

**Comment by dhague** [comment]
Great - thanks, guys. I will let you know as soon as we have something ready, hopefully in the next few weeks.

**Comment by dhague** [comment]
Hi folks,

I am now looking at merging our Identity V3 implementation into Fog. Currently we are using the class Fog::IdentityV3::OpenStack so that it can coexist with Fog::Identity::OpenStack - does that sounds OK, or is there some other pattern to follow when having parallel implementations of 2 API versions?

Thanks,
Darren

**Comment by geemus** [comment]
We hadn't run into it too much (non-openstack doesn't change quite so quickly or drastically). The only other example I can think of off hand would be rackspace and looking at their code it appears it basically follows a similar pattern. I guess the part that sticks out to me is where the nesting is here.

You suggest `Fog::IdentityV3::OpenStack` which seems a bit strange, as other identity stuff wouldn't be V3 per se. I guess I would expect `Fog::OpenStack::IdentityV3` or maybe `Fog::Identity::OpenStackV3`. ie the final, most nested part is versioned, not the containing thing. Does that help/make sense?

**Comment by TerryHowe** [comment]
Any progress is good progress, but it would be kind of nice if the auth url was v2 Fog::Identity::OpenStack was magically a v2 version and if the auth url was v3 it was a v3 version.

**Comment by geemus** [comment]
Yeah, you could just ask for Fog::Identity::Openstack.new to take a version param explicitly also, and switch based on that or something maybe?

**Comment by TerryHowe** [comment]
Well, all the services use this logic which looks good to me:

https://github.com/fog/fog/blob/master/lib/fog/openstack/compute.rb#L413

**Comment by dhague** [comment]
@geemus: All the other OpenStack services follow the pattern Fog::<ServiceName>::Openstack, so Fog::OpenStack::IdentityV3 doesn't quite fit. Using OpenStackV3 would suggest that this is V3 of OpenStack, also not quite right. Maybe Fog::Identity::OpenStack::V3?
@TerryHowe: So I guess that we could rename the current Fog::Identity::OpenStack to Fog::Identity::OpenStack::V2, and then it's just a matter of implementing a new Fog::Identity::OpenStack to inspect the URL and return a V2 or V3 object accordingly - something like the code snippet here: http://stackoverflow.com/questions/11074175/how-to-return-new-instance-of-subclass-while-initializing-parent-class#11074206

**Comment by TerryHowe** [comment]
I like that idea @dhague

**Comment by geemus** [comment]
@TerryHowe Ah, yeah, switching on URL sounds alright. Automatic definitely beats manual, I just didn't know if that was assured to be around in all installations or whatever.

@dhague yeah, definitely agree most of those options seemed a little weird. The ...::V2 and ...::V3 version you propose sounds like a good way to do it. Thanks!

**Comment by TerryHowe** [comment]
Well, I think v2 makes a lot more sense as a default than v1 like compute is using in that example I posted above.  Should consider dropping v1 support.
