### ISSUE TITLE
Why are the credential keys not generalized?

### ISSUE THREAD

**Issue by jfelchner** [fog/fog#3165]
We're currently implementing `fog` in one of our applications and were surprised to find that all of the credential keys for each service are specific to that service.

I would have thought that I'd be able to set something like:

```
STORAGE_PROVIDER=AWS
STORAGE_USERNAME=foo
STORAGE_PASSWORD=bar
```

And in my code do something like:

```ruby
    @connection ||= Fog::Storage.new(
      provider: ENV['STORAGE_PROVIDER'],
      username: ENV['STORAGE_USERNAME'],
      password: ENV['STORAGE_PASSWORD'])
```

Considering the point of fog is that you can abstract away your cloud providers, then theoretically changing it shouldn't require a code change.

Please let me know if I'm misunderstanding.

Thanks for all the hard work on this!

**Comment by plribeiro3000** [comment]
Closed in favor of fog/fog-aws#10
