### ISSUE TITLE
AWS S3 Server Side Encryption using Customer Key(SSE-C)

### ISSUE THREAD

**Issue by tacticiankerala** [fog/fog#3168]
I was trying to use AWS S3's Server Side Encryption using Customer Key(SSE-C) - http://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html . I was successful in getting the encryption working by setting the 'fog_attributes'.

But I need to send the same headers while making a GET request for the file as well (for decrypting). Unfortunately I could not make a GET request since AWS requires a computed signature of the request. I could not get it working with Fog since it does not allow me to set custom headers and make a GET request. It would be a great if you could give me pointers to get this working.

**Comment by vysakhf22** [comment]
@tacticiankerala Hey, I tried setting the fog_attributes in the Carrierwave initializer like you have said, but I couldn't save the file, getting a Bad request from Amazon. Tried with v.0.10.0 and the master branch versions of Carrierwave. 

Can you please tell what I'm doing wrong?

**Comment by tacticiankerala** [comment]
I am not sure what could be the problem. Can you post sample code?

PS: I am going out of town for a few days. Please expect delay in response.

**Comment by vysakhf22** [comment]
@tacticiankerala Thank you :) I just got it working, had issues with proper md5 encrypt key i think

**Comment by yogeshmanjhi1993** [comment]
@tacticiankerala hey i tried the config suggested by you above 
    key = 12345678901234567890123456789012

    config.fog_attributes = {
      'Cache-Control' => 'max-age=315576000',
      'x-amz-server-side-encryption-customer-algorithm' => 'AES256',
      'x-amz-server-side-encryption-customer-key' => 'MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=',
      'x-amz-server-side-encryption-customer-key-md5' => 'dnF5x6K/8ZZRzpfSlMMM+w=='
    }
but i am getting bad request error 
```
Errors::BadRequest (Expected(200) <=> Actual(400 Bad Request)
excon.error.response
  :body          => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidArgument</Code><Message>Requests specifying Server Side Encryption with Customer provided keys must provide an appropriate secret key.</Message><ArgumentName>x-amz-server-side-encryption</ArgumentName><ArgumentValue>null</ArgumentValue><RequestId>69C751E24E09A371</RequestId><HostId>wrfZQ8ANm7DGMTqRwMD/6iiy5wGJaowsxzVUyMAIFd9kMavRFkh5YHEn6tQPZyFECRCupztPp0Q=</HostId></Error>"
```
Any idea what could be wrong.Any idea or suggestions are greatly appreciated.Thanks

**Comment by yogeshmanjhi1993** [comment]
@geemus any idea what could be wrong

**Comment by geemus** [comment]
@yogeshmanjhi1993 yes, I think your usage on the keys is a bit off. Looks like you have:

```
'x-amz-server-side-encryption-customer-key' = Base64.encode64(key)
''x-amz-server-side-encryption-customer-key-md5' = Digest::MD5.base64digest(key)
```

I think the md5 should actually be of the base64 encoded value though (instead of the key directly), so that would be like this:

```
'x-amz-server-side-encryption-customer-key' = Base64.encode64(key)
''x-amz-server-side-encryption-customer-key-md5' = Digest::MD5.base64digest(Base64.encode64(key))
```

Hope that helps!

**Comment by yogeshmanjhi1993** [comment]
@geemus no it does not work still getting the same error 
this is the converted value according to the suggestion you provided 
`    key = '12345678901234567890123456789012' 
 
    config.fog_attributes = { 
      'Cache-Control' => 'max-age=315576000', 
      'x-amz-server-side-encryption-customer-algorithm' => 'AES256', 
      'x-amz-server-side-encryption-customer-key' =>"MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=\n", 
      'x-amz-server-side-encryption-customer-key-md5' => "YsMfwjQnXXLHLb+ebyLn2Q=="
    } 
`

**Comment by yogeshmanjhi1993** [comment]
these are the headers received in response from server 
`  :cookies       => [
  ]
  :headers       => {
    "Connection"       => "close"
    "Content-Type"     => "application/xml"
    "Date"             => "Thu, 30 Nov 2017 07:09:17 GMT"
    "Server"           => "AmazonS3"
    "x-amz-id-2"       => "OyKjwz/Bs8UZ7hg0Og1O+KatLI9dYZ2L0SHfzoZhq01T57F3AwzGXUl4xPGKF+HYrZG8/CR1pIg="
    "x-amz-request-id" => "461DA687A3F1FDA8"
  }
`

**Comment by geemus** [comment]
Oops, my code was maybe a bit off. I think you will probably need to strip the "\n" character from the key before passing it (and before md5-ing) it. Maybe that will help? (unfortunately I haven't used this interface directly, trying to extrapolate from other sources and docs).

**Comment by awinabi** [comment]
In case anyone is landing here searching for the configuration for server side encryption the following is the fog_attributes to set for 

```ruby
config.fog_attributes = { 
  'Cache-Control' => 'max-age=315576000', 
  'x-amz-server-side-encryption' => 'AES256', 
  'x-amz-server-side-encryption-customer-key' =>"12345678901234567890123456789012"
} 
```

The rest will be handled by Fog internally. (see file [here](https://github.com/fog/fog-aws/blob/77c4b1e3d2f9f2a19c01c2aaba9028801a8a1266/lib/fog/aws/models/storage/file.rb#L294)
 and [here](https://github.com/fog/fog-aws/blob/77c4b1e3d2f9f2a19c01c2aaba9028801a8a1266/lib/fog/aws/models/storage/file.rb#L311))

@yogeshmanjhi1993 @geemus

**Comment by geemus** [comment]
@awinabi cool, thanks!

**Comment by i-nomads** [comment]
Just FYI I made getting the encrypted file "work" this way:

[https://github.com/i-nomads/fog-aws](url)

**Comment by geemus** [comment]
@i-nomads thanks for the heads up.

**Comment by stanhu** [comment]
FYI, there are many other calls that need to be able to pass in the headers needed for SSE-C: https://github.com/fog/fog-aws/issues/571
