### ISSUE TITLE
Lazy Fog::Storage::OpenStack connection?

### ISSUE THREAD

**Issue by ysbaddaden** [fog/fog#3194]
I'm hitting a performance issue with Fog::Storage::Openstask which authenticates to the remote server as soon as it's initialized. The `auth_token` is indeed required when interacting with the storage, yet I often just need to generate signed URL to dowload private files, but these do require the `management_url` which is received along with the `auth_token` (to extract the scheme, host and port).

I was wondering if it would be safe to provide these values or the `management_url` directly? That would enable us to have a lazy connection, which would only authenticate before making the first request. Or maybe there are reasons to not do that in the Swift protocol?

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-openstack#41
