### ISSUE TITLE
Fog::AWS::Compute::Real#describe_instances does not conform to the published query standards

### ISSUE THREAD

**Issue by brandocorp** [fog/fog#3200]
While working with an internal project aimed at providing an API compatible with with Amazon's, it was found that the  [Fog::AWS::Compute::Real#describe_instances](https://github.com/fog/fog/blob/master/lib/fog/aws/requests/compute/describe_instances.rb#L65-L67) method does not follow the published [query standards](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/Query-Requests.html#query-parameters) for Amazon Elastic Compute Cloud API.

From the API Reference:

```text
Some operations take lists of parameters. These lists are specified using the param.n notation, 
where n is an integer starting from 1.
```

From the method mentioned above:

```ruby
instance_ids.each_with_index do |id, index|
  params.merge!("InstanceId.#{index}" => id)
end
```

This leaves the body of the request with an invalid query parameter `InstanceId.0`

I can submit a pull-request if you feel this is something you you want to correct. Technically, I have zero issues using fog to talk directly to Amazon's API.

**Comment by plribeiro3000** [comment]
Closing due inactivity.

@brandocorp Please create a new issue at [fog-aws](https://github.com/fog/fog-aws) if you still need this fix or intend to work on it.
