### ISSUE TITLE
Don't add all cloud modules as gem dependencies

### ISSUE THREAD

**Issue by aaronchi** [fog/fog#3279]
The fog gem currently forces you to load a bunch of extra cloud gems as dependencies when they likely won't be used. These should not be required dependencies so users have the choice to only load the ones they use into their application.

**Comment by synthead** [comment]
+1

**Comment by Temikus** [comment]
@synthead Unless your provider wasn't separated into a metagem or you _have_ to support ruby 1.9.3, there should be no reason for you to use fog/fog instead of a specific metagem you need. See "Dependency notice" in the readme.
