### ISSUE TITLE
Libvirt VM creation: disk of file type regardless volume/pool type

### ISSUE THREAD

**Issue by clsacramento** [fog/fog#3285]
Due to libvirt /models /compute/templates/server.xml.erb, when creating a VM the disk attached is always of file type : 
```erb
<% volumes.each do |vol| -%>
    <disk type='file' device='disk'>
      <driver name='qemu' type='<%= vol.format_type %>'/>
      <source file='<%= vol.path %>'/>
      <%# we need to ensure a unique target dev -%>
      <target dev='vd<%= ('a'..'z').to_a[volumes.index(vol)] %>' bus='virtio'/>
    </disk>
<% end -%>
```

When the volume type is not file such as scsi or rbd, in my case, I get 'vol.path' file not found error from libvirt.

To get around it, replacing the code snippet to this (should be more generic?):
```erb
 <% volumes.each do |vol| -%>
    <disk type='volume' device='disk'>
      <driver name='qemu' type='<%= vol.format_type %>'/>
      <source  pool='<%= vol.pool_name' volume='<%= vol.name %>'/>
      <%# we need to ensure a unique target dev -%>
      <target dev='vd<%= ('a'..'z').to_a[volumes.index(vol)] %>' bus='virtio'/>
    </disk>
<% end -%>
```

As far as I have tested, this works for file, block and network volumes.

It does not work in my scenario because libvirt does not support attaching disk from rbd pool yet.

So I had to add a condition to determine if the pool type is rbd and then provide specific disk configuration for attaching rbd volume. The problem with this is that I had to use to the name of the pool to tell if it's rbd type, which is not very clean. I also had to load specific rbd configuration from a rbd conf file that I added.

Is there anyway that in 'server.xml.erb' template I can get something like <%= vol.pool_type %> ?

What is the proper way to pass rbd specific configuration ?

Thanks in advance for any help with these questions and I would be happy to contribute to adapt the libvirt module so as to make it functional to every kind of volume.

**Comment by clsacramento** [comment]
Hi! Trying again... 

This is what I put on the template (server.xml.erb) that works for me:

<devices>
<% volumes.each do |vol| -%>
    <% args = {}
            File.readlines('/etc/foreman/ceph.conf').each do |line|
                pair = line.strip.split("=")
                key = pair[0]
                value = pair[1]
                args[key] = value
            end
        %>
    <% if vol.pool_name.include? args["libvirt_ceph_pool"]  %>
        <disk type='network' device='disk'>
            <source protocol='rbd' name='<%= vol.path %>'>
                <% args["monitor"].split(",").each do |mon| %>
                    <host name='<%= mon %>' port='<%= args["port"] %>'/>
                <% end %>
            </source>
            <auth username='<%= args["auth_username"] %>'>
                <secret type='ceph' uuid='<%= args["auth_uuid"] %>'/>
            </auth>
            <target dev='vd<%= ('a'..'z').to_a[volumes.index(vol)] %>' bus='virtio'/>
        </disk>
    <% else %>
        <disk type='file' device='disk'>
         <driver name='qemu' type='<%= vol.format_type %>'/>
         <source file='<%= vol.path  %>'/>
         <%# we need to ensure a unique target dev -%>
         <target dev='vd<%= ('a'..'z').to_a[volumes.index(vol)] %>' bus='virtio'/>
      </disk>
    <% end %>
<% end -%>

The content of /etc/foreman/ceph.conf :
monitor=192.168.100.50,192.168.100.51,192.168.100.52
port=6789
libvirt_ceph_pool=foreman-images
auth_username=foreman
auth_uuid=8e1050ae-a53c-4280-bc48-8abe0eebafb1

I also had to create a RBD pool called foreman-images on libvirt.

**Comment by geemus** [comment]
Thanks for the updates!

**Comment by charlesrg** [comment]
Great, this worked great for me too. Using Centos 7.2, Ceph Firefly and Foreman 1.11
