### ISSUE TITLE
TypeError - no implicit conversion of nil into String:

### ISSUE THREAD

**Issue by gentle0219** [fog/fog#3300]
I'm using now 
<h1>ruby '2.1.4' and rails 4.1.0</h1>

<h4>Hear are my gems</h4>

gem 'mongoid', git: 'https://github.com/mongoid/mongoid.git'
gem 'bson_ext'
gem 'carrierwave-mongoid', :require => 'carrierwave/mongoid'
gem 'fog'

<h5>This is carrierwave.rb file content</h5>

require 'carrierwave/mongoid'
CarrierWave.configure do |config|
  config.fog_credentials = {
    :provider                 => 'AWS',
    :aws_access_key_id        => ENV['S3_API_KEY_ID'],
    :aws_secret_access_key    => ENV['S3_API_SECRET_KEY'],
    :region                   => ENV['S3_API_REGION'],
    :host                     => 's3.amazonaws.com',
    :endpoint                 => 'https://s3.amazonaws.com' # optional, defaults to nil
  }
  config.fog_directory        = ENV['S3_API_BUCKET']
  config.fog_public           = false                                   # optional, defaults to true
  config.fog_authenticated_url_expiration = 24*60*60
  config.fog_attributes       = {'Cache-Control'=>'max-age=315576000'}  # optional, defaults to {}
end

<h5>This is document_file model</h5>

class DocumentFile
  include Mongoid::Document
  include Mongoid::Timestamps  

  mount_uploader :file, PdfFileUploader
  
  field :file,          type: String
  field :verified,      type: Boolean, default: false
  field :expire_date,   type: Date

  belongs_to :document 
  validates_presence_of :file
end

<h5>When I upload a file I got this errors</h5>

....
Completed 500 Internal Server Error in 66ms

<b>TypeError - no implicit conversion of nil into String:</b>
  fog-core (1.25.0) lib/fog/core/hmac.rb:29:in `block in setup_sha256'
  fog-core (1.25.0) lib/fog/core/hmac.rb:14:in `sign'
  fog (1.25.0) lib/fog/aws/signaturev4.rb:68:in `derived_hmac'
  fog (1.25.0) lib/fog/aws/signaturev4.rb:56:in `signature_components'
  fog (1.25.0) lib/fog/aws/storage.rb:501:in `request'
  fog (1.25.0) lib/fog/aws/requests/storage/put_object.rb:31:in `put_object'
  fog (1.25.0) lib/fog/aws/models/storage/file.rb:208:in `save'
  fog-core (1.25.0) lib/fog/core/collection.rb:50:in `create'
  carrierwave (0.10.0) lib/carrierwave/storage/fog.rb:261:in `store'
  carrierwave (0.10.0) lib/carrierwave/storage/fog.rb:80:in `store!'
  carrierwave (0.10.0) lib/carrierwave/uploader/store.rb:59:in `block in store!'
  carrierwave (0.10.0) lib/carrierwave/uploader/callbacks.rb:17:in `with_callbacks'
  carrierwave (0.10.0) lib/carrierwave/uploader/store.rb:58:in `store!'
  carrierwave (0.10.0) lib/carrierwave/mount.rb:375:in `store!'
  carrierwave (0.10.0) lib/carrierwave/mount.rb:207:in `store_file!'
  activesupport (4.1.0) lib/active_support/callbacks.rb:424:in `block in make_lambda'
  activesupport (4.1.0) lib/active_support/callbacks.rb:221:in `block in halting_and_conditional'
  activesupport (4.1.0) lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
  activesupport (4.1.0) lib/active_support/callbacks.rb:86:in `run_callbacks'
  app/controllers/dashboard/trial_documents_controller.rb:70:in `update'
....

**Comment by shwoodard** [comment]
I'm getting the same thing here,

```ruby
# hmac.rb:29
OpenSSL::HMAC.digest(@digest, @key, data)
```

data is nil.

What might cause this?

**Comment by geemus** [comment]
Not sure. It seems to be when region gets set to nil, but I haven't been able to track down when that might come up.

**Comment by tka** [comment]
I'm get the same problem.

there two line in my old config 

      :region: 'ap-northeast-1'
      :endpoint: "https://s3-ap-northeast-1.amazonaws.com"

when i remove the endpoint setting,  problem solved

**Comment by geemus** [comment]
I believe this should be the same as fog/fog-aws#2, so redirecting to there for further discussion. Will hopefully merge/release with that soon.

**Comment by nicholasklick** [comment]
@shwoodard 
Are you setting the `endpoint` attribute at all in your options? 
That will currently set `region` to nil.

https://github.com/fog/fog-aws/pull/33

**Comment by nicholasklick** [comment]
@geemus can get your thoughts on https://github.com/fog/fog-aws/pull/33 ?

**Comment by shwoodard** [comment]
I am currently sending endpoint and region and it is working.  However, if
endpoint sets region to nil, this might be ok, since we are in us-east-1,
which is the default, I believe.

**Comment by nicholasklick** [comment]
@shwoodard Yeah, setting `endpoint` currently ignores `options[:region]` completely. So `@region` is left nil. Would love to know why that control logic it setup up like that.

```
      def initialize(options={})
          @use_iam_profile = options[:use_iam_profile]
          if @endpoint = options[:endpoint]
            endpoint = URI.parse(@endpoint)
            @host = endpoint.host
            @scheme = endpoint.scheme
            @port = endpoint.port
          else
            @region     = options[:region]      || DEFAULT_REGION
            @host       = options[:host]        || region_to_host(@region)
            @scheme     = options[:scheme]      || DEFAULT_SCHEME
            @port       = options[:port]        || DEFAULT_SCHEME_PORT[@scheme]
          end
          @path_style = options[:path_style] || false
          setup_credentials(options)
        end
```

**Comment by erated** [comment]
@gching downgrading from 1.2.7 to 1.2.4 solved it for me as well. Thanks - found this only after a couple hours in....

**Comment by geemus** [comment]
Sorry for ongoing difficulties here. I just merged that if people would like to try against master, I'll probably try for a release tomorrow.

**Comment by sarat4a4** [comment]
a

**Comment by romenigld** [comment]
I'm following this tutorial and when I do  Multiple Uploads with Attachments I have this error:
```

TypeError (no implicit conversion of nil into String):

app/controllers/posts_controller.rb:16:in `create'
```

**Comment by geemus** [comment]
@romenigld what tutorial? What does your posts_controller look like?

**Comment by romenigld** [comment]
Hello @geemus, I'm followed this [tutorial](https://code.tutsplus.com/articles/uploading-with-rails-and-carrierwave--cms-28409).
And the controller was the same.

**Comment by geemus** [comment]
At a glance, it looks like the params coming in from the page are not formatted as expected (it looks likely that it is failing before it ever gets to fog). You may need to double check the views associated, otherwise it's hard for me to dig in much further without seeing more of the stack trace and/or code. Hope that helps.

**Comment by romenigld** [comment]
Hello @geemus, yes it was before the fog. I do Working With Multiple Uploads and the error occurs!

**Comment by geemus** [comment]
Yeah, I'm not sure off hand I'm afraid. Perhaps you could reach out to the author of the tutorial or post on stackoverflow where this question might reach a broader audience?
