### ISSUE TITLE
Large dependency tree with many un-used services/adapters

### ISSUE THREAD

**Issue by mbasset** [fog/fog#3305]
I really like fog but lately is dependency tree has grow very large. When we add fog into our build we get a ton of additional gems for services and systems that we will never use. In turn we also get all of their dependencies. I wonder if it would be possible to simply split these adapters out of the main fog core out so that we could require only the fog-core and the gems of the services/adapters we use in our project?

If there is a way to do this now please let me know.

**Comment by nj** [comment]
Is it something that will come in v2, though until now no change appear?

**Comment by geemus** [comment]
Our hope is to have things universally broken out for v2, but we aren't there yet. Many providers are separated and can be used independently, but not all of them.
