### ISSUE TITLE
The specified s3 bucket name contains a '.' so is not accessible over https as a virtual hosted bucket

### ISSUE THREAD

**Issue by joshwayne** [fog/fog#3318]
I'm using middleman-s3_sync (3.0.38) and fog (1.25.0).

I'm getting this warning repeated around 50 times anytime I try to sync to my s3 bucket:

`
[fog][WARNING] fog: the specified s3 bucket name(bucketname.com) contains a '.' so is not accessible over https as a virtual hosted bucket, which will negatively impact performance.  For details see: http://docs.amazonwebservices.com/AmazonS3/latest/dev/BucketRestrictions.html
`

I read the doc on the referenced URL but it says having dots in bucket names are valid: 

> Bucket names must be a series of one or more labels. Adjacent labels are separated by a single period (.). Bucket names can contain lowercase letters, numbers, and hyphens. Each label must start and end with a lowercase letter or a number.

So it looks like conflicting information. Am I missing something?

**Comment by joost** [comment]
I had a similar problem (with v1.27.0). I also had to remove the :region option for the buckets to be found.

**Comment by geemus** [comment]
@joost thanks for the note, good to know.

**Comment by kieaiaarh** [comment]
Just example.

```
CarrierWave.configure do |config|
  config.fog_provider = 'fog/aws'
  config.fog_credentials = {
    provider: 'AWS',
    aws_access_key_id: ENV['AWS_ACCESS_KEY'],
    aws_secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
    region:                'ap-northeast-1',
    path_style: true # add this line
  }

  config.fog_directory  = ENV['S3_BUCKET']
  :
end
```
