### ISSUE TITLE
Google Cloud Storage File Listing Limit

### ISSUE THREAD

**Issue by germs12** [fog/fog#3320]
I am connecting to Google Cloud Storage where I have 20,000+ records, but when I connect to the bucket with Fog and list all files I only get 1000.  Is there a way to increase the number of files returned?  I was hoping to programmatically go through all of these and make modifications, but now I'm stuck.  Anyone?  Thanks and great work on this Gem. :smile:

**Comment by plribeiro3000** [comment]
I'm closing this issue in favor of fog/fog-google#42.

If you have something to share, please do so there. Thanks!
