### ISSUE TITLE
[Openstack] Move to a separate gem

### ISSUE THREAD

**Issue by bdunne** [fog/fog#3333]
Similar request to https://github.com/fog/fog/issues/2877 but for Openstack.

Benefits:
- Isolate Openstack changes from fog-core
- More easily follow SemVer (more stable API)
- More easily track Issues and PR's related to Openstack
- Smaller code base makes contribution easier

I saw the work [here in fog-openstack-core](https://github.com/fog/fog-openstack-core), but it doesn't appear to be very active or complete.  I didn't see any issues or milestones tracking the work to be done, is it tracked anywhere?  I would be happy to help in this effort, and may be able to find some other resources if needed.

cc @geemus @mwhagedorn

**Comment by mdarby** [comment]
Has this effort regained any steam? Can I help in any way? I am wanting to get Rackspace and OpenStack into provider gems.

**Comment by TerryHowe** [comment]
@mdarby I think this would be a good idea, but I'm spread a little thin to get too involved.  It would probably be best to abandon the refactoring effort and just move over the current code out of core.

**Comment by plribeiro3000** [comment]
I Can work towards extracting if you guys want.

Em seg, 15 de jun de 2015 13:07, Terry Howe <notifications@github.com>
escreveu:

**Comment by mdarby** [comment]
I'd be happy to take it on -- last time I tried was ~5 months ago and we ended with a circular dependency...

**Comment by plribeiro3000** [comment]
@mdarby Go for it. =)

I believe you would be the best one to do it!

**Comment by mdarby** [comment]
On it. :)

**Comment by plribeiro3000** [comment]
@mdarby Let me know if you need anything! =)

**Comment by geemus** [comment]
Awesome, just let us know if we can help!

**Comment by h0lyalg0rithm** [comment]
@geemus I think we can close this http://github.com/fog/fog-openstack

**Comment by geemus** [comment]
Thanks!
