### ISSUE TITLE
Accessing url with Google as a provider is slow

### ISSUE THREAD

**Issue by 0x414f** [fog/fog#3339]
So I'm having a problem where If I try to access say `image.url` it takes a little too long. For example calling `url` on 100 images takes around 28 seconds when using Google Storage but using S3 with the same function call takes around half a second.

This might be related to this [CarrierWave issue](https://github.com/carrierwaveuploader/carrierwave/issues/261). However, the problem they were having was for both Google Storage and S3. @geemus mentioned in that issue to use `public_url` instead but this is still slow compared to using **fog** + S3. 

This might not be a **fog** issue but a Google Storage issue. 

As a workaround I'm currently just hardcoding the url to my Google Storage API and appending `image.path` to that - much faster.

**Comment by plribeiro3000** [comment]
I'm closing this issue in favor of fog/fog-google#43.

If you have something to share, please do so there. Thanks!
