### ISSUE TITLE
[libvirt] hugepages support

### ISSUE THREAD

**Issue by eolamey** [fog/fog#3342]
Hi,

Would it be possible to optionally enable `hugepages` support for the libvirt driver? This could default to `false`, but having an option to enable it when creating the VM would be great.

When enabled, the `server.xml` template would have:

```xml
<domain>
  <memoryBacking>
    <hugepages/>
  </memoryBacking>
  ...
</domain>
```

Enabling hugepages support on a Linux system requires a few steps, but I'm guessing documenting them would be outside of fog's scope.

Thank you.

**Comment by plribeiro3000** [comment]
closing in favor of fog/fog-libvirt#6.
