### ISSUE TITLE
[libvirt] autostart support for servers

### ISSUE THREAD

**Issue by eolamey** [fog/fog#3343]
Hi,

There is an `autostart` attribute in the server model for libvirt. However, I don't see where this attribute could be enabled when creating a VM. I don't know libvirt's API, but it seems there's a [separate method](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainSetAutostart) to call when enabling `autostart`.

Is it currently possible to enable `autostart` when creating a VM with fog? If so, how? If not, would it be possible to add it?

Thank you.

**Comment by plribeiro3000** [comment]
closing in favor of fog/fog-libvirt#7
