### ISSUE TITLE
Fog 2.0 preparation / Fog 1.x feature freeze

### ISSUE THREAD

**Issue by tokengeek** [fog/fog#3347]
So this is the line in the sand to start on Fog 2.0

/cc @geemus @krames @plribeiro3000 @mdarby

I need some help with the following:

* Deciding on what to feature freeze and what is still viable for fog 1.x
* Last release date for a fog 1.x release
* If we are going to do a "1.99" release where deprecation warnings are switched on to the max
* Flag any unsupported providers ready for removal
* Communicating the changes

The major features for Fog 2.0 at the moment are probably going to be:

- [ ] Remove 1.8.7 support. I'll add a PR for that ASAP.
- [ ] Use Fog::Core registry to replace "bin" functionality (https://github.com/fog/fog-core/issues/105)
- [ ] Removal of `Provider...` classes or the "bin" stuff

I'd like to get a release candidate done over the holidays but just need people's changes they want NOW to be sorted so when the 2.0 changes start happening people aren't surprised they can't be released quickly as a few `2.0.RCx` gems appear.

I've not looked back at the older 2.0 tickets I've filed to get a fresh perspective. If someone could scan through and see if I mentioned something there that doesn't appear to have been addressed yet please mention.

**Comment by deepj** [comment]
I'd appreciate if fog would have always optional provider dependencies. I think it'd be nice a thing being in fog 2.x

Now in my applications I have a lot of unneeded providers which are taking a lot of RAM for an application.

**Comment by tokengeek** [comment]
@deepj - Problem with aiming for that in 2.0 is that a large number of providers still have to be extracted and don't have maintenance volunteers. So the fog gem still has a large number of providers included.

To streamline you can reference `fog-provider` separately if it has been extracted. That should work for most cases unless you have inadvertently used features meant for the `fog` CLI command.

However fog has a rudimentary autoload like behaviour so only a summary of these providers should be loaded unless you specifically reference them. So they take up disk space but shouldn't take up RAM.

**Comment by strzibny** [comment]
Hi,

fog currently depends on 15 modular providers (see https://github.com/fog/fog/blob/master/fog.gemspec#L56-L71). Could we make those providers opt in? Most people probably use fog with one provider and still have to download 15 gems. And if we want to update fog in Fedora we have to package and maintain all of them.

Can we please make the core independent of providers?

**Comment by plribeiro3000** [comment]
@strzibny The idea is to be optional as you mentioned but at this point we are still extracting stuff. All those providers were already being loaded together with fog before. The main difference here is that we will have one gem for each provider in the future.

Perhaps is the time for us to start talking/working on the optional stuff. But keep in mind that `fog` will always depend on all providers so maybe it is the chance to rethink how you guys are packaging fog and how we are going to make it available for you so no one got big issues.

cc/ @tokengeek @geemus

**Comment by geemus** [comment]
Yeah, `fog-core` + `fog-#{provider}` should be enough for those that have already been modularized, but we didn't want to break backwards compatibility (at least in a minor version release). In the longer term it is likely that people would require the independent ones and probably not the main one at all (and/or perhaps we can/should deprecate the main one), but a lot of work remains to be done there.

@strzibny to clarify, how would opt-in make it easier? Would you just not package many/most of them at that point?

**Comment by strzibny** [comment]
@geemus Yes. For instance we need fog for vagrant-libvirt, which obviously uses just libvirt. The things are even worse when I for instance package a Software Collection for RHEL (the collection is used only for vagrant and nothing else), then I need to repackage and maintain 10+ extra packages. Then people from CentOS come and want to have my SCL in CentOS repositories so they again take that and maintain. Not to say that fog can have many more providers in future....

I understand that for people that just `bundle install` it means _only_  waiting longer to download everything, parse docs etc., but for me it is a lot more work so I would really welcome the independent fog.

Btw. at this moment we are going forward with packaging everything in Fedora, but better options for future would be nice! Thanks.

**Comment by geemus** [comment]
Thanks for the context. So would getting something like `fog-libvirt` split out solve a lot of the problem? That is probably a lot more tenable than the bigger changes we are talking about, especially if you or others might be willing to help with pushing the files around. Thanks!

**Comment by strzibny** [comment]
Yes, it would definitely help. I could then propose the change for `vagrant-libvirt` to only use `fog-libvirt and we save a lot of unneeded work. I could also help with the extraction.

**Comment by tokengeek** [comment]
So I added a Roadmap (https://github.com/fog/fog/wiki/Roadmap) to cover this issue and onwards.

In terms of feature freeze I'd like it so nothing else gets into `Fog 1.x` unless it is critical.

I'd like to merge the fog 2 branch to master as soon as we have resolved the loading time issue.

I think new stuff should all be modular and not get added to the `fog` gemspec.

+1 to splitting out `fog-libvirt` since it had one of the more complex dependencies, hence the hacks in the gemspec around it.

Ideally 2.0 is a clean point to remove `libvirt` support from `fog` and if people need it they remain on `1.x` or switch to `fog-libvirt` when it is available.

**Comment by geemus** [comment]
@strzibny sounds like that extraction (sooner rather than later) may be a win-win for everyone. If you want to take a stab toward that it would be great. Definitely let us know if you need any help along the way.

@tokengeek thanks for chiming in.

**Comment by strzibny** [comment]
@geemus I will look into extracting then.

**Comment by geemus** [comment]
@strzibny sound great, thanks!

**Comment by strzibny** [comment]
@geemus 

So I went ahead and created https://github.com/strzibny/fog-libvirt repository with extracted `fog-libvirt`. I didn't do anything fancy, just took the `master` branch and deleted anything unrelated, fixed `gemspec` and rake tasks and added new simple README. Tests are passing. I am ready to transfer it under `fog` org on GitHub and probably create a clean start (without `fog` history as its confusing). What do you think? I am also unsure about the list of formal contributors at https://github.com/strzibny/fog-libvirt/blob/master/lib/tasks/changelog_task.rb#L105 as those are not direct contributors to `fog-libvirt`.

Afterwards my PR https://github.com/fog/fog/pull/3521 to delete `libvirt` provider from `fog` can be merged.

**Comment by plribeiro3000** [comment]
@strzibny Thank you for the work. We are currently facing a loading issue related to the extraction of providers (#3430) and to make sure it does not happen again we need to do some changes on the repo you just made or if you want i can just send a PR to it fixing.

I think that it would be good to have a clean git repo for it so we could use tools like `oscrsy` as discussed in fog/fog-google#9. Also i believe that a gem created from scratch would preferable so you won't get any patchs from `fog` like the releasing stuff.

Happy to discuss further.

**Comment by geemus** [comment]
@strzibny oops, I just asked about this in another request but seems you answered everything here.

@plribeiro3000 thanks!

**Comment by strzibny** [comment]
So, I made a fresh git, updated the contributors list from provider's git history and hopefully cleaned the remaining stuff from fog like unused helpers. I also added you guys (@geemus and @plribeiro3000) as contributors so you can move the repository under fog org or fix things.

**Comment by geemus** [comment]
@strzibny awesome, thanks!

**Comment by plribeiro3000** [comment]
@strzibny Awesome! Thank you for the work of remaking it from scratch and add autoloading to it. :heart:

**Comment by plribeiro3000** [comment]
@tokengeek The regression is fixed. Can we move on with this one?

What are we missing?

**Comment by tokengeek** [comment]
Not much. Just time for working on it!

Last time we discussed it was probably just going to be the drop 1.8.7 work for 2.0 which exists and just needs rebasing/updating.

**Comment by tokengeek** [comment]
Closing this.

The plan is to release a 2.0.0-alpha gem tomorrow which pretty much drops 1.8.7 support (the major backward incompatible part).

The remaining items tagged with 2.0.0 are the items to work on the next few weeks for a stable 2.0.0
