### ISSUE TITLE
How to detect whether there's an error and do something?

### ISSUE THREAD

**Issue by THPubs** [fog/fog#3367]
Im trying to catch the failed uploads and send a special notification to the admins. Here's how I tried to do it :

      def perform(photo_id)
        photo = Photo.find(photo_id)
        photo.file = File.open(photo.tempfile.file.file)
        user = photo.user

        if photo.save
          user.uploaded << photo.originalname
          user.save!
          photo.tempfile.remove!
          photo.tempfile = nil
          photo.save!
          #send notification
        else
          photo.file = nil
          photo.failed = true
          photo.save!
        end

      end

According to this, it should mark the photo as failed. But it won't. In the logs I can see this error (I intentionally caused the error) :

    Excon::Errors::SocketError: Connection reset by peer (Errno::ECONNRESET)
    from /home/pubudu/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/openssl/buffering.rb:383:in `syswrite_nonblock'

It looks like everything quits after getting this error! How to mark it failed after getting errors like this?

**Comment by geemus** [comment]
I believe the error there will be raised (rather than having save return false). So you may need to do something more like:

```
begin
  photo.save
  # ...
rescue Excon::Error, Fog::Error
  photo.file = nil
  photo.failed = true
  photo.save!
end
```
