### ISSUE TITLE
JRuby builds currently ignored due to Travis issue.

### ISSUE THREAD

**Issue by tokengeek** [fog/fog#3378]
Recent Travis failures are probably due to https://github.com/travis-ci/travis-ci/issues/3067

E.g. https://travis-ci.org/fog/fog/jobs/45708040

I set all the JRubies to be ignored failures in 44aa10f

I've tested some of the same changes locally on `jruby 1.7.16 (1.9.3p392)` and it passes with no problems with `curses`

Either the workaround mentioned needs to be implemented or when the platform issue is resolved we should continue testing these.

**Comment by geemus** [comment]
Thanks for tackling this.

**Comment by tokengeek** [comment]
Thanks to @domcleal for keeping an eye on this.

Newer versions of gems are out and `trollop` is not causing the issue
on travis any more. The old builds have been rerun and fixed.

**Comment by tokengeek** [comment]
Resolved

**Comment by geemus** [comment]
Thanks!
