### ISSUE TITLE
Compute's mock detach_volume fails

### ISSUE THREAD

**Issue by xian** [fog/fog#3382]
`attach_volume` adds an entry to `self.data[:volumes][volume_id]`, but `detach_volume` attempts to find it via `self.data[:volumes][attachment_id]`. Instead, it should find the volume in `self.data[:volumes]` that has an attachment with the given `attachment_id`:

```ruby
volume = self.data[:volumes].find { |v| v['attachments'].any? { |a| a['id'] == attachment_id } }
if volume
  volume['attachments'].reject! { |a| a['id'] == attachment_id && a['server_id'] == server_id }
end
```

https://github.com/fog/fog/blob/master/lib/fog/openstack/requests/compute/detach_volume.rb#L17

**Comment by geemus** [comment]
Good catch, could you turn the change into a quick pull request for us? Thanks!

**Comment by plribeiro3000** [comment]
@xian Are you up to submit a PR for your patch?

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-openstack#42
