### ISSUE TITLE
[OpenStack] Store user metadata at file creation

### ISSUE THREAD

**Issue by dblia** [fog/fog#3385]
Currently, for the `Fog::OpenStack` provider it is not possible to store user metadata while uploading a file using the `create` method.

Consider the following scenario:
```sh
  $ fog

  >> Fog::Storage['OpenStack'].directories.create(:key => 'container')

  >> dir = Fog::Storage['OpenStack'].directories.new(:key => 'container')
      <Fog::Storage::OpenStack::Directory
        key="container",
        bytes=nil,
        count=nil>

  >> obj = dir.files.create({
        :key       => 'objname',
        :body      => 'body',
        :myattr => 'temp'
      })
      <Fog::Storage::OpenStack::File
        key="objname",
        content_length=4,
        content_type=nil,
        content_disposition=nil,
        etag="841a2d689ad86bd1611447453c22c6fc",
        last_modified=2015-01-07 16:28:31 +0200,
        access_control_allow_origin=nil,
        origin=nil>

  >> pp dir.files.get('objname').attributes
      {:content_length=>4,
       "Accept-Ranges"=>"bytes",
       :last_modified=>2015-01-07 16:28:31 +0200,
       :etag=>"841a2d689ad86bd1611447453c22c6fc",
       "X-Timestamp"=>"1420640910.42471",
       :content_type=>"application/octet-stream",
       "X-Trans-Id"=>"tx80c13dee94ed4ff4acfdf-0054ad42ac",
       "Date"=>"Wed, 07 Jan 2015 14:29:00 GMT",
       :body=>"body",
       :key=>"objname"
      }
```
As it turns out, in order to set the metadata of a file you have to do the following actions:
```sh
  >> obj = dir.files.new({
        :key => 'objname',
        :body => 'body'
       })
  >> obj.metadata[:myattr] = 'temp'
  >> obj.save
  >> pp dir.files.get('objname').attributes
      {:content_length=>4,
       :content_type=>"application/octet-stream",
       "Accept-Ranges"=>"bytes",
       :last_modified=>2015-01-08 15:53:09 +0200,
       :etag=>"841a2d689ad86bd1611447453c22c6fc",
       "X-Timestamp"=>"1420725188.74493",
       "X-Object-Meta-Myattr"=>"temp",
       "X-Trans-Id"=>"tx835f1c3c63b44c649466c-0054ae8bc6",
       "Date"=>"Thu, 08 Jan 2015 13:53:10 GMT",
       :body=>"body",
       :key=>"objname"
      }
```
Is this the indented behavior? It would be a nice feature to allow setting the metadata of a file at a single step using the `create` method. To achieve that, maybe we could update the `metadata_attributes` method of the `lib/fog/openstack/models/storage/file.rb` module to properly set the metadata variable of a new file.

What do you think? Let me know if you have any further suggestions on the issue, and if we you agree I could proceed with the appropriate patch.

**Comment by geemus** [comment]
I don't think that is intended, but I think you might be able to get it to work with create via a slightly different invocation. In particular it looks like myattr might need to be nested, so you would have something like:

```
>> obj = dir.files.create({
        :key       => 'objname',
        :body      => 'body',
        :metadata => {
            :myattr => 'temp'
        }
      })
```

At least, that is in effect what you are doing with the #new related stuff above, so I suspect it might work here also. Let me know if it doesn't or you could use some further clarification from me. Thanks!

**Comment by dblia** [comment]
This should be the effect of the above example, but it doesn't. The reason behind this behavior might be that the `metadata` variable is not computed directly from the fog `attributes` but using a separate method, that is the `headers_to_metadata`. This method subsequently calls the  `metadata_attributes`, which always sets the `metadata` to `{}` if the `last_modified` option is not  set, resulting to an empty `metadata` dict while uploading a new file.

I also include the relevant threads of when this feature was introduced:

* https://github.com/fog/fog/pull/1251
* https://github.com/fog/fog/pull/1386

**Comment by geemus** [comment]
I think that ^ might help, could you check it out? Thanks!

**Comment by dblia** [comment]
I've applied the patch and the metadata are stored correctly using the nested structure you proposed. Thanks!

**Comment by geemus** [comment]
@dblia thanks for getting to that so quickly. I'll merge that in so it can go out with the next release (hoping that will be in the next 2-3 days).

**Comment by dblia** [comment]
That's great! Thank you for the immediate response!
