### ISSUE TITLE
Release any time soon?

### ISSUE THREAD

**Issue by i11** [fog/fog#3389]
Hi there!

Do you plan to release any time soon? It would be great to get the hands on those merged fixes.

Thanks.

**Comment by geemus** [comment]
Hey, thanks for the prod. Yes. I have a couple things to land still, but probably some time in the next 2-3 days anyway.

**Comment by geemus** [comment]
released v1.27.0

**Comment by i11** [comment]
Cool! Thanks!

**Comment by i11** [comment]
Hm.. still shows as 1.26.0 in rubygems.

**Comment by geemus** [comment]
Oops, I had finished it locally but part of the script failed before
everything was out. Should be there now.

**Comment by i11** [comment]
Yeah, it's there now. Thank you!
