### ISSUE TITLE
Release 1.27.0  - warning: duplicated key at line 196 ignored: :openstack_region

### ISSUE THREAD

**Issue by diasks2** [fog/fog#3391]
After installing 1.27.0 I get this warning when I open a console:

```
/app/vendor/bundle/ruby/2.2.0/gems/fog-1.27.0/lib/fog/openstack/volume.rb:191: warning: duplicated key at line 196 ignored: :openstack_region
```

**Comment by kyletolle** [comment]
I opened a PR in the hopes of addressing this issue: https://github.com/fog/fog/pull/3392

**Comment by geemus** [comment]
Yep, I believe #3392 should have this fixed (though doesn't feel quite worthy of a release since we just released yesterday). Thanks!

**Comment by colszowka** [comment]
@geemus I would be very grateful if you could reconsider a release since on 2.2.0 my rails app gives me this warning every time I load my environment, including running a spec file, rake tasks et cetera, which is slowly but steadily driving me insane :roller_coaster:

**Comment by farneman** [comment]
@geemus I would be grateful as well. We now have 2 apps running ruby 2.2 in production that throw whenever the environment is loaded. Since we're now more than a month since 1.27 was released would it be possible to get a patch release with this fixed?

**Comment by craig1410** [comment]
@geemus Given the last two comments came in the last 3 hours, this probably looks like a conspiracy but Occam's Razor suggests it's just a trio of OCD devs who can't stand clutter in their consoles. :) Thanks in advance for your time if you are able to push out a release to fix it.

**Comment by nheinrich** [comment]
@geemus Not a conspiracy, there are more of us OCD devs out here. :)

**Comment by geemus** [comment]
Understood. I have a bit of issue/PR backlog I want to try and catch up to, but hope to releases once that his sorted (later today or tomorrow if my luck holds).

**Comment by colszowka** [comment]
@geemus Thanks for your effort and time! :heart:

**Comment by geemus** [comment]
v1.28.0 is out

**Comment by craig1410** [comment]
@geemus thanks, much appreciated.

**Comment by nheinrich** [comment]
Thanks @geemus!

**Comment by farneman** [comment]
Awesome, thanks!

**Comment by tochman** [comment]
Using `fog-core 1.28.0` running ruby 2.2 still gives me this warning:
```
 ...warning: duplicated key at line 196 ignored: :openstack_region
```

**Comment by geemus** [comment]
@tochman I believe you need 1.28.0 or greater of the `fog` gem (where the bug is), rather than `fog-core`. Hopefully that clears it up for you.

**Comment by tochman** [comment]
@geemus: Yeah, my mistake. I see that now. Thx!
