### ISSUE TITLE
(RDoc::Error) unknown type of %string "i"

### ISSUE THREAD

**Issue by default50** [fog/fog#3395]
Hi,

on a freshly installed Ubuntu 14.04.01, fully upgraded, after trying to install fog-1.27.0 I got the following error:

> Installing ri documentation for fog-1.27.0...
> 
> RDoc::Parser::Ruby failure around line 40 of
> lib/fog/xenserver/requests/compute/create_sr.rb
> 
> Before reporting this, could you check that the file you're documenting
> has proper syntax:
> 
> /usr/bin/ruby1.9.1 -c lib/fog/xenserver/requests/compute/create_sr.rb
> 
> RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.
> 
> The internal error was:
> 
> (RDoc::Error) unknown type of %string "i"
> 
> ERROR:  While generating documentation for fog-1.27.0
> ... MESSAGE:   unknown type of %string "i"
> ... RDOC args: --ri --op /var/lib/gems/1.9.1/doc/fog-1.27.0/ri --charset=UTF-8 lib README.md --title fog-1.27.0 Documentation --quiet

Thanks!

**Comment by plribeiro3000** [comment]
@default50 #3396 should fix it.

**Comment by default50** [comment]
Thanks @plribeiro3000 and @geemus, you rock!
