### ISSUE TITLE
Duplicated key in hash [lib/fog/openstack/volume.rb]

### ISSUE THREAD

**Issue by andrew-github** [fog/fog#3401]
Ruby 2.2.0 says after rails s command: /Users/{user}/.rvm/gems/ruby-2.2.0/gems/fog-1.27.0/lib/fog/openstack/volume.rb:191: warning: duplicated key at line 196 ignored: :openstack_region

**Comment by plribeiro3000** [comment]
@andrew-github This was already solved at b8981c1d90d2954aca29fbebd30c789cfb83f08e.

Since it is just a warning i think we can let it until we cut a new release.

Thank you for reporting!
