### ISSUE TITLE
vsphere set_mv_customvalue(id,'date','1')

### ISSUE THREAD

**Issue by bechampion** [fog/fog#3402]
Hey guys any one experiencing problems when setting custom attributes on vsphere , here's my call and the error:

```
###call
c.set_vm_customvalue(myid,"date","1")

### error
/usr/local/rvm/gems/ruby-2.2.0/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:61:in `parse_response': InvalidArgument: A specified parameter was not correct.  (RbVmomi::Fault)
```

I see on the vcenter log that the call gets forwarded to vcenter but a message with the same error "Aspecified parameter was not correct. key" .
I've tried with different keys , with virtualmachines on and off ,  and when i create the custom parameter manually through vcenter everything works well.

Hope you can help , thanks!!

**Comment by geemus** [comment]
@nirvdrum could you take a look? thanks!

**Comment by nirvdrum** [comment]
@bechampion Are you trying to set a value that you've already added via the Administration -> Custom Attributes dialog?  If not, I think you need to:

http://pubs.vmware.com/vsphere-51/index.jsp#com.vmware.vsphere.vcenterhost.doc/GUID-0E69C0F6-9EDD-47E8-8F1D-200B394F54C1.html

My reading is the setCustomValue call we make can only use predefined keys.  It looks like there's a different API call we can make to add a new field:

https://www.vmware.com/support/orchestrator/doc/vco_vsphere55_api/html/VcCustomFieldsManager.html#addCustomFieldDef

I haven't had the chance to start down that rabbit hole.

**Comment by nirvdrum** [comment]
@bechampion Please confirm either way.  It'd help me determine whether this is a functional bug or a usability problem.

**Comment by nirvdrum** [comment]
@bechampion And finally, one quick way to check whether the key is valid is to look at the results of the `list_customfields` call.  If my understanding is correct, we can issue that call and validate the results to improve the error message at the very least.

**Comment by nirvdrum** [comment]
And finally, creating a new custom field can be done by:

```
@connection.serviceContent.customFieldsManager.AddCustomFieldDef(:name => "myField", :moType => "VirtualMachine") # scoped to virtual machine

@connection.serviceContent.customFieldsManager.AddCustomFieldDef(:name => "myOtherField") # scoped globally
```

**Comment by nirvdrum** [comment]
Having not heard anything in about 4 months, I'm going to close this.  Please comment if you think it should be reopened.

**Comment by geemus** [comment]
Thanks!
