### ISSUE TITLE
Errors backup gitlab to aws using specific region (in my case, singapore)

### ISSUE THREAD

**Issue by donnykurnia** [fog/fog#3406]
Version affected: fog 1.21.0 and fog 1.27.0

The stacktrace is here:
https://github.com/gitlabhq/gitlabhq/issues/8402#issuecomment-70442934
https://github.com/gitlabhq/gitlabhq/issues/8402#issuecomment-70443066

From the error, I guess it's because fog try to use default endpoint. Should the configuration also specify endpoint? Why not determine the endpoint automatically based on the region using this table:
http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

**Comment by fcheung** [comment]
The endpoint to use is a property of the bucket - the error message you post seems to be saying that you should be using the us-east-1 endpoint.

**Comment by donnykurnia** [comment]
@fcheung is this means that the endpoint should be set explicitly when initialize carrierwave?

Gitlab use fog with this initializer:
https://github.com/gitlabhq/gitlabhq/blob/7-7-stable/config/initializers/carrierwave.rb

**Comment by fcheung** [comment]
just setting the region should be enough, but that error message is (to me) saying that the bucket was created in the us-east-1 region. In at least some circumstances fog will auto connect to the correct region, but I'm not very familiar with that. Any ideas @geemus ?

**Comment by donnykurnia** [comment]
I found the solution. In aws console I see this message in the navigation bar: "S3 does not require region selection."
So, I remove region from the config file and now the upload work fine.

Setting the region other than default will cause the problems. So, you might need to update the document  to let the user know that Amazon expect the region to be default one.

**Comment by geemus** [comment]
Ah. I think it depends. If you know the region, it is best to specify it, but if you do not know the region you can ask for the default (and it will redirect/tell you where it might actually be).
