### ISSUE TITLE
Ruby 2.2 warning: duplicated key

### ISSUE THREAD

**Issue by yoshdog** [fog/fog#3409]
Keep getting this warning in ruby 2.2

```sh
ruby/gems/2.2.0/gems/fog-1.27.0/lib/fog/openstack/volume.rb:191: warning: duplicated key at line 196 ignored: :openstack_region
```

**Comment by yoshdog** [comment]
looks like it was fixed in this [commit](https://github.com/fog/fog/commit/b8981c1d90d2954aca29fbebd30c789cfb83f08e), however the warning still happens with version 1.27

**Comment by nofxx** [comment]
Yup, waiting for next release.

**Comment by wndxlori** [comment]
Is there an ETA on that next release?

**Comment by geemus** [comment]
Hey, I plan to try and cut a release some time this week. So hopefully the warning won't be an issue for much longer, thanks!
