### ISSUE TITLE
[google] Add support for JSON key format

### ISSUE THREAD

**Issue by erjohnso** [fog/fog#3413]
Google introduced a new Service Account key format (JSON) and over time this will likely become the preferred format.  We should begin by supporting this new format soon. If Google does make this the default, we may want to follow-up and issue a (debug | info) warning to users relying on P12 format.

AFAIK, there is no clear documentation on this format. However, if you open up the Developers Console and look under "APIs & Auth" -> "Credentials", you'll see the "Generate New JSON Key" button next to any existing Service Accounts (or be given the option to create one with a new SA).

/cc @icco, @frodenas

**Comment by frodenas** [comment]
@erjohnso I took a look into this today and it's seems an easy fix, but I'm concerned about the the repo split.

@icco is this something you're working on? I can submit a PR to support the new JSON format, but wonder if it's better to support it on the actual fog/fog or just wait to the new [fog/google](https://github.com/fog/fog-google) repo? Thoughts?

**Comment by icco** [comment]
I'm not actively working on it, and everything will make it over to the new repo. Just put everything in here and we'll work on keeping things in sync once https://github.com/fog/fog-google isn't an empty repo :p

**Comment by geemus** [comment]
Yeah, the cut-overs have usually been pretty quick once they were underway, so probably not too much threat of drift between the two places just yet.

**Comment by erjohnso** [comment]
Hiya @frodenas - any progress on tests / docs?  Want any help with that part of it?  We could likely merge what you have and then do the rest in separate PRs if @icco is cool with that approach and you don't have the time to do it all on your own.

**Comment by icco** [comment]
+1 to what @erjohnso said.

**Comment by frodenas** [comment]
@erjohnso @icco I started working on tests, but got stuck trying to mock the google client calls. Unfortunately, I'm traveling all this week, so I won't be able to work on this until next week. Feel free to merge what's done or pick up the PR and complement it with the required tests and docs.
