### ISSUE TITLE
AWS S3 requests to objects with '//' in path results in 403

### ISSUE THREAD

**Issue by tdg5** [fog/fog#3416]
I haven't had a chance to research this appropriately, but I'm consistently seeing requests to S3 that include '//' in the path fail with a 403 error.

This maybe part of the reason some folks are still seeing issues related to #3381. I imagine that similar to #3381, this probably affects 1.25.0+. I can confirm that it worked for 1.23.0, but otherwise I've only tested 1.27.0 running fog-core 1.27.3 and fog-aws 0.0.6. I've only tested head and initiate_multipart_upload requests.

Same type of error message as #3381: `The request signature we calculated does not match the signature you provided. Check your key and signing method.`

I am willing to accept a response of "you shouldn't do that," because honestly, I think it's dumb, but I've got to live with it for legacy reasons. That said, if it seems like a reasonable use-case, a patch is welcome :grinning:. To clarify, this is not a bad path concatenation issue, I mean I guess it could be, but, unfortunately for me, someone at some point decided it would be a good idea to put objects in S3 with paths that include full HTTP URLs.

This should allow you to reproduce the issue:
```ruby
require 'fog'

storage = Fog::Storage.new({
  :provider => 'AWS',
  :aws_access_key_id => 'YOUR_KEY_HERE',
  :aws_secret_access_key => 'YOUR_SECRET_HERE',
  :persistent => false,
  :region => 'us-east-1',
})
bucket = 'mr-test-bucket'
full_path = 'some/path//please-kindly-delete-this-test-file'
opts = { :chunk_size => 5242880 }

begin
  response = storage.initiate_multipart_upload(bucket, full_path, opts)
  upload_id = response.body['UploadId']
  storage.abort_multipart_upload(bucket, full_path, upload_id)
  puts 'SUCCESS'
rescue => e
  puts 'FAIL:'
  raise e
end
```

Let me know if I can provide any additional information or testing. Thanks!

**Comment by fcheung** [comment]
Probably an issue with how the request is being canonicalised in the signature_v4 code in fog-aws. There are test cases for // at the end of the path but not the start.

**Comment by geemus** [comment]
Yeah, it seems like a bad idea, even if technically valid, as you point out. That said, I wouldn't be opposed to fixing up the canonicalization (or whichever part of the signing might be off). A pull would be great, definitely just let us know if you have questions.

**Comment by crazymykl** [comment]
This still happens if the path starts with a double slash.
