### ISSUE TITLE
[DigitalOcean] Use the v2 API

### ISSUE THREAD

**Issue by nickvanw** [fog/fog#3419]
Opening this issue to track any progress toward using the DigitalOcean v2 api (documented [here](https://developers.digitalocean.com/)) in fog. 

There's a DO Engineer with an in-progress branch here: https://github.com/phillbaker/fog/tree/feature/digitalocean-v2/ if anyone wants to contribute to speed things along, as the v1 API is heading toward deprecation.

**Comment by geemus** [comment]
Thanks for the update and checking in. Just let us know if you have questions or anything we can help with along the way. Thanks!

**Comment by nickvanw** [comment]
Will do! I opened this in part so I could fund the progress via [Bountysource](https://www.bountysource.com/teams/fog/issues) (full disclosure: I'm another DO engineer with a vested interest in helping this move forward, as soon as I'm able, we'll be placing a bounty on this!)

**Comment by geemus** [comment]
Cool, thanks for the extra context!

**Comment by nirvdrum** [comment]
Not to cry the sky is falling, but I received an email from DO saying they're completely shutting the v1 API off on Nov. 1, 2015.  That's less than 6 months from now and fog still doesn't support V2.  I trust we'll get something in in one form or another, but there's a lot of tools built around fog that aren't going to have much time to adapt.

Having framed the context, has there been any additional movement on this?  It sounded like there was one volunteer from fog/fog-core#147.  It might be worthwhile to coordinate efforts.

**Comment by TJM** [comment]
I figured this was going to appear before it went out of beta at DO, but it is out of beta, and this doesn't appear to be much further. I am a "consumer" of this module, and would love to see some of the APIv2 functionality. Not sure if I can talk my boss into doing this though. Maybe we can get some more funding donated to https://www.bountysource.com/issues/8130303-digitalocean-use-the-v2-api to make it worth someone's time? I am willing to throw another $50 at it.

**Comment by nirvdrum** [comment]
I was really hoping DigitalOcean would step up to the plate.  They're naturally the one's most qualified to do the upgrade, they one's that want people off V1, and the one's that have the most to gain by people using the API.  It might be worth pinging them to see where they're at with things.

**Comment by bryanl** [comment]
We're going to release DigitalOcean API v2 support in a new fog-digitalocean module. Work has just started, but I expect to have results soon.

**Comment by geemus** [comment]
@bryanl thanks for the update, just let us know if there is anything we can help with.

**Comment by roflmao** [comment]
"Version 1 of the API is deprecated and will be shutdown on November 1st 2015"

**Comment by TJM** [comment]
@bryanl How are things going? Do you need assistance?

**Comment by bryanl** [comment]
@TJM I haven't forgotten about this, but there were other items were higher on the stack. I should start on this in the next two weeks. I'll ping here when I start.

**Comment by seanhandley** [comment]
`bryanl commented 14 days ago`

Hope you can look soon!

**Comment by seanhandley** [comment]
`bryanl commented 14 days ago`

Hope you can look soon @bryanl !

**Comment by hh** [comment]
Just to note, we have about 5 weeks of fog functionality on Digital Ocean...

If we (as a community, or any company who needs to make it a priority) have any funds anywhere to allocate to this, I'd be willing to pick it up if we don't hear from @phillbaker or @bryanl 

My focus is currently elsewhere, but could be bumped. ;)

**Comment by nirvdrum** [comment]
Unfortunately, the window for this has realistically been missed.  Even if a V2 compatible pull request landed today, we'd need lead time for a fog release and then that needs time to filter downstream.  That's a lot to expect of other projects . . . upgrade to a newer fog and rewrite & QA their client code before the V1 shutoff deadline. It may make sense to just start deprecating everything Digital Ocean related in fog and doing a new release before the API shutdown. I suspect we're going to see a lot of bug reports start flooding in when things suddenly don't work.

Of course I'd still love to see V2 support land in fog, but nothing substantial has materialized during the time this issue has been open.  I'm not looking to fault anyone for that.  However, I do think we need to take steps to prepare for the likely scenario that fog isn't V2 compatible when the V1 shutoff occurs.

**Comment by bryanl** [comment]
I've had a crazy travel schedule over the past few weeks. My goal this week is to complete the fog v2 work. @nirvdrum, we've set Nov 1 as the date, and that is a bit shorter than 7 weeks from now. Are you sure we are out of time? I realize the window is short.

**Comment by geemus** [comment]
@bryanl we will certainly do what we can to support changes, more time is just always better.

**Comment by nirvdrum** [comment]
@bryanl I think no matter what we're going to want to see Digital Ocean V2 support within fog, so please don't take my comment as disparaging. I just know of several Ruby-based projects that use fog as its cloud layer and they're going to need time to upgrade. Fog needs time to coordinate a release as well so something can be pushed out for downstream integration. And there's just going to be natural lag because fog isn't the sort of gem people just upgrade on a whim.

One suggestion for Digital Ocean is to keep the V1 API endpoints active but return an error with a message indicating the V1 API is dead.  Just returning a 404 that clients may not be able to deal with intelligently can be far more confusing than a 500 with an error message.

Anyway, I do look forward to what you have brewing.

**Comment by geemus** [comment]
Yeah, or 503 (or 410). 410 probably being the most semantically accurate.

**Comment by TJM** [comment]
@bryanl are you working on this somewhere publicly? I might have some time this afternoon or tomorrow to try to get this thing done. Even if you are not able to work on it, can you please at least push up what you have to a public repo so that others can help? We need to get the community behind this and get it done. I personally think we need to target the end of Sept, if not sooner.

**Comment by TJM** [comment]
one potential workaround that we are looking into is: https://github.com/digitalocean/droplet_kit

**Comment by grossjo** [comment]
Also looking for any work shared publicly, would gladly help contribute to this. @bryanl

**Comment by athirn** [comment]
I've added to the bounty to try and move this forward.  Would prefer for this not to be delayed until the last minute (or worst after the v1 api is turned off).

**Comment by bryanl** [comment]
@grossjo https://github.com/bryanl/fog/tree/dov2 is where I'm working. I'm currently weeding through tests for droplet creates and deletes. I'm open for all suggestions and tips and codes.

**Comment by grossjo** [comment]
@bryanl Any api's to be added still or are you just stuck on writing tests?

**Comment by bryanl** [comment]
@grossjo I submitted a PR here:
https://github.com/fog/fog/pull/3698

**Comment by anandvc** [comment]
Any update on this? We're cutting it pretty close waiting for v2 support. I see a pull request above.

**Comment by seanhandley** [comment]
I know @geemus has been away on honeymoon, but it should roll with the next minor release soon.

In the meantime @anandvc, if you wouldn't mind linking your Gemfile directly to master and trying it out in a test environment at your end? Would be good to get some additional testing!

**Comment by geemus** [comment]
Hey, I'm back and just trying to get caught up again. I think I have a plan for this, hoping to land it tomorrow or the day after. Sorry for delays, just unfortunate timing.

**Comment by petems** [comment]
Just noticed the new DigitalOcean stuff missed out the images#get method, just added it in: https://github.com/fog/fog/pull/3725 :smile:

**Comment by geemus** [comment]
released in v1.35.0

**Comment by TJM** [comment]
As far as I know 1.35.0 broke some compatibility with ruby 1.9.3, so we are hoping to see another release per issue #3711

**Comment by geemus** [comment]
Yeah, I hope to fix 1.9 compat soon.

**Comment by NeMO84** [comment]
@geemus , I am hoping the 1.9 compat fix is nearing a release. Any timeline you can offer?

**Comment by geemus** [comment]
I'm hoping to get it out this week, but have been a little swamped. Still, I'd like to get it done ASAP. Sorry for the delays, things have just been a bit crazy for me.

**Comment by geemus** [comment]
I just release 1.36.0, which should (hopefully) be working more nicely with 1.9. Definitely let me know if you still see issues, I think we are at least closer, but I'm not certain I squished all the edge cases.

**Comment by TJM** [comment]
Thanks, by the way @geemus

**Comment by NeMO84** [comment]
@geemus , Thanks for addressing this!
