### ISSUE TITLE
Google Services authentication

### ISSUE THREAD

**Issue by cdwilhelm** [fog/fog#3422]
Hello,

I can't seem to identify how to provide the credential to authenticate with the google servers using Fog.  Can someone provide some direction.  Thank you!

**Comment by geemus** [comment]
@icco could you help? Thanks!

**Comment by plribeiro3000** [comment]
Closing due inactivity.

Please comment back if you are still in trouble. Thanks!

**Comment by geemus** [comment]
Thanks!
