### ISSUE TITLE
[AWS] distributionConfig.enabled: Member must not be null

### ISSUE THREAD

**Issue by EZtheOG** [fog/fog#3428]
I have a Script to create a CDN Environment which does:

cdn = Fog::CDN.new({
     :provider               => 'AWS',
     :aws_access_key_id      => 'MY_KEY',
     :aws_secret_access_key  => 'MY_SECRET'
})

cdn.post_distribution({
  'CustomOrigin' => {
    'DNSName'               => 'cdn.foo.bar',
    'HTTPPort'              => '80',
    'OriginProtocolPolicy'  => 'match-viewer',
    'DefaultRootObject'     => '/',
  }

The error I get is:
/home/ezb/.rvm/gems/ruby-1.9.3-p547@fogDev/gems/excon-0.38.0/lib/excon/middlewares/expects.rb:10:in `response_call': Expected(201) <=> Actual(400 Bad Request) (Excon::Errors::BadRequest)
  response => #<Excon::Response:0x00000002300078 @data={:body=>"<?xml version=\"1.0\"?>\n<ErrorResponse xmlns=\"http://cloudfront.amazonaws.com/doc/2010-11-01/\"><Error><Type>Sender</Type><Code>MalformedXML</Code><Message>1 validation error detected: Value null at 'distributionConfig.enabled' failed to satisfy constraint: Member must not be null</Message></Error><RequestId>16ef24ab-ac80-11e4-8ff3-dd12c6d41832</RequestId></ErrorResponse>", :headers=>{"x-amzn-RequestId"=>"16ef24ab-ac80-11e4-8ff3-dd12c6d41832", "Content-Type"=>"text/xml", "Content-Length"=>"371", "Date"=>"Wed, 04 Feb 2015 15:11:26 GMT"}, :status=>400, :remote_ip=>"176.32.98.148", :local_port=>57905, :local_address=>"10.100.6.203"}, @body="<?xml version=\"1.0\"?>\n<ErrorResponse xmlns=\"http://cloudfront.amazonaws.com/doc/2010-11-01/\"><Error><Type>Sender</Type><Code>MalformedXML</Code><Message>1 validation error detected: Value null at 'distributionConfig.enabled' failed to satisfy constraint: Member must not be null</Message></Error><RequestId>16ef24ab-ac80-11e4-8ff3-dd12c6d41832</RequestId></ErrorResponse>", @headers={"x-amzn-RequestId"=>"16ef24ab-ac80-11e4-8ff3-dd12c6d41832", "Content-Type"=>"text/xml", "Content-Length"=>"371", "Date"=>"Wed, 04 Feb 2015 15:11:26 GMT"}, @status=400, @remote_ip="176.32.98.148", @local_port=57905, @local_address="10.100.6.203">

Now, the Fog Library says that the distributionconfig enabled is OPTIONAL but it seems that, for AWS anyways, that is HAS to be set at the end:

cdn = Fog::CDN.new({
     :provider               => 'AWS',
     :aws_access_key_id      => 'MY_KEY',
     :aws_secret_access_key  => 'MY_SECRET'
})

cdn.post_distribution({
  'CustomOrigin' => {
    'DNSName'               => 'cdn.foo.bar',
    'HTTPPort'              => '80',
    'OriginProtocolPolicy'  => 'match-viewer',
    'DefaultRootObject'     => '/',
  },
  'Enabled'                        => 'true'

It took awhile to figure it out WHY it wasn't working but I stumbled upon this gist:
https://gist.github.com/morten/3139f3ca80571f441f13

Anyways, not sure if this is a bug but I figure I'd bring it to your attention.

**Comment by plribeiro3000** [comment]
@EZtheOG Could you reopen this against [`fog-aws`](https://github.com/fog/fog-aws) and link it back here please?

**Comment by EZtheOG** [comment]
Yep!  Can do!  Sorry if I put it in the wrong place!
