### ISSUE TITLE
Implement floating disks attach and detach action in rbovirt provider

### ISSUE THREAD

**Issue by pdilung** [fog/fog#3432]
Implement disk attach and detach action in _ovirt_ provider based on abenari/rbovirt#60 proposal and abenari/rbovirt#61 pull request.

**Comment by pdilung** [comment]
I have made an initial implementation of the feature. Please see 6b64bd08cab234292034b94f000f620801759a52 for details.
Please note that this feature must be supported by `rbovirt` library as well. Currently, there is a pending pull request abenari/rbovirt#61. Once it is merged, I shall open a pull request on fog part as well.

**Comment by geemus** [comment]
Sounds good, thanks!

**Comment by pdilung** [comment]
Created a pull request #3435

**Comment by geemus** [comment]
Thanks! I'll close this in favor of continuing discussion on the pull as needed.
