### ISSUE TITLE
Allow prepending a custom user agent

### ISSUE THREAD

**Issue by everett-toews** [fog/fog#3433]
Give your users the ability to _prepend_ a custom user agent. So if the existing user agent is

    fog/1.1.0

Provide a method for your users to easily prepend their own user agent so they can further customize it.

    users-app/0.1.2 fog/1.1.0 

This will give cloud providers much better insight into how people are using fog. This should be well documented and part of examples that are written for fog so people just copy/paste it in. Just a friendly suggestion!

**Comment by geemus** [comment]
Yeah, makes sense, would you be up for working on a pull request around this?

**Comment by mdarby** [comment]
I'll take this one @geemus

**Comment by geemus** [comment]
Great, thanks!

**Comment by mdarby** [comment]
@geemus Could you assign this to me so that I may track more easily?

**Comment by mdarby** [comment]
Is this what you had in mine @everett-toews?

![1 irb ruby 2015-02-11 14-36-16](https://cloud.githubusercontent.com/assets/2805/6154682/8b18efc4-b1fb-11e4-82ab-0e76480e5d27.jpg)

**Comment by mdarby** [comment]
Something like this @everett-toews?
![adf](https://cloud.githubusercontent.com/assets/2805/6154764/336af5d2-b1fc-11e4-8362-499a72cb5440.jpg)

**Comment by geemus** [comment]
@mdarby I guess I can not assign to you since you are not a member of a team on this (or something?)

**Comment by mdarby** [comment]
Ahh yes.

**Comment by mdarby** [comment]
This can be closed as the discussion has moved to the PR.

**Comment by plribeiro3000** [comment]
@everett-toews @mdarby Thanks!
