### ISSUE TITLE
Extract local provider to a separate gem

### ISSUE THREAD

**Issue by lautis** [fog/fog#3439]
I tried to use extracted aws provider without the full fog gem as dependency. This worked, but I also needed the local provider for development environment. So, I went ahead and extracted it out as [a separate repo](https://github.com/lautis/fog-local). Would you be interested having fog-local as a separate gem?

There's still some things to do, such as

* moving the repository under fog organisation
* publishing the gem
* replacing local provider in fog with the extracted gem as a dependency

**Comment by geemus** [comment]
Yeah, I'd be up for having it be distinct. If you add me with full permissions on the repo I should be able to move it across.

**Comment by lautis** [comment]
Cool, I'll update the urls in the repo.

**Comment by geemus** [comment]
Thanks. I pulled it in to the org, I think you should have an invite to be a collaborator/admin on it, should you need it. If you want to work on the gem/removal parts that would be great. @plribeiro3000 has a lot of experience with these steps, so maybe he can give advice and/or guidance if you need it. Thanks!

**Comment by plribeiro3000** [comment]
@lautis LMK if you need anything!
