### ISSUE TITLE
1.28 seems to break the get_template() method

### ISSUE THREAD

**Issue by stonith** [fog/fog#3458]
@nirvdrum 
With fog 1.28.0 (commit ccafa8bf1), I get the following error:

```
irb(main):014:0> @connection.get_template('/Templates/template_name')
Fog::Compute::Vsphere::NotFound: /Templates/template_name was not found
	from /usr/lib64/ruby/gems/1.9.1/gems/fog-1.28.0/lib/fog/vsphere/requests/compute/get_virtual_machine.rb:28:in `get_vm_ref'
	from /usr/lib64/ruby/gems/1.9.1/gems/fog-1.28.0/lib/fog/vsphere/requests/compute/get_template.rb:6:in `get_template'
	from (irb):14
	from /usr/bin/irb:12:in `<main>'
```

However, I grabbed the previous version of get_virtual_machine.rb and it works properly.

**Comment by zarry** [comment]
Can confirm I am also hitting this since upgrading.  Currently just rolled back to 1.27.0 which is working correctly.

**Comment by geemus** [comment]
@nirvdrum When you have a minute could you take a look? Thanks!

**Comment by nirvdrum** [comment]
On the docket.  What's frustrating is this is change is one I scrutinized quite a bit.  Unfortunately, without being able to easily have regression tests running against vSphere and having very meager mocks, breakages sneak in :-/

**Comment by geemus** [comment]
Yeah, quite understandable.

**Comment by geemus** [comment]
Thanks again for your efforts!

**Comment by c1mark** [comment]
I can confirm 1.28 breaks Chefdk test kitchen when using the vsphere driver too.

**Comment by nirvdrum** [comment]
Sorry for taking so long on this.  Please comment if you find the fix insufficient.

**Comment by geemus** [comment]
Thanks!
