### ISSUE TITLE
Joyent Connection SSL Verify Error

### ISSUE THREAD

**Issue by hulu1522** [fog/fog#3459]
Connecting to a Joyent Cloudapi service fails if using a self-signed certificate. (Note: using test-kitchen also)

```
>>>>>> Create failed on instance <default-ubuntu-1404>.
>>>>>> Please see .kitchen/logs/default-ubuntu-1404.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Unable to verify certificate, please set `Excon.defaults[:ssl_ca_path] = path_to_certs`, 
`ENV['SSL_CERT_DIR'] = path_to_certs`, `Excon.defaults[:ssl_ca_file] = path_to_file`, 
`ENV['SSL_CERT_FILE'] = path_to_file`, `Excon.defaults[:ssl_verify_callback] = callback` (see OpenSSL::SSL::SSLContext#verify_callback),
 or `Excon.defaults[:ssl_verify_peer] = false` (less secure).
>>>>>> ----------------------
```

Please allow an option to be passed in that will disable this.  The only fix I found was to add the following to [this](https://github.com/fog/fog/blob/master/lib/fog/joyent/compute.rb) file:
```
Excon.defaults[:ssl_verify_peer]=false
```

This was also suggested as a fix for a different issue [here](https://github.com/joyent/knife-joyent/issues/6#issuecomment-5267278).

**Comment by geemus** [comment]
To clarify, where/how do you imagine the option would be passed in? Thanks!

**Comment by hulu1522** [comment]
@geemus  I don't know if this is proper implementation but something similar to this would work:

https://github.com/hulu1522/fog/commit/25db88412a8e7b3ba56fcd58b4e55c083409a0c1

**Comment by geemus** [comment]
Closing in favor of further discussion on #3464
