### ISSUE TITLE
Automatically use multipart upload when uploading files >5G to s3

### ISSUE THREAD

**Issue by yannh** [fog/fog#3466]
Hello, 

Directory.files.create fails on files larger than 5GB, as you need a multipart upload in this case. Would it make sense / would it be possible to make it transparent to fog users, and automatically do a multipart upload when the file is larger than 5G?

Or eventually add a new function multipart_create or similar that would mask the complexity to the user? I'd be happy to spend time on this, if there is consensus on the API.

**Comment by geemus** [comment]
I think we already have this, though it isn't well documented (you can see it here: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/models/storage/file.rb#L249).

Basically I think if you do something like:

```
file = Directory.files.new(...)
file.multipart_chunk_size = 5242880 # 5mb
file.save
```

Basically, at least at present, that multipart_chunk_size is the magical flag. Maybe you are right that we should default this when the file is > 5gb to some value and do the multipart upload.

But at least for now I wanted to point out that there is something to hide the complexity and allow this.

**Comment by yannh** [comment]
@geemus sorry for replying so late. Indeed this works, thanks a lot for your reply! I was unable to find any resource regarding this, nearly all sources on the web indicate to split the file first, which is a big no-no for files that big. Would there be any downside in selecting multipart upload automatically for files a certain size? Let me know if I can help, documentation could be a start :)

**Comment by geemus** [comment]
I guess my hesitation around automatically doing this is the added complexity of retries and whatnot, coupled with some suspicion that the actual usage might vary from case-to-case (ie I'm not sure there is a good one-size-fits-all version of this). I'd be happy to discuss further though. Thanks!

**Comment by plribeiro3000** [comment]
If i'm not mistaken i believe this issue can be closed.

Comment back or reopen if you still feel like we need to work on this.

Thanks!
