### ISSUE TITLE
[vcloud-director] undefined method `get_by_id' for VcloudDirector::VmCustomizations

### ISSUE THREAD

**Issue by monkey1016** [fog/fog#3472]
Hi,
I'm using the vCloud Director provider in fog and I receive the following stacktrace when trying to save a vm customization

```
c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/fog-1.27.0/lib/fog/vcloud_director/compute.rb:307:in `get': undefined method `get_by_id' for #<Fog::Compute::VcloudDirector::VmCustomizations:0x3f6dab8> (NoMethodError)
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/fog-core-1.28.0/lib/fog/core/model.rb:31:in `reload'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/fog-1.27.0/lib/fog/vcloud_director/compute.rb:277:in `block (2 levels) in make_lazy_load_method'
        from vapp_provision.rb:140:in `block in <main>'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/fog-core-1.28.0/lib/fog/core/collection.rb:19:in `each'
        from c:/opscode/chefdk/embedded/lib/ruby/gems/2.0.0/gems/fog-core-1.28.0/lib/fog/core/collection.rb:19:in `each'
        from vapp_provision.rb:137:in `<main>'
```

Not sure if I'm using the library correctly.  If it helps, here is the relevant block of code where the exception occurs:

``` ruby
  # Add random hostnames to the VMs
  vapp.vms.each do |vm|
    custom = vm.customization
    custom.computer_name = "#{custom.computer_name}-#{SecureRandom.hex(4)}"
    custom.admin_password = custom.admin_password
    custom.save
  end
```

If it actually is an issue, I can probably work around it and submit a PR in the future.  Any guidance in the right direction would be appreciated.  Thanks!

**Comment by geemus** [comment]
Looks like there is some meta-programming here. It looks like we need to add a `get_by_id` method to the collection for vm_customizations. I'm afraid I don't have much experience with vcloud (or a setup to test against). Would you be up for exploring this and working on a PR? Thanks!

**Comment by monkey1016** [comment]
Sure thing.  I'll check it out and see about submitting a PR.

**Comment by geemus** [comment]
Awesome, just let me know if you need anything along the way.
Thanks!
wes
