### ISSUE TITLE
PowerDNS Support

### ISSUE THREAD

**Issue by cluobah** [fog/fog#3478]
I've added support for PowerDNS to a forked fog. Does fog still prefer moving towards a modular system as mentioned in #3238 or is it OK if PowerDNS lives in the main fog gem? I saw that the fog-rage4 gem just has stubs whereas their real code is in fog...

**Comment by plribeiro3000** [comment]
Hello @cluobah. Thank you for your interest in adding support for `PowerDNS`. `fog-rage4` is not ready yet so thats the reason it has just stubs for now.

I think it would be nice to have it in a modularized gem but as we have a loading issue #3430.

cc/ @geemus @tokengeek What do you think?

**Comment by geemus** [comment]
I would prefer modularized, though the load issue does still need to get sorted out somehow.

**Comment by cluobah** [comment]
OK, I'll make it modularized and put in a PR within a week.

**Comment by geemus** [comment]
Sounds great, thanks!

**Comment by plribeiro3000** [comment]
The gem is out there already so i will go ahead and close this.

Thanks!

**Comment by geemus** [comment]
Thanks!
