### ISSUE TITLE
1.28 gem does not contain latest vm_clone.rb code?

### ISSUE THREAD

**Issue by c1mark** [fog/fog#3481]
Looking at the vm_clone.rb deployed by the 1.28 gem, it looks different to the 1.28 version in git. Specifically the gem version does not seem to contain the code for configuring VMware VM's onto a distributed virtual switch.

Copying the vm_clone.rb contents from git, and replacing the 1.27 version appears to work ok.

**Comment by geemus** [comment]
Hmm. Perhaps I messed something up in the release process. I think it should go out in the next release if it is on master though, so I don't think there should be further required action at present. Thanks!
