### ISSUE TITLE
Support Elastichosts API

### ISSUE THREAD

**Issue by lazzarello** [fog/fog#3492]
[Elastichosts has a cloud platform](http://www.elastichosts.com/support/) they sell as [white label proprietary software to licensees](http://www.elastichosts.com/reseller-programs/). I work for [one of these](http://openhosting.com/a/). I'm building a larger project for my company and would like to add support for the Elastichosts API to the library. This would in turn enable any licensee be supported through changing the [API endpoint URL](http://www.elastichosts.com/support/api/).

I've forked the project, read through the contributing documentation and *getting started with a new service* code. I also looked for existing open issues regarding the Elastichosts API. There are none! It appears I'll be the first. Looking forward to working with all of you.

Regards,
Lee

**Comment by plribeiro3000** [comment]
Hey @lazzarello . I think this files might be outdated. The goal now is to have one modularized gem for each provider like the many we already extracted from the main fog gem.

Could you start it as a standalone gem instead?

**Comment by lazzarello** [comment]
I'm confused. [I'm referencing](http://fog.io/about/contributing.html) the project documentation about making contributions, which is a little more detailed than the CONTRIBUTING.md in the master branch. This branch has many directories with classes which resemble the documentation I've referenced. Are you saying the community has decided to change the path of active development? If so is there a branch other than master which represents this path?

Regarding starting my project as a stand alone gem, [this is done](https://rubygems.org/gems/openhosting). How would I adapt this to work with Fog?
Thanks for your advice.

**Comment by plribeiro3000** [comment]
@lazzarello You can see active development in the modularized providers in master. (https://github.com/fog/fog/blob/master/fog.gemspec#L54-L70). All provider gems are under the `fog` organization. The documentation really needs to be updated.

The convention we are using is to have `fog-provider_name`. I think that perhaps it would be easier to create a fresh new repo since the structure and the name should change. Are you ok with that?

**Comment by lazzarello** [comment]
I see. So master has a combination of the legacy services, which use the documented class hierarchy and current modularized providers, which are simply gem deps? I'll have to figure out what the common interface is between the individual gems and Fog, correct?

Regarding renaming my existing gem, that's not a problem. It's a new release and there aren't many users of it. I can maintain a forked repo exclusively for Fog, since the user reach justifies the extra administration overhead.

**Comment by plribeiro3000** [comment]
@lazzarello Its the same for both the providers that are modularized and the ones that stand inside fog.

Once you have the new project code, push it to a repo here in github so we can move it under the `Fog` organization later.

**Comment by lazzarello** [comment]
Great thanks. I'll close out this issue. I'll try and do as much documenting as I can so perhaps you can use it to update some of what is on the public contributing section?

**Comment by plribeiro3000** [comment]
Sure. if you want to contribute to documentation, send a PR to https://github.com/fog/fog.github.com. =)

**Comment by geemus** [comment]
:+1: thanks for working through this, definitely appreciate any help you can give around docs also.
