### ISSUE TITLE
Ruby warnings Comparable & Return nil

### ISSUE THREAD

**Issue by mattheworiordan** [fog/fog#3503]
I receive the following warnings when require Fog with Ruby 2.2.1:

```
vendor/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fog-core-1.29.0/lib/fog/core/service.rb:166: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.
vendor/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/fog-core-1.29.0/lib/fog/core/service.rb:166: warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.
```

I am on Fog master, commit f16fae7b0b40af3212facbf317a76628e353fcc5

**Comment by plribeiro3000** [comment]
I believe this issue belongs to [`fog-core`](https://github.com/fog/fog). Could you move it please?

**Comment by mattheworiordan** [comment]
Sure, sorry about that, https://github.com/fog/fog-core/issues/142

**Comment by plribeiro3000** [comment]
No problem. Thanks for moving it!

**Comment by geemus** [comment]
Thanks!
