### ISSUE TITLE
More documentation in CONTRIBUTING.md: new developer with questions about testing, architecture, and contributing

### ISSUE THREAD

**Issue by ihmccreery** [fog/fog#3504]
I'm new to fog, and I'm hoping to contribute to getting fog-google working and tested better, and, if it's needed or wanted, to contribute to fog and fog-core as well, especially to support stability of gems that depend on fog, (e.g. [vagrant-google](https://github.com/mitchellh/vagrant-google)).

In getting started, I've been feeling a bit lost and without documentation to guide me.  More specifically:

- I haven't seen much about the move to split fog into separate gems,
- I haven't found anything about how the tests work, and
- I haven't found documentation about architecture in general, etc., though I have seen the [Roadmap in the wiki](https://github.com/fog/fog/wiki/Roadmap) and #1253 (Steps to split Fog into modules).

Am I missing some documentation somewhere?

If not, I'd like to suggest, (and would happily contribute or review,) significant additions to [CONTRIBUTING.md](https://github.com/fog/fog/blob/master/CONTRIBUTING.md) to include more information to help developers get started, especially in developing new provider gems, including information about how fog and fog-core are structured, where architecture is headed, (especially with the splitting up of gems,) and how to write tests and what coverage to ensure.

Thanks you all!

**Comment by ihmccreery** [comment]
I just found [fog.io/about/contributing.html](http://fog.io/about/contributing.html).  Looks like a lot of what I was looking for.  I'd like to propose to either:

1. Move that document into `CONTRIBUTING.md` in the Git repository, and link to that page at [fog.io/about/contributing.html](http://fog.io/about/contributing.html), or
2. Link to [fog.io/about/contributing.html](http://fog.io/about/contributing.html) from `CONTRIBUTING.md`.

I prefer option 1, since, as a developer, if I want to contribute, I look at the GitHub repo before I go poking around on the website, and because then I can see history, in case something seems out of date.

[fog.io/about/contributing.html](http://fog.io/about/contributing.html) doesn't seem to have information about architectural changes coming with splitting up the gem, though.  That remains an open question.

**Comment by ihmccreery** [comment]
Perhaps much of what I'm looking for is referenced in the [Roadmap](https://github.com/fog/fog/wiki/Roadmap) in the Wiki.  This document should probably be referenced from whatever the authoritative source ends up being, but I don't think it stands on its own as a reference for the current state of fog development.

**Comment by plribeiro3000** [comment]
I believe we are missing documentation for the migration indeed. Perhaps its time to start doing so.

I think that @geemus and @tokengeek are the ones with more background to say how to do the `dance` here.

**Comment by tokengeek** [comment]
At the moment it's sort of chicken and egg.

The little documentation that exists is scattered about and most of us were left copy/pasting what existed before.

We don't have new documentation because besides various ideas on tickets, there's nothing fixed about the new stuff.

Since there's potentially a big jump required (file layout, module namespacing etc) the hardest thing is planning it so we don't just break lots of production applications when things change.

We'll be grateful for help on the docs, I think I need to sit and write up what things "should" look like which might guide the code changes.

**Comment by ihmccreery** [comment]
@plribeiro3000 thanks for the references.

@tokengeek that all sounds about right.  I think at least noting that

- a lot of things are moving, (what things?  I know about the meta-gem movement, the change in testing framework, and the mocking question; are there are other big ones?)
- there's a chicken-and-egg problem with documentation, and
- that the documentation is out of date

would be extremely helpful.  That's a good start, so I'm opening issues (#3509) and, later today, pull requests to move the docs regarding contributing from [fog.io](https://github.com/fog/fog.github.com) to this repository, and reference them from [fog.io](https://github.com/fog/fog.github.com).

I think your idea about writing up what things "should" look like is spot on.  I probably can't be so much help on that for an initial draft, since I don't know this codebase very well, but I'd be more than happy to look over it and comment on it, (readability, sections that seem architecturally confusing or weird, etc.)  I'm opening another issue about that: #3508.

**Comment by ihmccreery** [comment]
I'm going to go ahead and close this issue, with #3508 remaining open.  It's possible we'll want to add more to CONTRIBUTING.md that points to a roadmap, but we can take care of that in #3508.

**Comment by geemus** [comment]
Sounds good. The other big issue is that our extraction work has run into some performance issues (post extraction, requiring fog is SLOW). This may relate to how we have chosen to structure some of this and remains unresolved (and seems to worsen with subsequent extractions). So whatever we did wrong (I have theories that I keep not quite managing to test) is being repeated/propagated...
