### ISSUE TITLE
Design document for ongoing changes

### ISSUE THREAD

**Issue by ihmccreery** [fog/fog#3508]
(First off, @tokengeek, is the title of this issue right?)

Per discussion and @tokengeek's idea in #3504, this is a request for the updating of documentation and the writing of a design document for v2.0.0.  A rough outline of what I think it should include, with amendments and additions more than welcome:
1. clear documentation of where the codebase is now and the major issues we're facing, though this might just reference CONTRIBUTING.md;
2. discussion of each major architectural change we're making, including
   - motivation, (likely referencing the section above,)
   - planned execution,
   - current questions, and
   - references to discussions where these were decided;
3. notes for contributors about what they should expect and/or strive for when writing new code.

**Comment by ihmccreery** [comment]
I've compiled a list of GitHub issues that seem like the most relevant ones to my confused little brain, but I'm probably missing some:

Meta-gem movement
---

- #1253, #2602, #2877 

Testing
---

- General: #1266 
- Shindo -> minitest: #2630 
- Mocking: #1252, #1266 starting about halfway down, #1418, #2629

**Comment by geemus** [comment]
Thanks! Will definitely try to continue fleshing these things out as I am able, but do let us know if you have specific questions we can help with along the way.

**Comment by ihmccreery** [comment]
@geemus Thanks.  I know this is a big project, and I don't expect it to all happen at once.

For a stop-gap, may I at least add notes about the following to CONTRIBUTING:

- a lot of things are moving, (what things?  I know about the meta-gem movement, the change in testing framework, and the mocking question; are there are other big ones?)
- there's a chicken-and-egg problem with documentation, and
- that the documentation is somewhat out of date

and put references to the above GitHub issues?

**Comment by tokengeek** [comment]
re: title and versioning

I'm trying to move us away from a "2.0" branding and using it in context of SemVer.

When we have discussed this most recently we're coming to the decision that for 2.0.0, we're going to drop 1.8.7 support and a few other things.

We don't want to then block releases whilst we then wait for some substantial changes to be designed, tested and documented.

So 2.0 will probably be next month whilst this issue / design document covers _n_ major releases.

What we do need is a good format to document deprecations and required changes for providers due to `fog-core` changes and customers due to unavoidable changes in `fog` - I don't think generating a commit list changelog is good enough for that.

**Comment by ihmccreery** [comment]
Definitely, thanks for the notes.

The [Roadmap](https://github.com/fog/fog/wiki/Roadmap) on the wiki seems like what you're describing, though it could definitely be fleshed out some.  Perhaps that's all we need, plus a link to it from CONTRIBUTING.md, and an introduction.

The downside to keeping this kind of thing in the wiki is that it's not synced under version control with the codebase.  If we want to (try to) keep it in sync with what the code actually looks like/where we are in the versioning, it would probably be better to pull it into the main repository.

**Comment by tokengeek** [comment]
The roadmap was a very quick attempt at something just for the sake of doing something. I ran out of time to itemise everything and cross reference.

I think we may have to duplicate things somewhat.

Putting plans and notes in the codebase doesn't work too well and with a multiple codebase set up like `fog` it gets worse. Most of the changes will probably be in `fog-core`, affect the providers but be tested in `fog` until all the specifications are done.

Of course users of the library will want to `git diff` and among the changes see:

```
BREAKING CHANGES:
* Support for Ruby 1.8.7 has been removed. If you require 1.8.7 support
  please update your Gemfile.lock dependencies to v1.xx
```

So the roadmap should cover everything, a design document will break the highlights down, cross reference implementation issues and a CHANGELOG should roll along in the codebase(s).

I think doing the documentation _properly_ is one of the things that is holding us up and will likely block me doing much coding anytime soon.

**Comment by ihmccreery** [comment]
Sounds good.  When we decide how documentation should be structured, I suggest we write it up in CONTRIBUTING.md in the fog repo, and have all other CONTRIBUTING docs across the different repos (including `fog-core`, likely) point there, with provider- or core-specific notes in the others docs as necessary.

Each repository should also probably have its own CHANGELOG, while also somehow referencing the fog and/or fog-core CHANGELOGS.

> Putting plans and notes in the codebase doesn't work too well and with a multiple codebase set up like fog it gets worse.

Where are you thinking we should put these other documents, (namely Roadmap and Design Doc)?  Solid version control seems important to me; I guess the wiki is technically under git version control, but you can't do much inspection without cloning the wiki and doing inspection locally.  Maybe that's enough.

**Comment by geemus** [comment]
Sounds good.

Yeah, I think the things you mention as moving are the main ones, though
1.8.7 deprecation is probably the biggest/nearest change. Having these in
issues sounds like a good next step and one that will help keep visibility
up.

Thanks!
