### ISSUE TITLE
How to contribute new provider?

### ISSUE THREAD

**Issue by zshannon** [fog/fog#3516]
Hello, I've put together a [provider for Dropbox](https://github.com/zshannon/fog-dropbox). What's the best way to share this with fog users?

**Comment by plribeiro3000** [comment]
@zshannon Awesome. We will have to move the repository to under the organization `fog` and them add it as a dependency here.

But as we are trying to fix a loading issue (#3430) we are kind of holding up. Once we finish this cleaning we can proceed with the official support on it. =)

**Comment by zshannon** [comment]
Exciting! Thanks. Let me know if there's anything I can do to pitch in.

**Comment by plribeiro3000** [comment]
@zshannon Could you check [this page](https://github.com/fog/fog/wiki/Create-New-Provider-from-Scratch) and see if `fog-dropbox` is somewhat following it?

Also, you should not have a `bin` folder in your gem or perhaps this is a solution to our problem with the fog `bin` for extracted providers?

cc/ @geemus @tokengeek

**Comment by geemus** [comment]
Thanks!

**Comment by geemus** [comment]
@tokengeek perhaps what is a solution?

@zshannon if you transfer the repo to me (or add me as admin) I can move it into the fog org. Thanks!

**Comment by zshannon** [comment]
@plribeiro3000 Hm, yeah the `bin` folder was there in the [`fog-google` gem](https://github.com/fog/fog-google) I used as a formatting base. I'll pull it out. One big difference is my tests are written in `rspec`, not `minitest`. Not sure what we should do about that.

**Comment by plribeiro3000** [comment]
@zshannon Awesome. Could you remake them in `minitest`? I think it should not be a pain. But this can be made after you release it. Since you already created tests it can go live.

**Comment by plribeiro3000** [comment]
Oh, wait. my mistake. Don't remove the bin. I thought it was on the root folder.:shame:

**Comment by zshannon** [comment]
@geemus I think I added you as an admin on my repo. Haven't done this before, so I'm not sure.

**Comment by geemus** [comment]
Looks like I have access now, but not administrative controls. Probably the easiest will be to transfer to me and then I can transfer to the org, I've done that before and know it works anyway. Thanks!

**Comment by plribeiro3000** [comment]
I believe this can be closed since the repo was already moved to the fog organization. Thank you for your work @zshannon!

**Comment by geemus** [comment]
Thanks!
