### ISSUE TITLE
uninitialized constant Fog::Service

### ISSUE THREAD

**Issue by vusaalab** [fog/fog#3524]
when i push to my app heroko error and logs says 

      uninitialized constant Fog::Service

Working perfectly local but not in heroku server

hero is the full stack 

       NameError: uninitialized constant Fog::Service
       /tmp/build_4daef779061b871c10200675ed5cb467/vendor/bundle/ruby/2.0.0/gems/fog-aws-

       0.1.2/lib/fog/aws/storage.rb:3:in `<module:Storage>'
       /tmp/build_4daef779061b871c10200675ed5cb467/vendor/bundle/ruby/2.0.0/gems/fog-aws-  

       0.1.2/lib/fog/aws/storage.rb:2:in `<module:Fog>'
       /tmp/build_4daef779061b871c10200675ed5cb467/vendor/bundle/ruby/2.0.0/gems/fog-aws-  

        0.1.2/lib/fog/aws/storage.rb:1:in `<top (required)>'
       /tmp/build_4daef779061b871c10200675ed5cb467/vendor/bundle/ruby/2.0.0/gems/bundler-  

       1.7.12/lib/bundler/runtime.rb:76:in `require'
       /tmp/build_4daef779061b871c10200675ed5cb467/vendor/bundle/ruby/2.0.0/gems/bundler-

      1.7.12/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
       /tmp/build_4daef779061b871c10200675ed5cb467/vendor/bundle/ruby/2.0.0/gems/bundler-

       1.7.12/lib/bundler/runtime.rb:72:in `each'         

      /tmp/build_4daef779061b871c10200675ed5cb467/vendor/bundle/ruby/2.0.0/gems/bundler-         

      1.7.12/lib/bundler/runtime.rb:72:in `block in require

       /tmp/build_4daef779061b871c10200675ed5cb467/vendor/bundle/ruby/2.0.0/gems/bundler-

**Comment by geemus** [comment]
Hey, sorry for the trouble, I think this might be fallout from some refactoring. It is likely to be the same as fog/fog-aws#83, so please check there for more discussion/info. Thanks!
