### ISSUE TITLE
Create openstack swift Directory  with metadata does not work

### ISSUE THREAD

**Issue by dixia** [fog/fog#3526]
In [this doc](https://github.com/fog/fog/blob/master/lib/fog/openstack/docs/storage.md), it was mentioned that create method support a :metadata key.

However, the create method does not really pass the metadata into headers when the put_container method is called in [directory class](https://github.com/fog/fog/blob/master/lib/fog/openstack/models/storage/directory.rb#L44)

Any reason why this is happening if it is not a bug?

**Comment by TerryHowe** [comment]
Bug or missing feature.  It looks kind of like put_container should have options[:metadata] support that iterates through some hash and creates the X-Container-Meta-{name}

**Comment by geemus** [comment]
Yeah, I suspect it was just accidentally overlooked. Definitely would welcome help in implementing it.

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-openstack#43
