### ISSUE TITLE
Files#get_url (expires) params returns a negative date

### ISSUE THREAD

**Issue by Tommyixi** [fog/fog#3528]
I'm currently trying to get the URL of a public item in one of my buckets:

    s3 = Fog::Storage.new(:provider => 'AWS',
                          :aws_access_key_id => Rails.application.secrets.aws_access_key_id,
                          :aws_secret_access_key => Rails.application.secrets.aws_secret_access_key,
                          :region                 => 'us-west-2')
    folder = s3.directories.get('staging', :prefix => "sitemaps/#{current_account.subdomain}").files
    folder.get_url("sitemaps/#{current_account.subdomain}/sitemap.xml", 1000)

Unfortunately folder.get_url returns a string with this Amz-Expiration information:

    X-Amz-Expires=-1428703005&X-Amz-Date=20150410T221325Z&X

And when I try and access the file via the URL, I get this:

    "X-Amz-Expires must be non-negative"

I'm thinking this is a bug (I've also tried putting the 1000 in a string, still no luck)?

**Comment by geemus** [comment]
Hey, I think expires expects an epoch time (rather than a duration). So you probably will want to change `1000` to `Time.now.to_i + 1000` for instance. Definitely let me know if that doesn't resolve the issue for you though. Thanks!
