### ISSUE TITLE
[Openstack] Issue Assigning NIC to server at create

### ISSUE THREAD

**Issue by drich10** [fog/fog#3532]
Hello,

Currently we are unable to create a server on our Openstack environment (Juno) with specific networking information. Here is a sample code snippet:

```
server = service.servers.create(
        name: vm_options[:name],
        flavor_ref: flavor.id,
        image_ref: image.id,
        key_name: vm_options[:key_name],
        security_groups: security_groups,
        nics: [
          { net_id: network.id, v4_fixed_ip: vm_options[:private_ip] }
        ],
      )
server.wait_for { ready? }
```

the request body by fog then comes out as such
```
"{\"server\":{\"flavorRef\":\"042923c8-a4af-4492-b259-09c8f6850bd8\",\"imageRef\":\"c2982704-f72a-4998-ab7d-9eaa6fc2870d\",\"name\":\"server_name\",\"key_name\":\"a_key_name\",\"security_groups\":[{\"name\":\"security_group_name\"}],\"networks\":[{\"uuid\":\"network_id\",\"fixed_ip\":\"192.168.111.100\"}]}}"
```
and the response from Openstack is this:
```
"{\"server\": {\"security_groups\": [{\"name\": \"security_group_name\"}], \"OS-DCF:diskConfig\": \"MANUAL\", \"id\": \"743c25ca-e9ee-4ea4-86ce-f6c44f0ffa93\", \"links\": [{\"href\": \"http://auth_url:8774/v2/guid/servers/743c25ca-e9ee-4ea4-86ce-f6c44f0ffa93\", \"rel\": \"self\"}, {\"href\": \"http://auth_ur:8774/guid/servers/743c25ca-e9ee-4ea4-86ce-f6c44f0ffa93\", \"rel\": \"bookmark\"}], \"adminPass\": \"admin_password\"}}"
```

Eventually the server fails to create with the error 'No valid host', code 500, and this stack trace:
```
File "/usr/lib/python2.7/dist-packages/nova/conductor/manager.py", line 614, in build_instances request_spec, filter_properties)
File "/usr/lib/python2.7/dist-packages/nova/scheduler/client/__init__.py", line 49, in select_destinations context, request_spec, filter_properties)
File "/usr/lib/python2.7/dist-packages/nova/scheduler/client/__init__.py", line 35, in __run_method return getattr(self.instance, __name)(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/nova/scheduler/client/query.py", line 34, in select_destinations context, request_spec, filter_properties)
File "/usr/lib/python2.7/dist-packages/nova/scheduler/rpcapi.py", line 108, in select_destinations request_spec=request_spec, filter_properties=filter_properties)
File "/usr/lib/python2.7/dist-packages/oslo/messaging/rpc/client.py", line 152, in call retry=self.retry)
File "/usr/lib/python2.7/dist-packages/oslo/messaging/transport.py", line 90, in _send timeout=timeout, retry=retry)
File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/amqpdriver.py", line 434, in send retry=retry)
File "/usr/lib/python2.7/dist-packages/oslo/messaging/_drivers/amqpdriver.py", line 425, in _send raise result
```
In the UI we noticed that all the attributes except Security Groups and Network information was populated correctly/at all.

This error does not occur on our instance of Icehouse so we believe the api may have changed between the two? Any insight into this issue would be welcome.

Thanks,
Pivotal Release Engineering

/cc @cppforlife @aramprice

**Comment by TerryHowe** [comment]
The request looks right to me kind of looks like that is what icehouse would expect https://github.com/openstack/nova/blob/stable/icehouse/nova/api/openstack/compute/servers.py#L668

**Comment by drich10** [comment]
Yeah this request works perfectly on our Icehouse environment that has a nova network configuration. The issue is with our Juno environment that has a neutron configuration. Sorry if that wasn't very clear

**Comment by TerryHowe** [comment]
My first guess is it doesn't like the fixed IP.  I would take that off and see if the server comes up.

**Comment by drich10** [comment]
You were correct that the fixed IP is the issue, unfortunately it is not viable for us to let Openstack choose which Private IP the VM has. Is there a way this could be fixed or worked around?

**Comment by TerryHowe** [comment]
I've never tried assigning fixed ips that way and I don't know how the internals work on that why neutron would reject that.  I would try assigning fixed ips to a port and see what errors you get doing that. 

Alternatively, you could assign a port to your server and then you would know the fixed ip.

**Comment by drich10** [comment]
So it seems we have stumbled upon the bug described [here](https://bugs.launchpad.net/nova/+bug/1396854) and the fix is unrelated to Fog. I'll go ahead and close this issue. We were able to fix our deployment of OpenStack with these steps:
```
On each compute node, change line 200 in file:

/usr/lib/python2.7/dist-packages/nova/network/neutronv2/api.py

from: 

port_req_body['port']['fixed_ips'] = [{'ip_address': fixed_ip}]

to:

port_req_body['port']['fixed_ips'] = [{'ip_address': str(fixed_ip)}]

Then restart the nova-compute service:

# etc/init.d/nova-compute restart
```
Thanks for the help!

**Comment by geemus** [comment]
Thanks for the details and update!
