### ISSUE TITLE
AWS S3 Disabling SSLv3 Support Findings

### ISSUE THREAD

**Issue by homezada** [fog/fog#3533]
This issue is mainly to record some findings of using fog with the upcoming AWS disabling of SSLv3 support on all S3 buckets on April 30th, plus ask some follow-ups. See here for all the gory details:

http://stackoverflow.com/questions/29656452/aws-s3-disabling-sslv3-support

We got in contact with AWS support after receiving an email that a number of our buckets were being accessed by SSLv3 and that support for that protocol was being dropped. As part of the follow-up we got given an end-point from AWS support to test through, where we used an IP mapped in a local etc/hosts to change s3.amazonaws.com to a set of services where SSLv3 support was disabled. We also set the hosts to bucket-name-1.s3.amazonaws.com to alias to that IP too.

In our app environment via rails console, we found the following fog issue (changed the bucket name in this example, but kept it's format with dashes in it):

> d = fog_api.directories.get("example-bucket-name")

Excon::Errors::SocketError: hostname "example-bucket-name.s3.amazonaws.com" does not match the server certificate (OpenSSL::SSL::SSLError)

We tried things like forcing the :ssl_version in excon defaults to TLSv1_2 but still got the same error.

The fix we found was to use the alternative URL format for the AWS provider in fog, i.e. 

:path_style => true

..in our fog.configuration block we pass down from Carrierwave. https://s3.amazonaws.com/example-bucket-dev is then used instead of the previous style of https://example-bucket-dev.s3.amazonaws.com

Even though there was no dots/periods in the bucket name (but dashes?), the disabling of SSLv3 through this AWS test system seems to have changed the behaviour of fog. Either that or our method of using a rerouted etc/hosts to the test IP rather than the real S3 servers impacts how OpenSSL behaves with excon?

Our only remaining issue is that we'd like to test this in one of our staging environments and that's in Heroku, where we don't get access to etc/hosts. We can't find any way (other than forking I guess) to reconfigure the default storage provider of AWS to our test IP address away from 's3.amazonaws.com'. 

Is there a way to do that in config? Thanks for any help.

**Comment by geemus** [comment]
I think you can explicitly pass in host/scheme/port and it should use them, see: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/storage.rb#L414

**Comment by homezada** [comment]
Thanks - we missed those. We we try to use :endpoint or the :host rather than just a /etc/hosts change for s3.amazonaws.com we get the excon OpenSSL error (IP edit incase AWS don't want it public), i.e.:

```
Excon::Errors::SocketError: hostname "XX.XXX.XX.X" does not match the server certificate (OpenSSL::SSL::SSLError)
	from /Users/hz/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/openssl/ssl.rb:178:in `post_connection_check'
	from /Users/hz/.rvm/gems/ruby-2.2.1/gems/excon-0.45.2/lib/excon/ssl_socket.rb:137:in `initialize'
	from /Users/hz/.rvm/gems/ruby-2.2.1/gems/excon-0.45.2/lib/excon/connection.rb:387:in `new'
	from /Users/hz/.rvm/gems/ruby-2.2.1/gems/excon-0.45.2/lib/excon/connection.rb:387:in `socket'
	from /Users/hz/.rvm/gems/ruby-2.2.1/gems/excon-0.45.2/lib/excon/connection.rb:106:in `request_call'
```

Is this an excon issue?

**Comment by geemus** [comment]
It's possible? Alternatively, it may be that AWS didn't setup a special new cert for this server and instead reused the other AWS cert, in which case it might well legitimately error in this way?

**Comment by homezada** [comment]
Our best guess would be they set up some sort of HTTPS proxy, with SSLv3 disabled. The endpoint they gave for testing allows access to all of our buckets.

It works ok (as in connects and gets data via fog) with path_style: set to true as an option, and a local /etc/hosts mapping s3.amazonaws.com to the test IP, but not with setting the :hosts or :endpoint set in the fog options. It makes testing on heroku harder (as in a proper staging environment for us rather than dev machines) but we'll continue to trace it through and see if there's a bug. Maybe excon via proxy?

Also, they extended the cut-off date, which doesn't sound like a bad idea:

"Based on the feedback received we are extending the deadline for discontinuing support of SSLv3 for securing connections to S3 buckets to 12:00 AM PDT May 20, 2015. 

Thanks,
The Amazon S3 Team"
https://forums.aws.amazon.com/thread.jspa?threadID=176062

**Comment by geemus** [comment]
Yeah, maybe a proxy could help. I'm not really sure and definitely find this stuff rather confusing as often as not. certainly let me know if there is anything more I can clarify or help with. Thanks!

**Comment by marcamillion** [comment]
@homezada It seems like you are also using Carrierwave, do you mind gisting your updated `config/initializers/carrierwave.rb` file, particularly your `fog_credentials` portion.

This is all quite confusing, so any code you can show about how you fixed it, would be greatly appreciated.

Thanks much!

**Comment by deathwishdave** [comment]
+1 marcamillion's request. Thanks

**Comment by homezada** [comment]
Sure, although all we changed to test through the AWS end-point was the path_style to true from the default of false:

https://gist.github.com/homezada/0469f1e24dc98f045c4b

This allowed us in a dev environment to use an /etc/hosts alias of s3.amazonaws.com to the IP we were given by Amazon for non SSLv3 bucket testing. The default path would otherwise be bucket1.s3.amazonaws.com, as in the bucket name as part of the subdomain, which Excon didn't like.

**Comment by ParthBarot-BoTreeConsulting** [comment]
Please see this SO link and a Excon bug.

http://stackoverflow.com/questions/29656452/aws-s3-disabling-sslv3-support

https://github.com/excon/excon/issues/478

I am facing the same issue, got the S3 setup without SSLv3 but now Excon is throwing the error. 

Any help would be great.

**Comment by geemus** [comment]
responded on the excon issue

**Comment by plribeiro3000** [comment]
@homezada @geemus I see that the `excon` issue seems is not closed yet. Can we move on with this one or do we need to fix something on our side?

If thats the case i would like to push this ticket to [`fog/fog-aws`](https://github.com/fog/fog-aws) since there are some people following only that repo that might have something to add.

**Comment by geemus** [comment]
I think we can probably just close this, but if any one would like to discuss further, a new issue on `fog/fog-aws` would be great. Thanks!
