### ISSUE TITLE
Add support for all nova-manage commands

### ISSUE THREAD

**Issue by kaseyalusi** [fog/fog#3536]
There is no support for the "nova-manage network create" commands in the fog library.

Nova-manage has been deprecated as of Folsom (https://wiki.openstack.org/wiki/NovaManage) but it has not been removed from the project.

**Comment by TerryHowe** [comment]
I think it would be best *not* to support a lot of those features.  Maybe there are some that it would be good to have support for.

**Comment by kaseyalusi** [comment]
That is a good point.  I created this so that the fog api could be used for the openstack-compute cookbook (https://github.com/stackforge/cookbook-openstack-compute) and it looks like that cookbook uses:
- nova-manage floating create
- nova-manage network create
- nova-manage network list
- nova-manage db sync

**Comment by geemus** [comment]
@TerryHowe any further thoughts?

**Comment by TerryHowe** [comment]
Sounds good to me.

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-openstack#44
