### ISSUE TITLE
[vsphere] Support more options as per vsphere API

### ISSUE THREAD

**Issue by fherbert** [fog/fog#3543]
I'd like to modify vm_clone.rd and create_vm.rb to support more of the options available (https://www.vmware.com/support/developer/converter-sdk/conv43_apireference/vim.vm.ConfigInfo.html). The first ones I'd like to add is the ability to manage Memory and CPU hot add enable.
This will also involve changing lib/fog/vsphere/models/compute/server.rb and lib/fog/vsphere/compute.rb to enable to enable the retrieval of these values from vsphere.

**Comment by geemus** [comment]
Sounds reasonable, anything we can do to help?

**Comment by fherbert** [comment]
I'm working on the commit now, nothing needed from you yet. Once I've tested it I'll create the pull request.

**Comment by geemus** [comment]
Great, thanks!
