### ISSUE TITLE
AWS S3 signing token expiring when using IAM profile

### ISSUE THREAD

**Issue by matkam** [fog/fog#3544]
When using fog with an IAM profile instead of key files, the S3 signing token does not get refreshed and expires after some time (~10 hours) causing signed S3 URLs to no longer be valid.

https://github.com/carrierwaveuploader/carrierwave/issues/1547

**Comment by geemus** [comment]
Hmm. I'm not aware of anything in particular around this, but perhaps just because I haven't done this before. I don't know of anything on our end that would be specifically ending up in this situation, it may be a limitation/setting on the AWS side. Have you looked at their documentation around instance profiles and/or raised it with their support?

**Comment by matkam** [comment]
I believe its by design. From their documentation (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html): "These security credentials are temporary and we rotate them automatically." Fog probably loads temporary credentials and stores them until it gets reinitialized. The temporary credentials give you the expiration time. So for every use of the token, fog would have to check to see if its passed the expiration time and then request new credentials if expired.

**Comment by geemus** [comment]
Thanks for the update. Looks like we store the expiration time already: https://github.com/fog/fog-aws/blob/5903a7819b12ec6feb3b1d4177f9a1f4a4ca3a59/lib/fog/aws/credential_fetcher.rb#L19. So presumably we could check against that before making subsequent requests and refresh if needed, would you be up for working on a related pull request? Thanks!

**Comment by matkam** [comment]
Looks like ```Fog::Storage::AWS::Utils#signed_url``` (https://github.com/fog/fog-aws/blob/5903a7819b12ec6feb3b1d4177f9a1f4a4ca3a59/lib/fog/aws/storage.rb#L141) just needs to make a call to ``refresh_credentials_if_expired```. I'll make a pull request after testing.

**Comment by geemus** [comment]
Good catch, thanks!
