### ISSUE TITLE
AWS region eu-central-1 is reported as unknown region

### ISSUE THREAD

**Issue by thebaron22** [fog/fog#3546]
AWS region eu-central-1 is reported as unknown region in latest version 1.23.0.

**Comment by geemus** [comment]
Sorry to hear it. Could you provide a bit more context around what you are doing that results in the error to help us pin things down? Thanks!

**Comment by fcheung** [comment]
According to the [changelog](https://github.com/fog/fog/blob/master/CHANGELOG.md) , eu-central-1 was only added in 1.25.0

**Comment by geemus** [comment]
@fcheung thanks for narrowing that down.
