### ISSUE TITLE
Amazon S3 Shifting from SSLV3 to TLS 

### ISSUE THREAD

**Issue by muaaz-vf** [fog/fog#3547]
Hi Guys,
     I just received an email regarding amazon is discontinuing the SSLV3 and moving to TLS, i just needed to verify with you guys that current implementation is good to go. Thanks for the very great gem, love to use it.  

Regards,
Muaaz Rafi

**Comment by geemus** [comment]
Hey, thanks for checking in. We use excon as our underlying http transport and by default it does not specify anything related to SSL versions, which I believe means it should just negotiate with the server about what version they ought to use together. I think this should make it transparent to us when this transition happens. If that doesn't turn out to be the case, there are ways to specifically ask for TLS, but I think we should try to use the negotiation route first as it is preferable when it works. Hope that clarifies.
