### ISSUE TITLE
Security Group IDs in AWS EC2 Network Interface

### ISSUE THREAD

**Issue by danjellesma** [fog/fog#3548]
I'm trying to launch some instances into a VPC that has public IPs disabled by default. The way I've been able to work around that is by using 

``` ruby
    ami = Ami.first
    @instance = connection.servers.create(
        image_id: ami_id,
        hypervisor: 'hvm',
        vpc_id: ami.vpc.vpc_id,
        #subnet_id: ami.subnet.subnet_id,
        #security_group_ids: [ ami.env.security_group.group_id],
        flavor_id: 't2.micro',
        key_name: 'aws-dev',
        iam_instance_profile_name: 'allow-ssm',
        network_interfaces:  [{
            'DeviceIndex'  => '0',
            'AssociatePublicIpAddress'  => true,
            'SecurityGroupIds: [ ami.env.security_group.group_id],
            'SubnetId'  => ami.subnet.subnet_id
        }]

```

This fails saying "UnknownParameter => The parameter SecurityGroupIds is not recognized".

Using the 'Parameter' => 'value' format was something I found in a Fog issue. The commented out 'security_group_ids' that worked before adding the network_interfaces can no longer be used. 

What would be the correct parameter for selecting a Security Group inside the network interface array? 

Also, how can I find what parameters are acceptable to use with connection.servers.create? The values that come back from 'servers.create' don't seem to match up with what needs to be passed when creating.

**Comment by geemus** [comment]
Sorry to hear you are having trouble with this, it is a bit tricky to navigate. 

You can see more about how it assigns those options here: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/models/compute/server.rb#L141

In particular, the network/security group related stuff is here: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/models/compute/server.rb#L174

From my reading of it just now, I believe that you'll want to just leave the security group ids at the top level (not nested under interfaces) and it should get added/assigned to the interfaces automatically via the code linked above. Hope that helps, but definitely let me know if you are still having issues or have further questions. Thanks!
