### ISSUE TITLE
Trying to make connection to Ovirt node using fog

### ISSUE THREAD

**Issue by nohtyp** [fog/fog#3559]
When I configure authentication to oVirt using curl command, I get back results from the API, but when using fog (1.29.0, 1.28.0, 1.25.0) I continuously get back the OVIRT::OvirtException: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
from /home/thomas.foster/.rvm/gems/ruby-2.1.4/gems/rbovirt-0.0.35/lib/rbovirt.rb:197:in `handle_fault'

The curl command is: curl -v -u "admin@internal" -H "Accept: application/xml" -X GET https://ovirt-mgmt.nsof-vtl.local:443/api/datacenters (i fill in the password) and get back results.

The fog command is (using pry..I don't know how to debug yet using pry):     test = Fog::Compute.new :provider => 'Ovirt', :ovirt_ca_cert_file => '/etc/pki/tls/certs/ca-bundle.crt', :ovirt_username => 'admin@internal', :ovirt_password => 'password', :ovirt_port => 443, :ovirt_ca_no_verify => true
=> #<Fog::Compute::Ovirt::Real:39464820 @client=#<OVIRT::Client:0x00000004ce14f0 @api_entrypoint="https://ovirt-mgmt.nsof-vtl.local", @credentials={:username=>"admin@internal", :password=>"password"}, @datacenter_id=nil, @cluster_id=nil, @filtered_api=nil, @ca_cert_file="/etc/pki/tls/certs/ca-bundle.crt", @ca_cert_store=nil, @ca_no_verify=true>>

[5] pry(main)> test.list_clusters
OVIRT::OvirtException: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
from /home/thomas.foster/.rvm/gems/ruby-2.1.4/gems/rbovirt-0.0.35/lib/rbovirt.rb:197:in `handle_fault'

Any help would be appreciated.

**Comment by geemus** [comment]
Could you set `EXCON_DEBUG=true` and run again? I think the output from that will give us a lot more to work with in terms of getting this debugged. Thanks!

**Comment by nohtyp** [comment]
This is what I get back...

irb
2.1.4 :001 > require 'fog'
 => true 
2.1.4 :002 > EXCON_DEBUG=true
 => true 
2.1.4 :003 > test = Fog::Compute.new :provider => 'Ovirt', :ovirt_ca_cert_file => '/etc/pki/tls/certs/ca-bundle.crt', :ovirt_username => 'admin@internal', :ovirt_password => 'new.one', :ovirt_port => 443
 => #<Fog::Compute::Ovirt::Real:17165780 @client=#<OVIRT::Client:0x0000000297a3e0 @api_entrypoint="https://ovirt-mgmt.nsof-vtl.local", @credentials={:username=>"admin@internal", :password=>"new.one"}, @datacenter_id=nil, @cluster_id=nil, @filtered_api=nil, @ca_cert_file="/etc/pki/tls/certs/ca-bundle.crt", @ca_cert_store=nil, @ca_no_verify=nil>> 
2.1.4 :004 > test.list_clusters
OVIRT::OvirtException: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
	from /home/thomas.foster/.rvm/gems/ruby-2.1.4/gems/rbovirt-0.0.35/lib/rbovirt.rb:197:in `handle_fault'
	from /home/thomas.foster/.rvm/gems/ruby-2.1.4/gems/rbovirt-0.0.35/lib/rbovirt.rb:114:in `rescue in http_get'
	from /home/thomas.foster/.rvm/gems/ruby-2.1.4/gems/rbovirt-0.0.35/lib/rbovirt.rb:109:in `http_get'
	from /home/thomas.foster/.rvm/gems/ruby-2.1.4/gems/rbovirt-0.0.35/lib/client/datacenter_api.rb:14:in `datacenters'
	from /home/thomas.foster/.rvm/gems/ruby-2.1.4/gems/rbovirt-0.0.35/lib/rbovirt.rb:101:in `current_datacenter'
	from /home/thomas.foster/.rvm/gems/ruby-2.1.4/gems/rbovirt-0.0.35/lib/rbovirt.rb:96:in `search_url'
	from /home/thomas.foster/.rvm/gems/ruby-2.1.4/gems/rbovirt-0.0.35/lib/client/cluster_api.rb:16:in `clusters'
	from /home/thomas.foster/.rvm/gems/ruby-2.1.4/gems/fog-1.29.0/lib/fog/ovirt/requests/compute/list_clusters.rb:6:in `list_clusters'
	from (irb):4
	from /home/thomas.foster/.rvm/rubies/ruby-2.1.4/bin/irb:11:in `<main>'
2.1.4 :005 >

**Comment by nohtyp** [comment]
I also tried it with the ovirt_ca_no_verify option:

 test = Fog::Compute.new :provider => 'Ovirt', :ovirt_ca_cert_file => '/etc/pki/tls/certs/ca-bundle.crt', :ovirt_username => 'admin@internal', :ovirt_password => 'new.one', :ovirt_port => 443, :ovirt_ca_no_verify => true
 => #<Fog::Compute::Ovirt::Real:21461600 @client=#<OVIRT::Client:0x000000028c5878 @api_entrypoint="https://ovirt-mgmt.nsof-vtl.local", @credentials={:username=>"admin@internal", :password=>"new.one"}, @datacenter_id=nil, @cluster_id=nil, @filtered_api=nil, @ca_cert_file="/etc/pki/tls/certs/ca-bundle.crt", @ca_cert_store=nil, @ca_no_verify=true>> 
2.1.4 :006 > test.list_clusters
OVIRT::OvirtException: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
	from /home/thomas.foster/.rvm/gems/ruby-2.1.4/gems/rbovirt-0.0.35/lib/rbovirt.rb:197:in `handle_fault'
	from /home/thomas.foster/.rvm/gems/ruby-2.1.4/gems/rbovirt-0.0.35/lib/rbovirt.rb:114:in `rescue in http_get'
	from /home/thomas.foster/.rvm/gems/ruby-2.1.4/gems/rbovirt-0.0.35/lib/rbovirt.rb:109:in `http_get'
	from /home/thomas.foster/.rvm/gems/ruby-2.1.4/gems/rbovirt-0.0.35/lib/client/datacenter_api.rb:14:in `datacenters'
	from /home/thomas.foster/.rvm/gems/ruby-2.1.4/gems/rbovirt-0.0.35/lib/rbovirt.rb:101:in `current_datacenter'
	from /home/thomas.foster/.rvm/gems/ruby-2.1.4/gems/rbovirt-0.0.35/lib/rbovirt.rb:96:in `search_url'
	from /home/thomas.foster/.rvm/gems/ruby-2.1.4/gems/rbovirt-0.0.35/lib/client/cluster_api.rb:16:in `clusters'
	from /home/thomas.foster/.rvm/gems/ruby-2.1.4/gems/fog-1.29.0/lib/fog/ovirt/requests/compute/list_clusters.rb:6:in `list_clusters'
	from (irb):6
	from /home/thomas.foster/.rvm/rubies/ruby-2.1.4/bin/irb:11:in `<main>'

**Comment by geemus** [comment]
I'm unsure, I believe we are passing the no verify option through, so perhaps this is an rbovirt issue? Asking there may be more helpful anyway as they may have more specific ideas than we have here. Do let me know if there is anything else I can help with, but without more knowledge of rbovirt/libvirt, I'm afraid I am not well equipped to help.
