### ISSUE TITLE
Attach instance to existing autoscaling group?

### ISSUE THREAD

**Issue by mg03** [fog/fog#3565]
Hi
The aws cli has a way to attach instances to an autoscaling group , for example ( taken from aws website) - 

aws autoscaling attach-instances --instance-ids i-93633f9b --auto-scaling-group-name basic-auto-scaling-group

Is there a way to do the same using fog?

Regards

**Comment by geemus** [comment]
It looks like that is implemented as http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_AttachInstances.html, which it doesn't appear we support yet. It could be added without too much trouble if you would be interested in working on it. Just let me know if you need any help or have questions. We would want to add it to the fog/fog-aws repo if so. Just let me know if you have questions and/or report against that repo if you feel you won't be able to get to it and you want to put it on the other maintainers radars. Thanks!
