### ISSUE TITLE
list virtualSwitches - vsphere

### ISSUE THREAD

**Issue by bechampion** [fog/fog#3569]
Hi there , Is there any example of how to list all virtual switches in a network?

I see some code in list_networks but not sure if that's the right way to get this done.

Thanks!

**Comment by geemus** [comment]
@nirvdrum any advice you can share? Thanks!

**Comment by nirvdrum** [comment]
`list_networks` will list all the standard networks, distributed switches, and distributed port groups, I believe.  The output of this call, however, is a simplified hash extracting key attributes.  If you need access to more information, you can get the raw network objects (from rbvmomi) by calling `raw_networks(datacenter_name)`.

**Comment by geemus** [comment]
Thanks!
