### ISSUE TITLE
Fog::Image::OpenStack does not correctly construct URL for versioned API

### ISSUE THREAD

**Issue by majewsky** [fog/fog#3578]
My `image` endpoint is configured as `http://glance.local:9292/` without an API version number, so `Fog::Image::OpenStack` uses `Fog::OpenStack.get_supported_version` to figure out the versioned API base URL by querying `GET /` on the Glance. This is the result returned from Glance (Kilo):

```js
{
    "versions": [
        // various entries for v2.x omitted for brevity
        {
            "id": "v1.1",
            "links": [
                {
                    "href": "http://glance.local:9292/v1/",
                    "rel": "self"
                }
            ],
            "status": "SUPPORTED"
        },
        {
            "id": "v1.0",
            "links": [
                {
                    "href": "http://glance.local:9292/v1/",
                    "rel": "self"
                }
            ],
            "status": "SUPPORTED"
        }
    ]
}
```

The `get_supported_version` method decides that it likes the `v1.1` version and returns that, but then Fog::Image::OpenSTack constructs the wrong URL in [lib/fog/openstack/image.rb:206](https://github.com/fog/fog/blob/master/lib/fog/openstack/image.rb#L206)

```
@path = "/" + Fog::OpenStack.get_supported_version(SUPPORTED_VERSIONS,
                                                   uri,
                                                   @auth_token,
                                                   @connection_options)
```

This breaks because the URL path is `/v1/` for the v1.1 API, not `/v1.1/`. Glance reports the correct URL in the response shown above, and that URL should be preferred over doing our own guesswork.

**Comment by majewsky** [comment]
Okay, it turns out that this was not the root cause for my problems (the main problem was that the database on the Glance host had crashed). I'd still consider the described behavior wrong for the same reason, even if Glance happens to accept the `/v1.1/` URL right now.

**Comment by TerryHowe** [comment]
What part of the behavior is wrong because it looks to me like get_supported_version is making a good choice out of the available versions.

**Comment by majewsky** [comment]
The choice of the v1.1 version is good, but it comes up with the URL path `/v1.1/` (as in: `http://glance.local:9292/v1.1/`) while Glance reports the v1.1 API to reside at `/v1/`. My point is that the reported URL should take precedence over guesstimated URL schemes.

**Comment by TerryHowe** [comment]
/v1.1/ shouldn't be in versions list if the URL isn't supported.

**Comment by majewsky** [comment]
v1.1 is supported, but its URL is not `/v1.1/`, as can be seen in the response from Glance above.

```js
        {
            "id": "v1.1", // the version
            "links": [
                {
                    "href": "http://glance.local:9292/v1/", // its location states "v1" !
                    "rel": "self"
                }
            ],
            "status": "SUPPORTED"
        }
```

**Comment by tealover** [comment]
hava you soloved this problem yet?? I also met with it when i want to deploy microbosh to kilo .

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-openstack#45
