### ISSUE TITLE
[OpenStack] NoMethodError: create_flavor_metadata

### ISSUE THREAD

**Issue by seanhandley** [fog/fog#3599]
For some reason, `Fog::Compute` is unaware of the `create_flavor_metadata` service method. The model object similarly is reporting to be unaware of the method. It seems to be declared in `compute.rb`, so it's not exactly clear what's going on.

```
irb(main):036:0> Fog::Compute.new(OPENSTACK_ARGS).create_flavor_metadata
NoMethodError: undefined method `create_flavor_metadata' for #<Fog::Compute::OpenStack::Real:0x007f6c7069e680>
```

Any ideas?

**Comment by geemus** [comment]
Did you figure out what you needed here?

**Comment by seanhandley** [comment]
Thanks @geemus 

Yeah, I had a slightly older version loaded
