### ISSUE TITLE
[openstack] randomly failing tests in CI

### ISSUE THREAD

**Issue by Ladas** [fog/fog#3603]
Randomly failing tests in CI, probably dependent on some variable order of things

  Fog::Compute[:openstack] | security_group (openstack) ++++++++      
      tests/openstack/models/compute/security_group_tests.rb
        success
        Fog::Compute[:openstack] | security_group (openstack)
      - successfully destroyed rule
        expected => true
        returned => false
      
      tests/openstack/models/compute/security_group_tests.rb
      - succeeds
        expected => true
        returned => false
      
      tests/openstack/models/compute/security_group_tests.rb
      - succeeds
        expected => true
        returned => false

and

Fog::Compute[:openstack] | server requests (openstack) +++++

tests/openstack/requests/compute/server_tests.rb
success
Fog::Compute[:openstack] | server requests (openstack)
- succeeds
expected => true
returned => false

**Comment by geemus** [comment]
Thanks for calling these out. I think I've tried to look into them once or twice before, but without much luck. Hopefully we'll be able to pin them down one of these days.

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-openstack#47
