### ISSUE TITLE
Mock only accepts string options

### ISSUE THREAD

**Issue by nirvdrum** [fog/fog#362]
Hi,

It's possible I have this wrong, but it looks like the Fog::AWS::Storage::Real class can accept symbols for the options hash, but the Mock class can only accept strings.

So whereas this seems to work fine when interacting directly with S3:

<pre>
response = @directory.connection.get_bucket(@directory.key, :prefix => prefix, :max_keys => MAX_KEYS, :marker => marker)
</pre>

It must be called like so in order for the Mock implementation to be satisfied:

<pre>
response = @directory.connection.get_bucket(@directory.key, 'prefix' => prefix, 'max-keys' => MAX_KEYS, 'marker' => marker)
</pre>

Since all the options have defaults or get ignored otherwise, this could trip someone up rather easily.

**Comment by geemus** [comment]
closing in favor of fog/fog-core#46
