### ISSUE TITLE
[vcloud-director] How to handle tasks

### ISSUE THREAD

**Issue by lasko** [fog/fog#3620]
This is more of a question rather than an issue -- as I have not found any documentation on this.

I'm trying to create a vapp from a template, but I also need to set the vm name (Virtual Machine Name, and Hostname) and the only way I know how to do this is via the put_vm method.

```
org = vcloud.organizations.first
vdcid = org.vdcs.get_by_name("My VDC").id
vdc = org.vdcs.get_by_name("MyVDC")
network = org.networks.get_by_name("Production_LAN")
catalog = org.catalogs.get_by_name("vCloud_Catalog")
template = catalog.catalog_items.get_by_name("CloudLinux")
new_vapp_id = template.instantiate(vapp_name, {vdc_id: vdcid, network_id: network.id})
new_vapp = vdc.vapps.get(new_vapp_id)
vcloud.put_vm(vm.id, "My New Name", {})
```

Well ... This produces an error

```
/var/lib/gems/1.9.1/gems/excon-0.45.3/lib/excon/middlewares/expects.rb:10:in `response_call': The entity CloudLinux is busy completing an operation. (Fog::Compute::VcloudDirector::BadRequest)
```

I know I need to wait for the new vapp to be created but I cannot figure out how to determine whether its been created and not busy completing the operation.

I'm new with this framework, and newish to ruby so any help would be great.

**Comment by geemus** [comment]
Usually in situations like this, it would be something like `new_vapp.wait_for { ready? }`, but I'm not really very familiar with vcloud specifically.
