### ISSUE TITLE
Danger! zero file uploading!

### ISSUE THREAD

**Issue by skyeagle** [fog/fog#3622]
Hello!

We experienced a serious bug in production. We discovered that small part of our files had been  uploaded with zero size. The issue involves `excon` gem (@geemus).

The main problem was with custom `chunker` and possible retries (e.x. re-authentication on stale auth token) during upload request. There is no `rewind` for a file in the code of [fog][1] and [excon][2] at the moment and it's hard to inject it when you use `chunker`.

[1]: https://github.com/fog/fog/blob/master/lib/fog/openstack/requests/storage/put_object.rb#L19
[2]: https://github.com/excon/excon/blob/095c87fa688ca1c5086797d94c5340a92a392a77/lib/excon/connection.rb#L145

This issue is a warning to anyone who use custom chunkers.

Anyway, thanks to everyone for work on these excellent gems.

**Comment by skyeagle** [comment]
It looks like the issue is not only `openstack` related. So, I'll edit the title.

**Comment by geemus** [comment]
Hmm, this does seem problematic. Could you elaborate on why you need a custom chunker? In many cases the default one (which loads ~1mb into memory and writes it to the socket at a time) is sufficient. Thanks!

**Comment by skyeagle** [comment]
We needed a progress of uploading on that moment. We use the default one now as a working solution but it also with a workaround. Idempotent behaviour did retry queries (4 default) even on auth error (401). As result, we have set retries to 0.

**Comment by geemus** [comment]
You might be able to write a middleware to manage your own idempotent behavior, I guess I'm not certain of the best approach here since I haven't really heard from others about running into this usage pattern/set of errors.

**Comment by skyeagle** [comment]
Ok, thank you. I'll close the issue.
