### ISSUE TITLE
condition based change of fog_directory 

### ISSUE THREAD

**Issue by MihirKumarThakur** [fog/fog#3626]
i have using fog successfully in recent year with paperclip with no issue. Now my requirement have changed .following are my requirements :-
1. i have two different uploader in project.
2. i want to store files in s3.
3. i don't want to make a new filed for paperclip in my database.
4. i have only one attached file .
5. i want to make the behaviour of attached file differently when it comes from different uploader.
6.i want to make two different fog_directory and use based on condition.

thanks.

**Comment by geemus** [comment]
I'm afraid I don't know off hand how best to accommodate this, it seems like mostly a paperclip usage issue rather than a fog one in particular though. So perhaps maintainers on that project would be better able to answer this question well?

**Comment by plribeiro3000** [comment]
@MihirKumarThakur Did you open an issue in `paperclip` for this?

If so can you link this issue?  Thanks!

**Comment by plribeiro3000** [comment]
Closing due lack of feedback.

If you have more information or think this was wrong please comment here again.
