### ISSUE TITLE
[openstack] Associate a floating IP address with certain interface

### ISSUE THREAD

**Issue by pdilung** [fog/fog#3632]
I would like to associate a floating IP address with certain fixed IP (interface). Although according to [OpenStack API documentation](http://developer.openstack.org/api-ref-compute-v2-ext.html#addFloatingIP) this should be possible by posting a following request:
```json
{
    "addFloatingIp": {
        "fixed_address": "166.78.185.201",
        "address": "172.24.4.225"
    }
}
```

It seems that [`associate_address`](https://github.com/fog/fog/blob/b2c6e0df30eae7fb9154ba6bd340f27c0c158855/lib/fog/openstack/requests/compute/associate_address.rb#L6) method does not support an optional `fixed_address` parameter and thus the floating IP gets associated with the first network entry of a given node instance (this is not a problem for single-NIC guests, though multiple-NIC guests may require floating IP is associations with specific fixed IP/interface) .

Could someone from Fog::OpenStack gurus confirm this or provide me with information how to associate a floating IP with a given fixed IP please? I am willing to create a PR if this is not yet implemented.

Thanks

Pali

**Comment by TerryHowe** [comment]
As I recall, you are supposed to supply a network id or port id with that.

**Comment by pdilung** [comment]
@TerryHowe Thanks, could you provide an example? To my understanding, [`associate_address`|https://github.com/fog/fog/blob/b2c6e0df30eae7fb9154ba6bd340f27c0c158855/lib/fog/openstack/requests/compute/associate_address.rb#L5] takes only two parameters, `server_id` and `ip_address` and the request body does not set `network_id` nor `port_id`:
```ruby
body = { "addFloatingIp" => {"address" => ip_address}}
```

**Comment by TerryHowe** [comment]
I thought if you were using neutron, you'd be using this extension

http://developer.openstack.org/api-ref-compute-v2-ext.html#os-interface

I was just talking OpenStack, not Fog.

**Comment by TerryHowe** [comment]
Yeh, I just don't see addFloatingIp working for that.  I don't see any support for os-interface in Fog unless it is hidden somewhere.

**Comment by pdilung** [comment]
@TerryHowe  I see, in that case, I am going to implement this feature and create a PR to have this in fog. IMHO, it should be pretty straightforward with minimal changes to current method interface:
```ruby
def associate_address(server_id, ip_address, fixed_address=nil)
...
```

**Comment by pdilung** [comment]
I implemented this feature and just tested it. It seems OK. I shall post a PR soon.

**Comment by pdilung** [comment]
It is not necessary to rewrite `accociate_address` at the end. I could reach my objective by using `ports` and `floating_ips` collections:
```
def add_node_floating_ip(attrs)
  ::Dopv::log.debug("Node #{nodename}: Adding floating IP to #{attrs[:nicname]}.")
  network_provider.floating_ips.create(attrs)
end

def add_node_floating_ips(node_instance)
  ::Dopv::log.info("Node #{nodename}: Adding floating IPs.")
  @network_ports ||= network_provider.ports.select { |p| p.device_id == node_instance.id }
  interfaces_config.each do |i|
    if i[:floating_network]
      floating_network = network(i[:floating_network])
      subnetwork = subnet(i[:network])
      port = @network_ports.find { |p| p.fixed_ips.find { |f| f["subnet_id"] == subnetwork.id } }
      attrs = {
        :floating_network_id => floating_network.id,
        :port_id => port.id,
        :fixed_ip_address => port.fixed_ips.first["ip_address"],
        :nicname => i[:name]
      }
      add_node_floating_ip(attrs)
    end
  end
end
```

Closing this issue

**Comment by geemus** [comment]
Thanks for the detailed update!
