### ISSUE TITLE
[dynect] Extract dynect to create fog-dynect

### ISSUE THREAD

**Issue by glennpratt** [fog/fog#3646]
I'd like to start splitting out dynect into it's own gem. Would this change be accepted as a fog organization project?

Is there a documented process or should I just follow what has been done in previous issues?

**Comment by plribeiro3000** [comment]
You should be fine if you follow [this](https://github.com/fog/fog/wiki/Create-New-Provider-from-Scratch) wiki page.

also take a look at #3430 and the solution being executed.

As for the organization i believe @geemus is your guy. =)

**Comment by geemus** [comment]
Yep, sounds good, just let me know if you have questions or anything I can help with. Thanks!

**Comment by glennpratt** [comment]
Thanks!

**Comment by glennpratt** [comment]
Here's the initial extraction:

https://github.com/glennpratt/fog-dynect

and Travis:

https://travis-ci.org/glennpratt/fog-dynect

Still cleaning up some things, like README.md and looking at the Travis 1.8 failures.

**Comment by glennpratt** [comment]
Fixed Travis and updated README.md.

**Comment by glennpratt** [comment]
I haven't made any changes for autoloading. Is needed for an initial release or can the be a follow up?

**Comment by plribeiro3000** [comment]
@glennpratt I would like so we don't touch that regression again. Is that a problem?

**Comment by glennpratt** [comment]
Not a problem, I'll make a PR for it.

**Comment by plribeiro3000** [comment]
Awesome. Thx!

**Comment by glennpratt** [comment]
@plribeiro3000 autoload changes for review: https://github.com/glennpratt/fog-dynect/pull/1

**Comment by glennpratt** [comment]
Merged. @geemus anything in particular I need to do to make this a proper fog project?

**Comment by glennpratt** [comment]
Created a removal PR at #3651

**Comment by glennpratt** [comment]
Published to rubygems: https://rubygems.org/gems/fog-dynect

**Comment by plribeiro3000** [comment]
Awesome. Closing. Lets keep the discussion under #3651.
