### ISSUE TITLE
[openstack] Create/list/delete server groups and assign VMs into them

### ISSUE THREAD

**Issue by pdilung** [fog/fog#3656]
Hello,

Does somebody know whether OpenStack provider implments creation/deletion/listing of server groups as well as asignment of VMs into them.
Basically I am interested in creation of virtual machine in a certain server group:
```
nova boot  --image ubuntu --flavor m1.small --hint group=aa8a69f4-2567-47c6-a28c-2934a8c7959c vm1
```

Thanks

**Comment by TerryHowe** [comment]
Like this?

https://github.com/fog/fog/blob/master/lib/fog/openstack/requests/compute/create_aggregate.rb

**Comment by pdilung** [comment]
Thanks for the tip. I am not sure if host aggregates are suitable for my usecase. My usecase would be to be able to define a bunch of VMs that have an anti-affinity to each other. According to API doc, `server-groups` are used for this. Any further help will be highly appreciated.

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-openstack#49
