### ISSUE TITLE
Does Fog::Storage have a general `configure` functionality?

### ISSUE THREAD

**Issue by marshallshen** [fog/fog#3661]
Based on Fog `README`, to set up a new connection to AWS storage:
```
connection = Fog::Storage.new({
  :provider                 => 'AWS',
  :aws_access_key_id        => YOUR_AWS_ACCESS_KEY_ID,
  :aws_secret_access_key    => YOUR_AWS_SECRET_ACCESS_KEY
})
```

Would it make sense to have the following syntax.
### To set up configuration (sometimes for entire application)
```
Fog::Storage.configure do |config|
   config.provider = "AWS"
   config.aws_access_key_id = YOUR_AWS_ACCESS_KEY_ID
   config.aws_secret_access_key = YOUR_AWS_SECRET_ACCESS_KEY
end
```

### When we need a new Fog::Storage connection:
```
Fog::Storage.new
```

I'm not sure if there's already support for this (I just briefly scanned through the code base and README).

Thanks!

**Comment by geemus** [comment]
I believe you can achieve this through using `Fog.credentials = {}`, at least for setting the aws access/secret keys. I think when creating new connections you would still need to specify that you wanted aws though. Does that make sense/help?
