### ISSUE TITLE
fog-ecloud dependency locking

### ISSUE THREAD

**Issue by pravi** [fog/fog#3679]
is it intentional to keep fog-ecloud exactly at 0.1.1?

**Comment by plribeiro3000** [comment]
I don't think so. it should be `>= 0.1.1`. Wanna send a PR?

**Comment by geemus** [comment]
`~>` would probably be better/safer than `>=`, actually.

**Comment by pravi** [comment]
~> 0.1.1 or ~> 0.1?

**Comment by geemus** [comment]
um, ~ 0.1.1 I think. That should give >= 0.1.1 + < 1.0.0, I believe, which
is what we want if I'm not mistaken.

**Comment by pravi** [comment]
~> 0.1.1 means >= 0.1.1, < 0.2.0. It is ~> 0.1 then.

**Comment by pravi** [comment]
how about other dependencies then? You just want to make sure its < 1.0.0, right?

**Comment by geemus** [comment]
Yeah, less than 1.0.0 I think. Sorry, you are correct, we want to leave off
the patch version and just have major/minor or it will limit to minor. I
think any/all of the dependencies being that way should (hopefully) be
fine. Thanks!

**Comment by geemus** [comment]
Thanks!
