### ISSUE TITLE
uninitialized constant Fog::Service

### ISSUE THREAD

**Issue by jogaco** [fog/fog#3683]
Having trouble with this error:

```
/home/my/.rvm/gems/ruby-2.1.3@myproject/gems/fog-aws-0.7.6/lib/fog/aws/storage.rb:3:in `<module:Storage>': uninitialized constant Fog::Service (NameError)
	from /home/my/.rvm/gems/ruby-2.1.3@myproject/gems/fog-aws-0.7.6/lib/fog/aws/storage.rb:2:in `<module:Fog>'
```
I get this error with versions from 1.33 to 1.29 inclusive.

Changed Gemfile spec to version 1.20, as I had in another project, and everything worked again

**Comment by geemus** [comment]
You may need to also bump your fog-core version in addition to fog. I think anyway that this will resolve that for you.

**Comment by jogaco** [comment]
I do not have fog-core in my Gemfile. It is included in Gemfile.lock at 1.32.1 version, which I think is the latest.

**Comment by geemus** [comment]
Ah, ok. @plribeiro3000 I think something like this came up historically at some point, do you happen to remember specifics?

**Comment by plribeiro3000** [comment]
Yeah. Which lib or code is triggering this `AWS` storage?
Are you using `route53`?

**Comment by jogaco** [comment]
I'm using fog as documented in Carrierwave README 'Optimized Loading of Fog':

```
gem 'fog', '1.20', require: 'fog/aws/storage'
```

I try to open a rails console and just get the error.

**Comment by plribeiro3000** [comment]
Please take some time to go over carrierwave `README` again.
The optimized loading of fog is for non extracted providers only. See [here](https://github.com/carrierwaveuploader/carrierwave#optimized-loading-of-fog).

**Comment by plribeiro3000** [comment]
Closing since this is not really an issue.

Thanks for your report.

**Comment by plribeiro3000** [comment]
More precisely, take a look [here](https://github.com/carrierwaveuploader/carrierwave#using-amazon-s3)
