### ISSUE TITLE
exception undefined method `body' for #<Fog::DNS::AWS::Error: Throttling => Rate exceeded>

### ISSUE THREAD

**Issue by benlong** [fog/fog#3690]
Started seeing this in our rate-limiting retry routines. Has the response from AWS changes?

```
exception undefined method `body' for #<Fog::DNS::AWS::Error: Throttling => Rate exceeded>
```

**Comment by geemus** [comment]
I don't think so, it looks more likely to be a mismatch of error expectations (it is probably expecting it to be an excon error, but it is a fog one, so it fails to do something). Could you share the rest of the stacktrace? I think that might help pin down where this is coming from. Thanks!

**Comment by benlong** [comment]
o\  here you go. thanks.

```
JobHelperAWS.should_retry? job_helper.rb:54 exception trace .rvm/gems/ruby-1.9.3-p545/gems/fog-aws-0.1.1/lib/fog/aws/models/dns/records.rb:29:in `all'
app/jobs/auto_dns_create.rb:47:in `block (2 levels) in perform'
lib/job_helper.rb:21:in `block in progressive_retry'
lib/job_helper.rb:34:in `execute'
lib/job_helper.rb:21:in `progressive_retry'
app/jobs/auto_dns_create.rb:43:in `block in perform'
lib/semaphore_lock.rb:22:in `protected_work'
lib/semaphore_lock.rb:10:in `protected_work!'
app/jobs/auto_dns_create.rb:12:in `perform'
app/jobs/wrap_all_jobs.rb:30:in `wrapped_perform'
```

**Comment by benlong** [comment]
looks like I may have the wrong repo.. can you confirm?

fog-aws-0.1.1

Thanks

**Comment by geemus** [comment]
Yeah, it is technically actually in the fog/fog-aws repo, but not a big deal.

**Comment by geemus** [comment]
Looks like the error is actually coming from job_helper.rb `JobHelperAWS.should_retry?`, which I don't think is inside the library?

**Comment by benlong** [comment]
Thanks for looking so far. should_retry? just handles exceptions, and raises within the app. The error seems to be happening here:

exception undefined method `body' for #<Fog::DNS::AWS::Error: Throttling => Rate exceeded>
.../fog-aws-0.1.1/lib/fog/aws/models/dns/records.rb:29:in `all'
```
data = service.list_resource_record_sets(zone.id, options).body
```

**Comment by geemus** [comment]
Ah, right you are. Sorry about the confusion. It looks like that is a rather old version of fog-aws (0.7.6 is current), could you try bumping that first to see if that helps? Thanks!

**Comment by benlong** [comment]
Great, thanks. We will be updating to the latest version.
