### ISSUE TITLE
[vcloud-director] Same Org Networks in different VDCs 

### ISSUE THREAD

**Issue by mreferre** [fog/fog#3692]
Hi there. 

I am working on a sample script that allows a user to instantiate VMs on VMware vCloud Air public cloud service (which uses vCloud Director underneath for delivering the compute service). 

One thing that I noticed is that the vcloud_director plugin has issues when inside the same Org there are multiple VDCs and each VDC has the very same Org Network. That's how it works in vCloud Air, when a new VDC is provisioned to a user, the workflow will create a "default-routed-network" Org Network in the VDC. So if you have 5 VDCs, you will have 5 "default-routed-network" Org Networks in your Org. 

This is the code I am using: 

---

inputvdc = "IT20 Data Center (Beta)"
inputcatalog = "Public Catalog"
inputtemplate = 'CentOS64-64BIT'
inputnetwork = "default-routed-network"
inputvappname = "webserver2"

vcloud = Fog::Compute::VcloudDirector.new(
  :vcloud_director_username => "user@org",
  :vcloud_director_password => "password",
  :vcloud_director_host => 'mycloud.stratogen.net',
  :vcloud_director_show_progress => true, # task progress bar on/off
)

org = vcloud.organizations.first

vdc = org.vdcs.get_by_name(inputvdc)

catalog = org.catalogs.get_by_name(inputcatalog)

template = catalog.catalog_items.get_by_name(inputtemplate)

network = org.networks.get_by_name(inputnetwork)

vapp = template.instantiate(inputvappname, {
  vdc_id: vdc.id,
  network_id: network.id
})

---

If you run this code in the context I described above the result is that it will pick the first href of one of the 5 "default-routed-network" networks and there is an 80% odd that it's picking up a wrong one so when it tries to deploy the vApp in one VDC and connect it to the Org Network network vCD will complain that _that_ does not belong to that particular VDC.  

I know this is very much a corner case BUT this is how it works by default on vCloud Air so I thought I'd bring this up (there are a number of users that are willing to use Fog with vCloud Air).

**Comment by geemus** [comment]
@mikepea any chance you could share some insight? Thanks!

**Comment by cstewart87** [comment]
IMO, the key here is getting a network by id instead of name.  I've run unto this as well in the past.  I'll take a look through the fog code base, but I believe there's a method to get network by id.

**Comment by mreferre** [comment]
@cstewart87 I think the code will have to parse ALL the networks and match the network name AND the VDC specified by the user. The current behaviour seems to be that the code parses ALL the networks and only match the network name (first occurrence).
