### ISSUE TITLE
[vcloud-director] VM customization doesn't work as advertised

### ISSUE THREAD

**Issue by mreferre** [fog/fog#3693]
I am trying to customize a VM following the sample here (https://github.com/fog/fog/tree/master/lib/fog/vcloud_director) but I am having a hard time. 

I have tried to use: 

vapp = vdc.vapps.get_by_name("myvm")
vm = vapp.vms.first
customization = vm.customization
customization.computer_name = inputvappname
customization.enabled = false
customization.script = "new userdata script"
customization.save 

But it keeps saying: 

/usr/local/rvm/gems/ruby-2.2.1/gems/excon-0.45.4/lib/excon/middlewares/expects.rb:6:in `response_call': 'AdminPassword' should either be reset or remain unchanged when auto (Fog::Compute::VcloudDirector::BadRequest)

I have tried (I think) all the combinations possible. I have tried to use the same combinations I used in this REST sample here (http://it20.info/2013/10/vchs-apis-102/) but I either get the error above or a message that refers to wrong boolean inputs of some sort. 

I really just want to change the computer name and set an admin password explicitly.

**Comment by rocurtis** [comment]
Not sure I completely understand the script, but http://pubs.vmware.com/vcd-80/topic/com.vmware.vcloud.api.reference.doc_90/doc/types/GuestCustomizationSectionType.html, if AdminPasswordAuto is true, then I think you have to omit <AdminPassword>, not leave it empty like it is in this example

<AdminPasswordEnabled>true</AdminPasswordEnabled>
<AdminPasswordAuto>true</AdminPasswordAuto>
<AdminPassword />

But you've probably tried that...?

**Comment by mreferre** [comment]
Thanks. I think I tried all combinations including setting Auto to true (and commenting out) the parameter to set the password and then setting Auto to false and populate the parameter to set the password.

**Comment by geemus** [comment]
@mikepea any chance you could share some insight?

**Comment by cstewart87** [comment]
@mreferre the [knife-vcair](https://github.com/chef-partners/knife-vcair) project makes use of some of this customization functionality, so you might be able to look there for a good example.

Checkout the [#update_customization](https://github.com/chef-partners/knife-vcair/blob/master/lib/chef/knife/vcair_server_create.rb#L155) method for an example of setting the admin password.

Here's a snippet from the source of knife-vcair:
```ruby
          c = vm.customization
          if password
            c.admin_password =  password 
            c.admin_password_auto = false
            c.reset_password_required = false
          else
            # Password will be autogenerated
            c.admin_password_auto=true
            # API will force password resets when auto is enabled
            c.reset_password_required = true
          end
          
          # TODO: Add support for admin_auto_logon to fog
          # c.admin_auto_logon_count = 100
          # c.admin_auto_logon_enabled = true

          # DNS and Windows want AlphaNumeric and dashes for hostnames
          # Windows can only handle 15 character hostnames
          c.computer_name = config_value(:chef_node_name).gsub(/\W/,"-").slice(0..14)
          c.enabled = true
          c.save
```

**Comment by mreferre** [comment]
DOH! When I thought I tried all combinations I probably left the below out: 

  c = vm.customization
  c.admin_password =  guestpassword 
  c.admin_password_auto = false
  c.reset_password_required = false 
  c.computer_name = vappname
  c.enabled = true
  c.save

(where guestpassword and vappname are two populated variables with proper strings)

This works. Thanks a lot @cstewart87 ! If you are coming to Barcelona for VMworld a beer (at least) is on me :)
