### ISSUE TITLE
Open Stack - 503 Service Unavailable

### ISSUE THREAD

**Issue by robear** [fog/fog#3696]
Hi there,
I am trying to get fog working with swift at an OpenStack provider.  I get what seems to be a correct service object after creation (correct urls and credentials for interacting with swift).  When I try to use that object, I get 503 Service Unavailable for requests.  How can I debug this?  I get the full excon response object after the unexpected response.  Am I able to capture the request object so that I can see what is going on?
Thanks,
Robert

**Comment by tunglam14** [comment]
Hi,

Have you try to place your debug code into this function: https://github.com/fog/fog/blob/master/lib/fog/openstack/storage.rb#L144

btw, i think 503 error that relate to server thing.

**Comment by robear** [comment]
I have used httplog to watch requests.  I did find an issue.  When adding the :query => {'format' => 'json'} to requests (this is in the ruby files in the requests folder), this literally adds  {'format' => 'json'} to the query string.  The :query option is looking for a string literal such as '?format=json' 

I have still not figured out the problem.  The Open Stack command line tools work so the server is there and working fine.  I will look at it further tomorrow.

**Comment by robear** [comment]
I haven't gotten any closer to solving this.  I wrote a small Ruby script using Net:HTTP to talk to the OpenStack api and it works fine.  The command line tools work fine.  There is something wrong in fog with OpenStack.  Maybe it is an api version thing or something?  Any pointers on where to look within fog to solve this?

**Comment by tunglam14** [comment]
It works fine for me:

```
[1] pry(main)> arg = {:provider=>"OpenStack", :openstack_auth_url=>ENV['OS_AUTH_URL'] + "/tokens", :openstack_username=>ENV['OS_USERNAME'], :openstack_api_key=>ENV['OS_PASSWORD'], :openstack_tenant=>ENV['OS_TENANT_NAME']}
=> xxxx
[2] pry(main)> 
[3] pry(main)> 
[4] pry(main)> Fog::Storage.new(arg).get_containers
=> #<Excon::Response:0x007f2ff495bd18
 @body="[]",
 @data=
 ...
>
```

You could try to compare 2 http requests, one comes from CLI tool, one comes from Fog, to find different things between them, i think :)

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-openstack#50
