### ISSUE TITLE
Move rackspace libs to fog-rackspace

### ISSUE THREAD

**Issue by grosser** [fog/fog#3700]
@mdarby 

I'm trying to get rid of the giant fog dependency and just require fog-rackspace ... can we just move lib/rackspace into it's own gem and release that ?

**Comment by ablearcher9** [comment]
+1

**Comment by mdarby** [comment]
That is my goal but timing has been an issue and unfortunately will be until Q1.

**Comment by grosser** [comment]
I guess it's not just mv lib ../fog-rackspace ...
Thx for working on this, will make our gemfile much slimmer :)

**Comment by mdarby** [comment]
Unfortunately not :) I was hoping for the same!

**Comment by plribeiro3000** [comment]
I'm in a rush as well. Otherwise i could finish the migration. Maybe in a couple of weeks i might find sometime and do it if @mdarby don't mind.

**Comment by mdarby** [comment]
I don't mind at all! :)

**Comment by h0lyalg0rithm** [comment]
@geemus You can close his one as well

**Comment by plribeiro3000** [comment]
Thanks!

**Comment by geemus** [comment]
Thanks!
