### ISSUE TITLE
[openstack] bug retrieving list server actions

### ISSUE THREAD

**Issue by tunglam14** [fog/fog#3702]
I can't list actions of a server through `server_actions` method

```
Fog::Compute.new(arg).server_actions(server_id)
```

It return 404 errror.

I've digged in to the code and found it's calling to `/v2/tenant_id/servers/server_id/actions`  [at here](https://github.com/fog/fog/blob/master/lib/fog/openstack/requests/compute/server_actions.rb#L15). 
It's wrong, right? Because by the [Openstack API Documentation](http://developer.openstack.org/api-ref-compute-v2-ext.html#listActions), the API url is `/v2/​{tenant_id}​/servers/​{server_id}​/os-instance-actions`

Can you please take a look and confirm this.

Thanks

**Comment by geemus** [comment]
@TerryHowe @Ladas could you guys advise? Thanks!

**Comment by Ladas** [comment]
@tunglam14 seems what you are saying is correct, according to doc. The 'actions' is probably some historical API call, I found OpenStack wiki mentioning that.

**Comment by tunglam14** [comment]
@Ladas Thanks, as PR was merged, i'm going to close this issue.
