### ISSUE TITLE
net-ssh 3.x now requires Ruby 2.0

### ISSUE THREAD

**Issue by domcleal** [fog/fog#3705]
net-ssh 3.0.1 has been released, the first non-RC that requires Ruby 2.0 as a minimum Ruby version.

* Fog unit tests are breaking on 1.9.3, e.g. https://travis-ci.org/fog/fog/jobs/82520247 which could be fixed with a Gemfile tweak.
* Runtime usage of Fog on Ruby 1.9.3 is failing gem installation, can be fixed by pinning net-ssh in the user's Gemfile.
* Possible incompatibility may need checking, https://github.com/net-ssh/net-ssh/blob/v3.0.1/CHANGES.txt#L3

**Comment by domcleal** [comment]
Sorry, filed against the wrong repo.  I see it's already being handled at https://github.com/fog/fog-core/issues/162.

**Comment by geemus** [comment]
No worries, thanks for the heads up. Seems we have a bit of legwork to get it sorted out, which we'll hopefully get underway soon.
