### ISSUE TITLE
get_https_url generating negative expiry

### ISSUE THREAD

**Issue by joshuamcginnis** [fog/fog#3710]
I'm attempting to generate a signed url for a file in S3; however, the url that get's returned always returns a negative expiry which causes the url to `400`.

```ruby    
connection = Fog::Storage.new(
  region: 'us-west-1',
  provider: 'AWS',
  aws_access_key_id: ENV['AWS_ACCESS_KEY'],
  aws_secret_access_key: ENV['AWS_SECRET_KEY']
)
bucket = connection.directories.get(BUCKET)
file = 'test.jpg'
p file_url = bucket.files.get_https_url("uploads/#{file}", 300)
```
Generated URL:
```
https://account.s3-us-west-x.amazonaws.com/files/test.doc?X-Amz-Expires=-1443648781&X-Amz-Date=20150930T213801Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AAAVA***FA/20150930/us-west-x/s3/aws4_request&X
-Amz-SignedHeaders=host&X-Amz-Signature=e31663f9b2470e***215825d585b14c37e
```

Am I missing something here? Can you also confirm the units that the `expiry` arg should be in? (I'm presuming it is in in ms)

**Comment by geemus** [comment]
I believe it expects a timestamp argument (rather than a duration). So you probably want `Time.now + 300`. Hope that helps, but let me know if you have further questions. Thanks!

**Comment by joshuamcginnis** [comment]
@geemus Perfect. This is exactly the issue. By chance, could you point me to the documentation (if any) that says this?

**Comment by geemus** [comment]
The best I was able to manage was here: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/requests/storage/get_object_https_url.rb#L15 (but I think it could certainly be improved if it were more explicit).
