### ISSUE TITLE
Fog 1.x doesn't work for Ruby 1.9.3

### ISSUE THREAD

**Issue by jrgarcia** [fog/fog#3711]
We are requiring `~> 1.32` and getting an error. [This line](https://github.com/fog/fog/blob/v1.34.0/fog.gemspec#L60) causes the error for us (using JRuby 1.7.21 which is Ruby 1.9.3 compatible). Using the `>=` means that `fog-google` 0.1.1 is acceptable which requires Ruby 2.0.0 or higher. Please switch that to be pessimistic. There are a few more [here](https://github.com/fog/fog/blob/v1.34.0/fog.gemspec#L62-L66) that should probably be updated to avoid this too. Also, the ones without a version specified will probably end up causing a problem as well.

**Comment by plribeiro3000** [comment]
So the only `fog-google` version that has a ruby version locked in is [0.1.1](https://rubygems.org/gems/fog-google/versions/0.1.1). This means you can solve this issue for now by locking those versions by hand at your `Gemfile`. But we do need a new release of the `1.x` series with locks for all providers in a way that it does not break.

Unfortunately `fog-google` is the one provider out with that change so it does not make sense to do the move here yet. And we still have an issue that the version bumped at `fog-google` is wrong. It should be a MAJOR bump.

I will see about this and try to fix it asap. Thank you for this feedback.

**Comment by jrgarcia** [comment]
We can definitely do that as a workaround for now. I just wanted to create the issue before it became more rampant. Thanks!

**Comment by plribeiro3000** [comment]
Sure. Thanks. =)

**Comment by disengage00** [comment]
+1 ran into this today, would love to see this resolved :)

**Comment by domcleal** [comment]
I think the new Fog 1.35.0 release might have exacerbated this, since it included commits from #3709 that require fog-google 0.1.1 which has a minimum Ruby version of 2.0.0.

It might be useful to branch Fog 1.x from master, so the deps can be locked as suggested above, and to avoid temporary reverts such as 4444f32.

**Comment by Suirtimed** [comment]
+1  I've been spending lots of time chasing problems with non-pessimistic dependencies and ruby 2.0.

**Comment by geemus** [comment]
@domcleal sorry to hear it. I had hoped to minimize, really that release was to get DO changes out the door more than anything else. A proper release with no 1.8 (and perhaps no 1.9) should be in the near future, hopefully.

@Suirtimed sorry to hear it. Let me know if there is anything I can do to help.

**Comment by mmoll** [comment]
This should be resolved with 1.36, correct?

**Comment by geemus** [comment]
@mmoll that was my plan/the hope, do let me know if you are still having issues though and I'll keep working on it.

**Comment by domcleal** [comment]
1.36.0's fine, thanks!
