### ISSUE TITLE
Don't lock root user by default

### ISSUE THREAD

**Issue by martinb3** [fog/fog#3715]
We shouldn't be locking the root user by default in the Rackspace compute drivers. I think this is pretty counterintuitive, and "for better security," as the original PR https://github.com/fog/fog/pull/2492 says, seems like a very poor argument. I think the default should be to leave the server as-is (which may or may not be a locked root user), so that tools work, and allow the user/caller to opt-in to this behavior.

The argument that users should opt-in to this behavior is especially strong given that this behavior is different than the default behavior of using Rackspace's control panel and different than calling the Rackspace APIs.

**Comment by geemus** [comment]
@mdardy could you review/comment? Thanks!

**Comment by martinb3** [comment]
@geemus I think you're looking for @mdarby. Ping me if you have any questions Matt :)

**Comment by mdarby** [comment]
I don't have a clear picture of this area -- but I trust @martinb3.  It sounds like we definitely should go with the Chef flow.

**Comment by geemus** [comment]
Oops! @martinb3 good call...

**Comment by martinb3** [comment]
Thanks all!
