### ISSUE TITLE
Linode API changes

### ISSUE THREAD

**Issue by RomanKapitonov** [fog/fog#3718]
I've been looking into Linode's API implementation. There are some changes to the API so some of the API calls are not up-to-date. `avail.kernels` is one of them. Here is the link to the api call https://www.linode.com/api/utility/avail.kernels. The implementation does not contain currently available parameters for the call: https://github.com/fog/fog/blob/master/lib/fog/linode/requests/compute/avail_kernels.rb

`kernelId` should be eliminated. `isXen` and `isKVM` should be passed as parameters to the API call. There may also be other changes but this is still to be figured out.

**Comment by geemus** [comment]
Thanks for the heads up. We would certainly welcome any help in this area. I'm happy to provide guidance, but am not presently using linode so don't feel well placed to fix it myself.

**Comment by philr** [comment]
I have created pull request #3733 to update the implementation of the `avail.kernels` API call. The pull request also updates the other "avail" API requests to match the currently documented behaviour.

I've not looked for changes and differences to any other Linode API calls.

**Comment by plribeiro3000** [comment]
:+1: for the PR!

**Comment by RomanKapitonov** [comment]
:+1:

**Comment by geemus** [comment]
Cool, going to close this for now as we are not presently aware of other things that are missing (and we can always address them individually/later as they come up). Thanks!
