### ISSUE TITLE
Rackspace reverse dns

### ISSUE THREAD

**Issue by hkmaly** [fog/fog#3721]
Hello,

Rackspace DNS have option to modify reverse DNS (PTR records) for servers and load balancers, see http://docs.rackspace.com/cdns/api/v1.0/cdns-devguide/content/ptr_records.html

Would it be possible to add it to fog?

   Honza

**Comment by mdarby** [comment]
Hi Honza! I'm sure this would possible, unfortunately I'm buried on other projects...

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-rackspace#7
