### ISSUE TITLE
[OpenStack] Swift temp url not working, raised 401 unauthorized execption

### ISSUE THREAD

**Issue by jiangyt** [fog/fog#3727]
Hi,

I just using openstack swift as storage provider, trying to use fog to generate the tempurl link of a private object, here's the code related 

<pre><code>require 'fog'
swift = Fog::Storage.new({
:provider => 'OpenStack',
:openstack_auth_url => ENV["OS_AUTH_URL"],
:openstack_username => ENV["OS_USERNAME"],
:openstack_api_key => ENV["OS_PASSWORD"],
:openstack_temp_url_key => ENV["OS_TEMP_URL"]
})

swift.post_set_meta_temp_url_key(ENV["OS_TEMP_URL"])

directories = swift.directories
buildpacks = directories.get 'cc-buildpacks'
afile = buildpacks.files[0]
afile_pub_url = swift.get_object_http_url('cc-buildpacks', afile.key, 1445414679, {:port => 8080})
</pre></code>

I am sure about the openstack credentials are correct, but the tempurl generated raised 401 error. which means the temp url not correctly generated.

But using the python code is fine
<code><pre>
import hmac
from hashlib import sha1
from os.path import basename
from sys import argv, exit, stderr
from time import time

from six.moves import urllib

if __name__ == '__main__':
    if len(argv) < 5:
        prog = basename(argv[0])
        print 'Syntax: %s <method> <seconds> <path> <key>' % prog
        print
        print 'Where:'
        print '  <method>   The method to allow; GET for example.'
        print '  <seconds>  The number of seconds from now to allow requests.'
        print '  <path>     The full path to the resource.'
        print '             Example: /v1/AUTH_account/c/o'
        print '  <key>      The X-Account-Meta-Temp-URL-Key for the account.'
        print
        print 'Example output:'
        print '    /v1/AUTH_account/c/o?temp_url_sig=34d49efc32fe6e3082e411e' \
              'eeb85bd8a&temp_url_expires=1323482948'
        print
        print 'This can be used to form a URL to give out for the access '
        print 'allowed. For example:'
        print '    echo https://swift-cluster.example.com`%s GET 60 ' \
              '/v1/AUTH_account/c/o mykey`' % prog
        print
        print 'Might output:'
        print '    https://swift-cluster.example.com/v1/AUTH_account/c/o?' \
              'temp_url_sig=34d49efc32fe6e3082e411eeeb85bd8a&' \
              'temp_url_expires=1323482948'
        exit(1)
    method, seconds, path, key = argv[1:5]
    try:
        expires = int(time() + int(seconds))
    except ValueError:
        expires = 0
    if expires < 1:
        print 'Please use a positive <seconds> value.'
        exit(1)
    parts = path.split('/', 4)
    # Must be five parts, ['', 'v1', 'a', 'c', 'o'], must be a v1 request, have
    # account, container, and object values, and the object value can't just
    # have '/'s.
    if len(parts) != 5 or parts[0] or parts[1] != 'v1' or not parts[2] or \
            not parts[3] or not parts[4].strip('/'):
        stderr.write(
            'WARNING: "%s" does not refer to an object '
            '(e.g. /v1/account/container/object).\n' % path)
        stderr.write(
            'WARNING: Non-object paths will be rejected by tempurl.\n')
    if '--quoted' in argv[5:]:
        real_path = urllib.parse.unquote(path)
    else:
        real_path = path
    sig = hmac.new(key, '%s\n%s\n%s' % (method, expires, real_path),
                   sha1).hexdigest()
    print '%s?temp_url_sig=%s&temp_url_expires=%s' % (path, sig, expires)
</pre></code>

**Comment by geemus** [comment]
@dhague @Ladas @TerryHowe - perhaps one of you could provide guidance? Thanks!

**Comment by Ladas** [comment]
@jiangyt seems like the signature might be computed badly https://github.com/fog/fog/blob/master/lib/fog/openstack/requests/storage/get_object_https_url.rb#L57

Could you compare the signatures created from fog and python, given the same input? Also if sig_to_hex() is equivalent to .hexdigest() called in python

**Comment by jiangyt** [comment]
I figured out that fog calculate the expired time using what you input, but python code just using it as a offset time of current time. So fog generated a expired time if the time you input not long enough

**Comment by Ladas** [comment]
@jiangyt ah, I am glad you figured it out :-)

**Comment by geemus** [comment]
Yep, that would do it. Thanks for the update.
