### ISSUE TITLE
[vsphere] - unable to add more than 7 disks

### ISSUE THREAD

**Issue by fherbert** [fog/fog#3728]
Due to the SCSI controller taking id 7, when creating a vm with more than 7 disks, and if one (generally disk #8) of those disks are set to use unitNumber = 7, then creating the vm will fail.

A relatively easy fix can be done to lib/fog/vsphere/requests/compute/create_vm.rb. I'll submit a pull request shortly.

**Comment by plribeiro3000** [comment]
I´m not that into `vsphere` so perhaps you could help me out here. Where does this SCSI controller come from?

**Comment by fherbert** [comment]
Any disk attached to a vm requires a scsi controller, it is created when the vm is created, before the disks are created. Check this adaptec page for info on scsi ID's http://ask.adaptec.com/app/answers/detail/a_id/689/~/can-the-scsi-id-of-an-adaptec-scsi-controller-card-be-changed%3F
The current fog code creates a single scsi controller just before the disks are created, you don't get the option to set the controller ID.

**Comment by plribeiro3000** [comment]
Awesome. Thx for the explanation.

**Comment by geemus** [comment]
I believe this is closed by #3729
