### ISSUE TITLE
Documentation on Openstack Orchestration Mocks

### ISSUE THREAD

**Issue by davejohnston** [fog/fog#3732]
There doesn't appear to be any documentation on using Fog mocking with the Openstack Orchestration API.
Are there mocks available and could examples be added to the relevant documentation ?

**Comment by geemus** [comment]
@Ladas @TerryHowe - could either of you offer some help here?

**Comment by Ladas** [comment]
@davejohnston I don't plan to do it in the near future. Example of deploying stack is in our ManageIQ code, if you like to look or even make the doc from it :-) https://github.com/ManageIQ/manageiq/tree/master/spec/tools/environment_builders/openstack/services/orchestration

I assume that just examples of heat stack-create and update might be relevant.

**Comment by davejohnston** [comment]
Thanks, I worked it out.  I'll update the document with some examples.

**Comment by geemus** [comment]
Sounds great, thanks!

**Comment by plribeiro3000** [comment]
Closing since it seems this was addressed already.
