### ISSUE TITLE
Directory problem

### ISSUE THREAD

**Issue by juanpastas** [fog/fog#3734]
I am getting:

```
Excon::Errors::SocketError (hostname "myapp-staging1.myapp-staging1.s3-us-west-2.amazonaws.com" does not match the server certificate (OpenSSL::SSL::SSLError)):
```

with this config:

```
CarrierWave.configure do |config|
    config.fog_credentials = {
      :provider               => 'AWS',                        # required
      :aws_access_key_id      => ENV["aws_access_key_id"],                        # required
      :aws_secret_access_key  => ENV["aws_secret_access_key"],                        # required
      :region                 => 'us-west-1',                  # optional, defaults to 'us-east-1'
    }
    config.fog_directory  = ENV["fog_directory"]                          # required
  end
```

`ENV["fog_directory"]` is `myapp-staging1` on server console.

Why I could be getting a repeated part in `myapp-staging1.myapp-staging1.s3-us-west-2.amazonaws.com`?

I also created an issue on [carrierwave](https://github.com/carrierwaveuploader/carrierwave/issues/1761).  And a [gist](https://gist.github.com/juanpastas/eea1b7b236b35835ebc2) with the entire trace.

**Comment by rscardinho** [comment]
the content of your `ENV["fog_directory"]` is only `myapp-staging1`?
Got this issue some time ago and fixed it just setting the `path_style` to `true` inside the `fog_credentials` configs. This happens because the `fog_directory` contains dots, so CarrierWave understands it as a url

**Comment by juanpastas** [comment]
I tried that, no change...

I made an application from the start copying current one config, and is working for me... :confused: .

**Comment by rscardinho** [comment]
hmmm. but env var that you're using to set the fog directory have any dots?
add this on your carrierwave config block `Fog.credentials = { path_style: true }` and check if it works

**Comment by sajoku** [comment]
It seems I'm running into the same problem. 
What version of fog and carrierwave are you using @juanpastas?
We're using carrierwave (= 0.5.8), fog (1.21.0).

**Comment by geemus** [comment]
I haven't seen this before, so I'm uncertain. The duplication of that value in the subdomain is certainly unexpected.

@sajoku you may need to update versions, 1.21.0 is from some time ago and the issue may be resolved.

**Comment by juanpastas** [comment]
I solved it by adding, region and endpoint:

```
region = 'us-west-1'
endpoint = 'https://s3,amazonaws.com'
```

Google for aws regions to know possible values. Remember to use http:// in
endpoint.

**Comment by plribeiro3000** [comment]
@juanpastas Did you upgrade your `fog` version?

Thank you for your feedback. It seems the issue was a misconfiguration. If thats not the case please comment below and reopen this ticket.

Thanks!

**Comment by sajoku** [comment]
I have done some further research and came to the conclusion that this probably is due to some old version in combination with our aws config. It seems updating should work (haven't had the chance in the actual project since that requires an update of rails also).

**Comment by plribeiro3000** [comment]
@sajoku Thank you for the feedback. Please let me know if it does not work for you!

Thanks!

**Comment by geemus** [comment]
Thanks!
