### ISSUE TITLE
Support S3 auto-expiring files?

### ISSUE THREAD

**Issue by dimitko** [fog/fog#3736]
EDIT: Wrong board.

**Comment by plribeiro3000** [comment]
@dimitko Can you open this against [`fog-aws`](https://github.com/fog/fog-aws) instead?

Thanks!

**Comment by dimitko** [comment]
@plribeiro3000 Sure. Thank you!

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-aws#194.

Thanks!
