### ISSUE TITLE
Update digitalocean/examples/getting_started.md to show V2

### ISSUE THREAD

**Issue by hh** [fog/fog#3739]

**Comment by geemus** [comment]
Good call, thanks for the heads up.

/cc @bryanl in case you have a moment to help out here. Thanks!

**Comment by bryanl** [comment]
I'll create a PR for this.

**Comment by geemus** [comment]
Great, thanks!

**Comment by petems** [comment]
I updated, may have found some live bugs in the new v2 provider, need to check
