### ISSUE TITLE
[vsphere] Extract provider into it's own repository

### ISSUE THREAD

**Issue by jrgarcia** [fog/fog#3740]
I've extracted fog/vsphere into it's own repository [here](https://github.com/jrgarcia/fog-vsphere). If you are interested, let me know how you'd like to go about adding it to the fog organization.

**Comment by plribeiro3000** [comment]
Awesome @jrgarcia !
There are just some small details that i need you to do before we actually move on with the extraction.
Since #3430 that we are using `autoload` to reduce the loading time. Also we are getting rid of the `core` file and moving its content to the main file (in this case `lib/fog/vsphere`) and reducing the amount of requires between models.
Take a look at `fog-xenserver` or `fog-aws` to see how we are doing.

Let me know if you need any help with this.

Thanks!

**Comment by jrgarcia** [comment]
I'll fix that up and let you know when it's ready. Thanks!

**Comment by plribeiro3000** [comment]
Awesome. Just to make it clear. What you did is good to go. The only issue is that we need to keep an eye close for the loading time and that refactoring i just mentioned above should take care of that.

:+1:

**Comment by jrgarcia** [comment]
@plribeiro3000 Is this along the lines of what you were looking for? https://github.com/jrgarcia/fog-vsphere/commit/42ae84a6cfe77a3b9e0453aa33c86283c1255cff

**Comment by jrgarcia** [comment]
@plribeiro3000 So how would you like to go about moving this to the fog organization?

**Comment by plribeiro3000** [comment]
@jrgarcia Actually the `autoload` inside the models are kind of wrong. Do they work?
You need to push the content of the `core` file to inside the main file (`fog/vsphere`). This file does not make sense when we are working with a gem anymore.
I guess the `autoload` inside the models you did can be removed.

Let me know how it goes.

Regarding the moving, you can give me admin permissions on the repo so i can move it to the `fog` organization. :+1:

**Comment by jrgarcia** [comment]
@plribeiro3000 Everything appears to work. The current core file doesn't contain any of that stuff. See https://github.com/fog/fog/blob/master/lib/fog/vsphere/core.rb. I'm glad to change anything that needs to be changed. I'll add you to my repo shortly. I noticed some new commits to the vSphere stuff. I'll need to move that stuff over later as well.

**Comment by plribeiro3000** [comment]
Awesome @jrgarcia. sorry for the trouble here. Let me move the repo.

**Comment by plribeiro3000** [comment]
It seems i have push access but not admin access so i can´t move it to the `fog` organization. =s
Maybe you could try to do so?

**Comment by jrgarcia** [comment]
Let me "merge" in any new commits and make sure the contributors list is still correct and I'll transfer ownership later tonight or tomorrow morning.

**Comment by plribeiro3000** [comment]
:+1:

**Comment by jrgarcia** [comment]
@plribeiro3000 It appears I can't transfer the repository without first having admin rights to the 'fog' organization. Can you either fork my repo and add it to the fog organization (safer) or short-term give me admin rights to fog (easier)?

**Comment by plribeiro3000** [comment]
I don't have admin rights in `fog` as well. Maybe @geemus can chime in and solve the issue for us?

**Comment by geemus** [comment]
Hey! @jrgarcia if you add me as an admin on the repo I can do the remaining steps. Thanks!

**Comment by jrgarcia** [comment]
@geemus I gave you push access (that's all you can give for a non-organization repository). Let me know if that works for you.

**Comment by geemus** [comment]
@jrgarcia Hmm. Unfortunately that appears to be insufficient. If you can't give me more privilege, I guess you could also just transfer to me and then I can kick it across? Once there I would give you admin to that repo, I just try to keep the "admin to every repo" list fairly short as there are a growing number and most people only work on one or two anyway. Does that make sense? Seem reasonable?

**Comment by jrgarcia** [comment]
Thanks @plribeiro3000 and @geemus!

**Comment by plribeiro3000** [comment]
You are welcome!

Thank you for your efforts!

**Comment by geemus** [comment]
Thanks!

**Comment by lksv** [comment]
Hi @plribeiro3000, @jrgarcia, there is merged vsphere pull request #3749 by @ireznice (maybe more pull requests) to the fog/fog. If you are planning to extract vspehre from fog repo completly, how will be managed taking new commits?

I am asking that because at least two more pull requests are comming (probably by @ireznice) for upload, download and exec command functionality.

Probably if you created https://github.com/fog/fog-vsphere based on fog/fog it would be easy to merge new changes, but now is probably late to do so.

**Comment by jrgarcia** [comment]
I copied the files from fog/fog and made some minor modifications. It should be easy enough to make the modifications necessary (if there are any needed). If it's too much trouble, feel free to make a PR to fog/fog and I'll move the changes to fog/fog-vsphere.

**Comment by geemus** [comment]
@lksv thanks for checking in. As @jrgarcia mentions, we'll do it whatever way works for the time being (and remove the fog/fog side of things to de-dedup soon). Hopefully that will keep it as a short-lived problem at least and then it will hopefully be easier/faster to continue moving forward after that. Thanks!

**Comment by plribeiro3000** [comment]
@lksv One of the issues is that we need both to live together until the extraction ends. So as long as it takes more we need to work on this kind of stuff but i'm afraid the only way to go easier is to finish the extraction asap.

**Comment by jrgarcia** [comment]
@lksv I will certainly try to keep an eye on fog/fog as much as possible to ensure I get every commit related to vSphere over there pulled into fog/fog-vsphere.

**Comment by plribeiro3000** [comment]
@jrgarcia :+1: Thanks!
