### ISSUE TITLE
Akamai provider

### ISSUE THREAD

**Issue by alexandru-calinoiu** [fog/fog#3751]
I've started working on a provider for akamai, https://github.com/alexandru-calinoiu/fog-akamai, it only has some basic netstorage endpoints for now, but it used already on a project I work on.

I will appreciate some feedback.

**Comment by plribeiro3000** [comment]
Awesome @alexandru-calinoiu. I will take a look at asap. If if take too long, please ping here again.

**Comment by plribeiro3000** [comment]
@alexandru-calinoiu It looks good to me besides some details that i think is better to just open issues at the repo once we migrate it over to the `fog` organization.
@geemus Can you help migrating the project to the `fog` organization?

**Comment by alexandru-calinoiu** [comment]
@plribeiro3000 thanks for your feedback, I will do some more work on it this week as I have a couple of free days.

**Comment by alexandru-calinoiu** [comment]
@plribeiro3000 I've added the rest of the storage api along with mock support, please take a second look and provide me with feedback.

I will release a new gem shortly.

**Comment by plribeiro3000** [comment]
@alexandru-calinoiu Awesome. I will take a look at it soon.

**Comment by geemus** [comment]
@alexandru-calinoiu In terms of migration, I think the easiest is just to transfer the repo to me personally (and then I have the right permissions to move it into the org from there). Let me know if that doesn't work or you have questions/concerns. Thanks!

**Comment by alexandru-calinoiu** [comment]
@geemus I've send a transfer request

**Comment by geemus** [comment]
Transfer should be complete, just let me know if you have anything else you need here.
