### ISSUE TITLE
Can not get meters by fog when openstack's region name is not  RegionOne

### ISSUE THREAD

**Issue by sunyao5411** [fog/fog#3752]
Dear all,
  when i use the manageIQ to collect the data from openstack with api list_meters,there throw an error below:
[----] E, [2015-11-05T01:03:12.399007 #15240:10d7e8c] ERROR -- : <Fog> excon.error     #<Excon::Errors::Timeout: read timeout reached>

[----] E, [2015-11-05T01:03:12.399547 #15240:10d7e8c] ERROR -- : MIQ(VmOpenstack.perf_collect_metrics_openstack) [realtime] for: [VmOpenstack], [41], [centos6-test-23] Unhandled excep
tion during perf data collection: [read timeout reached], class: [Excon::Errors::Timeout]
[----] E, [2015-11-05T01:03:12.399765 #15240:10d7e8c] ERROR -- : MIQ(VmOpenstack.perf_collect_metrics_openstack) [realtime] for: [VmOpenstack], [41], [centos6-test-23]   Timings at ti
me of error: {:capture_state=>0.02372145652770996, :connect=>1.7999422550201416, :capture_counters=>60.15708899497986}
[----] E, [2015-11-05T01:03:12.399958 #15240:10d7e8c] ERROR -- : [Excon::Errors::Timeout]: read timeout reached  Method:[rescue in perf_collect_metrics_openstack]
[----] E, [2015-11-05T01:03:12.400096 #15240:10d7e8c] ERROR -- : /opt/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/excon-0.45.3/lib/excon/socket.rb:299:in `raise_timeout_error'
/opt/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/excon-0.45.3/lib/excon/socket.rb:49:in `rescue in readline'
/opt/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/excon-0.45.3/lib/excon/socket.rb:44:in `readline'
/opt/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/excon-0.45.3/lib/excon/response.rb:53:in `parse'
/opt/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/excon-0.45.3/lib/excon/middlewares/response_parser.rb:6:in `response_call'
/opt/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/excon-0.45.3/lib/excon/connection.rb:372:in `response'
/opt/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/excon-0.45.3/lib/excon/connection.rb:236:in `request'
/opt/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/fog-core-1.30.0/lib/fog/core/connection.rb:83:in `request'
/opt/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/fog-1.28.0/lib/fog/openstack/metering.rb:139:in `request'
/opt/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/gems/fog-1.28.0/lib/fog/openstack/requests/metering/list_meters.rb:20:in `list_meters'
/var/www/miq/vmdb/app/models/metric/ci_mixin/capture/openstack_base.rb:73:in `block in list_meters'
/var/www/miq/lib/util/extensions/miq-benchmark.rb:12:in `realtime_store'
/var/www/miq/lib/util/extensions/miq-benchmark.rb:31:in `realtime_block'
/var/www/miq/vmdb/app/models/metric/ci_mixin/capture/openstack_base.rb:72:in `list_meters'
/var/www/miq/vmdb/app/models/metric/ci_mixin/capture/openstack_base.rb:97:in `list_resource_meters'
/var/www/miq/vmdb/app/models/metric/ci_mixin/capture/openstack_base.rb:89:in `find_meter_counters'
/var/www/miq/vmdb/app/models/metric/ci_mixin/capture/openstack_base.rb:43:in `perf_capture_data_openstack_base'
/var/www/miq/vmdb/app/models/metric/ci_mixin/capture/openstack.rb:6:in `perf_capture_data_openstack'
/var/www/miq/vmdb/app/models/metric/ci_mixin/capture/openstack_base.rb:15:in `perf_collect_metrics_openstack'
/var/www/miq/vmdb/app/models/metric/ci_mixin/capture.rb:14:in `perf_collect_metrics'
/var/www/miq/vmdb/app/models/metric/ci_mixin/capture.rb:164:in `block in perf_capture'
/var/www/miq/lib/util/extensions/miq-benchmark.rb:12:in `realtime_store'
/var/www/miq/lib/util/extensions/miq-benchmark.rb:31:in `realtime_block'
/var/www/miq/vmdb/app/models/metric/ci_mixin/capture.rb:161:in `perf_capture'
/var/www/miq/vmdb/app/models/miq_queue.rb:356:in `block in deliver'
/opt/rubies/ruby-2.0.0-p645/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/var/www/miq/vmdb/app/models/miq_queue.rb:352:in `deliver'
/var/www/miq/vmdb/lib/workers/queue_worker_base.rb:107:in `deliver_queue_message'
/var/www/miq/vmdb/lib/workers/queue_worker_base.rb:135:in `deliver_message'
/var/www/miq/vmdb/lib/workers/queue_worker_base.rb:152:in `block in do_work'
/var/www/miq/vmdb/lib/workers/queue_worker_base.rb:146:in `loop'
/var/www/miq/vmdb/lib/workers/queue_worker_base.rb:146:in `do_work'
/var/www/miq/vmdb/lib/workers/worker_base.rb:323:in `block in do_work_loop'
/var/www/miq/vmdb/lib/workers/worker_base.rb:141:in `run'
/var/www/miq/vmdb/lib/workers/worker_base.rb:122:in `start'
/var/www/miq/vmdb/lib/workers/worker_base.rb:23:in `start_worker'
/var/www/miq/vmdb/lib/workers/bin/worker.rb:3:in `<top (required)>'
/opt/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/bundler/gems/rails-4842a8377644/railties/lib/rails/commands/runner.rb:52:in `eval'
/opt/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/bundler/gems/rails-4842a8377644/railties/lib/rails/commands/runner.rb:52:in `<top (required)>'
/opt/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/bundler/gems/rails-4842a8377644/railties/lib/rails/commands.rb:64:in `require'
/opt/rubies/ruby-2.0.0-p645/lib/ruby/gems/2.0.0/bundler/gems/rails-4842a8377644/railties/lib/rails/commands.rb:64:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'

if i use the openstack with region name RegionOne ,that's OK.
Can anyone help me?
Thanks!

**Comment by geemus** [comment]
@dhague @Ladas @TerryHowe - could one of you advise? Thanks!

**Comment by Ladas** [comment]
@sunyao5411 I think you have to specify options[:openstack_region] when you authenticate, it's the same options where you sent e.g. tenant name

RegionOne is OpenStack internal default AFAIK

**Comment by sunyao5411** [comment]
@Ladas I have test this way ,but  it is not work,  so is there any other way to find the reason?
Thanks!

**Comment by Ladas** [comment]
@sunyao5411 write here exact Fog commands you are using, please. Is it keystone v2 o v3? Paste also endpoint list please.

The timeout is pretty weird, could you try the same command for obtaining metrics through OpenStack CLI? It's possible that error is in your setup or firewall, cause seems like the endpoint was obtained correctly, then it timeouted speaking to it. 

Fog should handle different regions even without specifying. You will need to specify only when you have multiple regions.

If it will work in Fog, it will work in ManageIQ, though I think ManageIQ doesn't support multiple regions.

**Comment by sunyao5411** [comment]
@Ladas  below is my steps:
1.exact Fog commond:
[----] I, [2015-11-11T04:13:14.786210 #4157:557e90]  INFO -- : Fog/openstack/requests/metering/list_meters.rb;data=>---
q:
- field: resource_id
  value: 42c41e7f-9605-4c7a-a699-e1eec7336ef8
[----] E, [2015-11-11T04:13:15.728196 #4160:7ffe90] ERROR -- : <Fog> excon.error     #<Excon::Errors::Timeout: read timeout reached>
........

2.use the some command through the openstack cli 
[root@controller1~(keystone_admin)]# ceilometer  meter-list -q  resource_id=42c41e7f-9605-4c7a-a699-e1eec7336ef8 
('Connection aborted.', error(104, 'Connection reset by peer'))
[root@controller1~(keystone_admin)]# 

3.show the vms details
[root@controller1~(keystone_admin)]# nova show 42c41e7f-9605-4c7a-a699-e1eec7336ef8
+--------------------------------------+---------------------------------------------------------------+
| Property                             | Value                                                         |
+--------------------------------------+---------------------------------------------------------------+
| OS-DCF:diskConfig                    | AUTO                                                          |
| OS-EXT-AZ:availability_zone          | nova                                                          |
| OS-EXT-SRV-ATTR:host                 | compute13                                           |
| OS-EXT-SRV-ATTR:hypervisor_hostname  |  compute13                                           |
| OS-EXT-SRV-ATTR:instance_name        | instance-00000055                                             |
| OS-EXT-STS:power_state               | 1                                                             |
| OS-EXT-STS:task_state                | -                                                             |
| OS-EXT-STS:vm_state                  | active                                                        |
| OS-SRV-USG:launched_at               | 2015-11-02T05:41:23.000000                                    |
| OS-SRV-USG:terminated_at             | -                                                             |
| accessIPv4                           |                                                               |
| accessIPv6                           |                                                               |
| config_drive                         |                                                               |
| created                              | 2015-09-18T03:02:59Z                                          |
| flavor                               | m1.small (2)                                                  |
| hostId                               | 4ce6f71e6a84defe873ce077693b49a3f3f9dccc428240325575363a      |
| id                                   | 42c41e7f-9605-4c7a-a699-e1eec7336ef8                          |
| image                                | centos-guest-image-6.5 (46b10530-90d5-486a-a1bf-ecbbdeb73853) |
| key_name                             | -                                                             |
| metadata                             | {}                                                            |
| name                                 | centos6-test-11                                               |
| os-extended-volumes:volumes_attached | []                                                            |
| progress                             | 100                                                           |
| security_groups                      | default                                                       |
| status                               | ACTIVE                                                        |
| tenant_id                            | db88e69381f84e8eaad7b2937ff1106d                              |
| updated                              | 2015-11-03T04:03:49Z                                          |
| user_id                              | 09b6111bc1074a5a91f9d91c055a7ddb                              |
| net01  network                  | 192.168.1.86                                                  |
+--------------------------------------+---------------------------------------------------------------+

4.use postman get data by rest api 
http://ip:8777/v2/meters
No response.

5. In openstack horizon , I can see ceilometer's data.

I use the openstack RDO with multiple nodes, the region  of ceilometer's component can't changed by answerfile,so when install is completed i changed the /etc/ceilometer/ceilometer.conf file's region to my region configured by answerfile and restart the ceilometer's services.

Is there any steps wrong?

Thank you!

**Comment by Ladas** [comment]
@sunyao5411 hm the error in 2) means it's configured badly and you can't talk to ceilometer.
Not sure why it works in Horizon? It uses the same api request as CLI.

Maybe you forgot to change the region also in keystone endpoint? Or maybe checking how RDO does that for other services might be good.

**Comment by sunyao5411** [comment]
@Ladas Thank you! 

I checked all the compute nodes and the region changed to myregion,but controller node was not, after i changed the controller node's region and restart the ceilometer's services  at the openstack CLI i can get the meter and also in fog .

Thanks！

**Comment by Ladas** [comment]
@sunyao5411 awesome :-)
