### ISSUE TITLE
ArgumentError: aws is not a recognized storage provider

### ISSUE THREAD

**Issue by ericpeters0n** [fog/fog#3759]
So, I'm testing out syncing Rails assets to my S3 bucket, and it appears fog is not recognizing aws as a valid provider name...?
```
$ export AWS_ACCESS_KEY_ID=xxx
$ export AWS_SECRET_ACCESS_KEY=yyy
$ export FOG_DIRECTORY=my-assets
$ export FOG_PROVIDER=AWS
$ bundle exec rake assets:precompile
```
yields--
```
...
Compiled foo_asset.html  (34ms)  (pid 35500)
** Invoke assets:sync (first_time)
** Invoke assets:environment 
** Execute assets:sync
AssetSync: Syncing.
rake aborted!
ArgumentError: aws is not a recognized storage provider
/Users/ericpeters0n/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/fog-core-1.29.0/lib/fog/storage.rb:27:in `new'
/Users/ericpeters0n/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/asset_sync-1.1.0/lib/asset_sync/storage.rb:15:in `connection'
/Users/ericpeters0n/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/asset_sync-1.1.0/lib/asset_sync/storage.rb:20:in `bucket'
/Users/ericpeters0n/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/asset_sync-1.1.0/lib/asset_sync/storage.rb:99:in `get_remote_files'
/Users/ericpeters0n/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/asset_sync-1.1.0/lib/asset_sync/storage.rb:211:in `upload_files'
```

Any hints?

**Comment by geemus** [comment]
I'd start by updating to latest versions of things, from there if you are still having an error we can definitely dig in further.

**Comment by ericpeters0n** [comment]
Alas, we're obliged to support Ruby 1.9.3 for now --hence the older branch.

Eric Peterson
Founder + CEO
eric@links.ee
213.304.4547

**Comment by geemus** [comment]
Ah, got it. I'm working on trying to release a new version that will be back to 1.9.x support, but not quite there yet I'm afraid. Hoping to stage/release it all soon though.

**Comment by ericpeters0n** [comment]
Good to hear. We've worked around it for now, but I'd be happy to test out that version when it arrives!

**Comment by geemus** [comment]
I just released 1.36.0, which I hope fixes this (or at least moves us in the right direction, I think a couple sharp edges may remain). Definitely let me know if you find any remaining gotchas. Thanks!

**Comment by gmcnaughton** [comment]
Any pointers on what the problem is, or how to work around it?

I'm seeing this same error on fog (1.40.0) when i try to sync assets using the asset_sync gem (1.3.0)

```
bundle exec rake assets:sync RAILS_ENV=...

rake aborted!
ArgumentError: aws is not a recognized provider
gems/fog-core-1.44.3/lib/fog/core/services_mixin.rb:12:in `new'
gems/fog-core-1.44.3/lib/fog/storage.rb:27:in `new'
gems/asset_sync-1.3.0/lib/asset_sync/storage.rb:15:in `connection'
gems/asset_sync-1.3.0/lib/asset_sync/storage.rb:20:in `bucket'
gems/asset_sync-1.3.0/lib/asset_sync/storage.rb:85:in `get_remote_files'
gems/asset_sync-1.3.0/lib/asset_sync/storage.rb:199:in `upload_files'
gems/asset_sync-1.3.0/lib/asset_sync/storage.rb:221:in `sync'
...
```

**Comment by gmcnaughton** [comment]
In case anyone lands here from google I'll document what fixed it for me.

The `aws is not a recognized provider` error was caused by having a fog-* gem explicitly listed in my Gemfile without *also* explicitly listing fog-aws.

Having this in my Gemfile causes the error:
```
gem 'asset_sync'
gem 'fog-xenserver' # <= oops!
```

But any of these are fine:
```
gem 'asset_sync' # no fog-* listed
```

```
gem 'asset_sync'
gem 'fog-aws'    # just fog-aws listed
```

```
gem 'asset_sync'
gem 'fog-xenserver' # some fog-* listed
gem 'fog-aws'       # but also fog-aws!
```

**Comment by geemus** [comment]
Strange, I wouldn't expect the dependency you mention. I suspect a bug in fog-xenserver, but I'm not sure what it would be exactly.
