### ISSUE TITLE
Breaking change in mime-types-data prevents installation of fog 1.5.0

### ISSUE THREAD

**Issue by joshi4** [fog/fog#3775]
Configuration detail: 

* `ruby -v = ruby 1.9.3p547 (2014-05-14 revision 45962) [x86_64-linux]`
* chef-client -v = 11.16.4`
* running on ubuntu trusty 

I was installing fog through `chef` using the `chef_gem` resource and till yesterday everything was fine. 
However, recently Nov 21 or Nov 20th ( 2015) they introduced `mime-types-data` which requires ruby 2.0 and since fog depends on `mime-types >=0` we end up pulling the breaking dependency. 

I tried downloading an earlier version of mime-types that does not have the mime-types-data dependency but that doesn't work as when installing the gem it still tries to pull in `mime-types-data` 

~~~ruby 
chef_gem "fog" do
      action :install
      version '1.5.0'
 end
~~~ 

I saw a past issue where the dependency on mime-types was changed to `~> 1.16` but that was only for ruby 1.8.7 maybe ? Is a similar solution possible for ruby `1.9.x` ? 
mime-types link: https://rubygems.org/gems/mime-types

**Comment by GAV1N** [comment]
My PR above specifies the latest non-breaking version of `mime-types` in the `gemspec`. I'm not sure if the maintainers will like that approach, but I figured it's worth a shot because I too have been bitten by this issue and I'd like to see it resolved quickly.

**Comment by joshi4** [comment]
@GAV1N : nice I was able to modify my cookbook to download a compatible version of mime-types explicitly before installing fog and that seems to have solved the issue for me: 

~~~ruby
chef_gem "mime-types" do 
  action :install 
  version '1.25.0'  
end 

Gem.clear_paths
require 'mime-types' 
~~~ 

definitely hacky and your solution is more cleaner and better for the longterm.

**Comment by plribeiro3000** [comment]
@joshi4 I suggest you to use @GAV1N solution which is the best one for this kind of issue.
You can specify it on your `Gemfile` directly since `fog` does not specify it directly and it will work out of the box. In the meantime i believe we might get @GAV1N solution into `fog` soon.

Thank you both. Since there is an open PR already i will close this so we can continue to discuss it there if needed.
