### ISSUE TITLE
Digital Ocean's list_images request does not return the full list of images 

### ISSUE THREAD

**Issue by mafraba** [fog/fog#3777]
It seems that by default the Digital Ocean API uses pagination, so it returns a page with a few images and a link to the next.

Right now the list_images request is just returning the images that come in the first page, but I guess this is not the behavior one would expect.

**Comment by geemus** [comment]
@bryanl could you take a look when you have a chance? Thanks!

**Comment by bryanl** [comment]
@mafraba I'll take a look at this.

**Comment by angelman** [comment]
Any updates? Thanks. :purple_heart:

**Comment by geemus** [comment]
I merged https://github.com/fog/fog/issues/3777#issuecomment-190408860 earlier today, I think that should resolve this actually. Do let me know if that doesn't seem to be the case though.
