### ISSUE TITLE
Newest fog is not compatible with newest fog-google

### ISSUE THREAD

**Issue by Ladas** [fog/fog#3778]
It's due to ruby version, Fog has now dependency on older fog-google that still supports ruby 1.9. So now we can't use newest Fog with OpenStack and fog-google together

possible solutions
1. Drop 1.9 support in Fog 2.0
2. Move OpenStack to different repo (fog-openstack) and drop ruby 1.9 support there
3. Fix fog-google so it supports ruby 1.9, so all Fog project are consistent in dependencies
4. ...

**Comment by geemus** [comment]
I thought the lock in fog on max fog-google version prevented this particular edge case?

**Comment by Ladas** [comment]
@geemus right, in ManageIQ we fetch newest version of fog-google, we started a google provider and I think the google guys want the latest greatest stuff there. So now it conflicts for us.

https://github.com/ManageIQ/manageiq/commit/12e84b03d9e1b36dd84322a8619c2e9868b95793 
this is the commit from a google guy explaining the need of a new version, it didn't conflict at that time,

**Comment by geemus** [comment]
@icco @temikus - thoughts?

**Comment by Temikus** [comment]
There's very little actual difference between 1.0.0, it's basically this commit:
https://github.com/fog/fog-google/commit/a66b16fa7c2373f9c8be2e80bc942ad8d13ece3f
So, with that said, it should be ok with relaxing the gemspec a bit. I looped in @lwander, change should be proposed soon.

**Comment by Ladas** [comment]
@Temikus @lwander awesome, thank you guys

**Comment by Temikus** [comment]
PR submitted, adding to track: https://github.com/ManageIQ/manageiq/pull/5768

**Comment by Ladas** [comment]
@Temikus awesome, thank you @lwander

**Comment by geemus** [comment]
Sounds like this is probably resolved elsewhere then? Let me know if I misunderstand. Thanks!
