### ISSUE TITLE
[digitalocean] SSH Key creation and deletion currently not implemented

### ISSUE THREAD

**Issue by petems** [fog/fog#3781]
I'm not sure if I'm doing something wrong, but it looks like the SSH key creation and deletion aren't working...

## Creation
```
docean.ssh_keys.create(
  :name        => 'Default SSH Key',
  :ssh_pub_key => File.read("#{Dir.home}/.ssh/id_rsa.pub"))
)
NoMethodError: undefined method `save' for #<Fog::Compute::DigitalOceanV2::SshKey:0x007fb3032db938>
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/fog-core-1.34.0/lib/fog/core/collection.rb:51:in `create'
	from (irb):3
	from /opt/boxen/rbenv/versions/2.1.2/bin/irb:11:in `<main>'
```

## Deletion

```
>> key_id = # Redacted
>> docean.ssh_keys.get(key_id).nil?
=> false
>> docean.ssh_keys.get(key_id).name
=> "Work Macbook"
>> docean.ssh_keys.destroy(key_id)
NoMethodError: undefined method `destroy' for #<Fog::Compute::DigitalOceanV2::SshKey:0x007fb3019e2fa8>
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/fog-core-1.34.0/lib/fog/core/collection.rb:56:in `destroy'
	from (irb):18
	from /opt/boxen/rbenv/versions/2.1.2/bin/irb:11:in `<main>'
```

**Comment by geemus** [comment]
@bryanl could you take a look and/or advise? Thanks!

**Comment by bryanl** [comment]
This looks valid. I'll take a look. Thank you @petems for finding the issue.

**Comment by petems** [comment]
@bryanl I'm not sure if it's related, but he V1 version has

```ruby
require 'fog/digitalocean/models/compute/ssh_key'
``` 
https://github.com/fog/fog/blob/master/lib/fog/digitalocean/models/compute/ssh_keys.rb#L1

At the top of its ssh_keys model, I tried adding that but no dice. But it might point in the right direction?

**Comment by petems** [comment]
It looks like save works correctly now (on bbe707e2b6304a51d615624bea85ca3c74c2d30c)

```
docean.ssh_keys.create(
  :name        => 'Default SSH Key',
  :public_key   => File.read("#{Dir.home}/.ssh/example_key.pub"))
)
<Fog::Compute::DigitalOceanV2::SshKey
    id=1578111,
# blah blah
   ...
```

I might've just had the wrong syntax before!

Delete now works due to #3783 

```ruby
>> key_id = 1578111 # key I just made
=> 1578084
>> docean.ssh_keys.get(key_id).nil?
=> false
>> docean.ssh_keys.get(key_id).name
=> "Default SSH Key"
>> docean.ssh_keys.destroy(key_id)
=> #<Excon::Response:0x007fdf8c8971c8 @data={:body=>"", :headers=>{"Server"=>"cloudflare-nginx", "Date"=>"Tue, 01 Dec 2015 15:25:09 GMT", "Connection"=>"keep-alive", "Status"=>"204 No Content",
# blah blah
```

**Comment by geemus** [comment]
Cool, if I'm not mistaken this sounds fixed. Let me know if I missed anything.

**Comment by petems** [comment]
:+1: Need to update the getting started doc! :+1:

**Comment by geemus** [comment]
Good call, I would certainly welcome your help in making it match with your experience!

**Comment by rroa** [comment]
This fix seemed to solve issues for Deletes, but creation is still not working on 1.36.0

**Comment by petems** [comment]
@rroa What's the command you're trying:

```ruby
docean.ssh_keys.create(
  :name        => 'Default SSH Key',
  :public_key   => File.read("#{Dir.home}/.ssh/example_key.pub"))
)
```
 worked for me?

**Comment by rroa** [comment]
`docean.ssh_keys.create(
  :name        => 'Default SSH Key',
  :public_key   => File.read("#{Dir.home}/.ssh/id_rsa.pub")
)`

**Comment by petems** [comment]
Ah, can you try that on the master branch of fog rather than the latest gem? I think that was fixed in a recent PR

**Comment by petems** [comment]
In fact, I know that to be true because it was fixed in https://github.com/fog/fog/commit/808205cc1b532b8b5dc6ec6019c2337ceff6b453 which hasn't been released yet :+1:

**Comment by rroa** [comment]
I'm referencing the gem this way

```gem 'fog', :git => 'https://github.com/fog/fog.git', :branch => 'master'```

Should I use that commit as a ref?

**Comment by rroa** [comment]
Nevermind, had some issues with my local environment, using the git repo fixes that issue.

**Comment by geemus** [comment]
Thanks for the updates/confirmation. Sorry about no release just yet, I'll try to remedy that in the next couple days.
