### ISSUE TITLE
[digitalocean] Change to use v2 provider for default?

### ISSUE THREAD

**Issue by petems** [fog/fog#3782]
Since the v1 API is officially EOL, should we remove the v1 API code and then point the provider to use v1 by default?

**Comment by geemus** [comment]
I think you meant v2 by default? If so, sounds good to me. /cc @bryanl

**Comment by petems** [comment]
Yep! :+1:

**Comment by bryanl** [comment]
Yes, this should happen since the v1 API is no more. I won't be able to look at this before the weekend, but if anyone else wants to get it started, that would be great as well.

**Comment by h0lyalg0rithm** [comment]
The code that manages the api version is on fog/fog-core repo.I have created a PR there https://github.com/fog/fog-core/pull/172
