### ISSUE TITLE
Fog::Mock.reset fails

### ISSUE THREAD

**Issue by borski** [fog/fog#3784]
With master, for some reason, `Fog::Mock.reset` throws the following exception: 

```
NameError: uninitialized constant Fog::Vsphere::Compute
from /Users/borski/.../gems/fog-core-1.35.0/lib/fog/core/mock.rb:96:in `const_get'`
```

Reproducing is very easy:
```
[1] pry(main)> require 'fog'
=> true
[2] pry(main)> Fog.mock!
=> true
[3] pry(main)> Fog::Mock.reset
NameError: uninitialized constant Fog::Vsphere::Compute
from /Users/borski/.../gems/fog-core-1.35.0/lib/fog/core/mock.rb:96:in `const_get'
```

No idea where it's coming from / how to fix it, or when it was introduced, but it's breaking some of my specs, sadly.

**Comment by borski** [comment]
I'm guessing this might be related to #3762?

**Comment by geemus** [comment]
@jrgarcia @plribeiro3000 any ideas on fixing this up? Thanks!

**Comment by jrgarcia** [comment]
@geemus @borski I'll take a look at it at some point today.

**Comment by borski** [comment]
Bump. Any update on this?

**Comment by jrgarcia** [comment]
This is fixed in the latest fog-vsphere. I can make a PR to require the latest version of fog-vsphere in fog tonight.

**Comment by borski** [comment]
@jrgarcia No problem - I saw the fix. If you wouldn't mind pushing a release, I can certainly make the pull req to update the version (or you can, either way). :)

**Comment by jrgarcia** [comment]
@borski Sorry. I somehow missed the fact that there wasn't a release after that. I've pushed a new release of `fog-vsphere`. Feel free to make the PR for the version update. Thanks!

**Comment by geemus** [comment]
Thanks!
