### ISSUE TITLE
Is there any way not setting public acl while `public` option is true

### ISSUE THREAD

**Issue by yanke-guo** [fog/fog#3790]
I've set acl to `private` at s3 bucket level, and add a policy to allow anonymous read from specified HTTP Referer header.

Now I have a problem, if I set `public` option to false, all image urls will be signed, that is a waste, but if I set `public` to true, `fog` will add `public-read` acl to object level, which will override HTTP Referer policy.

**Comment by plribeiro3000** [comment]
@yanke-guo Could you open this against [`fog-aws`](https://github.com/fog/fog-aws) instead please?

Thanks!

**Comment by yanke-guo** [comment]
@plribeiro3000 OK

**Comment by yanke-guo** [comment]
@see https://github.com/fog/fog-aws/issues/207

**Comment by plribeiro3000** [comment]
@yanke-guo Awesome! Thank you!
