### ISSUE TITLE
[digitalocean] server destroy throws NoMethodError

### ISSUE THREAD

**Issue by rroa** [fog/fog#3798]
Even though the request is defined, the destroy method doesn't seem to be implemented for the server model.

```
undefined method `destroy' for #<Fog::Compute::DigitalOceanV2::Server:0x007fce7c8b2728> 
(NoMethodError)
```

**Comment by h0lyalg0rithm** [comment]
Hi @rroa, to delete the server from digitalocean you have call the delete method.

**Comment by h0lyalg0rithm** [comment]
@geemus I think you can close this one :)

**Comment by h0lyalg0rithm** [comment]
@rroa I realized that the example in the repo was wrong.Thanks for letting us know.
