### ISSUE TITLE
Travis runs are failing on OpenStack provider

### ISSUE THREAD

**Issue by pedantic-git** [fog/fog#3801]
It's not clear what's changed since the last commit to master 6 days ago, but all Travis runs on pull requests since then are failing on the OpenStack provider.

For example, [#3794](https://github.com/fog/fog/pull/3794) is a one-line change in the vCloud Director provider, and it is exhibiting this behaviour.

**Comment by h0lyalg0rithm** [comment]
Even documentation changes cases the build to fail #3803

**Comment by geemus** [comment]
@dhague @Ladas @TerryHowe any ideas?

**Comment by Ladas** [comment]
actually those are not fails, those are not implemented test e.g. https://github.com/fog/fog/blob/master/spec/fog/openstack/image_v2_spec.rb#L233
but it's not causing CI failure, just prints the failures as pending

The actual CI fail is in digitalocean, I saw those failures before, not sure what is causing this, seems like some race condition, cause it usually disappears for me after restarting the test.

**Comment by pedantic-git** [comment]
My apologies - I read that output incorrectly. @Ladas is correct that it is the digitalocean provider that is causing the CI failures.

**Comment by geemus** [comment]
Thanks for clarification.

@bryanl would appreciate any insight you might have. Thanks!

**Comment by geemus** [comment]
Just pushed a couple fixes for the digital ocean stuff, so hopefully back in business now.
