### ISSUE TITLE
Rackspace storage copy_object doesn't preserve content-type by default

### ISSUE THREAD

**Issue by gb-timeplay** [fog/fog#3815]
Using copy_object to duplicate a file in Rackspace Cloud Files storage, the content-type is set to application/json unless a 'Content-Type' header is explicitly set.

**Comment by geemus** [comment]
@mdarby could you check this out? Thanks!

**Comment by gb-timeplay** [comment]
More details on this:
If no Content-Type header is set in the call to copy_object, the FOG storage model automatically adds a Content-Type of application/json. If no Content-Type header is set in the request, Rackspace Cloud Files uses the Content-Type of the object being duplicated.

My workaround was to explicitly set 'Content-Type' => nil in the options hash.

**Comment by geemus** [comment]
@gb-timeplay Nice to hear there is a workaround, seems like we might have a bug still though. Would you be up for working toward a fix? I'm happy to support you however I can in that, but don't actively use Rackspace myself so wouldn't easily be able to verify or anything.

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-rackspace#9
