### ISSUE TITLE
Propose to add compute API v2.1 to openstack - new features, Servers password (servers, os-server-password)

### ISSUE THREAD

**Issue by thindiyeh** [fog/fog#3831]
please add compatibility to openstack compute v2.1 API, it has new functionality such as Servers password (servers, os-server-password)

Thanks in advance!

**Comment by thindiyeh** [comment]
I added a support to get_os_password from openstack, see PR #3833

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-openstack#57
