### ISSUE TITLE
[vcloud_director] Support CPU/Memory 'Weight' and 'Reservation' parameters

### ISSUE THREAD

**Issue by saw792** [fog/fog#3832]
vCloud Director supports a few different resource allocation models for VDCs, one of which is 'Reservation Pool'. This allows individual VMs to have a 'priority' value and a 'reserved' value for CPU and memory resources. In the ovf format these values are mapped to in the 'Weight' and 'Reservation' fields respectively.

Currently when updating CPU/Memory these values are hard-reset to 0 (see extract from put_cpu.rb below). I would like to add these fields to the vm model so that they are preserved when changes to CPU/memory are made, and ideally allow them to be modified as well.

``` ruby
def put_cpu(id, num_cpus)
          data = <<EOF
          <Item 
            xmlns="http://www.vmware.com/vcloud/v1.5" 
            xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xmlns:ns12="http://www.vmware.com/vcloud/v1.5" 
            ns12:href="#{end_point}vApp/#{id}/virtualHardwareSection/cpu" 
            ns12:type="application/vnd.vmware.vcloud.rasdItem+xml" 
            xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5 #{end_point}v1.5/schema/master.xsd http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2.22.0/CIM_ResourceAllocationSettingData.xsd">
            <rasd:AllocationUnits>hertz * 10^6</rasd:AllocationUnits>
            <rasd:Description>Number of Virtual CPUs</rasd:Description>
            <rasd:ElementName>#{num_cpus} virtual CPU(s)</rasd:ElementName>
            <rasd:InstanceID>4</rasd:InstanceID>
            <rasd:Reservation>0</rasd:Reservation>
            <rasd:ResourceType>3</rasd:ResourceType>
            <rasd:VirtualQuantity>#{num_cpus}</rasd:VirtualQuantity>
            <rasd:Weight>0</rasd:Weight>
            <Link rel="edit" type="application/vnd.vmware.vcloud.rasdItem+xml" href="#{end_point}vApp/#{id}/virtualHardwareSection/cpu"/>
          </Item>
EOF

          request(
            :body    => data,
            :expects => 202,
            :headers => {'Content-Type' => 'application/vnd.vmware.vcloud.rasdItem+xml'},
            :method  => 'PUT',
            :parser  => Fog::ToHashDocument.new,
            :path    => "vApp/#{id}/virtualHardwareSection/cpu"
          )
        end
      end
```

**Comment by geemus** [comment]
Sounds reasonable. Just let me know if you have questions or anything I can help with toward that enhancement. Thanks!

**Comment by seanhandley** [comment]
If a server returns a polling URI in the `Location` header of a `202` response, is there a native Fog mechanism for handling it synchronously in some way?

**Comment by geemus** [comment]
@seanhandley The closest is probably the `wait_for` stuff, though I think it mostly relies on just doing a `get` to a model to look for changes (instead of an arbitrary URI). I think you probably could do something with `Fog.wait_for` directly with something appropriate in the block, but nothing that would just automatically do it comes to mind.
