### ISSUE TITLE
mock in fog openstack snapshot 'list_snapshots' error

### ISSUE THREAD

**Issue by zhitongLBN** [fog/fog#3836]
i got a error while using: `.snapshot.all` when i'm in the Mock mode
cause in request/compute/list_snapshots.rb
it call `get_snapshot_details.body['snapshot']` but `get_snapshot_details` need a `snapshot_id` argument.

**Comment by geemus** [comment]
Ah, probably just an oversite as the interface as evolved. Would you be up for trying to work on a fix? Thanks!

**Comment by zhitongLBN** [comment]
Please look at my pull request and tell me what should I improve, thx :)

**Comment by geemus** [comment]
@zhitongLBN looks good, thanks!
