### ISSUE TITLE
[joyent] Version 6.5 of Joyent API is deprecated 

### ISSUE THREAD

**Issue by mafraba** [fog/fog#3839]
Joyent does not support 6.5 version of their API anymore (see https://apidocs.joyent.com/cloudapi/, apendix E).

The api version to use can be specified when creating a Fog::Compute::Joyent object, but I found that the deprecated 6.5 is being used by default.

Moreover, support for Basic authentication should also be removed since the newer versions of the API don't support it.

**Comment by geemus** [comment]
Thanks for pointing this out. Would you be willing and able to help us out with a patch? Thanks!

**Comment by mafraba** [comment]
I'd be glad to do it if I find the time. Can't promise anyway.

**Comment by geemus** [comment]
Thanks!

**Comment by geemus** [comment]
closed by #3878

-
