### ISSUE TITLE
[openstack]Is that making associate and disassociate in floating-ip objet is useful?

### ISSUE THREAD

**Issue by zhitongLBN** [fog/fog#3847]
I found that `associate` and `disassociate` a public_ip with a port is not in object `model/floating_ip`, 
but in `requests/` there are services `associate_floating_ip` to `disassociate_floating_ip` to do the thing.

https://github.com/fog/fog/blob/master/lib/fog/openstack/models/network/floating_ip.rb#L6-L37
https://github.com/fog/fog/blob/master/lib/fog/openstack/requests/network/associate_floating_ip.rb
https://github.com/fog/fog/blob/master/lib/fog/openstack/requests/network/disassociate_floating_ip.rb

So do you think is useful to put them into class `floating_ip`? 

I'm up to do this, if you are agree :)

**Comment by geemus** [comment]
@zhitongLBN yeah, I think that sounds reasonable and useful. Just let me know if you have questions or anything I can help with.

**Comment by seanhandley** [comment]
There's quite a lot of that in the OpenStack code (requests available but not exposed on models) so please feel free to fix :+1:

**Comment by zhitongLBN** [comment]
please check the PR #3850, it should do the thing.
please also tell me the way you want me to improve :)

**Comment by geemus** [comment]
closed by #3850
