### ISSUE TITLE
Map complex attributes

### ISSUE THREAD

**Issue by blackms** [fog/fog#3855]
Hello,
I have a doubt, I'm trying to map in the correct whay the following structure as attribute:
server.attributes['NetworkAdapters'][0]['IPAddresses'][0]['Value']

It's an array of array, how can I map in a model using attribute?

**Comment by geemus** [comment]
Could you give a bit more detail about which provider you mean?

**Comment by blackms** [comment]
arubacloud :) I'm developing it. (it's on fog repo already)

**Comment by plribeiro3000** [comment]
you should use the `association` feature. Then `server.network_adapters` will give you a collection of the model `NetworkAdapter` and each `NetworkAdapter` would have an association for `IpAddress` with a method called `value`.

So code wise:

```ruby
class Server
  has_many :network_adapters, :network_adapters, aliases: "NetworkAdapters"
end

class NetworkAdapter
  has_many :ip_addresses, :ip_addresses, aliases: "IPAddresses"
end

class IpAddress
  attribute :value
end
```

PS: You will need a collection class for both models (`NetworkAdapter` and `IpAddress`).

This will be available as:

```ruby
connection.servers.get('id).network_adapters.first.ip_addresses.first.value
```

Is this what you are trying to achieve?

**Comment by blackms** [comment]
Yes, that's exactly what I was trying to achieve. Thank you very much for the help!
