### ISSUE TITLE
[vcloud-director] Migrate to Minitest

### ISSUE THREAD

**Issue by tlawrence** [fog/fog#3858]
Hi,

I'm about to add a few bits to the vcloud_director provider and would like to support the new Minitest framework. 
Does anyone have a 101 for getting minitest setup (dir structure etc) on a provider?

is this a good example?
https://github.com/fog/fog/blob/c7348b2b369b69a5125349fc11a41eaabf39dafc/spec/fog/openstack/network_spec.rb

Also, the current tests are rolled up into largeish files based on a high level object (eg vm_tests.rb)
I wonder if it would make contributing simpler to have a spec per request (where most complexity resides) instead. e.g put_create_network_spec.rb

Any thoughts?

**Comment by geemus** [comment]
Good question. @plribeiro3000 @tokengeek @mdarby perhaps one of you have some tips?

**Comment by geemus** [comment]
@tlawrence I haven't done a ton around the minitest side of this stuff so I defer there. In most other providers we do most of the testing more at the per-request level, so that sounds like a good plan.
