### ISSUE TITLE
[xen] "affinity is required for this operation" when trying to create new VM using XenServer provide

### ISSUE THREAD

**Issue by jjasghar** [fog/fog#3860]
https://github.com/chef/chef-provisioning-fog/issues/123

Is effected by this change.

fog version (1.35.0 -> 1.34.0) 
fog-core (1.35.0 -> 1.32.1)

Need to figure out what changes for Xen happened in these and see what may have caused this issue.

**Comment by plribeiro3000** [comment]
So thats it. `affinity` is required for `Vm` creation.

You can see it [here](https://github.com/fog/fog-xenserver/blob/master/lib/fog/compute/xen_server/models/server.rb#L100).

BTW, lets move this to the right repo.

**Comment by plribeiro3000** [comment]
@jjasghar Lets follow up at fog/fog-xenserver#57.
