### ISSUE TITLE
Rackspace identification not needed

### ISSUE THREAD

**Issue by bl4ckdu5t** [fog/fog#3861]
I'm basically just using the gem to upload files to rackspace and I don't think it should be doing anything outside of the upload process but I realized it delays my application rendering by taking up to 7s identifying with https://identity.api.rackspacecloud.com/ before each page loads. I took out the gem temporarily since I wasn't doing any uploads and got this:
```
ActionView::Template::Error (uninitialized constant Fog):
<%= image_tag 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==', 'data-src' => featured.uploads.first.image.url(:medium), 'data-src-medium' => featured.uploads.first.image.url(:medium), 'data-src-small' => featured.uploads.first.image.url(:small), class: 'b-lazy' %>
```
which made me realize Fog was doing more than just directing my uploads to the right rackspace container. How can I fix this? I think the asset url from my database is enough to fetch assets

**Comment by geemus** [comment]
I think it looks like you may be using fog indirectly through something like carrierwave or paperclip? That might make it a bit more complicated. But the big thing is using `files.new` instead of `files.get` for things like this. `new` just instantiates a local reference, whereas `get` makes a remote lookup. Hope that helps steer you in the right direction anyway.

**Comment by bl4ckdu5t** [comment]
I'll like to change it from `files.get` to `files.new` but I have no idea where to do that. Is there somewhere I can set toggle it as an option? Here's how I'd used fog in my application:
```ruby
# Paperclip config
config.paperclip_defaults = {
  storage: :fog,
  fog_credentials: {
    provider: "Rackspace",
    rackspace_username: ENV['FOG_USERNAME'],
    rackspace_api_key: ENV['FOG_API_KEY'],
    rackspace_region: ENV['FOG_REGION']
  },
  fog_directory: ENV['FOG_CONTAINER']
}
```

**Comment by geemus** [comment]
I looked a little, but I'm afraid I am not very familiar with the paperclip code. If you can make the urls public, it seems like that might help? But outside that I would recommend asking on the paperclip repo, as I think the issue is somewhere on that side of things.

**Comment by bl4ckdu5t** [comment]
I looked through carrierwave. Saw you as a contributor there and I was making the switch when I found the part that says set `config.action_controller.asset_host` to the the CDN url or it has to get it each time.
> his is highly recommended, as without it every request requires a lookup of this information.
 I remained in paperclip and did just that which reduced my response time. I think it's something that should also be added to the Fog readme

**Comment by geemus** [comment]
I guess it seems more like a paperclip issue than fog. Also I'm confused since you mention carrierwave but the info above seems to refer to paperclip.

**Comment by bl4ckdu5t** [comment]
I'm sorry I didn't clearly express myself. I was only saying I tried to move to carrierwave and since I saw you contributed to its repository then I'd thought it'll probably work perfect from there. While I was reading through the readme I saw the line I referenced there which suggested that I set a asset host and I didn't have to migrate to carrierwave from paperclip

**Comment by geemus** [comment]
Ah, ok. Thanks for clarifying. I've worked on both carrierwave and paperclip, but it's been quite a long time. Glad to hear you got what you needed.
