### ISSUE TITLE
IPFS?

### ISSUE THREAD

**Issue by sesam** [fog/fog#3863]
Considering this quote "The all-clouds-in-one library of choice is fog." from your website :-), is IPFS likely to be added? Any pointers / intuition on how hard it would be?

**Comment by geemus** [comment]
We are open to supporting new stuff, as long as someone is up to writing the code. I'm not particularly familiar with IPFS. In most cases the best starting point can be to look at existing examples. @plribeiro3000 usually has some good resources/tips to share also though.

**Comment by plribeiro3000** [comment]
:+1: 

so a (not so) good start point is [this](https://github.com/fog/fog/wiki/Create-New-Provider-from-Scratch) wiki page.

As someone start woking on it i can guide the rest of the process.

**Comment by sesam** [comment]
Oh, right, that looks like a full evening or weekend to get through. Hm.

**Comment by plribeiro3000** [comment]
Closing in favor of #3644
