### ISSUE TITLE
[OpenStack Swift] Object tempURL generation is very slow

### ISSUE THREAD

**Issue by benlangfeld** [fog/fog#3865]
Using Fog via Paperclip in a Rails application with objects stored in Swift, I found the tempURL generation to be a significant bottleneck in my application, particularly when generating many of them in a single request. This is because the current method makes a request to Swift to generate the URL on our behalf, and these network connections are much slower than [generating a URL signature ourselves](http://docs.openstack.org/kilo/config-reference/content/object-storage-tempurl.html).

I have a solution monkey-patched in my app as a monkey-patch of Paperclip and it works well. I'd like to submit this upstream, and fog seems like the right place to do this. On the other hand, given the dependency chain, I'm going to be on 1.x for a while. If I were to prepare a patch to fog to the above effect, is it likely to be accepted into the 1.x series of releases?

**Comment by seanhandley** [comment]
Hi @benlangfeld,

FYI we moved all OpenStack code over to a separate gem at https://github.com/fog/fog-openstack so please feel free to raise issues/pull requests over there.

**Comment by benlangfeld** [comment]
That gem is only used by fog 2.x. Does that mean this change would not be accepted into the 1.x series?

**Comment by seanhandley** [comment]
I'm not sure. I didn't hear anything about the 1.x series of releases coming to an end.

Are we due another release before 2 lands @geemus ?

**Comment by benlangfeld** [comment]
It turns out Fog is [already doing the same thing](https://github.com/fog/fog/blob/v1.37.0/lib/fog/openstack/requests/storage/get_object_https_url.rb#L19-L67) as [my monkey-patch to Paperclip](https://gist.github.com/benlangfeld/0c2cbc3deca1d8bf561d), but the latter is significantly faster. I'm going to have to do some benchmarking to figure out what's going on.

**Comment by geemus** [comment]
We'll probably keep doing 1.x for a while yet. We've considered/desired 2.x but have a few things we'd like to finish first (like the rest of splitting things up, which has been slow but steady).
