### ISSUE TITLE
[vsphere] add support for adding raw devices to VMs

### ISSUE THREAD

**Issue by gpetras** [fog/fog#3866]
This support is available in PowerCLI and the Perl SDK, which indicates the vSphere API supports it. It'd be great if fog also supported this functionality.

**Comment by geemus** [comment]
Thanks for the heads up. Any chance you would be interested in working on a pull request adding the functionality? Thanks!

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-vsphere#45
