### ISSUE TITLE
ruby 1.9 Support

### ISSUE THREAD

**Issue by icco** [fog/fog#3872]
So, when do we fully drop 1.9 support in Fog?

IIRC, the main reason was debian support.

According to https://packages.debian.org/search?keywords=ruby, wheezy, aka oldstable, still only has 1.9. According to https://wiki.debian.org/DebianOldStable, on April 26th, 2016, the Debian team will drop support for Wheezy. Which in my mind, means we can drop 1.9.

But.... https://wiki.debian.org/LTS/ says external volunteers will be maintaining Wheezy until June 1st, 2018. whoo.

For ubuntu, http://packages.ubuntu.com/search?keywords=ruby shows us that 14.04 has 1.9... which according to https://wiki.ubuntu.com/LTS is supported until late 2019.

Soooo, writing this issue made me really sad. @geemus or @plribeiro3000 say something to make me happier, please...

**Comment by geemus** [comment]
ug... I guess we should just make a call at some point, continuing to support is definitely a pain and things probably aren't going to sort themselves out. What are other's opinions on how/when we should proceed?

**Comment by plribeiro3000** [comment]
Yeah. so i think the point is: Are we going to fix the problem of LTS operational systems and the fact that ruby development goes way faster then that ourselves?

I say no. This is a huge problem and is really painful to do so. On another side we need to provide them at least something that makes sense. And i believe this is us moving to `2.0.0` and those operational systems sticking with `1.x.x`.

We were all aligned to follow this solution before. Not really sure what happened because we are back in the `1.x.x` releases.

@geemus What is blocking us to move to `2.0.0`? Something i can tackle?

**Comment by nirvdrum** [comment]
I'm probably to blame for the extra 1.x releases. DigitalOcean threw us in a bind by dropping v1 of their API and I didn't think forcing people using DigitalOcean to also go through a major Ruby & Fog upgrade was the best option.

I'm a fan of calling 1.x done, releasing Fog 2.0, and making that Ruby 2.0+.

**Comment by plribeiro3000** [comment]
@nirvdrum Sure man. No one is to blame here. You did a good call on the DigitalOcean thing and now i do remember why we are back on `1.x.x`. I was onboard on that decision at the time and i'm still but now i guess is the time to kill `1.x.x` and let everyone know that they should stick to the last version if they want `1.9` support.

Just to be clear, our latest `1.x.x` dropped ruby `1.9` support? no right?

**Comment by nirvdrum** [comment]
I thought one of the releases did. But it was unintentional -- a fog gem or two went 2.0+ plus a bit early. It looks like that's been fixed though. 1.38.0 just installed cleanly in 1.9.3-p551 for me.

**Comment by icco** [comment]
yeah, that was my fault (we're all horrible!), because version 0.1.1 of fog-google made ruby be >= 2.0. Whenever we do make fog 2.0, we should unpin fog-google as well.

**Comment by icco** [comment]
Oh, and unpin mimetypes and net-ssh?

**Comment by plribeiro3000** [comment]
@icco Good points. We should definetely do so when bumping to `2.0.0`.

@geemus thoughts?

**Comment by Temikus** [comment]
My 0.02$: I'm in favor of this, but one note for the sake of keeping all the info together: AFAIK there's not only the LTS use-case, there's also the Jruby thing, since not everyone has migrated to 9k and old one doesn't have proper Ruby 2.0 support.

**Comment by icco** [comment]
@nirvdrum do you still know all of the jruby stuff?

**Comment by plribeiro3000** [comment]
@Temikus Good point dude! I forgot about it.

**Comment by icco** [comment]
https://github.com/jruby/jruby/wiki/Roadmap looks like jruby 9.0.1.0 and later all support Ruby 2.2 syntax, and older versions of jruby aren't supported any more.

**Comment by geemus** [comment]
Yeah, there were a few things that just needed releases ASAP, but where we didn't feel like it was 2.0 ready quite yet. Also, we seem to be factoring out more independent gems the longer we wait, which is a nice "feature" toward 2.0. We could probably move back to a bigger push here though, it just kind of fell off my radar.

**Comment by Temikus** [comment]
I propose the following:
- Drop Ruby 1.9.3/1.8.7 support from 2.X hard.
- If something is direly needed (for security issues, etc.) - backport it to 1.X.
- Otherwise - recommend people to upgrade or use 1.X if they need support for legacy ruby versions.

This should not block existing people and allow us to clean up the project at the same time. Makes sense?

**Comment by geemus** [comment]
I think that sounds fine, just need to get 2.x back on track and moving forward.

**Comment by plribeiro3000** [comment]
👍

**Comment by icco** [comment]
Pinging this as it's now September, and this is the last time we talked about releasing 2.0 (there is also https://github.com/fog/fog/issues/3883, but this bug is more recent).

**Comment by geemus** [comment]
@icco good call, back on my radar.

**Comment by plribeiro3000** [comment]
@geemus What do we need to do to be able to bump to `2.0.0` on next release?

**Comment by geemus** [comment]
Good question, maybe it is time for us to just bite the bullet and do it (event though not everything is extracted, etc). I guess we can always do 3.0 at split time if needed. Anyone have other concerns?

**Comment by kenn** [comment]
Let's just get this thing out. You can always do `gem uninstall fog; gem install fog -v=1.38.0` if you want to go back. It's time to create a healthy momentum going forward! 👊

**Comment by geemus** [comment]
Yeah, definitely need to rip-off the band-aid so to speak.

**Comment by lauramorillo** [comment]
Any update on this? I was trying to use the access to GCS using fog and fog-google with the JSON API but it looks like it was added in a version after 0.1.0, so It is blocked until this change is ready.

Thanks!

**Comment by geemus** [comment]
@lauramorillo sorry for the difficulty. I think you can simply require `fog-google` directly to workaround this issue (as long as you only need google). Hopefully that should prevent this from blocking you.

**Comment by lauramorillo** [comment]
Hi @geemus! Thanks for your answer! I had already tried that but it throws an error when installing because of conflict with the version set in fog. 

I can wait, It is ok, I just wanted to know if I can expect the change soon to be able to release the feature.

**Comment by geemus** [comment]
Ah, sorry to hear that. @icco @Temikus maybe one of you could advise on current best practice?

**Comment by icco** [comment]
@lauramorillo Most people have been just requiring the select subprojects they need. So unless you need a project that doesn't have a subproject, then you shouldn't need to require `fog` at all.

**Comment by lauramorillo** [comment]
Well, the gem that I am extending (https://github.com/backup/backup) has
fog as a dependency. If I have time I will try to create a PR to change the
dependency and check all the subprojects being used there, but I find it a
bit out of the scope of simply adding support to Google Cloud Storage.

**Comment by geemus** [comment]
That's fair. Some other projects (like carrierwave) just don't include anything from fog, leaving it to the end user to add whichever bits they need. This might be tenable, but I ] agree it unfortunately increases the scope of change.

**Comment by Temikus** [comment]
Note: Ruby 2.0 is no longer supported either, so we'll need to bump to 2.1 at the very least.

**Comment by geemus** [comment]
@Temikus good point.

**Comment by plribeiro3000** [comment]
ping. How are we with this?

**Comment by Temikus** [comment]
@plribeiro3000 - #3942 is blocking probably. I'm still dealing with some issues, but I'll try to put some engineering time towards it in the next 2 weeks.

**Comment by plribeiro3000** [comment]
@Temikus Hmm, good point. 👍

**Comment by plribeiro3000** [comment]
Closing this since we already dropped support for ruby `1.9`.

https://github.com/fog/fog/blob/a4cdb7390a18556bf76ceab706b785db2ed50d42/fog.gemspec#L47
