### ISSUE TITLE
Heroku deploy fail

### ISSUE THREAD

**Issue by atebit** [fog/fog#3873]
Having a weird issue. Searching for it—I found this thread, which seems to be the problem [https://github.com/fog/fog-aliyun/issues/8]. It's deploying to an existing app, but not to a new one on Heroku. Thoughts?

-----> Using set buildpack heroku/ruby
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.2.1
-----> Installing dependencies using bundler 1.11.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Fetching gem metadata from https://rubygems.org/...........
       Fetching version metadata from https://rubygems.org/...
       Fetching dependency metadata from https://rubygems.org/..
       Could not find fog-aliyun-0.0.10 in any of the sources
       Bundler Output: Fetching gem metadata from https://rubygems.org/...........
       Fetching version metadata from https://rubygems.org/...
       Fetching dependency metadata from https://rubygems.org/..
       Could not find fog-aliyun-0.0.10 in any of the sources
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app

`

		config.storage :fog
	  # config.fog_provider = 'fog/aws'                        # required
	  config.fog_credentials = {
	    provider:              'AWS',                        # required
	    # host:                  's3.example.com',             # optional, defaults to nil
	    # endpoint:              'https://s3.example.com:8080' # optional, defaults to nil
	  }
	  config.fog_directory  = 'talk-tei-dev'                          # required
	  config.fog_public     = false                                        # optional, defaults to true
	  # config.fog_attributes = { 'Cache-Control' => "max-age=#{365.day.to_i}" } # optiona
	end`

**Comment by plribeiro3000** [comment]
@atebit At the moment there is nothing we can do since `rubygems` does not allow unyanking anymore.
Can you do a gem update `fog-aliyun` please?

@geemus I would suggest if that thing does not get fixed we remove `fog-aliyun` out of fog until we do.
It clearly need some :heart:. It is depending on `xml-simple` when it should be depending on `fog-xml`. It might have some other issues to be fixed as well.

**Comment by atebit** [comment]
@plribeiro3000 @geemus  I'm not using the fog-aliyun, is it possible to bypass? I tried using just fog-aws but it is throwing the same error.

**Comment by plribeiro3000** [comment]
Change your `Gemfile` from:

```ruby
gem 'fog'
```

to

```ruby
gem 'fog-aws'
```

and you should be good.

**Comment by atebit** [comment]
had to manually remove the reference to 'fog-aliyun' from the lock file, interesting..

**Comment by plribeiro3000** [comment]
No. don't do that! You are not supposed to play with `Gemfile.lock`.

Just change your `Gemfile` and then do a `bundle install`.

**Comment by atebit** [comment]
For some reason, bundle install wasn't removing old references. Had to nix it and do a fresh bundle install. But, that got it to work. Thanks for your help on this!

**Comment by plribeiro3000** [comment]
Sure. No worries. I'm glad to help!

**Comment by geemus** [comment]
Thanks for working through this!
