### ISSUE TITLE
Fog directory appends local system path with amazon url when i try to give dynamic fog directory

### ISSUE THREAD

**Issue by vf-sohail** [fog/fog#3874]
I am using FOG with Paperclip. I added the following code to give dynamic directory name.

`fog_directory: proc { |file| file.instance.repo.name }`

It creates the fog directory correctly but when i try to get url it added the local system path with amazon url.

https://s3.amazonaws.com/%23%3CProc:0x4ae8f3bb@/home/apple/projects/project.name/config/initializers/paperclip.rb:8%3E/abc.jpg

**Comment by geemus** [comment]
I've not seen usage quite like this before. I think it may be a paperclip error rather than one inherently in fog, but I could be wrong.

**Comment by plribeiro3000** [comment]
closing in favor of fog/fog-aws#295
