### ISSUE TITLE
Support Backblaze as Cloud Storage provider

### ISSUE THREAD

**Issue by Ybrin** [fog/fog#3875]
I think it would be great to support [Backblaze](https://www.backblaze.com/b2/cloud-storage.html) as a Cloud Storage provider because it is also one of the bigger services and it is more attractive to smaller customers because of their lower prices.

**Comment by plribeiro3000** [comment]
Sure. Thank you! I will close this issue in favor of #3644 so we won't have a lot of tickets just for new provider requests.

Would you be able/want to work on that provider?

**Comment by Ybrin** [comment]
Hi, I don't know that much about their API but I could read through their docs and implement it if you want to.

**Comment by BilalReffas** [comment]
@Ybrin is it already implemented?

**Comment by qqnc** [comment]
Someone is working on it? If no, I might be work on that.

**Comment by geemus** [comment]
Please refer to: fog/fog-backblaze (which is the main work I'm currently aware of and appears to be active)
