### ISSUE TITLE
Bump fog-core to >=1.38.0

### ISSUE THREAD

**Issue by voelzmo** [fog/fog#3880]
To include excon 0.49.0 we need fog-core >=1.38.0. Can we please get a bump to fix https://github.com/excon/excon/issues/542 as described in https://github.com/fog/fog-core/issues/184?

Thanks!

**Comment by icco** [comment]
Do you need to even be including fog in your project? We can do this (we should), but it looks like you might only need one of the sub-projects, not the actual fog gem.

**Comment by voelzmo** [comment]
@icco  thanks for the suggestion. We need aws and openstack, so now that fog-openstack is its own thing, we should probably switch to including those two directly. However, currently we don't so not sure if we should mix those two things for now.

**Comment by icco** [comment]
It should be seamless, if you only use aws and openstack, just change your deps to `fog-aws` and `fog-openstack`.
