### ISSUE TITLE
2.0 release ETA?

### ISSUE THREAD

**Issue by kenn** [fog/fog#3883]
Sorry if it's mentioned elsewhere already, but just a general status inquiry: Is it OK to start using `2.0.0.pre.0` right now? Or are we expecting breaking changes before final?

I like the idea of untangling dependencies from the core, and I'd love to use the new version. 😍

**Comment by plribeiro3000** [comment]
@kenn you are certainly encouraged to use version `2.0.0` or just eh extracted providers.

Regarding ETA and breaking changes we are not that close to be able to give you an answer. It might be soon in the same way that it might not.

We will announce in here and on [twitter](https://twitter.com/fog).

Hope this helps.

**Comment by kenn** [comment]
Thanks @plribeiro3000 ! I sure hope it would be on the soon side. 😆

I thought I'd close this issue, but also thought it might work as an FAQ. Feel free to close whenever / if you want to.

**Comment by plribeiro3000** [comment]
Yeah, i think we can leave this open so other people will find it more easily. =)

**Comment by Temikus** [comment]
Hi @kenn!

I saw you said that your use-case was:
> untangling dependencies from the core

If that is indeed your main point - this has already happened, you can already use just your relevant gem.
To quote the dependency notice from the README:

> Currently all fog providers are getting separated into metagems to lower the load time and dependency count.
> 
> If there's a metagem available for your cloud provider, e.g. fog-aws, you should be using it instead of requiring the full fog collection to avoid unnecessary dependencies.
> 
> 'fog' should be required explicitly only if:
> 
> The provider you use doesn't yet have a metagem available.
> You require Ruby 1.9.3 support.

Cheers,
A.

**Comment by geemus** [comment]
Yeah, many have been separated, but many also have not. We have been headed slowly but steadily in that direction, but don't really have a concrete date when we hope to be there as it's all volunteer effort.

**Comment by plribeiro3000** [comment]
@geemus Could you do a final `2.0` release please?

**Comment by geemus** [comment]
@plribeiro3000 are we ready now to do it? I guess this would be just following up on existing fog-core 2.0? (where the major breaking change is dropping earlier ruby support)

**Comment by plribeiro3000** [comment]
Yeap. One benefit is that we can deal with the headaches that might happen on dropping ruby support prior of the problems when we finish extracting everything.

**Comment by geemus** [comment]
done
