### ISSUE TITLE
Fog::DNS::Rackspace::BadRequest: [HTTP 400 | ] Validation failed

### ISSUE THREAD

**Issue by KaGeN101** [fog/fog#3888]
We started getting this error all of a sudden today updating our load balancer with Fog on Rackspace.

Has the Rackspace API changed and Fog not in sync with it currently?

We are on the latest gem versions, here is a list or our Fog gem versions:
fog (1.38.0)
fog-aliyun (0.1.0)
fog-atmos (0.1.0)
fog-aws (0.9.2)
fog-brightbox (0.10.1)
fog-cloudatcost (0.2.1)
fog-core (1.40.0)
fog-dynect (0.0.3)
fog-ecloud (0.3.0)
fog-google (0.3.2)
fog-json (1.0.2)
fog-local (0.3.0)
fog-openstack (0.1.6)
fog-powerdns (0.1.1)
fog-profitbricks (0.0.5)
fog-rackspace (0.1.1)
fog-radosgw (0.0.5)
fog-riakcs (0.1.0)
fog-sakuracloud (1.7.5)
fog-serverlove (0.1.2)
fog-softlayer (1.1.1)
fog-storm_on_demand (0.1.1)
fog-terremark (0.1.0)
fog-vmfusion (0.1.0)
fog-voxel (0.1.0)
fog-vsphere (0.7.0, 0.6.3)
fog-xenserver (0.2.3)
fog-xml (0.1.2)

Thanks

**Comment by plribeiro3000** [comment]
@KaGeN101 Could you open this against [`fog/fog-rackspace`](https://github.com/fog/fog-rackspace) instead please?

**Comment by KaGeN101** [comment]
Okay sure makes more sense :/

**Comment by plribeiro3000** [comment]
Awesome. Thank you!

**Comment by plribeiro3000** [comment]
Closing this in favor of fog/fog-rackspace#14
