### ISSUE TITLE
InvalidClientTokenId => The security token included in the request is invalid

### ISSUE THREAD

**Issue by msommerville** [fog/fog#3889]
I've looked for a solution to this - everything I have found has said this should work, but I can't find any details on what's happening. I don't know if it's a bug or I'm doing something egregiously wrong.

When executing this snippet:

    awsclient = Fog::DNS::AWS.new(
      :aws_access_key_id => @aws_access_key_id,
      :aws_secret_access_key => @aws_secret_access_key,
    )

    p awsclient
    puts "\n\n\n"
    zone = awsclient.zones.all.select { |zone| zone.domain == "citnow.com." } [0]
(same happens executing basically any command)

I get the following output (credentials etc. redacted, but all correct):

#<Fog::DNS::AWS::Real:35746200 @use_iam_profile=nil @aws_access_key_id="..." @aws_secret_access_key="..." @aws_session_token=nil @aws_credentials_expire_at=nil @hmac=#<Fog::HMAC:0x0000000442e2e0 @key="...", @digest=#<OpenSSL::Digest: da39a3ee5e6b4b0d3255bfef95601890afd80709>, @signer=#<Proc:0x0000000442e240@/usr/lib/ruby/vendor_ruby/fog/core/hmac.rb:21 (lambda)>> @instrumentor=nil @instrumentor_name="fog.aws.dns" @connection_options={:debug_response=>true, :headers=>{"User-Agent"=>"fog/1.34.0 fog-core/1.32.1"}, :persistent=>true} @host="route53.amazonaws.com" @path="/" @persistent=true @port=443 @scheme="https" @version="2013-04-01" @connection=#<Fog::XML::Connection:0x0000000442e0d8 @excon=#<Excon::Connection:442db10 @data={:chunk_size=>1048576, :ciphers=>"HIGH:!SSLv2:!aNULL:!eNULL:!3DES", :connect_timeout=>60, :debug_request=>false, :debug_response=>true, :headers=>{"User-Agent"=>"fog/1.34.0 fog-core/1.32.1"}, :idempotent=>false, :instrumentor_name=>"excon", :middlewares=>[Excon::Middleware::ResponseParser, Excon::Middleware::Expects, Excon::Middleware::Idempotent, Excon::Middleware::Instrumentor, Excon::Middleware::Mock], :mock=>false, :nonblock=>true, :omit_default_port=>false, :persistent=>true, :read_timeout=>60, :retry_limit=>4, :ssl_verify_peer=>true, :tcp_nodelay=>false, :thread_safe_sockets=>true, :uri_parser=>URI, :versions=>"excon/0.45.1 (x86_64-linux-gnu) ruby/2.3.0", :write_timeout=>60, :host=>"route53.amazonaws.com", :hostname=>"route53.amazonaws.com", :path=>"/", :port=>443, :query=>nil, :scheme=>"https"} @socket_key="https://route53.amazonaws.com:443">>>

/usr/lib/ruby/vendor_ruby/excon/middlewares/expects.rb:6:in `response_call': InvalidClientTokenId => The security token included in the request is invalid (Fog::DNS::AWS::Error)
        from /usr/lib/ruby/vendor_ruby/excon/middlewares/response_parser.rb:8:in `response_call'
        from /usr/lib/ruby/vendor_ruby/excon/connection.rb:372:in `response'
        from /usr/lib/ruby/vendor_ruby/excon/connection.rb:236:in `request'
        from /usr/lib/ruby/vendor_ruby/fog/xml/sax_parser_connection.rb:37:in `request'
        from /usr/lib/ruby/vendor_ruby/fog/xml/connection.rb:7:in `request'
        from /usr/lib/ruby/vendor_ruby/fog/aws/dns.rb:141:in `_request'
        from /usr/lib/ruby/vendor_ruby/fog/aws/dns.rb:136:in `request'
        from /usr/lib/ruby/vendor_ruby/fog/aws/requests/dns/list_hosted_zones.rb:39:in `list_hosted_zones'
        from /usr/lib/ruby/vendor_ruby/fog/aws/models/dns/zones.rb:15:in `all'
        from /home/malcolm/sandbox/infrastructure/bin/mkserver.rb:540:in `<main>'
    

Thanks,

Malcolm

**Comment by plribeiro3000** [comment]
Hey @msommerville. Can you open this against [fog-aws](https://github.com/fog/fog-aws) instead?

Thanks!

**Comment by msommerville** [comment]
No need - found the problem - I'm a fat fingered idiot!
