### ISSUE TITLE
support new versions of fog-google

### ISSUE THREAD

**Issue by pravi** [fog/fog#3890]
Currently fog declares fog-google <= 0.1.0 and latest release of fog-google is 0.3.2. Does new versions introduce breaking changes? Is there a plan to support newer versions?

**Comment by Temikus** [comment]
Hi @pravi 

As currently written in the README:
> Currently all fog providers are getting separated into metagems to lower the load time and dependency count.

> If there's a metagem available for your cloud provider, e.g. fog-aws, you should be using it instead of requiring the full fog collection to avoid unnecessary dependencies.

> 'fog' should be required explicitly only if:

> The provider you use doesn't yet have a metagem available.
> You require Ruby 1.9.3 support.

Are you using Ruby 1.9.3? If not - you should be using and requiring `fog-google` directly instead of the whole Fog collection.

**Comment by pravi** [comment]
@Temikus I'm packaging gitlab and diaspora for debian. gitlab already moved to individual gems and has fog-google ~> 0.3. But diaspora is still requiring whole fog collection, so it is conflicting.

I have asked diaspora about their plan https://github.com/diaspora/diaspora/issues/3855#issuecomment-226730378

**Comment by icco** [comment]
@pravi Fog won't support newer versions of Fog-Google till Ruby 1.9 support is dropped in Fog 2.0

 - https://github.com/fog/fog/issues/3872
 - https://github.com/fog/fog/issues/3883
