### ISSUE TITLE
can't not bundle install on fog cause fog-core version not found

### ISSUE THREAD

**Issue by zhitongLBN** [fog/fog#3892]
Hi guys, I can't no more `bundle install` in fog because it can't found `fog-core 1.40.1`
```
Bundler could not find compatible versions for gem "fog-core":
  In Gemfile:
    fog was resolved to 1.38.0, which depends on
      fog-core (>= 1.40.1, ~> 1.40)

Could not find gem 'fog-core (>= 1.40.1, ~> 1.40)', which is required by gem 'fog', in any of the sources.
```
fog-core cannot find `1.40.1` using `.gemspec`, 
But using command-line `gem install fog-core -v 1.40.1` it went just fine, weird O.0

**Comment by geemus** [comment]
I must have done it wrong. Just pushed a commit that I think should fix it, but let me know if you still have issues.
