### ISSUE TITLE
Bug in Fog Mock?

### ISSUE THREAD

**Issue by darokel** [fog/fog#3895]
I am using Fog in a Rails app to do file uploads via a library called Carrierwave. When trying to test the upload, I've set this in an Rspec support file:

```ruby
Fog.mock!

def fog_directory
  ENV['S3_BUCKET_NAME']
end

connection = ::Fog::Storage.new(
  aws_access_key_id: ENV['S3_ACCESS_KEY'],
  aws_secret_access_key: ENV['S3_SECRET_ACCESS_KEY'],
  provider: 'AWS'
)

connection.directories.create(key: fog_directory)

Fog::Mock.reset

```

My tests return:

```
     Excon::Error::NotFound:
       Expected(200) <=> Actual(404 Not Found)
```

Because `self.data[:buckets]` is `nil` in:
```shell
/.rvm/gems/ruby-2.3.1@tutoring-api/gems/fog-aws-0.9.4/lib/fog/aws/requests/storage/shared_mock_methods.rb:30:in `verify_mock_bucket_exists'
```
```ruby
        def verify_mock_bucket_exists(bucket_name)
          require 'pry'; binding.pry
          if (bucket = self.data[:buckets][bucket_name])
            return bucket
          end

          response = Excon::Response.new
          response.status = 404
          raise(Excon::Errors.status_error({:expects => 200}, response))
        end
```

Shouldn't this be set correctly after configuring Fog mock like above?

**Comment by geemus** [comment]
Hey, I think the issue might just be in how your support file is structured.

`connection.directories.create(key: fog_directory)` should create the directory, but, `Fog::Mock.reset` will actually drop everything from mocks, which would get you back to square one (and cause the issue you are seeing). I don't think the reset should be needed there, so if you just drop that I think you will have better luck. Certainly let me know if that is insufficient.

**Comment by darokel** [comment]
Thanks for the response @geemus, but can we re-open this? The issue still occurs even after I remove the reset.

**Comment by darokel** [comment]
This is what's in `self.data`, (note I've omitted some values):

```ruby
[2] pry(#<Fog::Storage::AWS::Mock>)> self.data
=> {:acls=>
  {:bucket=>{},
   :object=>
    {"my_bucket_name_is_present_here"=>
      {"uploads/avatar/file/142/sample.png"=>
        {"AccessControlList"=>
          [{"Permission"=>"FULL_CONTROL",
            "Grantee"=>{"DisplayName"=>"me", "ID"=>"asd"}},
           {"Permission"=>"READ", "Grantee"=>{"URI"=>"http://acs.amazonaws.com/groups/global/AllUsers"}}],
         "Owner"=>{"DisplayName"=>"me", "ID"=>"adds"}}}}},
 :buckets=>{},
 :cors=>{:bucket=>{}},
 :bucket_notifications=>{},
 :bucket_tagging=>{},
 :multipart_uploads=>{}}
[3] pry(#<Fog::Storage::AWS::Mock>)>
```

**Comment by geemus** [comment]
Is there a particular need to reach down into the internals to look for this information (vs just using models/requests to look it up through existing mechanisms?)

The mock data is persistent, could it be the order your tests run in? ie does one of the tests delete the bucket? I notice in particular that the code you include here does not create that object, so it must be coming from somewhere else.

**Comment by darokel** [comment]
@geemus Sorted it out! It was my mistake. I was overriding my test environment configuration by configuring `storage: :fog` in the uploaders. Thanks for your help

**Comment by geemus** [comment]
No problem, glad you found the fix.

**Comment by strider9450** [comment]
@fourcolors what is the fix?

**Comment by taher435** [comment]
@darokel @fourcolors if you don't have `storage :fog` in your uploader then how does it work? As per the README in carrierwave, its required

https://github.com/carrierwaveuploader/carrierwave/blob/master/README.md#using-amazon-s3

**Comment by luizsignorelli** [comment]
Thanks, @darokel, I had the same issue. You can't have `storage :fog` configured in the uploader.
