### ISSUE TITLE
fog-dnsimple

### ISSUE THREAD

**Issue by weppos** [fog/fog#3896]
I started working on a new repo that pulls out the Dnsimple provider from this repo. From what I've understood, this is the direction that the library is taking.

The repo is available at https://github.com/dnsimple/fog-dnsimple

At the time being, this is mirroring the same features provided by fog/fog. My plan is to upgrade it to the DNSimple API v2 and remove the legacy code.

I did not find any sample repo to use, nor any docs or guidance on how to proceed. Let me know if I did anything wrong.

How can we move the repo to this organization?

**Comment by plribeiro3000** [comment]
:+1: for The new repo. You can find instructions [here](https://github.com/fog/fog/wiki/Create-New-Provider-from-Scratch).

Regarding The move i believe tou will need to give @geemus access so he can move.

Let me know if The Wiki page ia not enough or if you need any help.

**Comment by weppos** [comment]
Thanks for the info @plribeiro3000, I admit I didn't notice the page. Actually, is the page up-to-date? For instance, I was under the impression that fog-core didn't support anything below Ruby 2.0:

From https://github.com/fog/fog

> 'fog' should be required explicitly only if: You require Ruby 1.9.3 support.

As for the permissions, is kind of complicated. Perhaps @geemus or someone with privileges to create a repo under `fog` can create it and clone/push the repo. I can then go ahead and delete `dnsimple/fog-dnsimple` (and make it a fork of the new fog repo).

The repo has no tickets for now (I've avoided doing it on purpose), hence doesn't have to be physically moved. A clone/push should be fine. Are you ok with tat?

**Comment by plribeiro3000** [comment]
Hey @weppos . I believe a clone is ok. I can do that but won't be able to give you the right permissions.

That page should be up-to-date with the exception of fog `2.0.0`. As we started moving in that direction and dropping support for ruby `1.8.7` and `1.9.3` we got a lot of feedback from people that can't move to another version yet (e.g LTS distros that still support older versions of ruby).

I believe o forgot to update that page with this info. I will do so now. Thanks for the reminder.

I will also create the new repo here for you.

**Comment by plribeiro3000** [comment]
@weppos The repo is [here](https://github.com/fog/fog-dnsimple)

**Comment by plribeiro3000** [comment]
I just created everything. I only don't have permission to invite new people to the organization.

cc/ @geemus

**Comment by plribeiro3000** [comment]
Hmm. It seems tha wiki page is up-to-date after we got support back. I guess we need to update our README with that info. I will try to do that later.

**Comment by geemus** [comment]
@weppos I think you should have an invite with sufficient access/etc, just let me know if you need anything else there.

@plribeiro3000 as always, thanks so much for helping this along.

**Comment by plribeiro3000** [comment]
:+1:

Em seg, 11 de jul de 2016 12:14, Wesley Beary <notifications@github.com>
escreveu:

**Comment by weppos** [comment]
Thanks @geemus, it worked perfectly. Thanks @plribeiro3000 for the assistance.
About the deploy to RubyGems, what is your policy? Do you want me to deploy it and share it with you, or vice-versa?

**Comment by geemus** [comment]
@weppos I'm fine with you deploying, I would just ask that you add (at least me) to the owners list. That way should we ever have security or other issues that involved rolling out new versions (or other critical bugs) we would be able to make sure those could go out in a timely fashion.

**Comment by weppos** [comment]
No problems at all. I'll try to prep a blank release today to reserve the namespace, and I'll add you.

**Comment by geemus** [comment]
Sounds good, thanks!

**Comment by weppos** [comment]
Done! https://rubygems.org/gems/fog-dnsimple

**Comment by plribeiro3000** [comment]
@weppos Once you finish the extraction let me know so i can go over and check some minor details to ensure its ready to be added as a dependency at the main repo.

**Comment by weppos** [comment]
@plribeiro3000 I will! Feel free to add comments even right now as tickets. I'll be happy to handle them.

Also, I assume that I should provide a patch to remove the code from the current fog library. Is it correct?

**Comment by plribeiro3000** [comment]
Yeap. Once we make sure everything is ok we can merge the patch. =)

**Comment by plribeiro3000** [comment]
@weppos It seems to be ready.

Once you release it. Open a Pull Request removing the code here and adding it as a dependency.

**Comment by weppos** [comment]
@plribeiro3000 I updated the docs, and I tested it live. I confirm the `fog-dnsimple` module works correctly.

I refrained from making more changes right now, so that the module is fully compatible with the legacy codebase in the `fog` gem.

Once 1.x is released, we'll start working on the 2.x branch that will be a breaking change (in terms of required parameters) and will support our new API v2.

But for now, this gem is a drop-in replacement for the module included in `fog`. Let me know if you have any issue with the codebase. If you are 👍  I'll release fog-dnsimple 1.0 and provide a patch to remove the code from fog.

**Comment by plribeiro3000** [comment]
Sure. Go ahead and submit the patch. =)

**Comment by geemus** [comment]
Sounds good.

**Comment by plribeiro3000** [comment]
Closing this since the provider was already extracted. 

Thanks for your work on this!
