### ISSUE TITLE
403 Forbidden when reading from S3

### ISSUE THREAD

**Issue by jogaco** [fog/fog#3897]
I am using a gem which relies on fog for S3 storage I/O.
While debugging, I noticed the gem calls `Fog::Storage::AWS::Real#get_object(bucket_name, object_name)`, which in turn calls `Fog::Storage::AWS::Real#request`.
Inside this method, this snippet adds the authorization headers:

```
if @signature_version == 2
  expires = date.to_date_header
  params[:headers]['Date'] = expires
  params[:headers]['Authorization'] = "AWS #{@aws_access_key_id}:#{signature_v2(params, expires)}"
end
```

However, @signature_version is  in this case equals to 4, and thus does not add the header.
As a contrast, during put_object call, the value is 2 and the header is correctly added.

Is this a bug? How can I have the credentials added on accessing S3 for retrieving objects?

Below the error I get:
```
Excon::Error::Forbidden: Expected([200, 206]) <=> Actual(403 Forbidden)
excon.error.response
  :body          => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>F7D843A4BAC2928C</RequestId><HostId>ahostid</HostId></Error>"
  :cookies       => [
  ]
  :headers       => {
    "Content-Type"     => "application/xml"
    "Date"             => "Mon, 11 Jul 2016 10:51:26 GMT"
    "Server"           => "AmazonS3"
    "x-amz-id-2"       => "nFtRzdoefQslnL2x9H04OirOYZyvTD05iqFOKGCHzYZGFdmra5HW3CJia9rHAg9V7NZHEyRadZo="
    "x-amz-request-id" => "F7D843A4BAC2928C"
  }
...
  :status        => 403
  :status_line   => "HTTP/1.1 403 Forbidden\r\n"
```

**Comment by plribeiro3000** [comment]
Hello @jogaco . Would you be kind enough to open this against [`fog-aws`](https://github.com/fog/fog-aws) instead?
