### ISSUE TITLE
OpenNebula allocate fails when a VM name has a space

### ISSUE THREAD

**Issue by Angerslave** [fog/fog#3900]
>...
  INFO fog: compute!
"CPU=1\nVCPU=12\nMEMORY=16384\nDISK=[\"DRIVER\"=\"qcow2\", \"IMAGE_ID\"=\"206\"]\nNIC=[MODEL=\"\",NETWORK_ID=\"13\"]\nOS=[\"ARCH\"=\"x86_64\", \"BOOT\"=\"hd\"]\nGRAPHICS=[\"LISTEN\"=\"192.168.0.4\", \"PORT\"=\"5602\", \"TYPE\"=\"spice\"]\nRAW=[\"DATA\"=\"<devices>   <memballoon model='virtio'/> </devices> <memory unit='MiB'>16384</memory> <currentMemory unit='MiB'>2048</currentMemory>\", \"TYPE\"=\"kvm\"]\n\n\nNAME=My Team - Virtual Machine [Web] [Ubuntu]"
ERROR warden: Error occurred: [VirtualMachineAllocate] Error allocating a new virtual machine. Parse error: syntax error, unexpected VARIABLE, expecting EQUAL or EQUAL_EMPTY at line 11, columns 382:387
...
I just dumped the XML sent to OpenNebula to show that it doesn't escape the VM name.

**Comment by plribeiro3000** [comment]
Could you open a PR please?

**Comment by Angerslave** [comment]
Here you are
https://github.com/fog/fog/pull/3901

I'm closing this issue as there's the PR now.
