### ISSUE TITLE
Add support for minio

### ISSUE THREAD

**Issue by dcharbonnier** [fog/fog#3907]
the api is s3 compatible, should be easy https://github.com/minio/minio

**Comment by geemus** [comment]
We welcome contributions around stuff like this, so would be happy to support you in working on it. Otherwise it may be a while before one of us gets around to it. Thanks!

**Comment by dcharbonnier** [comment]
I understand, maybe some one else will be interested on allowing backup of gitlab with an opensource system

**Comment by plribeiro3000** [comment]
Closing in favor of #3644.

Thanks for your interest in improving `fog` support!
