### ISSUE TITLE
GCE integration

### ISSUE THREAD

**Issue by DaveTaboola** [fog/fog#3908]
Hey guys 
I've been working with Foreman for some while and recently started working on GCE integration (We had EC2 integration for some while and its working properly) 

I don't know if you're aware but foreman is using your library to work with various cloud providers 

I've found several issues with the current library and GCE specifically 

1. You don't support regions and subnetworks: 
**Issue:** Once a subnet is defined in foreman by default it assumes you have using the Google predefined "default" network and all the configuration comes with it.
As of both VPN and security improvement.
**Solution:** I had to change lib/fog/google/requests/compute/insert_server.rb file,
Currently I've added hard coded section that looks at the following code: 

          networkInterfaces = []
          if ! network.nil?
            networkInterface = {
              'network' => @api_url + @project + "/global/networks/#{network}",
              'subnetwork' => @api_url + @project + "/regions/<region_name>/subnetworks/<subnetwork_name>"
            }
            networkInterface['accessConfigs'] = [access_config] if access_config
            networkInterfaces << networkInterface
          end

The hard coded area specifies that we're using the region name (which is specified in the GCE plugin configuration) and subnetwork specified 

2. custom METADATA:
**Issue:** As google instances are blocked for root access, and therefor foreman is blocked of running finish script we had to open it at least temporarily, and the best way to do so (while maintaining the base google images, at least the RedHat and CentOS) was adding metadata for the GCE to run a script as the instance comes up.

**Solution:** I had to add the following def on lib/fog/google/models/compute/server.rb

        def allow_ssh
          if self.metadata.nil?
            self.metadata = Hash.new("")
          end

          if !self.metadata["startup-script"]
            self.metadata["startup-script"] = ""
          end

          if !self.metadata["startup-script"].empty?
            self.metadata["startup-script"] += "\n"
          end

          self.metadata["startup-script"] += "#!/bin/bash\n/bin/sed -i 's/PermitRootLogin no/PermitRootLogin yes/g' /etc/ssh/sshd_config\nservice sshd restart"
        end

and obviously call it later on in the code

**Comment by DaveTaboola** [comment]
forgot to mention i think we also need to add support for custom metadata for GCE 
I know i'd use it with Foreman but i think it'll be used by others as well

**Comment by icco** [comment]
Could you refile this in https://github.com/fog/fog-google/? That way it'll get more eyes.

Also, which foreman are you? It looks like there are four major projects with that name. Including a link to your code would be helpful.

**Comment by geemus** [comment]
Closing here, but please do re-open on fog-google and discuss!
