### ISSUE TITLE
Add Fog Azure RM to gemspec

### ISSUE THREAD

**Issue by bilal-naeem-confiz** [fog/fog#3910]
Pull Request #3909 @plribeiro3000 
Ruby versions less than 2.0 are not supported by fog-azure-rm due to multiple conflicts.
Shindo unit tests are not supported. Minitest unit tests are used.

**Comment by plribeiro3000** [comment]
Hmmm. Ruby version is an issue. Right now we still support old ruby versions. If we put `fog-azure` as a dependency it will break for a lot of users that use fog with old ruby versions.
Isn't there a way to support ruby 1.9?

**Comment by bilal-naeem-confiz** [comment]
It appears that Ruby v1.9.3 can be supported by modifying the source code to some extent. Previous versions of Ruby (i.e. < 1.9.3) cannot be supported due to conflicts arising in the dependent gems.
Please let me know if providing support for v1.9.3 is enough or if we have to provide support for previous versions as well.

**Comment by bilal-naeem-confiz** [comment]
We can not support ruby versions below v2.0 because the azure sdk that we are using only supports for ruby v2.0 and above as mentioned here `https://github.com/Azure/azure-sdk-for-ruby/blob/master/README.md`

**Comment by abbas-sheikh-confiz** [comment]
@plribeiro3000 is there any plan to deprecate Ruby v1.9 support from Fog?

**Comment by plribeiro3000** [comment]
Yes. There is but there are many moving pieces we need to take in consideration. There are some use cases of `fog` that are still using old versions of ruby (even `1.8.x`). So we can't just drop support.
We have it on radar but didn't manage to find the right time/way to go. See #3872

**Comment by plribeiro3000** [comment]
Would it be to big of a refactoring to do plan http calls instead of using the Azure SDK gem?

**Comment by abbas-sheikh-confiz** [comment]
Hi @plribeiro3000,

Yes, that would be a lot of effort doing plain http calls. We depend heavily on Azure Ruby SDK and doing http calls would be 
- Re inventing the wheel
- It would not add any new functionality for end users and hence no business value
- Lot of rework required just to support older ruby version for Fog that would be deprecated in near  future

Regards,

**Comment by geemus** [comment]
I think for the time being we may just be in a place where we would want to have it as a standalone-gem without including in fog gemspec? That should make it compatible/usable, just not automatically installed (this is the direction we think we want to head anyway). This provides more freedom/flexibility and helps limit the total dependencies users need to pull in. The fog gemspec including everything has as much to do with history/legacy as anything else, we've continued with that to try and maintain backwards compatibility, but I don't think it is tenable to do this forever.

**Comment by plribeiro3000** [comment]
I'm gonna close this issue in favor of #3913 so we can focus all the conversation in just one place.

Thanks for your work and help on this matter.
