### ISSUE TITLE
Azure storage support in Fog

### ISSUE THREAD

**Issue by abbas-sheikh-confiz** [fog/fog#3913]
Hi @geemus, @plribeiro3000 ,

As discussed in https://github.com/fog/fog/issues/3910, we can not add fog-azure-rm right away to fog gemspec. This would require either

1) Fog deprecates support for ruby v1.9.3 OR
2) We bypass Azure ruby SDK(which requires ruby v2.x) and do direct API calls to Azure. BTW, it requires a lot of rework.

However, we have a time pressing need to support Fog Azure storage via Fog gemspec. Are you guys OK if we release Azure storage ONLY gem which supports ruby version >= 1.9.3. It will help us utilize Azure storage support via Fog in [cloud foundry](https://github.com/cloudfoundry)

This requires minimal effort on our end and we will create a separate branch for this change. Meanwhile, user still has the option to use full support fog-azure-rm as independent gem and its active development continues. We will update Fog to take leverage of complete Azure services(fog-azure-rm) when 1 is complete. 

If you are OK with this, we will get it done. Please let us know.

Thanks,
cc: @NingKuang @AbelHu

**Comment by plribeiro3000** [comment]
@abbas-sheikh-confiz Yeah, Releasing only the Storage service supporting ruby `1.9.3` would be awesome. 🏆 
How do you plan to release this?
I can see that `fog-azure-rm` was already released so you can't just drop support of all of its features. Are you planning to create another gem just for the Storage Service?

PS: Thanks for _bearing_ with me on this. All the users that need to use fog with ruby `1.9.3` appreciates it very much. 👍

**Comment by geemus** [comment]
Hey, that should probably be fine. That said, I didn't think that this would make it not possible for you to use this as you wanted. Basically I think fog and fog-azure would work together (if you are in ruby 1.9.3), but might not work for everyone. Could you just require the two separately?

**Comment by AbelHu** [comment]
@abbas-sheikh-confiz I think @geemus 's idea looks good. How do you think?

**Comment by abbas-sheikh-confiz** [comment]
Hi @geemus , @plribeiro3000,

Following is our 2 step plan to make this happen.
Step 1:
We will fork and do Azure storage ONLY support. Verify this for ruby version >= 1.9.3. Have this support available as a separate branch and gem.
Azure storage support from fog-azure-rm will be stripped. So that effort for storage is not duplicated. Anyone wanting to use Fog Azure storage will use Fog Azure storage gem instead. We will update the documentation to reflect this.

Note: This step is subject to @AbelHu team, adding support for ruby 1.9.3 in Azure storage gem.

Step 2:
Add entry in fog for Fog Azure storage compatible with ruby >=1.9.3. This will enable @AbelHu , @NingKu to use Fog Azure storage within cloud foundry.

Please let us know what you think. We will get it done.

Thanks,

**Comment by abbas-sheikh-confiz** [comment]
Hi @plribeiro3000 , @geemus ,

I also have one other suggestion. That we release fog-azure-rm without ruby 1.9.3 support, and add 'allow_failures' entry in travis config file for ruby 1.9 just like entry for jruby-head. (https://github.com/fog/fog/blob/master/.travis.yml#L22)

Currently Azure support is NOT available via Fog gem therefore benefits of doing this are
- It will not break anything for people already using Fog gem for ruby version >=1.9.3.
- People using Fog gem for ruby version 2.x have added advantage that they can use Fog Azure out of the box
- We do not need to maintain Fog Azure storage separately 
- Cloud Foundry can use Azure storage via Fog gem with minimum effort

The only downside, I see is Fog build failing for ruby 1.9 which we can fix via travis config update mentioned above.

Please let us know what you think? We will do the necessary.

Regards,

**Comment by plribeiro3000** [comment]
Your 2 steps plan sounds good.
I'm not sure about allowing runy 1.9.3 failures on Travis. Any code that is
not 1.9.3 supported will silent break and we wont notice until we get users
complaining about it.
Lets start with The fog azure storage gem and later we can decide which
path to follow if needed. WDYT?

Em ter, 20 de set de 2016 01:38, abbas-sheikh-confiz <
notifications@github.com> escreveu:

**Comment by geemus** [comment]
I'm fine either way. Splitting things out seems likely to be a pain to do and maintain. So if you are willing to accept that it is only > 1.9.3, marking the failure just in the azure repo seems reasonable to me. This should allow this to work by itself for people greater than 1.9.3 without a lot of work from either us (to drop 1.9 support) or you to split stuff out.

**Comment by NingKuang** [comment]
Thanks @plribeiro3000 @geemus ! I think @abbas-sheikh-confiz's proposal is an ideal solution for our current situation. So far customers involved in this project, including Cloud Foundry are all good with only > 1.9.3.  We will monitor customer's usage and feedback closely. Thanks.

**Comment by plribeiro3000** [comment]
No worries. Thank you all for _bearing_ with us on this. `1.9` support has been on our toes for a while now and we definitely know the pain of maintaining support for it. 👍

**Comment by abbas-sheikh-confiz** [comment]
Hi @plribeiro3000, @geemus ,

@plribeiro3000 just to clarify @NingKuang meant adding fog-azure-rm support for ruby 2.x. Since geemus is fine with either approach i.e. complete fog-azure-rm with ruby 2.x support OR storage only(>=1.9.3+)support. We are going with fog-azure-rm support for ruby 2.x. Knowing that it will break for ruby 1.9.3.

We have generated [PR](https://github.com/fog/fog/pull/3909). Please merge the PR. Please note that we have done compliance with Fog standards as suggested [here](https://github.com/fog/fog/issues/3904#issuecomment-239829364). 

Secondly, whats the time-line for Fog gem release that includes fog-azure-rm?

Thanks for you understanding.

Regards,

**Comment by plribeiro3000** [comment]
I think there is a miss communication issue here. We can't drop support for `1.9` and adding `fog-azure-rm` with only ruby `>2.x` support means `fog` is gonna break for a lot of people.

@geemus meant to mark ruby failures for `1.9.3` on `fog-azure-rm` repo only. We cannot accept that PR as is. We just can't drop support for ruby `1.9` yet.

The only 2 options here are:
* `fog-azure-rm` as standalone provider with only ruby `> 2.0` support
* Storage` service only with `1.9` support

The one implemented is not an option.

**Comment by geemus** [comment]
Yeah, sorry for any confusion. I think @plribeiro3000 describes the two options accurately. We can't just merge it without breaking support, but if it is standalone, anyone on 2.0+ could include it themselves (such and CloudFoundry). Does that make sense?

**Comment by NingKuang** [comment]
Hi @plribeiro3000  @geemus : Just to confirm your statement:
1. For Azure storage only - setup a separate branch from fog-azure-rm, supporting 1.9.3, and merge as Azure provider to Fog
2. For  fog-azure-rm   - two options A. only supporting 2.0, release as stand alone package;  B. supporting 1.9 (or dropping the dependency on Ruby), and later merge as Azure provider 
Is this the correct expectation? Thanks.

**Comment by geemus** [comment]
@NingKuang yes, although the dropped dependency for 2.B. would be on the azure ruby sdk (not on Ruby in general).

Also, post fog-2.0, we may just stop merging more providers and have everything be standalone anyway (we have discussed this possibility). I think standalone is good and probably the way of the future, so I would certainly consider this as a great and simple possibility.

**Comment by NingKuang** [comment]
Thanks @geemus for the clarification.  Do you have a rough idea on how long you will continue supporting Ruby SDK 1.9.3? In addition, when will the next new release scheduled?  Thanks.

**Comment by geemus** [comment]
We haven't set an exact timeline for dropping 1.9, it may tie into when we manage to split out the rest of the projects (and it's hard to know how soon that might occur.

We can make another release just about any time. We usually try to do it about once a month, but I think I am a little behind at this point. Do you need a new release soon?

Thanks.

**Comment by AbelHu** [comment]
@plribeiro3000 New fog-azure-rm 0.1.1 was released yesterday. Now users can use standard fog storage interfaces to operate Azure storage. Could you help to add Azure storage in this [page](http://fog.io/about/supported_services.html)? Thanks.

**Comment by plribeiro3000** [comment]
@AbelHu Just to confirm, are you guys following `semver`?

To add `fog-azure-rm` to that page you just need to send a PR to https://github.com/fog/fog.github.com and you are golden.

**Comment by plribeiro3000** [comment]
I believe i can close this PR now, right?

**Comment by AbelHu** [comment]
@plribeiro3000 For storage, all interfaces in fog-azure-rm are as same as others. You can check the [docs](https://github.com/fog/fog-azure-rm/blob/master/lib/fog/azurerm/docs/storage.md#create-a-storage-container)
We will create a doc PR to add Azure storage.

**Comment by plribeiro3000** [comment]
@AbelHu But does it follow [semver](http://semver.org/)?

Docs are not as important as following semantic versioning.

**Comment by zeeshan-arshad-confiz** [comment]
Hi @plribeiro3000,

Thanks for your feedback on this.

fog-azure-rm is not using semantic versioning, instead we are using incremental numbering scheme for versioning. 
I do not see any guideline for fog gem versioning [here](https://github.com/fog/fog/wiki/Create-New-Provider-from-Scratch). Is semver mandatory for a fog gem?

Please let us know.

Thanks,

**Comment by plribeiro3000** [comment]
Yeah. That web page is for creation only. We don't have the guideline for maintenance anywhere yet.
We do use `semver` at `fog` thus you guys will need to follow it as well. 
Once we break all providers a part we won't need this anymore and each provider team will be able to choose its standards but as of now we need to use the same across all gems.

**Comment by abbas-sheikh-confiz** [comment]
Hi @AbelHu/ @NingKuang,

If I understand it correctly, you are asking to add fog-azure-rm to fog [gemspec](https://github.com/fog/fog/blob/master/fog.gemspec) and update the documentation [here](http://fog.io/about/supported_services.html)?

Please confirm.

Thanks,

**Comment by geemus** [comment]
I guess I don't ultimately care too much what versioning is used. I prefer semver and use it, just as some of my other preferences are reflected in the broader codebase, but other repos can do whatever works for them I think.

@abbas-sheikh-confiz an update to those docs would be great, they live here: https://github.com/fog/fog.github.com. I thought, given some of the other dependencies and 1.9 conflicts that we were going to leave it as standalone for now (vs adding to the fog gemspec)? Perhaps I misremember or misunderstand though.

**Comment by plribeiro3000** [comment]
Closing this since [`fog-azure-rm`](https://github.com/fog/fog-azure-rm) was already extracted.

Missing only PR to add it as a dependency to `fog`.

**Comment by geemus** [comment]
Thanks!
