### ISSUE TITLE
Fog transfer acceleration endpoints

### ISSUE THREAD

**Issue by ilyakatz** [fog/fog#3918]
When using `Fog::Storage` with `AWS`

Method `put_object_url` does not support [AWS Transfer Acceleration](https://aws.amazon.com/blogs/aws/aws-storage-update-amazon-s3-transfer-acceleration-larger-snowballs-in-more-regions/).

Usually, you can you can upload files to `https://s3.amazonaws.com/bucketname`, however, with transfer acceleration, it needs to be `https://bucketname.s3-accelerate.amazonaws.com`, hence the parameter [`bucket_name`](https://github.com/fog/fog/blob/master/lib/fog/internet_archive/requests/storage/put_object_url.rb#L18) becomes superfluous

**Comment by plribeiro3000** [comment]
Hey @ilyakatz. Thanks for submitting this ticket.
Would you be kind of opening this against [`fog-aws`](https://github.com/fog/fog-aws) instead?

Thanks!

**Comment by ilyakatz** [comment]
Ah, sorry about that! Opened https://github.com/fog/fog-aws/issues/303

**Comment by plribeiro3000** [comment]
No worries man. Thanks!
