### ISSUE TITLE
Getting LoadError: cannot load such file -- fog/digitalocean/compute_v2 on master

### ISSUE THREAD

**Issue by tameem92** [fog/fog#3924]
Hey, 

I recently updated to the laster master and i am seeing this error. 

LoadError: cannot load such file -- fog/digitalocean/compute_v2

I believe the digital ocean part has been split into its own gem, but there have been a bunch of recent changes to clean up digital ocean code but seems like its still broken. Any ideas as to the cause? I currently have both 'fog' and 'fog-digitalocean' gems installed.

**Comment by plribeiro3000** [comment]
Which versions of `fog`, `fog-digitalocean` and `fog-core` are you using?

**Comment by plribeiro3000** [comment]
And which service are you trying to use?

**Comment by tameem92** [comment]
fog-digitalocean ->  fog-digitalocean-0.2.0.gem
fog   -> commit 5cb43829c0edeb7885f8466597b484f8fc37fbf7 (Tied to latest commit) 
fog-core  ->   (~> 1.42)

I am receiving the error on making a connection to digital ocean:
Fog::Compute.new(provider: 'DigitalOcean', version: 'v2', digitalocean_token: <toke>)

**Comment by plribeiro3000** [comment]
Do you have a stacktrace?

**Comment by tameem92** [comment]
Here is the stack trace: 
LoadError: cannot load such file -- fog/digitalocean/compute_v2
        from /shared/bundle/ruby/2.0.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
        from /shared/bundle/ruby/2.0.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `block in require'
        from /shared/bundle/ruby/2.0.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /shared/bundle/ruby/2.0.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
        from /shared/bundle/ruby/2.0.0/gems/fog-core-1.42.0/lib/fog/compute.rb:38:in `new'
        from (irb):27
        from /shared/bundle/ruby/2.0.0/gems/railties-3.2.22.2/lib/rails/commands/console.rb:47:in `start'
        from /shared/bundle/ruby/2.0.0/gems/railties-3.2.22.2/lib/rails/commands/console.rb:8:in `start'
        from /shared/bundle/ruby/2.0.0/gems/railties-3.2.22.2/lib/rails/commands.rb:41:in `<top (required)>'
        from script/rails:5:in `require'
        from script/rails:5:in `<main>'

**Comment by tameem92** [comment]
Seems like there were some changes made to fog-core that are needed. Updated to v1.43.0 seems to have solved the problem. Specifically commit: 

https://github.com/fog/fog-core/commit/b5683a589b4720c3af25fe0acbad4b94190d15ba

**Comment by plribeiro3000** [comment]
I'm glad you figure it out. Closing.

Thanks!
