### ISSUE TITLE
Is there a configuration setting for the AWS provider to adjust the url scheme for S3 buckets?

### ISSUE THREAD

**Issue by stevenmaguire** [fog/fog#3927]
There is a [closed issue](https://github.com/fog/fog/issues/3318) related to accessing buckets with virtual host over HTTPS. In my experience accessing the bucket using the alternate naming scheme works well over https. Is there an existing config to use the alternate URL pattern?

`https://my.production.bucket.s3.amazonaws.com/myObject` has problems

`https://s3.amazonaws.com/my.production.bucket/myObject` works

Any thoughts?

**Comment by plribeiro3000** [comment]
Hello @stevenmaguire. Could you open this same ticket against [`fog-aws`](https://github.com/fog/fog-aws) instead?
This way the experts on the `AWS` portion of `fog` will be more likely to see your issue.

Thanks!

**Comment by stevenmaguire** [comment]
Of course!
