### ISSUE TITLE
Issue with loading credentials from yaml file

### ISSUE THREAD

**Issue by tameem92** [fog/fog#3929]
Hey Guys, 

I am currently seeing an issue loading up the credentials file. It works for Ruby 2.1 but doesn't work for Ruby2.2.5. 

On Ruby 2.2.5: 
Fog::Core::Utils.prepare_service_settings(YAML.load_file(credentials_path))
```
[4] pry(main)> Fog::Core::Utils.prepare_service_settings(YAML.load_file(credentials_path))
=> {:":default"=>
  {:":aws_access_key_id"=>"xxxxxxxx",
   :":aws_secret_access_key"=>"xxxxxxxx",
   :":rackspace_api_key"=>"xxxxxxxx",
  }
```

On ruby 2.1.10: 
```

{ :default=>{ 
   :aws_access_key_id=>"xxxxxxx", 
   :aws_secret_access_key=>"xxxxxxx"
}


```

As you can see the keys on ruby 2.2.5 are messed up after parsing the credentials hence, it breaks when you do Fog.credentials. 

Fog           =>  fog (1.38.0)
Fog-Core =>  fog-core (~> 1.32)

**Comment by tameem92** [comment]
Seems like the function "YAML.load_file(credentials_path)" is the one having issues in loading the credential files in ruby2.2. Its not handling the symbols as strings properly.

**Comment by tameem92** [comment]
Updating safe_yaml and providing the :deserialize_symbols options seems to be resolving the issue.  

YAML.load_file(credentials_path, :deserialize_symbols => true)

**Comment by tameem92** [comment]
Seems like an issue with safe_yaml gem which we are using in our project.

**Comment by plribeiro3000** [comment]
Ouch. Thanks for the feedback.

I'm glad you solved your issue.
