### ISSUE TITLE
Regex support in file search?

### ISSUE THREAD

**Issue by nc-zhux** [fog/fog#3939]
I have some file with key pattern `dir_name/not_sure_dir_name/dir_name/file_name` So, I'm wondering if I can use some regex to represent the `not_sure_dir_name`? I tried use `files.all(:prefix => Regex' but it doesn't work. Is it not supported yet or I'm using it wrong?

**Comment by plribeiro3000** [comment]
Which provider are you using? `local`?

**Comment by nc-zhux** [comment]
aws
I found the prefix was compared as string in here:`object['Key'][0...prefix.length] != prefix`.
So I'm wondering maybe the regex is not supported yet

**Comment by plribeiro3000** [comment]
Could you please open this issue against [`fog-aws`](https://github.com/fog/fog-aws) instead?

All the aws experts follow that repo and are likely to answer you faster over there.

Thanks!

**Comment by nc-zhux** [comment]
Oh, ok. Thanks!

**Comment by plribeiro3000** [comment]
You are welcome. =)
