### ISSUE TITLE
fog-softlayer repository is gone?

### ISSUE THREAD

**Issue by cphrmky** [fog/fog#3941]
has this repo been deleted from the org?  or just made private for some reason?

last I knew it existed and I had commit access to it, it now appears missing as far as I can tell

the fog gem still depends on it, and the gem is still being hosted on rubygems.org

what gives?

**Comment by plribeiro3000** [comment]
Something weirdo happened. Even the softlayer group is gone.

@geemus Any words on this?

**Comment by geemus** [comment]
What? I don't know, this is news to me.

I see a fog-softlayer group still (it's just private).

@fog/fog-softlayer any chance somebody in this group could help us clear up the mystery?

**Comment by cphrmky** [comment]
Any word on this?  I've got changes I'd like to push to the project I
started a few years ago and have been maintaining ever since...

**Comment by tokengeek** [comment]
According to the access log @fernandes triggered a repo delete 29 days ago.

https://github.com/organizations/fog/settings/audit-log?utf8=%E2%9C%93&q=repo%3Afog%2Ffog-softlayer

**Comment by plribeiro3000** [comment]
@cphrmky I just created the repo back. But i dont have access to the @fog/fog-softlayer group to give access.

@geemus Could you give access to the group so @cphrmky can push master again?

We need at least the repo back since we still have it as a dependency of `fog`.

**Comment by tokengeek** [comment]
@plribeiro3000 @cphrmky - I've assigned the group to the recreated repo so you should both have access.

**Comment by fernandes** [comment]
hey guys... today I received a mail that @plribeiro3000 created the repo, and I was subscribed to it

when I saw, the repo was wiped, then I asked @plribeiro3000 on skype about it, and he pointed me to this issue

honestly I have *NO* idea what happened, but as the logs don't lie, I made some sh*t on my side, my apologies @cphrmky @plribeiro3000 @geemus @tokengeek (I have 2FA, don't know if some authorized app did it, usually I don't give repo admin, whatever now it's gone 😢 )

shame on me 😢

**Comment by geemus** [comment]
Well, though the mystery was not solved, sounds like we have back what we need. I'll close this, but please let me know if anybody needs anything further. Thanks!
