### ISSUE TITLE
Change hostname by different groups

### ISSUE THREAD

**Issue by Catskan** [fog/fog#3947]
Hi,

I'm running Fog 1.3.4 and I want deploy mny images with a sysprep files.

I have 3 differents groups corresponding to 3 rooms (Geneve, Lisboa, Paris) and computer's hostname change into these 3 differents rooms.
Geneve : 01-G, 02-G, ...
Lisboa : 01-L, 02-L, ...
Paris : 01-P, 02-P, ...

Can I choose the name syntax group by group for that fog change hostname with correct name for each group ?
I found hostname change option in Fog settings but not separatly per group.

Thanks you :)

**Comment by plribeiro3000** [comment]
@catskan which provider are you using?
How are you deploying this files?

**Comment by Catskan** [comment]
I using Fog client 0.11.9 and Fog server 1.3.4.

My clients are only Windows 7 x64.

I create an master image (Geneve) with all of software and fog client. I want to deploy this on my room. Fog client can register and I add manualy computers into the fog group. If it is that you want to know.

**Comment by plribeiro3000** [comment]
Hmmm. I'm not sure I follow. Fog is just a ruby client. Which provider are you using? And by that I mean the server you are uploading the files.

**Comment by plribeiro3000** [comment]
Closing by lack of feedback. Feel free to reopen and/or comment back if you want to continue the discussion.

**Comment by geemus** [comment]
Thanks!
