### ISSUE TITLE
Creating instances in AWS fails very offen

### ISSUE THREAD

**Issue by phanindrakalva** [fog/fog#3949]
We are seeing below error when ever we try to create instances in AWS. Sometime it succeeds but most of the time it is throwing error. If we try to create 5 nodes it creates, 1 or 2 and fails on other.

> Failure/Error: conn.servers.length
>     Excon::Error::Socket:
>        XML declaration allowed only at the start of the document (Nokogiri::XML::SyntaxError)

```
      Fog::Compute.new(
        :provider               => 'AWS',
        :region                 => @region,
         :use_iam_profile              => true
      )
```

 ```
  def valid_connection?(conn)
      conn.servers.length
      true
    rescue Excon::Errors::Forbidden, Excon::Errors::Unauthorized, Fog::Compute::AWS::Error
      false
    end
```

I tried to enable the debug logging as well but it does not show much info.

**Comment by plribeiro3000** [comment]
Would you open this against [fog-aws](https://github.com/fog/fog-aws) instead please?

The experts on aws will respond faster on that repo.

Thanks!

**Comment by phanindrakalva** [comment]
Ok, created in fog-aws. 

https://github.com/fog/fog-aws/issues/352

**Comment by plribeiro3000** [comment]
Awesome! Thanks!
