### ISSUE TITLE
'gem install fog' fails on 1.39.0

### ISSUE THREAD

**Issue by don-code** [fog/fog#3951]
The release of fog 1.39.0 seems to break a `gem install` on a clean gemset - the `fog` binary conflicts with one provided by `fog-digitalocean`.

This is reproducible by creating a new, empty rvm gemset and running `gem install fog` in both Ruby 1.9.3 and 2.2.1. Accepting the conflict (e.g. letting `fog`'s binary override `fog-digitalocean`'s binary) manually works; however, this causes a failure in automation that doesn't provide any input (CI, Chef runs, etc.)

Expected behavior is that `gem install fog` should run without user intervention.

https://gist.github.com/don-code/687e3fe503344910b8943e9422a45656 shows the output of `gem install fog` after selecting to override the executable. This is for 2.2.1 specifically, but things look similar on 1.9.3.

**Comment by geemus** [comment]
Thanks for the heads up, let me dig in.

**Comment by geemus** [comment]
Hmm. I've tried to fix this via:

1. removing `bin/fog` from fog-digitalocean and releasing
2. updating `fog/fog` to require new fog-digitalocean that does NOT have this `bin/fog` and releasing

Hopefully this will solve it, but I haven't seen this particular error before, so I'm not sure if it's sufficient or not. Just let me know (I don't have rvm setup, so I can't easily follow your instructions).

**Comment by don-code** [comment]
Confirming that `gem install fog` works without manual input on version 1.40.0. Thanks for the quick response!

**Comment by geemus** [comment]
@don-code thanks for the detailed report and confirmation. I was worried it was going to require yanking or other craziness, so I'm quite glad to hear it was simple (though I think we may need to do more work so that fog-digitalocean has what it needs/wants, this at least prevents the big issue we saw today).
