### ISSUE TITLE
fog-google version

### ISSUE THREAD

**Issue by giacomomacri** [fog/fog#3953]
Hi all,

I've a simple question: 

why in fog 1.34.0 the required fog-google is >= 0.0.2 , and in fog 1.40.0 the required fog-google has to be <= 0.1.0 

Why a new version of fog requires a really old version of fog-google ?

Thanks in advance
Giacomo

**Comment by icco** [comment]
fog-google dropped support of ruby 1.9 at version 0.1.1, which fog still supports.

It's generally suggested you just include the providers you need, and not the entire fog gem. https://github.com/fog/fog-google talks about this.
