### ISSUE TITLE
Unable to require metagem

### ISSUE THREAD

**Issue by dolvany** [fog/fog#3959]
dolvany:dnssync dolvany$ gem list | grep fog
fog (1.40.0)
fog-aliyun (0.1.0)
fog-atmos (0.1.0)
fog-aws (1.3.0)
fog-brightbox (0.11.0)
fog-cloudatcost (0.1.2)
fog-core (1.44.1)
fog-digitalocean (0.3.0)
fog-dnsimple (1.0.0)
fog-dynect (0.0.3)
fog-ecloud (0.3.0)
fog-google (0.1.0)
fog-json (1.0.2)
fog-local (0.3.1)
fog-openstack (0.1.20)
fog-powerdns (0.1.1)
fog-profitbricks (3.0.0)
fog-rackspace (0.1.5)
fog-radosgw (0.0.5)
fog-riakcs (0.1.0)
fog-sakuracloud (1.7.5)
fog-serverlove (0.1.2)
fog-softlayer (1.1.4)
fog-storm_on_demand (0.1.1)
fog-terremark (0.1.0)
fog-vmfusion (0.1.0)
fog-voxel (0.1.0)
fog-vsphere (1.9.2)
fog-xenserver (0.3.0)
fog-xml (0.1.3)
dolvany:dnssync dolvany$ ruby -e 'require "fog"'
dolvany:dnssync dolvany$ ruby -e 'require "fog-aws"'
/Users/dolvany/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- fog-aws (LoadError)
	from /Users/dolvany/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
dolvany:dnssync dolvany$

**Comment by dolvany** [comment]
I've tried this on three different systems now, including the official docker ruby container image. All will load the fog gem, but none will load the metagems, including fog-aws and fog-dynect. Is it a problem with the command I am using to test gem loading? Is the suggestion to use the metagem bad advice?

**Comment by geemus** [comment]
I'm not sure off hand. You shouldn't need to require both fog and fog-aws though (if you just need fog-aws, you can skip the fog require). Do you need all of the gems or just aws?

**Comment by dolvany** [comment]
Just aws, but to be clear, I am not attempting to use both. The output demonstrates that `require 'fog-aws'` does not work, while `require 'fog'` does work.

**Comment by geemus** [comment]
Ah, I misread it as requiring the two sequentially.

I think what you want is `require 'fog/aws'` instead, for historical reasons (though I either didn't realize or forgot that fog-aws doesn't work in that way).

@lanej fwiw, I can't remember if we made this choice explicitly or it is coincidental. Do you recall?

**Comment by lanej** [comment]
@geemus I believe you are right.  Before it was extracted, it would have been at `lib/fog/aws.rb` so internally it was required as `fog/aws`.  I think Bundler tries both `fog-aws` and `fog/aws`.   It costs us very little to support both methods.

**Comment by dolvany** [comment]
I don't use bundler... not even sure what bundler does. Here is the thing that misled me. It implies that I should use `require 'fog-aws'` instead of `require 'fog'`.

```
------------------------------
Thank you for installing fog!

IMPORTANT NOTICE:
If there's a metagem available for your cloud provider, e.g. `fog-aws`,
you should be using it instead of requiring the full fog collection to avoid
unnecessary dependencies.

'fog' should be required explicitly only if:
- The provider you use doesn't yet have a metagem available.
- You require Ruby 1.9.3 support.
------------------------------
```

**Comment by geemus** [comment]
@lanej I would be in favor of supporting both, particularly if it is low effort to get there.

@dolvany thanks for the feedback, we'll see what we can do.
