### ISSUE TITLE
json 2.0.2 not supported (Ruby 2.4.1)?

### ISSUE THREAD

**Issue by wiicode** [fog/fog#3966]
Hi, 
Relatively new to this, but ran into this error while running a script using fog:
 `raise_if_conflicts': Unable to activate fog-1.41.0, because json-2.0.2 conflicts with json (< 2.0, >= 1.8) (Gem::ConflictError)
In process of debugging but wanted to post it in case it's a bug.

**Comment by icco** [comment]
Could you post the Gemfile of the project you're including fog in? Sounds like you have dependencies that don't agree.

**Comment by wiicode** [comment]
That would make sense.  I may have mistakenly thought it was coming from within Fog.   If you happen to know a workaround, I'll gladly take it. The tool is https://gist.github.com/miketheman/f5103e1eff741a8e3a5b

**Comment by icco** [comment]
I'd suggest a gemfile of https://gist.github.com/icco/9fc761e53571f29598d2d58ae59c8712#file-gemfile (note I also slightly tweaked the requires at the head of the ruby file to be more specific), and then running `bundle install` to install the dependencies, and `bundle exec ruby ./clouddns_to_route53.rb` to make sure you execute with the right versions of things.

**Comment by geemus** [comment]
Thanks!

**Comment by ddfreyne** [comment]
fog historically depended on `json (< 2.0, >= 1.8)` for Ruby 1.9.x compatibility, but that no longer is the case. #3971 upgrades JSON, so this issue should go away!
