### ISSUE TITLE
fog-dnsimple's executable "console" conflicts with fir-cli

### ISSUE THREAD

**Issue by Coeur** [fog/fog#3968]
```
Updating fog
Fetching: fog-core-1.45.0.gem (100%)
Successfully installed fog-core-1.45.0
Fetching: fog-digitalocean-0.3.0.gem (100%)
Successfully installed fog-digitalocean-0.3.0
fog-dnsimple's executable "console" conflicts with fir-cli
Overwrite the executable? [yN]  n
ERROR:  Error installing fog:
	"console" from fog-dnsimple conflicts with installed executable from fir-cli
```

What is the recommendation to solve this?
fir-cli is from https://github.com/FIRHQ/fir-cli

**Comment by plribeiro3000** [comment]
Hello @Coeur. Could you open this at [`fog-dnsimple`](https://github.com/fog/fog-dnsimple) instead please?

I believe the executable name is too generic thus why it is conflicting. We might have to rename it to something more specific.

**Comment by Coeur** [comment]
@plribeiro3000 sure: https://github.com/fog/fog-dnsimple/issues/2

**Comment by plribeiro3000** [comment]
Awesome. Thanks!
