### ISSUE TITLE
can not find aliyun in fog installation package

### ISSUE THREAD

**Issue by demonwy** [fog/fog#3969]
Hi,
   I intend to use aliyun fog provider in our product, found it in the [fog github group](https://github.com/fog/fog-aliyun)
  So I install fog locally, but could not found aliyun plugin. 

OS: Ubuntu 14.04
Install: gem install fog
Fog Version: 1.41.0

**Comment by plribeiro3000** [comment]
Try to use `fog-aliyun` in your Gemfile instead.

And please open this against the `fog-aliyun` repo instead so the collaborators can fix it.

Thanks!
