### ISSUE TITLE
Hello fog-backblaze (WIP)

### ISSUE THREAD

**Issue by Paxa** [fog/fog#3972]
I started to create integration for Backblaze B2 Cloud Storage, source code: https://github.com/Paxa/fog-backblaze

I'm new to fog development, please help to review

Features:
* Simple operations support: `*_object`, `*_bucket`
* Collections and models: `directories`, `files`
* Token Cache - place to cache temporary values (configurable and extendable)
* Fast `bucker_id` lookup - most of command requires `bucker_id` not `bucker_name` and `bucket_id` usually doesn't change. We can specify it as `b2_bucket_name` & `b2_bucket_id`

Questions:
* ~~how to use fog-json? I can't find documentation~~
* ~~where to find specification on return values of each command, such as `put_object` and `head_object`?~~
* Is there any common way to keep temporary values? (obtained authentication token)? (I created my own https://github.com/Paxa/fog-backblaze/blob/master/lib/fog/backblaze/token_cache.rb)
* ~~anybody still use ruby 1.*? (about https://github.com/fog/fog/wiki/Create-New-Provider-from-Scratch)~~

**Comment by icco** [comment]
- Most providers are dropping support for unsupported Rubies. 
 - fog-json is mainly a wrapper around multi-json. It has two functions: https://github.com/fog/fog-json/blob/master/lib/fog/json.rb
 - Usually the models have similar interfaces, and requests are platform dependent. So most file apis look like https://github.com/fog/fog-aws/blob/master/lib/fog/aws/models/storage/files.rb, but they call individual request files https://github.com/fog/fog-aws/blob/master/lib/fog/aws/requests/storage/get_object.rb, which for each service has a different api.

**Comment by icco** [comment]
Also, eventually you'll want to add @geemus as a contributor to move this into the fog organization.

**Comment by Paxa** [comment]
I don't have active aws account, I use fog-google to compare return values

Add @geemus - done

**Comment by Paxa** [comment]
I see some libraries has `files.each` method (https://github.com/fog/fog-google/blob/master/lib/fog/storage/google_json/models/files.rb#L25)

What's the difference between `files.each` and `files.all.each` ?

**Comment by icco** [comment]
It's for memory management. .all loads everything into memory before returning an iterator, while each should return an iterator that gets items on the fly

**Comment by geemus** [comment]
@Paxa Unfortunately, collaborate doesn't quite have enough permission. The easiest method I've found is if you simply transfer the repo directly to me (and then I'll transfer it into the org from there, and make sure you have the right permissions). Thanks!

**Comment by Paxa** [comment]
Ok, let's do it

**Comment by icco** [comment]
(My apologies for the misinformation re-repo-ownership)

**Comment by icco** [comment]
@paxa re: token-cache. Most services authenticate using something like env vars or the `.fog` file, and then don't store it. There has been some work in [fog-core](https://github.com/fog/fog-core/blob/71513c51b95aa5c4e7022353ac98619cc19839e6/lib/fog/core/cache.rb) to create a model cache, which kind of does what you want, I think... but I don't think I understand your use case...

**Comment by geemus** [comment]
It should now be transferred and @Paxa should see an invite to join the fog-backblaze team (which will give you admin rights). Let me know if/when you need anything else. Thanks!

**Comment by icco** [comment]
@paxa normally we recommend against caching any authentication for security reasons, and also for usability, since the client is constructed with auth. I personally would recommend you keep auth caching out of the gem, and let users deal with it.

**Comment by plribeiro3000** [comment]
@Paxa How is it going with `fog-backblaze`. Does it work?

I checked the code and it seems it would not work as you are not loading the model files.
Also, it would be good if you could switch the requires with autoload.

Is there something i can help you with?

**Comment by Paxa** [comment]
It works for me, but I don't know how to verify all feature. I use it with carrierwave and directly (`connection.put_object`).

Is there any check list for all expected interfaces or example code to check plugins?

And mocks are not ready yet...

**Comment by plribeiro3000** [comment]
If you are not requiring the storage service, how does it work?

Did you release it already? I can't see the tag in github to figure out it is just in master.

Can you point me the exact code version you are using?

Your `lib/fog/backblaze` should look like this:  https://github.com/fog/fog-xenserver/blob/master/lib/fog/xenserver.rb

**Comment by Paxa** [comment]
I pushed to rubygems recently, just latest from master (I should have add tag, thanks for telling)

I mostly use it like this:
```ruby
fog_connection = Fog::Storage.new(
  provider: 'backblaze',
  b2_account_id: 'xxx',
  b2_account_token: 'yyy',
  b2_bucket_name: 'test',
  b2_bucket_id: 'xxxx',
)

bucket_name = fog_connection.options[:b2_bucket_name]
fog_connection.put_object(bucket_name, filename, content)

puts fog_connection.get_public_object_url(bucket_name, filename)
```

**Comment by icco** [comment]
@Paxa my early tests for fog-google were similar to what's on fog.io

```
# First, a place to contain the glorious details
directory = connection.directories.create(
  :key    => "fog-demo-#{Time.now.to_i}", # globally unique name
  :public => true
)

# list directories
p connection.directories

# upload that resume
file = directory.files.create(
  :key    => 'resume.html',
  :body   => File.open("/path/to/my/resume.html"),
  :public => true
)

# list files
p directory.files
```

This uses the model framework which is a nice test on top of the request layer

**Comment by plribeiro3000** [comment]
@Paxa Can you really confirm it is working from latest master?
Because it shouldn't. The `Storage` service require is commented out. See [here](https://github.com/fog/fog-backblaze/blob/723c07b7c4a8f6f9ab7ced7d6b8c5889d861d77f/lib/fog/backblaze.rb#L8).

Also, what are you using to control the release of the gem? If you use bundle it should upload the tag automatically for you.

**Comment by plribeiro3000** [comment]
Gosh. Just realized what this method is doing now. It kind of bloats all the efforts i've been doing to decrease loading time. See #3430. I will see what to do about it in `fog-core`. 

Anyway @Paxa . You should not rely on `fog-core` to do the loading of your dependencies as it impacts the loading time of `fog`. Could you please add the loading of the service yourself? And do use autoload please.

I will push this forward will all the providers asap.

**Comment by plribeiro3000** [comment]
Hello @Paxa . I just did fog/fog-backblaze#3 to help you out on this. =)
