### ISSUE TITLE
Fog upgrade broke PXE installation 

### ISSUE THREAD

**Issue by cgirda** [fog/fog#3973]
Hi, 
       We use FOG for both imaging and pxe installation. The hooks that were created with Tom's (author) help in version 1.3 & 1.4 worked like a champ. Upgraded to the latest 1.5-RC9. Where I noticed the 
/var/www/fog/lib/hooks/boottask.hook.php file format was changed. Re-created all our hooks in new format. 
     Now the PXE install is starting. The install freezes right after fetching the initrd image. Tried with different flavors of linux ( ubuntu & centos ). Tried adding "acpi=off" to the kernel arguments. Looks like this more on the fog services. Can't see any debugging logs. Now I am tempted to role back to old version. Before that wanted to try for support. 

Thank you
Chakri

**Comment by geemus** [comment]
Hey, I think you may be in the wrong repository for the issue you mention (this is a ruby cloud computing library and it sounds like you are having a PHP issue).
