### ISSUE TITLE
Fog::Compute::AWS::Error iamInstanceProfile.name is invalid

### ISSUE THREAD

**Issue by binlialfie** [fog/fog#3975]
Hello, I am re-running some of my script to start EC2 server using `knife ec2 server create`

It indeed works before, but now it gave the errors:

ERROR: Fog::Compute::AWS::Error: InvalidParameterValue => Value (VPC-DEV_eu-west-1_elk) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name

VPC-DEV_eu-west-1_elk do exist in EC2 IAM, it is a value i copied from AWS console which do exist.

here is my fog related gem versions if any help:

$ chef gem list |grep fog
chef-provisioning-fog (0.21.0)
fog (1.41.0)
fog-aliyun (0.2.0)
fog-atmos (0.1.0)
fog-aws (1.4.1)
fog-brightbox (0.13.0)
fog-cloudatcost (0.1.2)
fog-core (1.45.0)
fog-digitalocean (0.3.0)
fog-dnsimple (1.0.0)
fog-dynect (0.0.3)
fog-ecloud (0.3.0)
fog-google (0.1.0)
fog-internet-archive (0.0.1)
fog-joyent (0.0.1)
fog-json (1.0.2)
fog-local (0.4.0)
fog-openstack (0.1.21)
fog-powerdns (0.1.1)
fog-profitbricks (4.0.0)
fog-rackspace (0.1.5)
fog-radosgw (0.0.5)
fog-riakcs (0.1.0)
fog-sakuracloud (1.7.5)
fog-scaleway (0.3.0)
fog-serverlove (0.1.2)
fog-softlayer (1.1.4)
fog-storm_on_demand (0.1.1)
fog-terremark (0.1.0)
fog-vmfusion (0.1.0)
fog-voxel (0.1.0)
fog-vsphere (1.12.0)
fog-xenserver (0.3.0)
fog-xml (0.1.3)

**Comment by icco** [comment]
You should probably file this against `fog-aws`. Also, in general it's good practice to just require `fog-aws` not all of `fog`

**Comment by geemus** [comment]
closing in favor of fog/fog-aws#410
