### ISSUE TITLE
[tracking] fog-packet for packet.net

### ISSUE THREAD

**Issue by vielmetti** [fog/fog#3982]
Packet (http://packet.net) is a bare-metal cloud provider. This issue is to track efforts to port Fog to run on Packet.

There is an existing Ruby client for Packet at https://github.com/packethost/packet-rb & it is to be hoped that some of that design and code can be adapted for this.

**Comment by plribeiro3000** [comment]
closed in favor of #3644

**Comment by geemus** [comment]
Thanks for the heads up (and consolidation!)
