### ISSUE TITLE
Release version 2.0.1 with updated fog-google dependency

### ISSUE THREAD

**Issue by meddario** [fog/fog#3986]
Hi, do you plan to release a new version with the updated fog-google dependecy (commit dd05dd079cd3f24f3f8ae38bc88601d7ab98f025)? As now the fog-google dependency in 2.0.0 is from 2 years ago!

Thanks in advance!

**Comment by icco** [comment]
@meddario While I think this is a good idea, it should be mentioned that we generally suggest you require `fog-google` and other gems separately if you can.

cc @geemus who can do releases

**Comment by geemus** [comment]
Yeah, we will likely update at some point, but I think there are a few dependency conflicts floating around that we may yet need to deal with. If you can work directly with individual providers, that is probably the better path forward for now.

**Comment by Temikus** [comment]
@meddario as per [postinstall](https://github.com/fog/fog/blob/master/fog.gemspec#L109):
```
IMPORTANT NOTICE:
If there's a metagem available for your cloud provider, e.g. `fog-aws`,
you should be using it instead of requiring the full fog collection to avoid
unnecessary dependencies.
'fog' should be required explicitly only if the provider you use doesn't yet
have a metagem available.
```

However, if you have a use case that requires supporting 20+ providers at the same time - can you let us know so we can keep it in mind?

**Comment by meddario** [comment]
The problem I'm having is some strange dependency entanglement between fog, fog-google, carrierwave and google-api-client, the only way I found to make it work is to point to fog master. 

I'll try to provide a minimal (non-)working example as soon as I can find the time!

**Comment by geemus** [comment]
@meddario Sounds good, thanks!

**Comment by geemus** [comment]
Hoping this has subsequently resolved...
