### ISSUE TITLE
Is fog will Support IBM AIX/pseries

### ISSUE THREAD

**Issue by yrmallu** [fog/fog#3987]
I want to integrate IBM using fog but I haven't seen any library to support IBM

Any help

**Comment by plribeiro3000** [comment]
What do you mean by library to support IBM?
Usually the best idea on a provider is to use the apis directly removing any dependencies but some providers do use a third party to help working with complex API's.

What exactly are you looking for?

**Comment by yrmallu** [comment]
@plribeiro3000 
I want to integrate IBM cloud like Azure and AWS but I I haven't seen any API to communicate with IBM.
Fog official site says fog will support IBM.
http://fog.io/about/supported_services.html

Any help how can I do this?

**Comment by plribeiro3000** [comment]
Yeah. Not sure about IBM apis either. IBM now have both softlayer and bluebox so dunnon if they have their own api at this point.

I can help you with building the gem but i'm afraid can't do much regarding the apis. Since i don't use ibm and never did i have no idea where their apis are.

**Comment by yrmallu** [comment]
@plribeiro3000 Can you help how can I do through fog or gem for IBM

**Comment by geemus** [comment]
There is some really old, basic support here: https://github.com/fog/fog/blob/master/lib/fog/ibm/compute.rb. I have no idea if it still works though, or how it might relate to their newer APIs. I don't think it's really seen much interest/usage. That would be a good place to start looking though.

**Comment by plribeiro3000** [comment]
Also, there is a wiki page to create new providers: https://github.com/fog/fog/wiki/Create-New-Provider-from-Scratch
