### ISSUE TITLE
Packet provider 

### ISSUE THREAD

**Issue by jasmingacic** [fog/fog#3992]
@geemus I'm finishing [Fog Packet](https://github.com/packethost/fog-packet) provider, and I wanted to find out what is required for it to become official.

**Comment by geemus** [comment]
@jasmingacic thanks for checking in. We would prefer to move it under the fog organization, if possible, to keep everything organized and help manage permissions. Similarly we ask that you would grant one or two of us write permission for the gem in case we needed to do security or compatibility updates at some future time. I think that is most of it. @plribeiro3000 may be able to remind us of other things though, as he has assisted with many of these in the past.

**Comment by vielmetti** [comment]
@geemus Invite sent!

**Comment by geemus** [comment]
Thanks, I believe it should all be transferred and have fixed up
permissions as well.

Just let me know if I missed anything or you have further questions.

Thanks!
wes

On Wed, May 16, 2018 at 10:44 AM, Edward Vielmetti <notifications@github.com

**Comment by vielmetti** [comment]
Looks good to me @geemus !
