### ISSUE TITLE
NameError: uninitialized constant Fog::JSON

### ISSUE THREAD

**Issue by lhellebr** [fog/fog#3993]
When using Foreman with Fog and Fog-oVirt (Create Host -> select oVirt -> OS -> Image Based), I get the attached traceback.
[tb.txt](https://github.com/fog/fog/files/1942443/tb.txt)

**Comment by lhellebr** [comment]
This is probably an issue with fog-ovirt AND fog-core, moving there and closing this one:
https://github.com/fog/fog-ovirt/issues/19
https://github.com/fog/fog-core/issues/234

Based on this discussion:
[irclog.txt](https://github.com/fog/fog/files/1947130/irclog.txt)

**Comment by geemus** [comment]
closing in favor of fog/fog-ovirt#20
