### ISSUE TITLE
Include OpenNebula metagem

### ISSUE THREAD

**Issue by dann1** [fog/fog#3994]
Hello, I've successfully managed to extract OpenNebula code into a metagem. Here is the repo https://github.com/dann1/fog-opennebula. Can you include it in fog repo? It would also be nice to show OpenNebula in the [fog provider docs](http://fog.io/about/provider_documentation.html) since it is absent right now, and code in the big fog gem works fine.

**Comment by geemus** [comment]
@dann1 awesome. Yes, we can certainly work on getting it moved and included. The easiest way we have found is if you grant me admin collaborator status on your repo. That puts me in a place to have enough permissions on both sides to just do the transfer and setup as needed. The website info is open source also, so I'd be happy to get your help adding the relevant info to https://github.com/fog/fog.github.com. From there we can follow up if there are extra steps. Thanks!

**Comment by dann1** [comment]
Sorry for the delay, I don't know why I didn't get the notification. Collaboration granted https://github.com/dann1/fog-opennebula/invitations

**Comment by geemus** [comment]
@dann1 to do the transfer, one needs to have admin access on both sides (if I'm not mistaken). So if you could bump me to that level on the repo, I'll happily do the transfer (I try to keep the list of admin level to the whole org short for safety of the many different repos). Thanks!

**Comment by dann1** [comment]
Hey, I just transferred the repo to you. Didn't find other permissions to be given rather than collaborator. Thanks for the feedback!

**Comment by geemus** [comment]
Great, thanks for that. I believe everything is transfered in and permissions are fixed, just let me know if I missed anything. Thanks!

**Comment by dann1** [comment]
OK thanks!

**Comment by dann1** [comment]
Just missing the changes in the websites.

**Comment by geemus** [comment]
Sure, the website is opensource too, so I'd be happy to accept the changes from you to the fog/fog.github.com repository. Thanks!

**Comment by dann1** [comment]
made a PR to the website

**Comment by geemus** [comment]
Awesome, merged. Just let me know if I can help with anything else. Thanks!

**Comment by dann1** [comment]
Thank you for your attention!
