### ISSUE TITLE
Can Fog::Compute.new use .fog profile?

### ISSUE THREAD

**Issue by jongillies** [fog/fog#3995]
When connecting, can you specify an argument to use a profile in the within the `~/.fog` file?

Something like `fog_profile`?

If not, how can you use the `.fog` withing the Ruby script?

```
require 'fog-aws'
connection = Fog::Compute.new(provider: 'AWS',..., fog_profile: 'prod', ...)

```

**Comment by icco** [comment]
Depending on your `.fog` file, we use the `FOG_CREDENTIAL` env var to select this: https://github.com/fog/fog-core/blob/f6ef6c3d9458bc235be57100acdced264e85e52a/lib/fog/core/credentials.rb#L40-L42 shows how this is set.
