### ISSUE TITLE
Google::Apis::ClientError: Access Not Configured

### ISSUE THREAD

**Issue by EUGinsane** [fog/fog#3996]
Hi, I'm having an issue while trying to list out all the image of google cloud project with this following code: 

**require 'fog/google'
connection = Fog::Compute.new ({
   :provider => 'google',
   :google_project => 'hoangtrinh-XXX',
   :google_client_email => 'XXXXX-compute@developer.gserviceaccount.com',
   :google_json_key_location => '/home/ubuntu/hoangtrinh-9dff8136a8df.json'
})
connection.images.all**

Then I got this error message 

> Google::Apis::ClientError: accessNotConfigured: Access Not Configured. Compute Engine API has not been used in project 255964991331 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=255964991331 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry

**I have already enable Compute Engine API, I also can list out all the zones**, but when trying to list out all the images then this error message comes out, I'm using fog-google version 1.4.0 and google-api-client version 0.23. Any ideas ? 

Thanks

**Comment by plribeiro3000** [comment]
Hello @EUGinsane . Could you open this against [fog-google](https://github.com/fog/fog) instead please?

You will get more feedback for `google` there.

Thanks!

**Comment by Temikus** [comment]
@EUGinsane See https://github.com/fog/fog-google/pull/356
We'll roll out a fix shortly.

**Comment by Temikus** [comment]
This is fixed in `1.5.0`

**Comment by EUGinsane** [comment]
@Temikus Thanks, really appreciated
