### ISSUE TITLE
Not hard requiring deps, splitting out deps

### ISSUE THREAD

**Issue by emilebosch** [fog/fog#4006]
SCENARIO:

- We only use openstack part of fog
- Not interested in the rest
- We want to build a minimal container
- Jet because of the tons of providers fog support I need to have all the deps.

Ie.  still I need to have a bunch of native extensions and libs installed to even install the gem. Even if I am not interested in those other storage methods.

Isn't it better that we make them all soft dependencies?

In this case I'm building against `FROM ruby:2.3-alpine`.

```
current directory:
/usr/local/bundle/gems/ovirt-engine-sdk-4.2.4/ext/ovirtsdk4c
/usr/local/bin/ruby -r ./siteconf20180726-6-76nk3t.rb extconf.rb
checking for xml2-config... yes
checking for curl-config... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
	--with-libcurl-config
	--without-libcurl-config
	--with-pkg-config
	--without-pkg-config
extconf.rb:40:in `<main>': The "libcurl" package isn't available. (RuntimeError)
```

**Comment by plribeiro3000** [comment]
Hello!

We are already pursuing this. =)

And you can add `fog-openstack` to your `Gemfile` instead of `fog`. 😉

**Comment by plribeiro3000** [comment]
If this does not solve your problem feel free to reopen and/or comment back in this thread. 

Thanks for your support!

**Comment by emilebosch** [comment]
Ok i should add it to the readme then ? I couldnt find it the manual.

**Comment by geemus** [comment]
This section is intended to point that out: https://github.com/fog/fog#dependency-notice

I'd certainly welcome suggestions and improvements though. Thanks!

**Comment by emilebosch** [comment]
Hahahah, omg I am blind. I think because we're so used to skipping to the install that we forget to read.  My bad.
