### ISSUE TITLE
SSL Cert has expired on fog.io

### ISSUE THREAD

**Issue by lacostenycoder** [fog/fog#4011]
Looks like the Let's Encrypt cert expired so can't get to documentation without warnings.

**Comment by icco** [comment]
Hmm, this is working for me, maybe the cert took a few to be updated?

Working here as well: https://www.ssllabs.com/ssltest/analyze.html?d=fog.io&latest

Closing this, but cc @geemus just as an FYI.

**Comment by geemus** [comment]
Thanks. I don't think we manage it directly anyway, pretty sure it is github pages magic. Anyway, sorry it wasn't working, but glad it resolved.

**Comment by lacostenycoder** [comment]
Yeah looks like it's provisioned by Let's Encrypt so perhaps the auto-renew had not fully updated.

![screen shot 2018-09-25 at 10 04 53 am](https://user-images.githubusercontent.com/6077905/46019657-9addca80-c0aa-11e8-8a08-756d54d90bdb.jpg)
