### ISSUE TITLE
Unpinned version of fog-xenserver breaks with older ruby versions

### ISSUE THREAD

**Issue by powellchristoph** [fog/fog#4012]
Greetings, 

It looks like a recent release of `fog-xenserver` has a new dep on `xmlrpc` which requires Ruby version >= 2.3. 

Would it be possible to add some version constraints?
https://github.com/fog/fog/blob/v1.37.0/fog.gemspec#L73

```
# /opt/chef/embedded/bin/gem install fog --no-rdoc --no-ri -v "1.37.0"
ERROR:  Error installing fog:
    xmlrpc requires Ruby version >= 2.3.
```

ruby: 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]

https://github.com/fog/fog-xenserver/issues/74

**Comment by plribeiro3000** [comment]
Hmmmm. Can't you use a recent version of `fog`? Like `1.42.1`?

This one is to old and the problem you describe should be fixed at the latest.

**Comment by reist** [comment]
I just encountered the same issue. Using fog 1.42.1 is not enough, as it pulls in the latest fog-xenserver, which will try to install xmlrpc anyway.
There's also a problem with fog-openstack, which needs Ruby>2.2.0 now.
The way I install fog on 2.1 is this:
`gem install --no-ri --no-rdoc fog-core:1.45.0 fog-openstack:0.1.24 fog-xenserver:0.3.0 fog:1.42.1`

**Comment by plribeiro3000** [comment]
@geemus Maybe is time for us to start dropping the dependencies on `fog > 2`?

Ok. So i believe a new patch version on `fog` will be needed, locking the dependency versions. WDYT @geemus ?

**Comment by geemus** [comment]
@plribeiro3000 yeah, locking may be easiest for now, but dropping would be better in the longer term.

**Comment by geemus** [comment]
@reist is that the newest openstack that will work? (it's a rather old version)

**Comment by reist** [comment]
@geemus Maybe 0.1.25 will also work with Ruby 2.1, but that's it, because immediately after the spec was changed to this:
`spec.required_ruby_version = '>= 2.2.0'`

**Comment by geemus** [comment]
One last avenue, as I'm a bit concerned about breakage here. How many providers does chef actually utilize? Could we start moving toward individual gem requires, and away from blanket fog require instead?

**Comment by plribeiro3000** [comment]
I will leave this issue closed since we did not get feedback.

Feel free to comment back or reopen if you want/need.
