### ISSUE TITLE
Cloudstack | escape is not compatible with Ruby 2.5+

### ISSUE THREAD

**Issue by voxik** [fog/fog#4016]
Testing with Ruby 2.5, I observer the following test failure:

~~~
  Cloudstack | escape (cloudstack)     
    tests/cloudstack/signed_params_tests.rb
      Cloudstack | escape (cloudstack)
    - returns "%27St%C3%B6p%21%27%20said%20Fred_-~."
      expected => "%27St%C3%B6p%21%27%20said%20Fred_-~."
      returned => "%27St%C3%B6p%21%27%20said%20Fred_-%7E."
~~~

This appears to correspond to this change in Ruby 2.5 https://github.com/ruby/ruby/commit/e1b432754553423008a14d39d0901eabc99e7ddb

**Comment by geemus** [comment]
Thanks for the heads up. There are some other possibilities within stdlib, but they all have their own idiosyncracies. Maybe we should just consider our own explicit escape function in fog-core to use in order to avoid any confusion/surprise. We could probably borrow from fog-aws: https://github.com/fog/fog-aws/blob/master/lib/fog/aws.rb#L134. What do you think?

**Comment by voxik** [comment]
It seems that the CGI.escape is trying to follow the RFC3986, which is not completely bad thing. Although the success is varying.

**Comment by geemus** [comment]
Yeah, the change makes some sense for future use, but seems a bit unkind to existing users. I wouldn't mind if there was a clearer replacement/migration for those who would like to maintain the existing behavior, instead it's pretty confusing/muddled.

**Comment by voxik** [comment]
This is still an issue AFAIK

**Comment by geemus** [comment]
Thanks for the heads up. I would welcome help fixing this up.

**Comment by voxik** [comment]
This is still issue testing with Ruby 2.6 and fog 2.1.0.

**Comment by geemus** [comment]
@voxik thanks for the ping/reminder. Do you think we should just copy from fog-aws: https://github.com/fog/fog-aws/blob/master/lib/fog/aws.rb#L134 and call that good-enough?

**Comment by voxik** [comment]
1. It seems that the AWS escape is just old version of CGI.escape. So if you want to have your own copy, then the Ruby version is probably better.
2. There are already some exceptions handled in Cloudstack.escape. I don't see why there should not be more exceptions handled.
3. I really don't know what is expected, if tilde should be escaped or not. This probably depends on Cloudstack API. Maybe just test fix is enough or ignoring the tilde is enough.

Sorry, I don't have a better answer. I am just trying to make the test suite run, I don't have higher expectations :blush:

**Comment by geemus** [comment]
@voxik thanks for clarifying. I'd like to see it fixed, but haven't used Cloudstack. So I'm worried that in trying to fix it, I'll just make it worse. Hopefully somebody with some more experience may come along to help us out here.
