### ISSUE TITLE
Errore while creating VM on GCE

### ISSUE THREAD

**Issue by vincur96** [fog/fog#4017]
I made a script to create a virtual machine in google compute engine:
`require "fog/google"

COMPUTE_ZONE = "us-central1-f"
MACHINE_TYPE = "f1-micro"

connection = Fog::Compute::Google.new

disk = connection.disks.create(
  :name => "new-disk",
  :size_gb => 10,
  :zone_name => COMPUTE_ZONE,
  :source_image => "debian-8-jessie-v20161020")

puts "Creating disk"

disk.wait_for { disk.ready? }

puts "Disk ready"

server = connection.servers.create(
  :name => "new-server",
  :zone_name => COMPUTE_ZONE,
  :disks => [disk],
  :machine_type => MACHINE_TYPE,
  :private_key_path => File.expand_path("~/.ssh/id_rsa"),
  :public_key_path => File.expand_path("~/.ssh/id_rsa.pub"),
  :user => ENV["VinCur"])

puts "Creating server"

server.wait_for { server.ready? }

puts "Server ready"`

but it give me an error:
Traceback (most recent call last):
	3: from vm.rb:6:in `<main>'
	2: from /Users/VinCur/.rvm/rubies/ruby-2.6.0-preview2/lib/ruby/gems/2.6.0/gems/fog-core-2.1.0/lib/fog/core/service.rb:98:in `new'
	1: from /Users/VinCur/.rvm/rubies/ruby-2.6.0-preview2/lib/ruby/gems/2.6.0/gems/fog-core-2.1.0/lib/fog/core/service.rb:268:in `handle_settings'
/Users/VinCur/.rvm/rubies/ruby-2.6.0-preview2/lib/ruby/gems/2.6.0/gems/fog-core-2.1.0/lib/fog/core/service.rb:244:in `validate_options': Missing required arguments: google_project (ArgumentError)

why?

**Comment by geemus** [comment]
I believe when you create the connection, you would need to supply some credentials, including the project. But I'm not certain. Could you please post this on the fog/fog-google repository? I think you should be more likely to find experts over there.
