### ISSUE TITLE
FOG won't boot hard drive

### ISSUE THREAD

**Issue by JasmineTF** [fog/fog#4021]
I have windows 10 version 1809, build 17763.557
I have 32-bit Ubuntu 16.04 and Fog version 1.5.6
I have Windows 10 in legacy boot mode.  

When started, the pxe initiates normally and, when it sees there are no FOG commands, the white menu box appears with the default highlighted command being to boot from the hard drive, just like it normally does.  The problem is that a black screen appears with a blinking cursor and remains indefinitely.  There is no boot to the hard drive.   If I boot and manually cancel the pxe boot with a keystroke, it has no problem booting from the hard drive.  The problem seems to be with FOG correctly accessing the hard drive from its boot menu.  Any ideas what to do?

**Comment by tokengeek** [comment]
I believe you want https://github.com/FOGProject/ instead of this one.

This repo is for http://fog.io/ and not https://fogproject.org/

**Comment by JasmineTF** [comment]
Sorry!  Thank you!  :)
