### ISSUE TITLE
Uploading Base64 decoded image throws "contains forbidden "\r" or "\n"" error

### ISSUE THREAD

**Issue by mohamednajiullah** [fog/fog#4023]
I'm using the `fog-google` gem to upload an image to a Google Cloud Storage bucket. 

I get a `data_string` that contains the Base64 encoded image to my service which I then decode using Base64 and then try to upload that using the interoperability API in fog for GCS.

I tried to upload a small 1x1 gif which seems to work fine. When I try to upload any other larger image, I get the following error

```
contains forbidden "\r" or "\n"" error
```
This is the code I use

```
directory = @connection.directories.get(@settings.bucket_name)
file = directory.files.create :key => path, :body => Base64.decode64(data_string)

file.metadata = { 'Content-Type' =>  'image/jpeg' }
file.save
```
How do I fix this? Am I missing something?

**Comment by geemus** [comment]
@mohamednajiullah I would guess the 1x1 gif is small enough to not cause a line feed to be added (at 76 characters, I think). I believe there are two options that could work. The first would be to modify where the base64 encoding is originally taking place and use a method that will not insert those characters (in Ruby, I believe this would be `Base64.strict_encode64`). Alternatively, after doing the decode here, you could use gsub to strip out the `\r\n`. Does that make sense?
