### ISSUE TITLE
fog/xml issue on MacOS Catalina

### ISSUE THREAD

**Issue by PhilippeBo** [fog/fog#4024]
I've installed my ruby project on a recently updated mac, and I'm facing an issue when using fog. 

It's failling on the `require 'fog/xml'` at line 13 of the `lib/fog.rb` file.

Here is the errors I get in the terminal running a simple db creation task : 
```rake db:create
rake aborted!
LoadError: cannot load such file -- fog/xml
PROJECT_PATH/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
PROJECT_PATH/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
PROJECT_PATH/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
PROJECT_PATH/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
PROJECT_PATH/vendor/bundle/ruby/2.5.0/gems/fog-1.42.0/lib/fog.rb:13:in `<top (required)>'
PROJECT_PATH/config/application.rb:7:in `<top (required)>'
PROJECT_PATH/Rakefile:4:in `require_relative'
PROJECT_PATH/Rakefile:4:in `<top (required)>'
PROJECT_PATH/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/Users/philippe/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
/Users/philippe/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'
```

I've found nothing about this issue online.
I've tried to use only `fog-aws`, resulting on the same issue with `fog/xml`.

Any clue/idea?

**Comment by geemus** [comment]
Not sure off hand. It might be worth trying to reinstall the gems (something in paths or otherwise may have changed moving into Catalina). It might also be something like needing to re-install developer tools so it can find the c stuff nokogiri needs, seems like I always need to do something along those lines after a mac os update. I haven't personally moved to Catalina yet though, so it's hard for me to do much more than speculate at present.

**Comment by PhilippeBo** [comment]
Thanks for taking time to reply.
Indeed I've reinstalled everything, and it seems to be working now

**Comment by geemus** [comment]
Great, seems like there is always some amount of issues like that with mac updates, glad you found your way through it. Thanks for taking time to report back.
