### ISSUE TITLE
file.exists? does not work properly with AWS s3

### ISSUE THREAD

**Issue by namila** [fog/fog#4029]
Environment details
  ruby 2.6.2
  rails 5.1
  carrierwave 2.0
  carrierwave-mongoid 1.3

Steps to reproduce

take an object which has a file in s3 and call
offer.offer_pdf.file.exists? 

expected result : true, actual_result: true

delete that file from the s3 bucket and call the same method again
offer.offer_pdf.file.exists? 

expected result: false, actual_result: true

**Comment by tokengeek** [comment]
That sounds like a typical caching problem.

Are you calling `reload` between the `#exists?` calls?

Typically fog would query an API (S3 in this case) only the first time it is used and then the state of the S3 bucket at that time would be stored in memory.

A second call to `#exists?` would have a stale view of the bucket from in memory.

I'm guessing `offer.offer_pdf.file.reload` would have fog reload the file from S3, potentially getting `nil` if it had been deleted or raising an error when S3 returns 404.

By way of comparison, Ruby's STDLIB `File` can do the same thing as well:

```ruby
# Given a file "test.txt" on disk
irb> file = File.open("test.txt")
=> #<File:test.txt>
irb> file.size
=> 0
# Remove file from disk
irb> file.size
=> 0
irb> file.to_path
=> "test.txt"
```

The `File` instance does not register the changes on the local file system.

Fog has the same problem but the file system is remote and is based on a simpler, one-way API GET call.

So I don't think this is an issue within Fog unless I've missed something?

**Comment by namila** [comment]
Hi @tokengeek Thanks a lot for the quick response and the detailed explanation :)

but I cannot find a reload method on "offer.offer_pdf.file"
calling "offer.offer_pdf.file.reload" will result following error

undefined method `reload' for #<CarrierWave::Storage::Fog::File:0x00007fe4564b00e0>

Is there any other way of getting the file status refreshed? 
(I tried calling offer.reload, but still it did not reflect the actual status of file in s3)

**Comment by tokengeek** [comment]
Ah, I didn't realise it was from Carrierwave.

From https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/storage/fog.rb#L329 it looks like `CarrierWave::Storage::Fog::File#exists?` is based on the presence of `file`.

A reload would try to get the file again but I can't see a way to trigger that nicely from the instance you already have.

`CarrierWave::Storage::Fog::File#file` is a private instance method which calls `directory.files.head(path)` and memoizes the result. That gives a simple "cache" with the stale result.

I'm guessing trying to get the file again would be the quickest way to confirm it is no longer present on S3.

It may be worth asking the Carrierwave folks about a way to solve your problem in case it is a standard case they have seen before: https://github.com/carrierwaveuploader/carrierwave#getting-help

I think as far as Fog is concerned, it isn't really an issue for us to deal with as it is a Carrierwave implementation around one of the hardest problems in computer science!

**Comment by namila** [comment]
Thanks a lot @tokengeek :) I will ask from carrierwave whether they have a built in way for this :)
