### ISSUE TITLE
How do I migrate to Ruby 3.0?

### ISSUE THREAD

**Issue by szeryf** [fog/fog#4034]
I'm using fog in my Ruby on Rails project and wanted to migrate to Ruby 3.0. However, this is blocked by fog:

```
Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    Ruby (~> 3.0.0.0)

    fog (~> 2.2.0) was resolved to 2.2.0, which depends on
      fog-google (~> 1.0) was resolved to 1.12.1, which depends on
        Ruby (~> 2.0)
```

Any advice on what to do? I probably do not need `fog-google`, is there a way to get rid of it if it's blocking the upgrade?

**Comment by Temikus** [comment]
As the post install says you do not need the 'fog' metagem anymore.

Just require whichever provider you need directly, e.g. "fog-aws", "fog-google" and you're good to go :)

**Comment by geemus** [comment]
Yes, thanks @Temikus.

@szeryf using the particular sub-gem you need is the best bet. Just let us know if that won't work for some reason though.

**Comment by szeryf** [comment]
Thanks guys, that helped!
