### ISSUE TITLE
Switch to rbvmomi2

### ISSUE THREAD

**Issue by micwoj92** [fog/fog#4086]
https://github.com/fog/fog/blob/33135e607612188579f7f598977e606e38ef3654/fog.gemspec#L94
As latest fog-vsphere uses rbvmomi2 rather than rbvmomi I think it makes sense to switch development dependency here.

This is also issue for:
- fog-hadoop
- fog-sakuracloud
- fog-softlayer

Should this issue be also opened on respective repos separately?

reference
https://github.com/fog/fog-vsphere/pull/281

**Comment by geemus** [comment]
@micwoj92 Thanks for letting us know. I suspect that opening separate issues might be helpful to make sure this happens in all the right places. I'd also welcome PRs if you have the time and inclination. Thanks!

**Comment by micwoj92** [comment]
Sorry, unfortunately I do not know ruby. Best I could do is just replace dependency and check if tests pass, but seeing that these fail now anyway I don't know if I can offer any help. https://github.com/fog/fog/actions/runs/3686030546

**Comment by geemus** [comment]
Understood, thanks for letting me know.

**Comment by geemus** [comment]
Yeah, I'm definitely comfortable with Ruby, but I am not using vsphere, hadoop, sakuracloud, or softlayer. So I'm a bit reticent to make changes without having a good way to test them out. We definitely also should try to get more of those tests passing, ideally, but without having live stuff to double check with I've been a bit stuck. Hopefully someone with more active interest/need will step up at some point though.

**Comment by geemus** [comment]
Good question, I had almost no familiarity, which made me worried about changing things I didn't understand. Reading/looking around a bit more, I would tend to agree that it looks relatively safe. Let me see what I can do.

**Comment by geemus** [comment]
Ok, I think those should all be fixed now, so hopefully we will be good moving forward. I bumped them all to use the same `~> 3.0` for now to be consistent and hopefully guard against backwards compatibility problems if a new major comes out.

**Comment by micwoj92** [comment]
Thanks.
