### ISSUE TITLE
Excon::Errors::NotFound: Expected(200) <=> Actual(404 Not Found)

### ISSUE THREAD

**Issue by dessy** [fog/fog#511]
I switched from aws to fog, and I'm getting Excon::Errors::NotFound: Expected(200) <=> Actual(404 Not Found) errors intermittently. It's difficult to track down because I can't consistently reproduce it. I'm using ruby 1.9.2-p0.

There is an issue on paperclip for this same error: https://github.com/thoughtbot/paperclip/issues/554

**Comment by abepetrillo** [comment]
Sorry for the revival but any updates on this? The following does not work:
```ruby
Fog.mock!
connection = Fog::Storage.new(provider: 'AWS', aws_access_key_id: 'whatever', aws_secret_access_key: 'awd')
connection.directories.create(key: 'bucket')
```

**Comment by geemus** [comment]
@abepetrillo that code seems to work fine for me. What error(s) are you seeing?

**Comment by a-barbieri** [comment]
I'm facing the same issue with Paperclip and I don't know how to solve it too. 

I get the error when I call 
```
<%= image_tag admin_asset.item.url(:thumb) %>
```
and among the request parameters I've seen this line. Can it be the reason why it doesn't work?
```
:path          => "/admin%2Fassets%2Fitems%2F000%2F000%2F004%2Fthumb%myimage.jpg"
```

As the other ones, I get this error randomly, but it started appearing when I first migrate my database.

**Comment by a-barbieri** [comment]
Sorry, forget what I was saying, apparently it's simply a record that doesn't exist anymore on my bucket, but has remained in my database for some unknown reason.

**Comment by geemus** [comment]
@a-barbieri thanks for the update, yeah I think I would expect something like this if it was in DB but not on S3 any more.
