### ISSUE TITLE
Creating an S3 signed URL without downloading the object

### ISSUE THREAD

**Issue by benbc** [fog/fog#836]
I'm using `fog` to generate signed URLs for S3, like this:

``` ruby
s3.directories.get(BUCKET).files.get(object).url(expiry)
```

This causes `fog` to download the entire object, which I don't need to do.

Is there any way to create the signed URL without downloading the object?

**Comment by tischler** [comment]
@geemus this page comes up fairly easy when googling for signed URLs.  if you know a better way, you should add a link to this thread... cheers!

**Comment by geemus** [comment]
Hmm, hard to remember now. I think basically you can just do the second part above (with `new` calls), but skip the head step. If the file doesn't really exist it would be invalid, but if you have reason to believe it does, it saves you the round-trip. I think that is probably what I meant, but, has been a while. Hope that helps!
