### ISSUE TITLE
AWS AuthFailure, perhaps due to account managed with IAM??

### ISSUE THREAD

**Issue by stepheneb** [fog/fog#978]
I am getting authentication errors right from the start trying to use fog with AWS -- but I AM able to use the Amazon ec2-api-tools.

I'm wondering if the fact that my account is managed as part of "AWS Identity and Access Management (IAM)" for our company is part of the problem ???

---- details ----

Following these instructions: http://fog.io/1.3.1/compute/

I installed fog and created this simple program to test the connection (copyingmy actual access key credentials from the AWS Management Console):

```
require 'fog'

# create a connection
connection = Fog::Compute.new({
  :provider                 => 'AWS',
  :aws_secret_access_key    => YOUR_SECRET_ACCESS_KEY,
  :aws_access_key_id        => YOUR_SECRET_ACCESS_KEY_ID
})

puts connection.servers.length
```

Running it generates this error:

```
/Users/stephen/.rvm/gems/ruby-1.9.3-p194/gems/excon-0.13.4/lib/excon/connection.rb:266:in `request_kernel': AuthFailure => AWS was not able to validate the provided access credentials (Fog::Compute::AWS::Error)
    from /Users/stephen/.rvm/gems/ruby-1.9.3-p194/gems/excon-0.13.4/lib/excon/connection.rb:97:in `request'
    from /Users/stephen/.rvm/gems/ruby-1.9.3-p194/gems/fog-1.3.1/lib/fog/core/connection.rb:20:in `request'
    from /Users/stephen/.rvm/gems/ruby-1.9.3-p194/gems/fog-1.3.1/lib/fog/aws/compute.rb:320:in `request'
    from /Users/stephen/.rvm/gems/ruby-1.9.3-p194/gems/fog-1.3.1/lib/fog/aws/requests/compute/describe_instances.rb:75:in `describe_instances'
    from /Users/stephen/.rvm/gems/ruby-1.9.3-p194/gems/fog-1.3.1/lib/fog/aws/models/compute/servers.rb:64:in `all'
    from /Users/stephen/.rvm/gems/ruby-1.9.3-p194/gems/fog-1.3.1/lib/fog/core/collection.rb:131:in `lazy_load'
    from /Users/stephen/.rvm/gems/ruby-1.9.3-p194/gems/fog-1.3.1/lib/fog/core/collection.rb:18:in `length'
    from connect.rb:9:in `<main>'
```

I then followed the instructions here to generate sbannasch.crt and sbannasch.key, put them in ~/.ec2 (setting permissions correctly), and uploaded sbannasch.crt to the Signing Certificates section of my account.

  http://michaelnovi.com/2011/prerequisites-preparing-to-work-with-amazon-ec2/

Then I modified ~/.bash_profile to setup some EC2 environmental variables:

```
export EC2_HOME=/Users/stephen/dev/bin/ec2-api-tools-1.5.5.0
export PATH=$PATH:$EC2_HOME/bin
export EC2_PRIVATE_KEY=~/.ec2/sbannasch.key
export EC2_CERT=~/.ec2/sbannasch.crt
```

And downloaded the ec2-api-tools-1.5.5.0 from here and put them on my path:

  http://aws.amazon.com/developertools/351

Running the EC2 CLI/API commands works. For example: ec2-describe-instances shows all of our running instances.

**Comment by sheldonh** [comment]
By the way, this one reason why the AWS IAM documentation recommends key rotation even when the key id is exposed.
